import {lazy,Suspense,useEffect,useRef} from 'react';
import PetCompanion from '../components/PetCompanion.jsx';
import {ISLAND_GOALS,getIslandGoalProgress,getIslandIncome} from '../data/petIslandStrategy.js';
import './pet-island.css';

const IslandScene=lazy(()=>import('../components/PetIslandScene.jsx'));
function Dice({value}){return <span className="p3-die" aria-hidden="true">{[1,2,3,4,5,6,7,8,9].map(dot=><i key={dot} className={({1:[5],2:[1,9],3:[1,5,9],4:[1,3,7,9],5:[1,3,5,7,9],6:[1,3,4,6,7,9]})[value]?.includes(dot)?'is-dot':''}/>)}</span>}

export default function PetIslandView(v){
  const {encounter,resolveEvent,learning,setLearning,learningUsed,openLearning,toolTarget,setToolTarget,blockOpponent,buyTool,shopUsed,soundOn,toggleSound,Hdr,exitGame,gameStarted,result,tiles,position,owned,computers,computerCount,selectedPet,selectedPetDef,
    routes,inspected,setInspected,paused,moving,startGame,roundLimit,setRoundLimit,setupComputerCount,setSetupComputerCount,
    stake,setStake,pets,petIndex,setPetIndex,goalId,setGoalId,visited,turn,gameCoins,score,rankings,pauseGame,skipLearning,
    pending,answer,answerReview,setAnswerReview,queueComputerRound,offer,offerTile,buyProperty,skipOffer,roll,moveAlongRoute,
    feedback,cardHand,cardEffects,cardUsedTurn,cards,useCard,screenEffect,eventFlash,rentFlash,rentDialog,confirmRentMoment,
    upgradeCurrentProperty,upgradedTurn,upgradeDiscount,pauseDialogRef,resumeGame,abandonGame,exitRequested,
    setGameStarted,setResult,resultTitleRef,onBack,onNavigate,tileCost,tileRent,tileUpgradeCost,typeMeta,eventCount}=v;
  const rentRef=useRef(null);
  useEffect(()=>{if(rentDialog)rentRef.current?.showModal?.()},[rentDialog]);
  const activeGoal=ISLAND_GOALS.find(goal=>goal.id===goalId)||ISLAND_GOALS[0];
  const goalProgress=getIslandGoalProgress(goalId,owned,visited),goalDone=goalProgress>=activeGoal.target;
  const income=getIslandIncome(owned,tiles);
  const inspectIndex=inspected??position,inspectTile=tiles[inspectIndex],property=owned[inspectTile.id];
  const owner=computers.slice(0,computerCount).find(cpu=>cpu.active!==false&&cpu.owned?.includes(inspectTile.id));
  const cost=property?Math.max(5,tileUpgradeCost(property)-upgradeDiscount):0;
  const idle=!encounter&&!toolTarget&&!moving&&!pending&&!offer&&!answerReview&&!rentDialog&&!paused&&!routes.length;
  const describeRoute=route=>{
    const tile=tiles[route.index],mine=owned[tile.id],cpu=computers.slice(0,computerCount).find(c=>c.active!==false&&c.owned?.includes(tile.id));
    if(cpu)return `付租 ${Math.ceil(tileRent(tile,{level:1})*(cpu.rent?2:1)*(cardEffects.shield ? .5 : 1))} · ${cpu.name}`;
    if(mine)return `自己的建築 · Lv.${mine.level}`;
    if(['word','grammar','shop','training'].includes(tile.type))return `可收購 · ${tileCost(tile)} 旅費`;
    return tile.type==='event'?(['chance','island-fair'].includes(tile.id)?'命運卡 · 局勢變化':'機會卡 · 選擇與風險'):tile.type==='boss'?'冒險卡 · 做出你的選擇':'起點補給';
  };
  const scene=<Suspense fallback={<div className="p3-scene-loading">正在準備你的小島…</div>}><IslandScene {...{tiles,position,owned,routes,paused,moving}} computers={gameStarted?computers.slice(0,computerCount):[]} petId={selectedPet?.petId||'bunny'} selected={inspected} onSelect={setInspected} preview={!gameStarted}/></Suspense>;
  return <div className="pet-island-3d">
    <Hdr t="🎲 寵物大富翁" onBack={exitGame}/><button className="p3-sound" aria-pressed={soundOn} onClick={toggleSound}>{soundOn?"♪ 音效開啟":"♪ 開啟音效"}</button>
    <header className="p3-titlebar"><div><span className="p3-eyebrow">LITTLE ISLAND CLUB</span><h1>{!gameStarted?'把小島，變成你的模樣。':result?'把這一趟，好好收藏。':'下一站，由你決定。'}</h1></div><span className="p3-season">海風小鎮 <i>SEASON 01</i></span></header>
    {result?<div className="p3-result" data-testid="pet-monopoly-result"><div className="p3-result-scene">{scene}<div className="p3-result-badge">{result.goalDone?'✦':'⚑'}<b>{result.goalDone?'島主挑戰達成':'完成環島旅行'}</b></div></div><section>
      <span className="p3-eyebrow">YOUR ISLAND STORY</span><h2 ref={resultTitleRef} tabIndex={-1}>{result.rounds} 回合，順利抵達終點</h2><p>建成 {Object.keys(owned).length} 棟建築 · {result.rankings[0]?.id==='player'?'本局資產冠軍':'下次挑戰資產冠軍'}</p>
      <div className="p3-result-goal"><b>{activeGoal.icon} {activeGoal.name}</b><span>{result.goalProgress} / {activeGoal.target} · {result.goalDone?'完成':'下次再挑戰'}</span></div>
      <div className="p3-earned"><span>已存入你的錢包</span><strong>+{result.coins}<small>金幣</small></strong><p>完成 12{result.rankings[0]?.id==='player'?' ＋ 冠軍 6':''}{result.goalDone?' ＋ 島主挑戰 8':''}</p></div>
      <div className="p3-rankings" data-testid="pet-monopoly-rankings"><h3>小島資產排名</h3>{result.rankings.map((r,i)=><div key={r.id}><b>0{i+1}</b><span>{r.name}</span><strong>{r.score}</strong></div>)}</div>
      <p className="p3-fineprint">本局學習 XP +{result.xp}，寵物 XP +{result.petExp}。島嶼旅費只在本局使用。</p><button className="p3-primary" onClick={()=>{setResult(null);setGameStarted(false)}}>再選一趟旅程</button><button className="p3-text-button" onClick={()=>onNavigate?onNavigate('pets','activities'):onBack?.()}>帶夥伴回小家園 →</button>
    </section></div>:<>
      {gameStarted&&<div className="p3-game-top" data-testid="pet-monopoly-game-hud"><div><span>YOUR TURN</span><h2>第 {Math.min(roundLimit,turn+1)} / {roundLimit} 回合</h2></div><div><span>玩家旅費</span><b data-testid="pet-monopoly-player-cash">{gameCoins}</b></div><div><span>每輪建築收入</span><b>+{income.total}</b></div><button className="p3-icon-button" onClick={()=>pauseGame()} aria-label="暫停遊戲">Ⅱ</button><span className="p3-accessible">起始旅費 {stake} · {computers.slice(0,computerCount).map(cpu=>`${cpu.name} ${cpu.coins}`).join(' · ')}</span></div>}
      <div className={`p3-layout ${gameStarted?'is-playing':'is-setup'}`} inert={paused?'':undefined}>
        <section className="p3-world" data-testid={gameStarted?'pet-monopoly-board':undefined} aria-label="寵物大富翁棋盤">
          {scene}
          {gameStarted&&screenEffect&&!paused&&<div key={screenEffect.id} className={`p3-fx is-${screenEffect.kind}`} data-testid="pet-island-fx" aria-hidden="true"><div className="p3-fx-ripple"/>{Array.from({length:12},(_,i)=><i key={i} style={{'--angle':`${i*30}deg`,'--hue':`${i*27}`}}/>)}<strong>{screenEffect.icon} {screenEffect.title}</strong></div>}
          {gameStarted&&<div className="p3-inspect" data-testid="pet-island-inspect"><span className="p3-place-number">{String(inspectIndex+1).padStart(2,'0')}</span><div><small>{property?'你的建築':owner?owner.name:typeMeta[inspectTile.type]?.label}</small><h3>{inspectTile.name}{property&&` · Lv.${property.level}`}</h3><p>{property?`每輪收入 +${property.level*2} · 收租 ${tileRent(inspectTile,property)}`:owner?`停留支付 ${Math.ceil(tileRent(inspectTile,{level:1})*(owner.rent?2:1)*(cardEffects.shield?.5:1))} 旅費`:inspectTile.hint}</p></div>{property&&property.level<3?<button className="p3-build" disabled={!idle||upgradedTurn===turn||gameCoins<cost} onClick={()=>upgradeCurrentProperty(inspectTile.id)}>{upgradedTurn===turn?'下輪再升級':`升級 ${cost} 旅費`} <span>↑</span></button>:<span className="p3-place-icon">{inspectTile.icon}</span>}</div>}
          {!gameStarted&&<div className="p3-world-caption"><b>一隻小夥伴，一整座可能。</b><span>24 個地點 · 可旋轉的立體棋盤</span></div>}
        </section>
        {!gameStarted?<aside className="p3-setup" data-testid="pet-monopoly-setup"><span className="p3-eyebrow">開局設定 / MAKE IT YOURS</span><h2>今天，想當什麼島主？</h2><p className="p3-intro">選路搶地、道具攻防，打造你的小島版圖。</p>
          <div className="p3-goal-picker" aria-label="本局島主挑戰">{ISLAND_GOALS.map(goal=><button key={goal.id} aria-pressed={goalId===goal.id} onClick={()=>setGoalId(goal.id)}><span>{goal.icon}</span><div><b>{goal.name}</b><small>{goal.description}</small></div><i>{goalId===goal.id?'✓':'○'}</i></button>)}</div>
          <label className="p3-partner"><PetCompanion petId={selectedPet?.petId||'bunny'} size={45} animate={false}/><span>同行夥伴<select aria-label="同行夥伴" value={pets.length?petIndex:'solo'} onChange={event=>setPetIndex(Number(event.target.value))}>{pets.length?pets.map((pet,i)=><option key={pet.petId} value={i}>{pet.nickname||v.getPetName(pet)}</option>):<option value="solo">小兔嚮導陪你玩</option>}</select></span></label>
          <div className="p3-duration" aria-label="旅程長度">{[6,10].map(value=><button key={value} aria-pressed={roundLimit===value} onClick={()=>setRoundLimit(value)} aria-label={`${value} 回合 · ${value===6?'輕鬆散步':'深度探索'}`}><b>{value} 回合</b><span>{value===6?'小小試身手':'好好蓋座島'}</span></button>)}</div>
          <details className="p3-rules"><summary>對手、旅費與玩法</summary><p>同行電腦玩家</p><small>電腦 1 隨機選路；電腦 2、3 會避租搶地。</small><div className="p3-options">{[1,2,3].map(n=><button key={n} aria-pressed={setupComputerCount===n} data-testid={`pet-monopoly-setup-cpu-${n}`} onClick={()=>setSetupComputerCount(n)}>{n} 位</button>)}</div><p>局內起始旅費</p><div className="p3-options">{[100,300,500].map(n=><button key={n} aria-pressed={stake===n} data-testid={`pet-monopoly-setup-stake-${n}`} onClick={()=>setStake(n)}>{n}</button>)}</div><ol><li>擲出兩個骰子，選一個落點。可先看購地成本與租金。</li><li>抵達無主地就能買。機會卡做選擇；命運卡改變局勢，兩副各 6 張，抽完才重新洗牌。</li><li>每輪結束，所有玩家每級建築收入 2。同類兩棟組成街區，再加 4。</li><li>擲骰前可升級一次、買一張道具、用一張道具。遙控骰子指定落點，路障阻擋對手。</li><li>旅費歸零仍可用事件與收入翻身，不淘汰。最後以旅費＋地產排名。完成 +12、冠軍 +6、島主挑戰 +8 錢包金幣。</li></ol><span data-testid="pet-monopoly-event-deck-size" data-event-count={eventCount}>機會／命運 · {eventCount} 種事件</span></details>
          <label className="p3-learning-toggle"><input type="checkbox" checked={learning} onChange={e=>setLearning(e.target.checked)}/> 英文小彩蛋（自由挑戰，僅加學習 XP）</label><div className="p3-launch"><button className="p3-primary" data-testid="pet-monopoly-start" onClick={startGame}>出發，這次我當島主 <span>→</span></button><span>免費遊玩 · 不花錢包金幣</span></div>
        </aside>:<aside className="p3-play-panel">
          <div className={`p3-goal-status ${goalDone?'is-done':''}`} data-testid="pet-island-goal"><span>{activeGoal.icon}</span><div><b>{activeGoal.name}</b><small>{activeGoal.description}</small><div className="p3-progress"><i style={{width:`${Math.min(100,goalProgress/activeGoal.target*100)}%`}}/></div></div><strong>{goalDone?'✓':`${goalProgress}/${activeGoal.target}`}</strong></div>
          <div className="p3-actions pm-action-dock" data-testid="pet-monopoly-overlay" data-panel="dock" data-state={encounter?'event':toolTarget?'target':routes.length?'route':moving?'moving':pending?'question':answerReview?'review':offer?'offer':'idle'}>
            {encounter?<section className={`p3-event-card is-${encounter.kind}`} data-testid="pet-island-event-card"><span className="p3-eyebrow">{encounter.kind==='fate'?'✦ FATE / 命運':encounter.kind==='chance'?'? CHANCE / 機會':'到站了'}</span><div className="p3-event-symbol" aria-hidden="true">{encounter.kind==='fate'?'✦':'?'}</div><h2>{encounter.title}</h2><p>{encounter.text}</p>{encounter.options.map((option,i)=><button key={i} className="p3-event-option" data-testid={`pet-island-event-option-${i}`} disabled={(!!option.cost&&!option.debt&&gameCoins<option.cost)||(!!option.spendCard&&!cardHand[option.spendCard])} onClick={()=>resolveEvent(option)}>{option.label}<span>→</span></button>)}</section>
            :toolTarget?<section className="p3-event-card"><span className="p3-eyebrow">路障卡 / 選擇對手</span><h2>要擋住誰的下一步？</h2><p>對手停走一次，仍可領取建築收入。</p>{computers.slice(0,computerCount).filter(cpu=>cpu.active!==false).map(cpu=><button className="p3-event-option" key={cpu.id} disabled={cpu.blocked} data-testid={`pet-island-block-${cpu.id}`} onClick={()=>blockOpponent(cpu.id)}>{cpu.name} · 現金 {cpu.coins}<span>{cpu.blocked?'已被擋住':'設置路障'}</span></button>)}<button className="p3-text-button" onClick={()=>setToolTarget(false)}>取消，保留道具</button></section>
            :routes.length?<section className="p3-route-choice" data-testid="pet-island-routes"><span className="p3-eyebrow">THE CHOICE IS YOURS</span><h2>想往哪裡走？</h2><p>點選一個骰子，就會沿著路線前進。</p>{routes.map((route,i)=><button key={route.steps} data-testid={`pet-island-route-${i}`} onMouseEnter={()=>setInspected(route.index)} onFocus={()=>setInspected(route.index)} onClick={()=>moveAlongRoute(route)}><Dice value={route.face}/><div><small>前進 {route.steps} 格{route.steps!==route.face?' · 加速 +2':''}</small><b>{tiles[route.index].name}</b><span>{describeRoute(route)}</span></div><strong>↗</strong></button>)}</section>
            :moving?<section className="p3-moving" data-testid="pet-monopoly-moving"><Dice value={Number(moving.dice)||1}/><span className="p3-eyebrow">ON THE WAY</span><h2>{moving.actor==='player'?'玩家移動':`${moving.name} 的回合`}</h2><p>{moving.to?`前往 ${moving.to}`:'正在想下一步…'}</p><div className="p3-step-dots">{Array.from({length:moving.total||3},(_,i)=><i key={i} className={i<moving.step?'is-done':''}/>)}</div><button className="p3-primary" data-testid="pet-monopoly-roll" aria-label="擲骰" disabled>{moving.dice||'…'}</button></section>
            :pending?<section className="p3-question" data-testid="pet-monopoly-question-word" data-word={pending.question.word?.w||''}><span className="p3-eyebrow">{pending.tile.icon} {pending.tile.name} / 英文挑戰</span><span className="p3-question-tag" data-testid="pet-monopoly-question-mode">{pending.question.modeLabel||'文法挑戰'}</span><h2 data-testid="pet-monopoly-question-prompt">{pending.question.prompt}</h2><p data-testid="pet-monopoly-question-sub">{pending.question.sub}</p><div className="p3-answers">{pending.question.choices.map((choice,i)=><button className="pm-choice" key={`${choice}-${i}`} data-testid={i===pending.question.answer?'pet-monopoly-choice-correct':undefined} onClick={()=>answer(i)}><span>{String.fromCharCode(65+i)}</span>{choice}</button>)}</div><small>答對 +5 學習 XP；答錯不扣錢，也不影響遊戲。</small><button className="p3-text-button" onClick={skipLearning}>先繼續玩 →</button></section>
            :answerReview?<section className="p3-review"><span className="p3-eyebrow">再帶走一個新單字</span><h2>正確答案是<br/>{answerReview.explain}</h2><p>{answerReview.word?.m}</p><p>{answerReview.word?.ex||answerReview.sub}</p><button className="p3-primary" data-testid="pet-monopoly-review-next" onClick={()=>{setAnswerReview(null);queueComputerRound()}}>記住了，繼續這一輪 →</button></section>
            :offer&&offerTile?<section className="p3-offer" data-testid="pet-monopoly-deal"><span className="p3-eyebrow">收購機會 / BUILD SOMETHING</span><div className="p3-offer-house">⌂</div><h2>{offerTile.name}</h2><p>讓下一輪，開始有自己的收入。</p><div className="p3-offer-stats"><div><span>收購</span><b>{offer.cost}</b></div><div><span>每輪收入</span><b>+2</b></div><div><span>每次收租</span><b>+{tileRent(offerTile,{level:1})}</b></div></div><p>買下後剩 {Math.max(0,gameCoins-offer.cost)} 旅費。兩棟同類建築的街區收入再 +4。</p><button className="p3-primary" data-testid="pet-monopoly-buy" disabled={gameCoins<offer.cost} onClick={buyProperty}>收購 · {offer.cost} 旅費</button><button className="p3-text-button" data-testid="pet-monopoly-skip-buy" onClick={skipOffer}>保留旅費，繼續 →</button></section>
            :<section className="p3-your-turn"><span className="p3-eyebrow">MAKE YOUR NEXT MOVE</span><h2>一點運氣，<br/>一點你的主意。</h2><p>{Object.keys(owned).length?'點選自己的建築，可以先升級；或選張工具卡，再出發。':'先選工具卡，或直接擲骰。兩個落點，自己選一個。'}</p><button className="p3-primary p3-roll" data-testid="pet-monopoly-roll" aria-label="擲骰" disabled={!!rentDialog||paused} onClick={roll}><Dice value={5}/><b>擲骰，看看下一站</b><span>→</span></button></section>}
            {learning&&idle&&<button className="p3-text-button" data-testid="pet-island-learning" disabled={learningUsed===turn} onClick={openLearning}>{learningUsed===turn?'本回合小彩蛋已完成':'想順便學一個英文？ +5 XP'}</button>}<p className="p3-feedback" data-testid="pet-monopoly-feedback" role="status">{feedback}</p>
          </div>
          <div className="p3-rival-status">{computers.slice(0,computerCount).map(cpu=><span key={cpu.id}>{cpu.name} · {tiles[cpu.position]?.name}{cpu.blocked?' ⛔ 停走':''}{cpu.shield?' ◇ 護盾':''}{cpu.rent?' $ 租金加倍':''}</span>)}</div><div className="p3-tools" data-testid="pet-monopoly-cards"><div className="p3-tools-label">口袋裡的好主意 <span>每回合一張</span></div>{cards.map(card=><button key={card.id} data-testid={`pet-monopoly-card-${card.id}`} aria-label={`${card.name} ${card.desc}`} aria-pressed={!!cardEffects[card.id]} disabled={!idle||!!moving||!!pending||!!answerReview||!!rentDialog||routes.length>0||cardUsedTurn===turn||!cardHand[card.id]||cardEffects[card.id]} onClick={()=>useCard(card.id)}><i>{card.icon}</i><div><b>{card.name}</b><small>{card.desc}</small></div><span>x{cardHand[card.id]||0}</span></button>)}</div>
          <details className="p3-tool-shop"><summary>道具商店 <span>每回合可買一張</span></summary><p>使用局內旅費。每種最多持有 3 張；買完可立即使用。</p>{cards.map(card=><button key={card.id} data-testid={`pet-island-shop-${card.id}`} disabled={!idle||shopUsed===turn||gameCoins<card.price||(cardHand[card.id]||0)>=3} onClick={()=>buyTool(card.id)}><span>{card.icon} {card.name}</span><b>{card.price} 旅費</b></button>)}</details>
          {cards.some(card=>cardEffects[card.id])&&<p className="p3-tool-active" data-testid="pet-monopoly-card-active">已啟用：{cards.filter(card=>cardEffects[card.id]).map(card=>card.name).join('、')}</p>}
          {eventFlash&&<p className="p3-notice" data-testid="pet-monopoly-event">{eventFlash.title} · {eventFlash.text}</p>}
          {rentFlash&&<p className="p3-notice" data-testid="pet-monopoly-rent" data-effect={rentFlash.effect}>{rentFlash.title} · {rentFlash.text}</p>}
          {screenEffect&&<div className="p3-last-event" data-testid="pet-monopoly-screen-effect" data-effect={screenEffect.kind}><span data-testid={screenEffect.kind==='dice'?'pet-monopoly-dice-effect':screenEffect.source==='card'?'pet-monopoly-card-burst':undefined} data-effect={screenEffect.effect||screenEffect.kind}>{screenEffect.icon} {screenEffect.title} · {screenEffect.value}</span></div>}
        </aside>}
      </div>
      {gameStarted&&<div className="p3-bottom"><div className="p3-rankings" data-testid="pet-monopoly-rankings"><h3>小島資產排名</h3>{rankings.map((rank,i)=><div key={rank.id}><b>0{i+1}</b><span>{rank.name}</span><strong>{rank.score}</strong></div>)}</div><details className="p3-map-directory"><summary>地圖導覽與建築清單 <span>24 PLACES</span></summary><p>也可以使用這份清單選取建築。綠色是自己的建築，藍色是對手的。</p><div>{tiles.map((tile,i)=>{const property=owned[tile.id],cpu=computers.slice(0,computerCount).find(c=>c.active!==false&&c.owned?.includes(tile.id));return <button key={tile.id} className={`pm-tile ${position===i?'is-active':''}`} data-testid={`pet-monopoly-tile-${tile.id}`} data-owner={property?'player':cpu?.id||'none'} data-owner-level={property?.level||(cpu?1:0)} onClick={()=>{setInspected(i);document.querySelector('.p3-inspect')?.scrollIntoView?.({behavior:'smooth',block:'center'})}}><small>{String(i+1).padStart(2,'0')}</small><span>{tile.name}</span>{property?<b data-testid="pet-monopoly-player-owner">Lv.{property.level}</b>:cpu?<b data-testid="pet-monopoly-cpu-owner">{cpu.name}</b>:<i>{tile.icon}</i>}</button>})}</div><span data-testid="pet-monopoly-event-deck-size" data-event-count={eventCount}>機會／命運 · {eventCount} 種事件</span>{computers.slice(0,computerCount).map(cpu=><span className="p3-accessible" key={cpu.id} data-testid={`pet-monopoly-cpu-status-${cpu.id}`} data-active={String(cpu.active!==false)}>{cpu.coins}</span>)}</details></div>}
      {rentDialog&&<dialog ref={rentRef} className="p3-modal p3-rent-modal" onCancel={event=>event.preventDefault()} aria-label="本次旅費結算" data-testid="pet-monopoly-rent-dialog" data-flow="paused"><span className="p3-eyebrow">小島上的一筆生意</span><h2>{rentDialog.kind==='rent-in'?'收到租金了！':'路過別人的建築'}</h2><strong className="p3-rent-value">{rentDialog.kind==='rent-in'?'+':'−'}{rentDialog.amount}<small>旅費</small></strong><p>{rentDialog.payer} → {rentDialog.payee} · {rentDialog.tileName}</p><p>{rentDialog.joke}</p><button autoFocus className="p3-primary" data-testid="pet-monopoly-rent-confirm" onClick={confirmRentMoment}>收到，繼續旅行</button></dialog>}
    </>}
    <dialog ref={pauseDialogRef} className="p3-modal p3-pause" aria-label="小島遊戲已暫停" onCancel={event=>{event.preventDefault();resumeGame()}}><span className="p3-eyebrow">TAKE A LITTLE BREAK</span><h2>{exitRequested?'要先結束這趟旅行嗎？':'小島會在這裡等你。'}</h2><p>繼續會回到剛才的位置。結束這局會放棄棋盤進度與完成金幣；已得到的 XP 與親密會保留。</p><button className="p3-primary" onClick={resumeGame}>繼續旅行</button><button className="p3-text-button" onClick={abandonGame}>結束這局，回準備頁</button></dialog>
  </div>;
}
