import { useEffect, useMemo, useRef, useState } from 'react';
import PracticeArt from '../components/PracticeArt.jsx';
import { achievementProgress, dailyProgress, nextAchievement, nonnegative, studyWeek } from '../data/studyProgress.js';

export default function ProgressJournal({ onBack, onOpen, onQuickStart, xp, streak, stats, daily, weakWords, history, achUnlocked, lv, deps }) {
  const { definitions, Hdr, c, levelName, shareLine } = deps;
  const alive = useRef(false);
  useEffect(() => { alive.current = true; return () => { alive.current = false; }; }, []);
  const today = dailyProgress(daily), week = useMemo(() => studyWeek(history, daily), [history, daily]);
  const [selectedDay, setSelectedDay] = useState(null), [copyStatus, setCopyStatus] = useState('');
  const rows = achievementProgress(definitions, achUnlocked, { ...stats, xp, streak }), earned = rows.filter(row => row.earned), next = nextAchievement(rows);
  const selected = week.find(day => day.key === selectedDay) || week.at(-1), activeDays = week.filter(day => day.done > 0).length;
  const weak = [...new Map((weakWords || []).filter(word => word?.w && (!word.level || word.level === lv)).map(word => [word.w.toLowerCase(), word])).values()].sort((a, b) => nonnegative(b.n) - nonnegative(a.n));
  const highlighted = (() => { try { const id = JSON.parse(localStorage.getItem('eg_featured_badge')); return earned.find(row => row.id === id) || earned[0]; } catch { return earned[0]; } })();
  const practiceGoal = row => row.module === 'srs' ? onQuickStart() : onOpen(row.module, row.group);
  const shareText = `EnglishGo 學習紀錄（這台裝置）\n今天的小目標：${today.done} / ${today.target} 步\n過去 7 天有 ${activeDays} 天留下學習紀錄\n累積 ${nonnegative(xp)} XP\n完成單字卡 ${nonnegative(stats?.srsRounds)} 輪\n收藏徽章 ${earned.length} 枚\n${levelName}待複習清單：${weak.length} 個單字\n\nhttps://englishgo-vevan.netlify.app`;
  const copy = async () => { try { if (!navigator.clipboard?.writeText) throw new Error(); await navigator.clipboard.writeText(shareText); if (alive.current) setCopyStatus('已複製，可以貼給家人看。'); } catch { if (alive.current) setCopyStatus('目前無法自動複製，可以選取下面的紀錄文字。'); } };
  return <div className="practice-world progress-journal">
    <Hdr t="📊 我的學習足跡" onBack={onBack} cl={c.cl} />
    <section className="practice-intro"><PracticeArt kind="review" complete={today.done >= today.target} /><div><span className="practice-eyebrow">今天一點點，累積看得見</span><h2>{today.done >= today.target ? '今天的小目標完成了' : today.done > 0 ? '已經踏出今天的一小步' : '從一個小練習開始吧'}</h2><p>{today.done >= today.target ? '可以休息一下，或去聽一首喜歡的歌。' : today.done ? `已完成 ${today.done} 步，還有 ${today.target - today.done} 步到今天的小目標。` : '沒有趕進度的壓力，先試 5 張單字卡就好。'}</p><progress className="practice-progress" value={today.done} max={today.target} aria-label="今天的小目標" /><div className="journal-today"><b>{today.done} / {today.target} 步</b><span>{today.percent}%</span></div><div className="practice-actions"><button className="practice-primary" onClick={today.done >= today.target ? () => onOpen('songs', 'read') : onQuickStart}>{today.done >= today.target ? '去聽一首歌 ♫' : '開始 5 張單字小任務'}</button>{today.done >= today.target && <button onClick={onBack}>休息一下</button>}</div></div></section>
    <section className="practice-config journal-week"><div className="journal-section-heading"><div><span className="practice-eyebrow">過去 7 天</span><h3>每一天的小腳印</h3></div><b>{activeDays} 天有紀錄</b></div><div className="journal-calendar" role="group" aria-label="選一天看學習紀錄">{week.map(day => <button key={day.key} aria-pressed={selected.key === day.key} aria-label={`${day.label}，${day.today ? '今天，' : ''}${day.done} 步`} onClick={() => setSelectedDay(day.key)}><span>{day.today ? '今天' : `週${day.weekday}`}</span><div className="journal-bar-space" aria-hidden="true"><i style={{ height: `${day.done ? Math.max(12, day.done / day.target * 100) : 3}%` }} /></div><b>{day.done ? `${day.done} 步` : '—'}</b><small>{day.label}</small></button>)}</div><div className="journal-day-detail" role="status"><b>{selected.label} · {selected.today ? '今天' : `星期${selected.weekday}`}</b><span>{selected.done ? `留下 ${selected.done} 步學習紀錄${selected.done >= selected.target ? '，當天小目標已完成。' : '。'}` : '還沒有這一天的學習紀錄。'}</span></div><p className="practice-save-note">這裡顯示每日目標進度，不是學會的單字數；今天的進度也會即時顯示。</p></section>
    <section className="journal-next-grid" aria-label="接下來可以練什麼"><div className="practice-config"><span className="practice-eyebrow">{levelName}的複習清單</span><h3>{weak.length ? '這幾個字，再見一次面' : '換個方式，讓英文更熟'}</h3><p>{weak.length ? `有 ${weak.length} 個單字可以再練習，先從熟悉的節奏開始。` : '可以開口說一句，也可以準備下次考試的單字。'}</p>{weak.length > 0 && <div className="journal-word-chips">{weak.slice(0, 5).map(word => <span key={word.w} lang="en">{word.w}</span>)}</div>}<div className="practice-actions"><button className="practice-primary" onClick={() => onOpen(weak.length ? 'weak' : 'speak', weak.length ? 'tools' : 'learn')}>{weak.length ? '看看複習清單' : '練習勇敢說出口'}</button><button onClick={() => onOpen('exam', 'learn')}>準備考試範圍</button></div></div><div className="practice-config"><span className="practice-eyebrow">{highlighted ? '我的展示徽章' : '從第一枚徽章開始'}</span><h3>{highlighted ? `${highlighted.icon} ${highlighted.name}` : '努力會留下小紀念'}</h3><p>{next ? `下一個小目標：${next.name}，還差 ${next.remaining} ${next.unit}。` : '目前的徽章都收集到了，繼續照自己的步調學習。'}</p>{next && <progress className="practice-progress" value={Math.min(next.current, next.target)} max={next.target} aria-label={`${next.name}目標進度`} />}<div className="practice-actions">{next && <button className="practice-primary" onClick={() => practiceGoal(next)}>{next.action}</button>}<button onClick={() => onOpen('achievements', 'tools')}>看看我的徽章</button></div></div></section>
    <section className="practice-config"><span className="practice-eyebrow">這台裝置 · 所有年級累積</span><h3>每一種練習，都有足跡</h3><div className="journal-metrics">{[[nonnegative(xp), '累積 XP'], [nonnegative(stats?.srsRounds), '完成單字卡輪數'], [nonnegative(stats?.perfectQuiz), '測驗滿分次數'], [nonnegative(stats?.dictDone), '聽寫完成次數'], [nonnegative(stats?.scramDone), '重組完成次數'], [earned.length, '已收藏徽章']].map(([value, label]) => <div key={label}><b>{value}</b><span>{label}</span></div>)}</div><p className="practice-save-note">不同練習的題數可能不同，所以不把輪數換算成已學會的單字數。</p></section>
    <details className="practice-config journal-sharing"><summary>把進步給家人看看</summary><p>先看看要分享的內容，再選擇複製或開啟 LINE。</p><textarea aria-label="要分享的學習紀錄" readOnly value={shareText} /><div className="practice-actions"><button onClick={copy}>複製學習紀錄</button><button onClick={() => shareLine(shareText, 'https://englishgo-vevan.netlify.app')}>開啟 LINE 分享 ↗</button></div>{copyStatus && <p role="status">{copyStatus}</p>}</details><p className="practice-save-note">學習紀錄保存在這台裝置。換裝置或清除瀏覽器資料後，這裡可能看不到先前的紀錄。</p>
  </div>;
}
