-- Elementary watercolor illustrations, batch 3. Upload assets before metadata.
BEGIN;
UPDATE public.word_bank SET example = 'Let''s play with the ball.', example_zh = '我們一起玩球吧。'
WHERE level = 'elementary' AND word = 'ball' AND example = 'a ball of spittle; a fecal ball';
INSERT INTO public.word_illustrations (id, level, word, sort_order, sense, alt_zh, example, example_zh, image_url, local_path, style, version) VALUES
('elementary-bag-01-v1', 'elementary', 'bag', 1, '袋子', '一個有兩個提把的黃色帆布袋。', 'This is my bag.', '這是我的袋子。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/bag-01-v1.webp', '/images/vocabulary/elementary/bag-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-ball-01-v1', 'elementary', 'ball', 1, '球', '一顆有紅色、黃色與藍綠色拼片的球。', 'The ball is round.', '這顆球是圓的。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/ball-01-v1.webp', '/images/vocabulary/elementary/ball-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-bread-01-v1', 'elementary', 'bread', 1, '麵包', '一條金黃色麵包，前方放著兩片切下的麵包。', 'Here is some bread.', '這裡有一些麵包。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/bread-01-v1.webp', '/images/vocabulary/elementary/bread-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-egg-01-v1', 'elementary', 'egg', 1, '蛋', '一顆完整的淺褐色雞蛋。', 'This is an egg.', '這是一顆蛋。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/egg-01-v1.webp', '/images/vocabulary/elementary/egg-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-flower-01-v1', 'elementary', 'flower', 1, '花', '一朵有黃色花心、粉紅花瓣與綠色莖葉的花。', 'The flower is pink.', '這朵花是粉紅色的。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/flower-01-v1.webp', '/images/vocabulary/elementary/flower-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-hat-01-v1', 'elementary', 'hat', 1, '帽子', '一頂繫著藍綠色緞帶的寬邊草帽。', 'My hat has a ribbon.', '我的帽子上有一條緞帶。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/hat-01-v1.webp', '/images/vocabulary/elementary/hat-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-milk-01-v1', 'elementary', 'milk', 1, '牛奶', '透明玻璃杯與玻璃奶瓶裡裝著白色牛奶。', 'There is milk in the glass.', '玻璃杯裡有牛奶。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/milk-01-v1.webp', '/images/vocabulary/elementary/milk-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-tree-01-v1', 'elementary', 'tree', 1, '樹', '一棵枝葉茂密的大樹，底部有少許青草。', 'The tree has green leaves.', '這棵樹有綠色的葉子。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/tree-01-v1.webp', '/images/vocabulary/elementary/tree-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-in-01-v1', 'elementary', 'in', 1, '在……裡面', '一隻橘白色的貓坐在打開的紙箱裡。', 'The cat is in the box.', '貓在箱子裡。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/in-01-v1.webp', '/images/vocabulary/elementary/in-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-in-02-v1', 'elementary', 'in', 2, '在……裡面', '三顆紅蘋果放在編織籃子裡。', 'The apples are in the basket.', '蘋果在籃子裡。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/in-02-v1.webp', '/images/vocabulary/elementary/in-02-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-on-01-v1', 'elementary', 'on', 1, '在……上面', '一本藍綠色的書平放在木桌上。', 'The book is on the table.', '書在桌上。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/on-01-v1.webp', '/images/vocabulary/elementary/on-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-on-02-v1', 'elementary', 'on', 2, '在……上面', '一隻橘白色的貓坐在木椅的椅面上。', 'The cat is on the chair.', '貓在椅子上。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/on-02-v1.webp', '/images/vocabulary/elementary/on-02-v1.webp', 'watercolor-pencil-v1', 1)
ON CONFLICT (id) DO NOTHING;
COMMIT;
