-- EnglishGo - Elementary supplemental word seed
-- Generated from src/data/extraWords.js
-- Safe to re-run: existing (word, level) rows are preserved.

INSERT INTO public.word_bank (word, pos, meaning, level, ceec_level, example, example_zh, category, phonetic, forms, collocations) VALUES
('after','prep.','在...之後','elementary',1,'We play games after English class.','英文課後我們玩遊戲。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('afternoon','n.','下午','elementary',1,'In the afternoon, we play word games.','下午我們玩單字遊戲。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('again','adv.','再一次','elementary',1,'Please read the sentence again.','請再讀一次這個句子。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('alive','adj.','活著的','elementary',1,'The forest feels alive after the magic returns.','魔法回來後，森林充滿生命力。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('alone','adj.','獨自的','elementary',1,'Lily is not alone because Coco helps her.','莉莉並不孤單，因為可可幫助她。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('amazing','adj.','驚人的','elementary',1,'The amazing crystal shines like a star.','驚人的水晶像星星一樣發光。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('ancient','adj.','古老的','elementary',1,'Ancient stones stand near the hidden cave.','古老的石頭立在隱藏洞穴旁。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('and','conj.','和；而且','elementary',1,'I read and write after school.','我放學後閱讀和書寫。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('answer','v.','回答','elementary',1,'She answers the question in English.','她用英文回答問題。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('arm','n.','手臂','elementary',1,'She carries the doll in her arm.','她用手臂抱著娃娃。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('ask','v.','問','elementary',1,'I ask my teacher for help.','我向老師請求幫助。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('baby','n.','寶寶','elementary',1,'The baby smiles when we sing softly.','我們輕聲唱歌時，寶寶微笑了。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('bad','adj.','壞的','elementary',1,'Bad weather keeps us inside today.','今天的壞天氣讓我們待在室內。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('bag','n.','袋子；書包','elementary',1,'My school bag is heavy today.','我的書包今天很重。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('balance','n.','平衡','elementary',1,'The small shadow finds balance with the light.','小影子在光中找到平衡。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('banana','n.','香蕉','elementary',1,'A monkey eats a banana in the zoo.','猴子在動物園吃香蕉。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('bathroom','n.','浴室','elementary',1,'I wash my face in the bathroom.','我在浴室洗臉。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('bear','n.','熊','elementary',1,'The bear sits beside a tall tree.','熊坐在高樹旁。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('beautiful','adj.','美麗的','elementary',1,'A beautiful rainbow appears after the rain.','雨後出現一道美麗的彩虹。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('because','conj.','因為','elementary',1,'I smile because I know the answer.','我微笑，因為我知道答案。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('bed','n.','床','elementary',1,'I put my doll on the bed.','我把娃娃放在床上。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('bedroom','n.','臥室','elementary',1,'I read a book in my bedroom.','我在臥室讀書。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('bee','n.','蜜蜂','elementary',1,'A bee flies around the yellow flower.','蜜蜂繞著黃色花朵飛。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('beneath','prep.','在...下面','elementary',1,'A shining key waits beneath the water.','一把發亮的鑰匙在水下等待。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('bike','n.','腳踏車','elementary',1,'I ride my bike to the library.','我騎腳踏車去圖書館。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('bird','n.','鳥','elementary',1,'A bird sings in the tree every morning.','一隻鳥每天早上在樹上唱歌。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('black','n./adj.','黑色；黑色的','elementary',1,'My black pen is on the desk.','我的黑筆在書桌上。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('blue','n./adj.','藍色；藍色的','elementary',1,'The blue bag is under the chair.','藍色的書包在椅子下面。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('bottom','n.','底部','elementary',1,'The bell is at the bottom of the river.','鈴鐺在河底。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('boy','n.','男孩','elementary',1,'The boy asks a question in English.','那個男孩用英文問問題。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('branch','n.','樹枝','elementary',1,'A long branch helps Lily reach the bell.','長樹枝幫助莉莉拿到鈴鐺。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('brave','adj.','勇敢的','elementary',1,'The brave child speaks in front of the class.','勇敢的孩子在全班面前說話。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('bread','n.','麵包','elementary',1,'She puts an egg on the bread.','她把蛋放在麵包上。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('breakfast','n.','早餐','elementary',1,'Breakfast gives me energy for school.','早餐給我上學的精神。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('brother','n.','兄弟','elementary',1,'My brother rides his bike to the park.','我兄弟騎腳踏車去公園。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('brown','n./adj.','棕色；棕色的','elementary',1,'The brown dog runs beside me.','那隻棕色的狗在我旁邊跑。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('brush','v.','刷','elementary',1,'I brush my teeth before I sleep.','我睡覺前刷牙。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('bus','n.','公車','elementary',1,'The bus comes at seven thirty.','公車七點半來。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('but','conj.','但是','elementary',1,'The test is hard, but I try.','測驗很難，但我會嘗試。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('buy','v.','買','elementary',1,'We buy fruit at the market.','我們在市場買水果。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('by','prep.','在...旁邊；藉由','elementary',1,'Lily sits by the quiet river.','莉莉坐在安靜河流旁。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('cake','n.','蛋糕','elementary',1,'We share a cake at the birthday party.','我們在生日派對分享蛋糕。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('candy','n.','糖果','elementary',1,'I keep one candy in my bag.','我在書包裡放一顆糖果。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('car','n.','車子','elementary',1,'The red car stops near the school.','紅色車子停在學校附近。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('carry','v.','攜帶','elementary',1,'He carries a heavy bag to school.','他背著很重的書包去上學。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('cat','n.','貓','elementary',1,'The cat likes to sleep on the sofa.','貓喜歡睡在沙發上。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('cave','n.','洞穴','elementary',1,'The hidden cave is behind the rock wall.','隱藏洞穴在岩壁後面。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('chair','n.','椅子','elementary',1,'A blue bag is under the chair.','藍色書包在椅子下面。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('chicken','n.','雞；雞肉','elementary',1,'A chicken walks near the farm gate.','一隻雞走在農場大門旁。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('child','n.','小孩','elementary',1,'The child draws a flower on the page.','那個小孩在頁面上畫一朵花。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('children','n.','小孩們','elementary',1,'The children play games after class.','孩子們下課後玩遊戲。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('choose','v.','選擇','elementary',1,'Choose the moon stone to open the path.','選擇月亮石來打開道路。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('class','n.','班級；課','elementary',1,'Our class reads together every Friday.','我們班每週五一起閱讀。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('classroom','n.','教室','elementary',1,'Our classroom has a big window.','我們的教室有一扇大窗戶。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('claw','n.','爪子','elementary',1,'A dark claw reaches toward the crystal.','一隻黑色爪子伸向水晶。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('clean','adj./v.','乾淨的；打掃','elementary',1,'Please keep your desk clean after lunch.','午餐後請保持你的書桌乾淨。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('close','v.','關閉','elementary',1,'Close the window when the wind is strong.','風很大時把窗戶關上。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('cold','adj.','冷的','elementary',1,'I wear a jacket on a cold morning.','寒冷的早晨我會穿夾克。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('come','v.','來','elementary',1,'Please come to the classroom before class.','請在上課前來教室。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('complete','adj./v.','完整的；完成','elementary',1,'I complete my homework before dinner.','我在晚餐前完成作業。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('cook','v.','煮飯','elementary',1,'My dad cooks soup in the kitchen.','我爸爸在廚房煮湯。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('cookie','n.','餅乾','elementary',1,'The cookie is sweet and small.','這片餅乾又甜又小。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('cool','adj.','涼爽的；酷的','elementary',1,'A cool wind blows after the rain.','雨後吹來一陣涼爽的風。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('courage','n.','勇氣','elementary',1,'Lily''s courage helps her face the shadow.','莉莉的勇氣幫助她面對影子。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('cow','n.','牛','elementary',1,'The cow eats grass on the farm.','牛在農場吃草。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('crystal','n.','水晶','elementary',1,'The crystal shines in the hidden cave.','水晶在隱藏洞穴中發光。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('curious','adj.','好奇的','elementary',1,'The curious girl opens the old book carefully.','好奇的女孩小心地打開那本舊書。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('cute','adj.','可愛的','elementary',1,'The cute puppy follows the girl home.','那隻可愛的小狗跟著女孩回家。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('dad','n.','爸爸','elementary',1,'Dad plays basketball with me on Sunday.','爸爸星期日和我打籃球。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('dance','v.','跳舞','elementary',1,'The children dance when the music starts.','音樂開始時孩子們跳舞。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('day','n.','天；日子','elementary',1,'A sunny day is good for a picnic.','晴天很適合野餐。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('desk','n.','書桌','elementary',1,'My pencil is beside the desk.','我的鉛筆在書桌旁。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('destroy','v.','破壞','elementary',1,'The shadow wants to destroy the forest magic.','影子想破壞森林魔法。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('dinner','n.','晚餐','elementary',1,'We talk about our day at dinner.','我們在晚餐時聊今天的事。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('dirty','adj.','髒的','elementary',1,'My shoes are dirty after playing soccer.','我踢完足球後鞋子很髒。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('disappear','v.','消失','elementary',1,'The shadow disappears when the light shines.','光照耀時影子消失了。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('dive','v.','潛水','elementary',1,'The frog can dive into the cool water.','青蛙可以潛入涼涼的水中。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('dog','n.','狗','elementary',1,'My dog runs with me in the park.','我的狗和我在公園裡跑。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('door','n.','門','elementary',1,'Please close the door quietly.','請輕輕關門。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('draw','v.','畫畫','elementary',1,'Draw a small bird in your notebook.','在筆記本裡畫一隻小鳥。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('drink','v.','喝','elementary',1,'I drink water after I play soccer.','我踢足球後喝水。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('duck','n.','鴨子','elementary',1,'The duck swims across the pond.','鴨子游過池塘。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('ear','n.','耳朵','elementary',1,'I listen with my left ear.','我用左耳聽。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('early','adj./adv.','早的','elementary',1,'I get to school early on Monday.','星期一我很早到學校。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('easy','adj.','簡單的','elementary',1,'This easy sentence helps me read faster.','這個簡單的句子幫助我讀得更快。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('echo','n.','回音','elementary',1,'Lily hears an echo inside the cave.','莉莉在洞穴裡聽見回音。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('edge','n.','邊緣','elementary',1,'Lily stands at the edge of the forest.','莉莉站在森林邊緣。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('egg','n.','蛋','elementary',1,'There is one egg in my lunch box.','我的便當盒裡有一顆蛋。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('elephant','n.','大象','elementary',1,'The elephant uses its long nose.','大象使用牠長長的鼻子。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('entrance','n.','入口','elementary',1,'The cave entrance is cold and dark.','洞穴入口又冷又暗。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('eraser','n.','橡皮擦','elementary',1,'I use an eraser to fix my mistake.','我用橡皮擦修正錯誤。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('evening','n.','傍晚；晚上','elementary',1,'In the evening, Dad reads with me.','晚上爸爸和我一起閱讀。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('evil','adj.','邪惡的','elementary',1,'The evil shadow tries to steal the light.','邪惡的影子想偷走光。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('explore','v.','探索','elementary',1,'Lily explores the forest after school.','莉莉放學後探索森林。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('eye','n.','眼睛','elementary',1,'Close one eye and look at the picture.','閉上一隻眼睛看這張圖片。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('face','n.','臉','elementary',1,'I wash my face every morning.','我每天早上洗臉。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('fairy','n.','小精靈','elementary',1,'A little fairy hides under a mushroom.','一位小精靈躲在蘑菇下面。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('family','n.','家人；家庭','elementary',1,'My family eats dinner together at home.','我的家人在家一起吃晚餐。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('fast','adj.','快的','elementary',1,'The bus is fast in the morning.','早上的公車開得很快。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('father','n.','爸爸；父親','elementary',1,'My father drives us to the zoo.','我爸爸開車帶我們去動物園。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('favorite','adj./n.','最喜歡的','elementary',1,'My favorite animal is the elephant.','我最喜歡的動物是大象。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('feet','n.','腳','elementary',1,'My feet are tired after the long walk.','走了很久後我的腳很累。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('find','v.','找到','elementary',1,'I find my pencil under the desk.','我在書桌下面找到鉛筆。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('fish','n.','魚','elementary',1,'The fish swims in the blue river.','魚在藍色河裡游泳。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('flower','n.','花','elementary',1,'The flower opens in the warm sun.','花在溫暖的陽光下綻放。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('fly','v.','飛','elementary',1,'Birds fly high in the blue sky.','鳥兒在藍天中高飛。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('foot','n.','腳','elementary',1,'Put your right foot on the line.','把你的右腳放在線上。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('force','n.','力量','elementary',1,'Do not use force to open the old gate.','不要用力量打開舊大門。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('forest','n.','森林','elementary',1,'The forest is full of tall trees.','森林裡滿是高大的樹。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('full','adj.','飽的；滿的','elementary',1,'I am full after eating noodles for lunch.','午餐吃完麵後我很飽。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('funny','adj.','好笑的','elementary',1,'The funny story makes everyone laugh.','那個好笑的故事讓大家都笑了。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('gate','n.','大門','elementary',1,'The old gate opens with the moon key.','舊大門用月之鑰匙打開。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('gentle','adj.','溫柔的','elementary',1,'A gentle voice comes from the tree.','一個溫柔的聲音從樹裡傳來。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('girl','n.','女孩','elementary',1,'The girl carries a pink school bag.','那個女孩背著粉紅色書包。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('glow','v.','發光','elementary',1,'The magic leaf glows in Lily''s hand.','魔法葉子在莉莉手中發光。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('go','v.','去','elementary',1,'I go to school by bus every day.','我每天搭公車去上學。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('good','adj.','好的','elementary',1,'You did a good job on the reading test.','你在閱讀測驗中表現得很好。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('grass','n.','草','elementary',1,'The rabbit hops across the grass.','兔子跳過草地。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('gray','n./adj.','灰色；灰色的','elementary',1,'Gray clouds cover the mountain.','灰色的雲遮住了山。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('green','n./adj.','綠色；綠色的','elementary',1,'Green leaves grow on the tree.','綠色的葉子長在樹上。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('guide','v.','引導','elementary',1,'The Light Leaf guides Lily through the forest.','光之葉引導莉莉穿過森林。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('hair','n.','頭髮','elementary',1,'My hair is wet after I wash it.','我洗完頭後頭髮是濕的。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('hand','n.','手','elementary',1,'Raise your hand if you know the answer.','如果你知道答案就舉手。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('hard','adj.','困難的；硬的','elementary',1,'The puzzle is hard, but I keep trying.','這個謎題很難，但我繼續嘗試。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('head','n.','頭','elementary',1,'I put a hat on my head.','我把帽子戴在頭上。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('help','v.','幫助','elementary',1,'I help my friend carry her books.','我幫朋友拿她的書。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('helper','n.','幫助者','elementary',1,'Coco becomes Lily''s forest helper.','可可成為莉莉的森林幫手。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('here','adv.','這裡','elementary',1,'Come here and look at this picture.','來這裡看這張圖片。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('home','n.','家','elementary',1,'I go home after school and read.','我放學後回家閱讀。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('horse','n.','馬','elementary',1,'A horse runs on the farm.','一匹馬在農場奔跑。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('hot','adj.','熱的','elementary',1,'The soup is hot, so I wait a minute.','湯很燙，所以我等了一分鐘。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('house','n.','房子','elementary',1,'There is a tree beside my house.','我家旁邊有一棵樹。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('how','adv.','如何；怎麼','elementary',1,'How do you say this word?','這個單字怎麼說？','Supplemental','','[]'::jsonb,'[]'::jsonb),
('hungry','adj.','餓的','elementary',1,'I feel hungry after basketball practice.','籃球練習後我覺得很餓。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('in','prep.','在...裡面','elementary',1,'The pencil is in the blue bag.','鉛筆在藍色書包裡。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('journey','n.','旅程','elementary',1,'Their journey begins near the talking tree.','她們的旅程從會說話的樹旁開始。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('juice','n.','果汁','elementary',1,'I drink orange juice after soccer practice.','足球練習後我喝柳橙汁。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('jump','v.','跳','elementary',1,'The cat can jump onto the chair.','貓可以跳到椅子上。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('keyhole','n.','鑰匙孔','elementary',1,'There is no keyhole on the stone door.','石門上沒有鑰匙孔。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('kind','adj.','親切的；善良的','elementary',1,'A kind classmate shares his pencil with me.','一位親切的同學把鉛筆借給我。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('kindness','n.','善良','elementary',1,'Kindness changes the lonely shadow.','善良改變了孤單的影子。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('kitchen','n.','廚房','elementary',1,'Mom cooks breakfast in the kitchen.','媽媽在廚房做早餐。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('know','v.','知道','elementary',1,'I know the answer to this question.','我知道這個問題的答案。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('lake','n.','湖','elementary',1,'The quiet lake reflects the moon.','安靜的湖映出月亮。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('large','adj.','大的','elementary',1,'A large tree gives us shade in the park.','公園裡有一棵大樹幫我們遮陰。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('late','adj.','晚的；遲到的','elementary',1,'Tom is late because he missed the bus.','湯姆遲到了，因為他錯過公車。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('learn','v.','學習','elementary',1,'I learn three new words today.','我今天學三個新單字。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('leg','n.','腿','elementary',1,'My leg hurts after running fast.','我跑很快後腿會痛。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('like','v.','喜歡','elementary',1,'I like stories about animals.','我喜歡關於動物的故事。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('lion','n.','獅子','elementary',1,'The lion opens its mouth and roars.','獅子張開嘴巴吼叫。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('listen','v.','聽','elementary',1,'Listen to the sentence before you repeat it.','重複之前先聽句子。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('little','adj.','小的；少的','elementary',1,'I have a little notebook for English class.','我有一本上英文課用的小筆記本。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('lonely','adj.','孤單的','elementary',1,'The lonely shadow waits beside the tree.','孤單的影子在樹旁等待。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('long','adj.','長的','elementary',1,'My sister reads a long story before bed.','我妹妹睡前讀了一篇長故事。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('look','v.','看','elementary',1,'Look at the picture and say the word.','看著圖片並說出單字。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('loud','adj.','大聲的','elementary',1,'The music is too loud for the baby.','這音樂對寶寶來說太大聲了。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('love','v.','愛；喜愛','elementary',1,'I love reading with my family.','我喜歡和家人一起閱讀。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('lunch','n.','午餐','elementary',1,'I eat lunch with my classmates.','我和同學一起吃午餐。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('magic','n.','魔法','elementary',1,'The magic light helps the flowers grow.','魔法光幫助花朵生長。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('make','v.','製作','elementary',1,'I make a paper flower for Mom.','我做一朵紙花給媽媽。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('man','n.','男人','elementary',1,'The man waits beside the station.','那位男人在車站旁等待。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('market','n.','市場','elementary',1,'We buy fruit at the morning market.','我們在早市買水果。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('memory','n.','記憶','elementary',1,'The stone shows a memory from long ago.','石頭顯示很久以前的記憶。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('milk','n.','牛奶','elementary',1,'I drink milk with breakfast.','我早餐喝牛奶。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('mirror','n.','鏡子','elementary',1,'The lake looks like a silver mirror.','湖面看起來像銀色鏡子。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('miss','v.','想念；錯過','elementary',1,'I miss my friends during winter vacation.','寒假時我想念朋友。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('mistake','n.','錯誤','elementary',1,'A mistake helps me learn the right answer.','錯誤幫助我學會正確答案。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('mom','n.','媽媽','elementary',1,'Mom makes breakfast before I go to school.','媽媽在我上學前做早餐。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('monkey','n.','猴子','elementary',1,'The monkey climbs the tree quickly.','猴子快速爬上樹。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('month','n.','月','elementary',1,'This month, our class reads one book.','這個月我們班讀一本書。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('moon','n.','月亮','elementary',1,'The moon shines above the lake.','月亮照在湖上方。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('mother','n.','媽媽；母親','elementary',1,'My mother helps me read a story.','我媽媽幫我讀故事。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('mouse','n.','老鼠','elementary',1,'A small mouse runs behind the box.','一隻小老鼠跑到盒子後面。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('mouth','n.','嘴巴','elementary',1,'Open your mouth and say the word clearly.','張開嘴巴，清楚說出這個字。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('narrow','adj.','狹窄的','elementary',1,'The narrow path leads to a small lake.','狹窄的小路通往一座小湖。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('near','prep.','靠近','elementary',1,'My school is near the library.','我的學校在圖書館附近。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('need','v.','需要','elementary',1,'We need quiet voices in the library.','我們在圖書館需要輕聲說話。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('new','adj.','新的','elementary',1,'I write new words in my notebook.','我把新的單字寫在筆記本裡。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('nice','adj.','好的；友善的','elementary',1,'Our teacher says nice words when we try.','我們努力時，老師會說友善的話。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('night','n.','夜晚','elementary',1,'At night, I read with my family.','晚上我和家人一起閱讀。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('no','adv.','不；沒有','elementary',1,'No, the answer is not seven.','不，答案不是七。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('nose','n.','鼻子','elementary',1,'My nose feels cold in winter.','冬天我的鼻子覺得冷。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('notebook','n.','筆記本','elementary',1,'Write the new sentence in your notebook.','把新句子寫進你的筆記本。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('old','adj.','老的；舊的','elementary',1,'My grandpa keeps an old photo on his desk.','我爺爺把一張舊照片放在書桌上。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('on','prep.','在...上面','elementary',1,'The book is on the table.','書在桌上。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('open','v.','打開','elementary',1,'Open the book to page ten.','把書打開到第十頁。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('orange','n./adj.','橘色；柳橙','elementary',1,'I eat an orange after lunch.','我午餐後吃一顆柳橙。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('page','n.','頁','elementary',1,'Read the first page slowly.','慢慢讀第一頁。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('paper','n.','紙','elementary',1,'Fold the paper into a small boat.','把紙摺成一艘小船。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('parent','n.','父母親','elementary',1,'A parent signs my homework notebook.','一位家長在我的作業簿上簽名。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('path','n.','小路','elementary',1,'The silver path leads to the lake.','銀色小路通往湖邊。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('pattern','n.','圖案','elementary',1,'The moon pattern matches the key.','月亮圖案和鑰匙相符合。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('peaceful','adj.','平靜的','elementary',1,'The lake becomes peaceful under the moon.','月光下的湖變得很平靜。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('pen','n.','筆','elementary',1,'Use a black pen to write your name.','用黑筆寫你的名字。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('pencil','n.','鉛筆','elementary',1,'My pencil is sharp and ready.','我的鉛筆削好了，可以使用。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('petal','n.','花瓣','elementary',1,'A pink petal falls on Lily''s hand.','一片粉紅花瓣落在莉莉手上。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('pig','n.','豬','elementary',1,'A pink pig sleeps in the mud.','一隻粉紅豬睡在泥巴裡。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('pink','n./adj.','粉紅色；粉紅色的','elementary',1,'My sister wears a pink dress today.','我妹妹今天穿粉紅色洋裝。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('playground','n.','操場；遊樂場','elementary',1,'Children run on the playground after class.','孩子們下課後在操場跑。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('pond','n.','池塘','elementary',1,'A duck swims across the small pond.','一隻鴨子游過小池塘。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('practice','v.','練習','elementary',1,'We practice speaking English after class.','我們下課後練習說英文。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('purple','adj.','紫色的','elementary',1,'The purple flower grows near the gate.','紫色的花長在大門旁。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('puzzle','n.','謎題','elementary',1,'The wall puzzle has three glowing circles.','牆上的謎題有三個發光圓圈。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('quiet','adj.','安靜的','elementary',1,'The library is quiet in the afternoon.','下午的圖書館很安靜。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('rabbit','n.','兔子','elementary',1,'The rabbit hops across the grass.','兔子跳過草地。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('rain','n./v.','雨；下雨','elementary',1,'Rain falls softly on the window.','雨輕輕落在窗戶上。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('react','v.','反應','elementary',1,'The key reacts when it touches the door.','鑰匙碰到門時產生反應。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('read','v.','閱讀','elementary',1,'I read one English page every night.','我每天晚上讀一頁英文。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('ready','adj.','準備好的','elementary',1,'I am ready to read the next page.','我準備好閱讀下一頁了。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('red','n./adj.','紅色；紅色的','elementary',1,'I draw a red apple on the paper.','我在紙上畫一顆紅蘋果。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('reflect','v.','反射','elementary',1,'The lake reflects the moon at night.','夜晚湖面映出月亮。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('reject','v.','拒絕','elementary',1,'The crystal does not reject the small shadow now.','水晶現在沒有拒絕小影子。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('ribbon','n.','緞帶','elementary',1,'Lily ties a red ribbon to a branch.','莉莉把紅緞帶綁在樹枝上。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('rice','n.','飯；米','elementary',1,'I eat rice with vegetables for dinner.','我晚餐吃飯配蔬菜。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('river','n.','河流','elementary',1,'The river sings when the bell rings.','鈴聲響起時，河流唱歌。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('room','n.','房間','elementary',1,'My room has a desk and a bed.','我的房間有書桌和床。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('ruler','n.','尺','elementary',1,'The ruler helps me draw a line.','尺幫我畫直線。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('say','v.','說','elementary',1,'Say the word slowly and clearly.','慢慢並清楚地說出這個單字。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('see','v.','看見','elementary',1,'I see a rainbow after the rain.','雨後我看見一道彩虹。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('shadow','n.','影子','elementary',1,'A dark shadow moves behind the tree.','一道黑影在樹後移動。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('sheep','n.','羊','elementary',1,'The sheep stands on the green hill.','羊站在綠色山丘上。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('short','adj.','短的；矮的','elementary',1,'This short song is easy to sing.','這首短歌很容易唱。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('sick','adj.','生病的','elementary',1,'My brother is sick and stays at home.','我哥哥生病了，待在家裡。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('silent','adj.','安靜的','elementary',1,'The forest is silent before the birds sing.','鳥兒唱歌前，森林很安靜。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('sing','v.','唱歌','elementary',1,'We sing an English song together.','我們一起唱英文歌。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('sister','n.','姊妹','elementary',1,'My sister sings a song with me.','我姊妹和我一起唱歌。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('sit','v.','坐','elementary',1,'Please sit on the chair and listen.','請坐在椅子上聽。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('sky','n.','天空','elementary',1,'The sky is blue after the rain.','雨後天空是藍色的。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('sleep','v.','睡覺','elementary',1,'The baby sleeps after dinner.','寶寶晚餐後睡覺。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('slow','adj.','慢的','elementary',1,'The turtle walks slowly across the grass.','烏龜慢慢走過草地。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('small','adj.','小的','elementary',1,'The small cat sleeps beside my school bag.','那隻小貓睡在我的書包旁邊。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('smoke','n.','煙','elementary',1,'Dark smoke fills the old cave.','黑煙充滿古老洞穴。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('smoky','adj.','煙霧般的','elementary',1,'The smoky cave is hard to see inside.','煙霧般的洞穴裡面很難看清楚。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('snake','n.','蛇','elementary',1,'The snake hides under a rock.','蛇躲在岩石下面。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('snow','n./v.','雪；下雪','elementary',1,'Snow covers the street in the morning.','早上雪覆蓋了街道。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('solid','adj.','堅固的','elementary',1,'The solid rock wall does not move.','堅固的岩壁沒有移動。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('soup','n.','湯','elementary',1,'The hot soup smells good.','熱湯聞起來很香。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('sparkle','v.','閃耀','elementary',1,'The silver bell sparkles under the water.','銀色鈴鐺在水下閃耀。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('speak','v.','說','elementary',1,'I speak English with my teacher.','我和老師說英文。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('spiral','n.','螺旋','elementary',1,'The spiral symbol points to the secret door.','螺旋符號指向秘密門。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('spirit','n.','精靈','elementary',1,'The lake spirit speaks in a gentle voice.','湖的精靈用溫柔的聲音說話。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('spoon','n.','湯匙','elementary',1,'A shiny spoon helps Lily see under the lake.','一支亮亮的湯匙幫莉莉看見湖底。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('stand','v.','站','elementary',1,'Stand beside your desk and read aloud.','站在你的書桌旁大聲朗讀。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('star','n.','星星','elementary',1,'A bright star appears in the night sky.','一顆明亮的星星出現在夜空。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('steady','adj.','穩定的','elementary',1,'Lily walks with steady steps across the bridge.','莉莉用穩定的步伐走過橋。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('street','n.','街道','elementary',1,'Look left and right before crossing the street.','過街前左右看。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('strong','adj.','強壯的','elementary',1,'Practice makes my English stronger every day.','每天練習讓我的英文更強。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('student','n.','學生','elementary',1,'The student writes the answer carefully.','學生小心地寫下答案。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('sun','n.','太陽','elementary',1,'The sun shines over the playground.','太陽照在操場上。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('surface','n.','表面','elementary',1,'The key floats near the water surface.','鑰匙漂在水面附近。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('surround','v.','包圍','elementary',1,'Warm light surrounds Lily in the cave.','溫暖的光包圍洞穴中的莉莉。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('swim','v.','游泳','elementary',1,'Fish swim under the bridge.','魚在橋下游泳。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('symbol','n.','符號','elementary',1,'The moon symbol glows on the stone.','月亮符號在石頭上發光。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('table','n.','桌子','elementary',1,'The cake is on the table.','蛋糕在桌上。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('take','v.','拿；帶','elementary',1,'Take your notebook out of your bag.','把你的筆記本從書包拿出來。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('tall','adj.','高的','elementary',1,'The tall boy can reach the top shelf.','那個高個子男孩碰得到最上面的架子。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('tea','n.','茶','elementary',1,'Grandma drinks warm tea after dinner.','奶奶晚餐後喝溫茶。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('teacher','n.','老師','elementary',1,'The teacher tells us a funny story.','老師告訴我們一個好笑的故事。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('tell','v.','告訴','elementary',1,'Please tell me your favorite color.','請告訴我你最喜歡的顏色。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('there','adv.','那裡','elementary',1,'There is a rabbit under the tree.','樹下有一隻兔子。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('think','v.','想；認為','elementary',1,'I think this story is interesting.','我覺得這個故事很有趣。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('thirsty','adj.','渴的','elementary',1,'I am thirsty, so I drink some water.','我口渴了，所以喝一些水。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('tiger','n.','老虎','elementary',1,'The tiger walks quietly in the zoo.','老虎在動物園安靜地走著。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('tired','adj.','累的','elementary',1,'The children are tired after a long walk.','孩子們走了很久後很累。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('today','n./adv.','今天','elementary',1,'Today we learn a song about animals.','今天我們學一首關於動物的歌。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('tomorrow','n./adv.','明天','elementary',1,'Tomorrow we will read the next chapter.','明天我們會讀下一章。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('too','adv.','也；太','elementary',1,'I want to sing too.','我也想唱歌。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('tree','n.','樹','elementary',1,'A big tree stands beside the river.','一棵大樹立在河邊。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('tremble','v.','顫抖','elementary',1,'Lily''s hands tremble, but she stays brave.','莉莉的手在發抖，但她保持勇敢。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('trunk','n.','樹幹','elementary',1,'The tree trunk has glowing green lines.','樹幹上有發光的綠色線條。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('trust','v.','信任','elementary',1,'Trust your heart when you feel afraid.','害怕時要相信自己的心。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('truth','n.','真相','elementary',1,'Lily sees the truth inside the crystal.','莉莉在水晶裡看見真相。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('turtle','n.','烏龜','elementary',1,'The turtle moves slowly on the road.','烏龜在路上慢慢移動。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('twig','n.','小樹枝','elementary',1,'Lily moves the twig away from the fairy.','莉莉把小樹枝從小精靈身上移開。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('twisted','adj.','扭曲的','elementary',1,'A twisted branch lies beside the path.','一根扭曲的樹枝躺在小路旁。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('under','prep.','在...下面','elementary',1,'The dog sleeps under the chair.','狗睡在椅子下面。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('use','v.','使用','elementary',1,'Use a ruler to draw a straight line.','用尺畫一條直線。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('very','adv.','非常','elementary',1,'The story is very interesting.','這個故事非常有趣。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('wake','v.','醒來','elementary',1,'I wake up early for school.','我為了上學早起。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('walk','v.','走路','elementary',1,'We walk home together after school.','我們放學後一起走路回家。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('want','v.','想要','elementary',1,'I want a new pencil for class.','我想要一支上課用的新鉛筆。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('warm','adj.','溫暖的','elementary',1,'The warm sun shines through the window.','溫暖的陽光從窗戶照進來。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('wash','v.','洗','elementary',1,'Wash your hands before lunch.','午餐前洗手。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('watch','v.','觀看','elementary',1,'We watch a short movie in English class.','我們在英文課看一部短電影。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('wave','n.','波浪','elementary',1,'A small wave brings the key to Lily.','一個小浪把鑰匙帶到莉莉面前。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('week','n.','週','elementary',1,'I learn five new words every week.','我每週學五個新單字。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('what','pron.','什麼','elementary',1,'What do you eat for breakfast?','你早餐吃什麼？','Supplemental','','[]'::jsonb,'[]'::jsonb),
('when','adv.','什麼時候','elementary',1,'When does the song start?','這首歌什麼時候開始？','Supplemental','','[]'::jsonb,'[]'::jsonb),
('where','adv.','哪裡','elementary',1,'Where is your English notebook?','你的英文筆記本在哪裡？','Supplemental','','[]'::jsonb,'[]'::jsonb),
('whisper','v.','低語','elementary',1,'The trees whisper softly in the wind.','樹在風中輕輕低語。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('white','n./adj.','白色；白色的','elementary',1,'A white bird flies across the sky.','一隻白色的鳥飛過天空。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('who','pron.','誰','elementary',1,'Who is reading the story aloud?','誰正在大聲讀故事？','Supplemental','','[]'::jsonb,'[]'::jsonb),
('why','adv.','為什麼','elementary',1,'Why is the river so quiet?','為什麼河流這麼安靜？','Supplemental','','[]'::jsonb,'[]'::jsonb),
('wind','n.','風','elementary',1,'The wind moves the leaves on the tree.','風吹動樹上的葉子。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('window','n.','窗戶','elementary',1,'Open the window to let in fresh air.','打開窗戶讓新鮮空氣進來。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('wing','n.','翅膀','elementary',1,'The fairy''s blue wing sparkles in the light.','小精靈的藍色翅膀在光中閃耀。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('woman','n.','女人','elementary',1,'The woman buys vegetables at the market.','那位女人在市場買蔬菜。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('write','v.','書寫','elementary',1,'Write your name at the top of the page.','把你的名字寫在頁面上方。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('year','n.','年','elementary',1,'I grow taller every year.','我每年都長高。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('yellow','n./adj.','黃色；黃色的','elementary',1,'The yellow bus stops near my house.','黃色公車停在我家附近。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('yes','adv.','是；好的','elementary',1,'Yes, I can read this sentence.','是的，我會讀這個句子。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('yesterday','n./adv.','昨天','elementary',1,'Yesterday I practiced English with Mom.','昨天我和媽媽練習英文。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('young','adj.','年輕的','elementary',1,'The young student raises her hand to answer.','那位年紀小的學生舉手回答。','Supplemental','','[]'::jsonb,'[]'::jsonb)
ON CONFLICT (word, level) DO NOTHING;
