-- Elementary watercolor illustrations, batch 9. Upload assets before metadata.
BEGIN;
INSERT INTO public.word_illustrations (id, level, word, sort_order, sense, alt_zh, example, example_zh, image_url, local_path, style, version) VALUES
('elementary-shirt-01-v1', 'elementary', 'shirt', 1, '襯衫', '一件淺藍色長袖襯衫，有尖領和一排鈕扣。', 'The blue shirt has buttons.', '藍色襯衫上有鈕扣。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/shirt-01-v1.webp', '/images/vocabulary/elementary/shirt-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-tshirt-01-v1', 'elementary', 'tshirt', 1, 'T 恤', '一件黃色短袖圓領 T 恤，沒有圖案。', 'This yellow T-shirt has short sleeves.', '這件黃色 T 恤有短袖。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/tshirt-01-v1.webp', '/images/vocabulary/elementary/tshirt-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-pants-01-v1', 'elementary', 'pants', 1, '長褲', '一條藍色長褲，腰頭和兩條長褲管清楚可見。', 'These blue pants have two long legs.', '這條藍色長褲有兩條長褲管。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/pants-01-v1.webp', '/images/vocabulary/elementary/pants-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-shorts-01-v1', 'elementary', 'shorts', 1, '短褲', '一條綠色短褲，腰頭和兩個短褲管清楚可見。', 'These green shorts are ready for a sunny day.', '這條綠色短褲適合在晴天穿。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/shorts-01-v1.webp', '/images/vocabulary/elementary/shorts-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-skirt-01-v1', 'elementary', 'skirt', 1, '裙子', '一件粉紅色百褶裙，有腰頭和向外展開的裙襬。', 'The pink skirt has many pleats.', '粉紅色裙子有許多褶子。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/skirt-01-v1.webp', '/images/vocabulary/elementary/skirt-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-dress-01-v1', 'elementary', 'dress', 1, '洋裝', '一件淡紫色短袖洋裝，上半身和裙襬連在一起。', 'This purple dress has a wide skirt.', '這件紫色洋裝有寬寬的裙襬。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/dress-01-v1.webp', '/images/vocabulary/elementary/dress-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-shoes-01-v1', 'elementary', 'shoes', 1, '鞋子', '一雙紅色運動鞋並排放著，有白色鞋帶和白色鞋底。', 'The red shoes have white laces.', '紅色鞋子有白色鞋帶。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/shoes-01-v1.webp', '/images/vocabulary/elementary/shoes-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-socks-01-v1', 'elementary', 'socks', 1, '襪子', '一雙藍色短襪並排放著，襪口有白色條紋。', 'These blue socks have white stripes.', '這雙藍色襪子有白色條紋。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/socks-01-v1.webp', '/images/vocabulary/elementary/socks-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-coat-01-v1', 'elementary', 'coat', 1, '大衣；外套', '一件淺褐色長版冬季大衣，有長袖、翻領、鈕扣和兩個口袋。', 'This long coat keeps me warm in winter.', '這件長大衣讓我在冬天保持溫暖。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/coat-01-v1.webp', '/images/vocabulary/elementary/coat-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-jacket-01-v1', 'elementary', 'jacket', 1, '夾克', '一件綠色短版夾克，有長袖、前方拉鍊和兩個口袋。', 'The green jacket has a zipper.', '綠色夾克有一條拉鍊。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/jacket-01-v1.webp', '/images/vocabulary/elementary/jacket-01-v1.webp', 'watercolor-pencil-v1', 1)
ON CONFLICT (id) DO NOTHING;
COMMIT;
