-- Batch 11: upload assets before metadata.
BEGIN;
INSERT INTO public.word_illustrations (id, level, word, sort_order, sense, alt_zh, example, example_zh, image_url, local_path, style, version) VALUES
('elementary-chicken-01-v1', 'elementary', 'chicken', 1, '雞', '一隻棕色母雞站著，有紅色雞冠、短喙和兩隻腳。', 'The chicken pecks at seeds on the ground.', '這隻雞啄食地上的種子。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/chicken-01-v1.webp', '/images/vocabulary/elementary/chicken-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-tiger-01-v1', 'elementary', 'tiger', 1, '老虎', '一隻橘色老虎站著，身上有黑色條紋和長尾巴。', 'The tiger has black stripes on its orange fur.', '老虎的橘色毛皮上有黑色條紋。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/tiger-01-v1.webp', '/images/vocabulary/elementary/tiger-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-lion-01-v1', 'elementary', 'lion', 1, '獅子', '一隻公獅子坐著，頭部周圍有濃密的棕色鬃毛。', 'The lion has a thick brown mane.', '這隻獅子有濃密的棕色鬃毛。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/lion-01-v1.webp', '/images/vocabulary/elementary/lion-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-snake-01-v1', 'elementary', 'snake', 1, '蛇', '一條綠色蛇彎成平緩的 S 形，尾端逐漸變細。', 'The green snake curves across the ground.', '這條綠色的蛇彎著身體爬過地面。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/snake-01-v1.webp', '/images/vocabulary/elementary/snake-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-goat-01-v1', 'elementary', 'goat', 1, '山羊', '一隻白色山羊站著，有短角、小鬍鬚和四隻蹄子。', 'The goat has short horns and a little beard.', '這隻山羊有短角和小鬍鬚。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/goat-01-v1.webp', '/images/vocabulary/elementary/goat-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-kangaroo-01-v1', 'elementary', 'kangaroo', 1, '袋鼠', '一隻袋鼠用大後腳站著，粗長尾巴伸向身後。', 'The kangaroo has strong back legs for jumping.', '袋鼠有強壯的後腿，可以用來跳躍。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/kangaroo-01-v1.webp', '/images/vocabulary/elementary/kangaroo-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-koala-01-v1', 'elementary', 'koala', 1, '無尾熊', '一隻灰色無尾熊抱著樹幹，有毛茸茸的圓耳朵和黑色鼻子。', 'The koala holds on to the tree trunk.', '這隻無尾熊抱著樹幹。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/koala-01-v1.webp', '/images/vocabulary/elementary/koala-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-panda-01-v1', 'elementary', 'panda', 1, '貓熊', '一隻黑白貓熊坐著，前掌拿著一根綠色竹子。', 'The panda holds a green bamboo stalk.', '這隻貓熊拿著一根綠色竹子。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/panda-01-v1.webp', '/images/vocabulary/elementary/panda-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-airplane-01-v1', 'elementary', 'airplane', 1, '飛機', '一架白色客機在空中飛行，有藍色尾翼和兩側機翼。', 'The airplane flies high in the sky.', '飛機在高空中飛行。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/airplane-01-v1.webp', '/images/vocabulary/elementary/airplane-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-boat-01-v1', 'elementary', 'boat', 1, '小船', '一艘小木划船浮在水面上，船內放著一對船槳。', 'The small boat floats on the water.', '這艘小船浮在水面上。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/boat-01-v1.webp', '/images/vocabulary/elementary/boat-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-truck-01-v1', 'elementary', 'truck', 1, '卡車', '一輛藍色貨車有封閉的貨斗和黑色輪胎。', 'The blue truck carries boxes to the store.', '這輛藍色卡車載箱子到商店。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/truck-01-v1.webp', '/images/vocabulary/elementary/truck-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-ship-01-v1', 'elementary', 'ship', 1, '輪船', '一艘大型輪船航行在水面上，有多層甲板和煙囪。', 'The large ship sails across the sea.', '這艘大輪船航行在海上。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/ship-01-v1.webp', '/images/vocabulary/elementary/ship-01-v1.webp', 'watercolor-pencil-v1', 1)
ON CONFLICT (id) DO UPDATE SET level = EXCLUDED.level, word = EXCLUDED.word, sort_order = EXCLUDED.sort_order, sense = EXCLUDED.sense, alt_zh = EXCLUDED.alt_zh, example = EXCLUDED.example, example_zh = EXCLUDED.example_zh, image_url = EXCLUDED.image_url, local_path = EXCLUDED.local_path, style = EXCLUDED.style, version = EXCLUDED.version;
COMMIT;
