-- EnglishGo - Elementary supplemental word seed batch 2
-- Generated from src/data/extraWords.js
-- Safe to re-run: existing (word, level) rows are preserved.

INSERT INTO public.word_bank (word, pos, meaning, level, ceec_level, example, example_zh, category, phonetic, forms, collocations) VALUES
('about','prep.','關於','elementary',1,'This story is about a brave girl.','這個故事是關於一個勇敢的女孩。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('all','adj.','全部','elementary',1,'All the students listen to the story.','所有學生都聽這個故事。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('any','adj.','任何；一些','elementary',1,'Do you have any questions after class?','下課後你有任何問題嗎？','Supplemental','','[]'::jsonb,'[]'::jsonb),
('april','n.','四月','elementary',1,'April rain helps the grass grow.','四月的雨幫助草生長。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('art','n.','美術；藝術','elementary',1,'In art class, we draw colorful flowers.','美術課時，我們畫彩色花朵。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('august','n.','八月','elementary',1,'August days are hot and bright.','八月的日子又熱又明亮。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('baseball','n.','棒球','elementary',1,'My brother watches baseball with Dad.','我哥哥和爸爸看棒球。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('basketball','n.','籃球','elementary',1,'We play basketball on the playground.','我們在操場打籃球。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('beach','n.','海灘','elementary',1,'We build a sand house on the beach.','我們在海灘上蓋沙屋。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('beef','n.','牛肉','elementary',1,'The beef noodles smell very good.','牛肉麵聞起來很香。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('before','prep.','在...之前','elementary',1,'Wash your hands before lunch.','午餐前洗手。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('begin','v.','開始','elementary',1,'The story begins in a quiet forest.','故事從一座安靜的森林開始。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('behind','prep.','在...後面','elementary',1,'The cat hides behind the sofa.','貓躲在沙發後面。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('beside','prep.','在...旁邊','elementary',1,'The ball is beside the door.','球在門旁邊。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('between','prep.','在...之間','elementary',1,'The desk is between two chairs.','書桌在兩張椅子中間。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('both','adj./pron.','兩者都','elementary',1,'Both sisters like to read at night.','兩個姊妹都喜歡晚上閱讀。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('call','v.','打電話；呼叫','elementary',1,'Call your dad when you get home.','到家時打電話給爸爸。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('cap','n.','帽子','elementary',1,'He wears a cap at the baseball game.','他在棒球比賽時戴帽子。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('carrot','n.','紅蘿蔔','elementary',1,'The rabbit eats a carrot near the tree.','兔子在樹旁吃紅蘿蔔。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('chocolate','n.','巧克力','elementary',1,'I eat chocolate only after dinner.','我只有晚餐後才吃巧克力。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('cloud','n.','雲','elementary',1,'A white cloud moves across the sky.','一朵白雲飄過天空。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('coat','n.','外套','elementary',1,'I need a coat on a cold night.','寒冷的夜晚我需要外套。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('computer','n.','電腦','elementary',1,'We use a computer to listen to the story.','我們用電腦聽故事。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('corn','n.','玉米','elementary',1,'We put corn in the soup.','我們把玉米放進湯裡。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('cry','v.','哭','elementary',1,'The baby cries when he is hungry.','寶寶餓的時候會哭。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('december','n.','十二月','elementary',1,'December nights are cold and quiet.','十二月的夜晚寒冷又安靜。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('different','adj.','不同的','elementary',1,'These two pictures show different animals.','這兩張圖片展示不同的動物。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('doll','n.','娃娃','elementary',1,'My little sister plays with a doll.','我的妹妹玩娃娃。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('down','adv.','向下','elementary',1,'Put the box down beside the table.','把盒子放在桌子旁邊。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('dress','n./v.','洋裝；穿','elementary',1,'She wears a yellow dress to the party.','她穿黃色洋裝去派對。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('drive','v.','開車','elementary',1,'My father drives carefully on rainy days.','下雨天我爸爸小心開車。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('each','adj.','每個','elementary',1,'Each page has one new sentence.','每一頁都有一個新句子。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('eight','n.','八','elementary',1,'I wake up at eight on Sunday.','我星期日八點起床。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('eighteen','n.','十八','elementary',1,'Eighteen players stand on the field.','十八位球員站在場上。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('eleven','n.','十一','elementary',1,'Eleven children sing in the classroom.','十一個孩子在教室裡唱歌。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('every','adj.','每一個','elementary',1,'Every child gets a book today.','今天每個孩子都拿到一本書。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('everyone','pron.','每個人','elementary',1,'Everyone claps after the song ends.','歌曲結束後每個人都拍手。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('farm','n.','農場','elementary',1,'The farm has cows, pigs, and ducks.','農場裡有牛、豬和鴨子。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('february','n.','二月','elementary',1,'February has many cool days.','二月有許多涼爽的日子。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('few','adj.','少數的','elementary',1,'A few birds fly over the playground.','幾隻鳥飛過操場。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('fifteen','n.','十五','elementary',1,'I practice English for fifteen minutes.','我練習英文十五分鐘。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('fifty','n.','五十','elementary',1,'Grandma is fifty years old.','奶奶五十歲。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('finish','v.','完成；結束','elementary',1,'I finish my homework before I play.','我玩之前先完成作業。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('first','adj./adv.','第一；首先','elementary',1,'Read the first sentence on the page.','讀頁面上的第一個句子。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('five','n.','五','elementary',1,'We learn five words today.','我們今天學五個單字。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('for','prep.','為了；給','elementary',1,'This card is for my mother.','這張卡片是給媽媽的。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('forty','n.','四十','elementary',1,'The story has forty words.','這篇故事有四十個字。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('four','n.','四','elementary',1,'Four students answer the question.','四位學生回答問題。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('fourteen','n.','十四','elementary',1,'Fourteen students read the story aloud.','十四位學生大聲讀故事。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('friday','n.','星期五','elementary',1,'Friday is a good day for songs.','星期五很適合唱歌。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('from','prep.','從；來自','elementary',1,'This letter is from my teacher.','這封信來自我的老師。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('fruit','n.','水果','elementary',1,'Fruit is a healthy snack after class.','水果是下課後健康的點心。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('game','n.','遊戲','elementary',1,'The word game helps us learn quickly.','單字遊戲幫助我們快速學習。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('get','v.','得到；拿到','elementary',1,'I get a new book from the library.','我從圖書館拿到一本新書。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('give','v.','給','elementary',1,'Please give the pencil to your sister.','請把鉛筆給你的姊妹。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('hamburger','n.','漢堡','elementary',1,'Tom buys a hamburger for lunch.','湯姆午餐買了一個漢堡。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('has','v.','有','elementary',1,'She has a yellow kite.','她有一個黃色風箏。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('hat','n.','帽子','elementary',1,'A hat keeps the sun off my face.','帽子幫我的臉遮太陽。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('have','v.','有','elementary',1,'I have a picture book in my bag.','我的書包裡有一本圖畫書。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('he','pron.','他','elementary',1,'He answers the question clearly.','他清楚地回答問題。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('her','pron.','她；她的','elementary',1,'Her sister sings with the class.','她的姊妹和全班一起唱歌。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('him','pron.','他','elementary',1,'I give him a new eraser.','我給他一塊新橡皮擦。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('his','pron.','他的','elementary',1,'His bike is near the gate.','他的腳踏車在大門附近。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('homework','n.','家庭作業','elementary',1,'Homework helps me practice after school.','家庭作業幫助我放學後練習。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('hour','n.','小時','elementary',1,'We read for one hour on Sunday.','星期日我們閱讀一小時。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('hundred','n.','一百','elementary',1,'There are one hundred cards in the box.','盒子裡有一百張卡片。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('inside','adv./prep.','在裡面','elementary',1,'The key is inside the small box.','鑰匙在小盒子裡面。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('into','prep.','進入','elementary',1,'The frog jumps into the pond.','青蛙跳進池塘裡。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('it','pron.','它','elementary',1,'It is a small brown dog.','牠是一隻小棕狗。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('its','pron.','它的','elementary',1,'The bird opens its wing.','那隻鳥張開牠的翅膀。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('jacket','n.','夾克','elementary',1,'My jacket is on the chair.','我的夾克在椅子上。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('january','n.','一月','elementary',1,'In January, the morning air is cold.','一月的早晨空氣很冷。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('july','n.','七月','elementary',1,'In July, we swim in the pool.','七月我們在游泳池游泳。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('june','n.','六月','elementary',1,'June is the start of summer vacation.','六月是暑假的開始。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('keep','v.','保持','elementary',1,'Keep your room clean after you play.','玩完後保持房間乾淨。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('kite','n.','風箏','elementary',1,'We fly a kite on a windy day.','有風的日子我們放風箏。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('last','adj.','最後的','elementary',1,'The last page has a happy ending.','最後一頁有快樂的結局。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('laugh','v.','笑','elementary',1,'We laugh at the funny picture.','我們看到好笑的圖片就笑了。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('leaf','n.','葉子','elementary',1,'A green leaf falls into the river.','一片綠葉落進河裡。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('left','n./adj.','左邊；左邊的','elementary',1,'Turn left after the school gate.','經過校門後向左轉。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('lesson','n.','課；課程','elementary',1,'Today''s lesson is about animals.','今天的課是關於動物。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('letter','n.','字母；信','elementary',1,'The letter A is at the start of apple.','字母 A 在 apple 的開頭。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('library','n.','圖書館','elementary',1,'The library has many picture books.','圖書館有許多圖畫書。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('live','v.','居住；生活','elementary',1,'I live near a small park.','我住在一座小公園附近。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('many','adj.','許多','elementary',1,'Many students sing the song together.','許多學生一起唱這首歌。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('march','n./v.','三月；行進','elementary',1,'In March, flowers begin to grow.','三月花朵開始生長。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('may','n./v.','五月；可以','elementary',1,'In May, we sing for our mothers.','五月我們為媽媽唱歌。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('me','pron.','我','elementary',1,'This book is for me.','這本書是給我的。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('meat','n.','肉','elementary',1,'My dad cooks meat for dinner.','我爸爸晚餐煮肉。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('meet','v.','遇見；見面','elementary',1,'I meet my friend at the station.','我在車站和朋友見面。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('mine','pron.','我的東西','elementary',1,'This green notebook is mine.','這本綠色筆記本是我的。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('minute','n.','分鐘','elementary',1,'Wait one minute before you answer.','回答前等一分鐘。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('monday','n.','星期一','elementary',1,'We have English class on Monday.','我們星期一有英文課。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('more','adj./adv.','更多','elementary',1,'I want to learn more English words.','我想學更多英文單字。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('morning','n.','早上','elementary',1,'In the morning, I wash my face.','早上我洗臉。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('mountain','n.','山','elementary',1,'A cloud sits over the mountain.','一朵雲停在山上方。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('move','v.','移動','elementary',1,'Move your chair closer to the table.','把椅子移近桌子。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('movie','n.','電影','elementary',1,'The movie has a funny animal story.','這部電影有一個有趣的動物故事。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('much','adj./adv.','許多；非常','elementary',1,'I do not put much sugar in my tea.','我不在茶裡放太多糖。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('museum','n.','博物館','elementary',1,'The museum shows old pictures and stones.','博物館展示舊照片和石頭。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('music','n.','音樂','elementary',1,'Soft music plays before the song starts.','歌曲開始前播放輕柔的音樂。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('my','pron.','我的','elementary',1,'My bag is beside the chair.','我的書包在椅子旁邊。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('next','adj./adv.','下一個；接著','elementary',1,'Turn to the next page after you finish.','完成後翻到下一頁。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('nine','n.','九','elementary',1,'Nine flowers grow beside the path.','九朵花長在小路旁。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('nineteen','n.','十九','elementary',1,'Nineteen clouds move across the sky.','十九朵雲飄過天空。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('noodles','n.','麵','elementary',1,'We eat noodles on a rainy day.','下雨天我們吃麵。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('noon','n.','中午','elementary',1,'At noon, we eat lunch together.','中午我們一起吃午餐。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('november','n.','十一月','elementary',1,'November evenings get dark early.','十一月的傍晚很早變暗。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('october','n.','十月','elementary',1,'In October, the wind feels cool.','十月的風感覺涼爽。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('office','n.','辦公室','elementary',1,'My mother works in an office.','我媽媽在辦公室工作。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('ok','adj.','好的','elementary',1,'It is ok to make a small mistake.','犯一個小錯是沒關係的。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('one','n.','一','elementary',1,'I read one page before dinner.','我晚餐前讀一頁。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('our','pron.','我們的','elementary',1,'Our class reads in the library.','我們班在圖書館閱讀。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('out','adv.','外出；出去','elementary',1,'Take your book out of the bag.','把你的書從書包拿出來。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('outside','adv./prep.','在外面','elementary',1,'The children play outside after class.','孩子們下課後在外面玩。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('pants','n.','褲子','elementary',1,'These pants are too long for me.','這件褲子對我來說太長。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('phone','n.','電話','elementary',1,'Mom calls me on the phone after class.','媽媽下課後打電話給我。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('picture','n.','圖片；照片','elementary',1,'The picture shows a happy family.','這張圖片顯示一個快樂家庭。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('pizza','n.','披薩','elementary',1,'My friends share pizza after the game.','比賽後我的朋友們分享披薩。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('point','v./n.','指；點','elementary',1,'Point to the word you can read.','指出你會讀的單字。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('pork','n.','豬肉','elementary',1,'Mom puts pork in the lunch box.','媽媽把豬肉放進便當盒。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('post','n./v.','郵件；張貼','elementary',1,'I post a letter to my teacher.','我寄一封信給老師。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('potato','n.','馬鈴薯','elementary',1,'The hot potato is too warm to hold.','熱馬鈴薯太燙，不能拿。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('put','v.','放','elementary',1,'Put the ruler beside the notebook.','把尺放在筆記本旁邊。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('question','n.','問題','elementary',1,'Please read the question before you answer.','回答前請先讀問題。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('rainbow','n.','彩虹','elementary',1,'The rainbow has many beautiful colors.','彩虹有許多美麗的顏色。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('ride','v.','騎；搭乘','elementary',1,'She rides a bike to the playground.','她騎腳踏車去操場。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('right','n./adj.','右邊；正確的','elementary',1,'The library is on your right.','圖書館在你的右邊。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('rock','n.','岩石','elementary',1,'The frog sits on a warm rock.','青蛙坐在溫暖的岩石上。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('salad','n.','沙拉','elementary',1,'The salad has carrots and corn.','沙拉裡有紅蘿蔔和玉米。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('salt','n.','鹽','elementary',1,'Dad adds a little salt to the soup.','爸爸在湯裡加一點鹽。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('same','adj.','相同的','elementary',1,'We read the same story in class.','我們在課堂上讀同一個故事。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('sand','n.','沙','elementary',1,'Sand gets into my shoes at the beach.','沙子在海灘上跑進我的鞋裡。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('sandwich','n.','三明治','elementary',1,'I make a sandwich with egg and tomato.','我用蛋和番茄做三明治。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('saturday','n.','星期六','elementary',1,'On Saturday, we visit the zoo.','星期六我們參觀動物園。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('sea','n.','海','elementary',1,'The sea looks blue under the sun.','陽光下的大海看起來很藍。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('second','adj.','第二','elementary',1,'The second question is about the cat.','第二題是關於那隻貓。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('sentence','n.','句子','elementary',1,'Read the sentence and circle the answer.','讀句子並圈出答案。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('september','n.','九月','elementary',1,'School starts again in September.','九月學校再次開學。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('seven','n.','七','elementary',1,'Class starts at seven fifty.','七點五十開始上課。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('seventeen','n.','十七','elementary',1,'Seventeen pages are in this chapter.','這一章有十七頁。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('share','v.','分享','elementary',1,'We share cookies with our classmates.','我們和同學分享餅乾。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('she','pron.','她','elementary',1,'She reads a story after dinner.','她晚餐後讀故事。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('shirt','n.','襯衫','elementary',1,'He wears a white shirt to school.','他穿白襯衫去上學。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('shoes','n.','鞋子','elementary',1,'Put your shoes beside the door.','把鞋子放在門旁邊。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('shorts','n.','短褲','elementary',1,'I wear shorts on a hot day.','熱天我穿短褲。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('shout','v.','大叫','elementary',1,'Do not shout in the classroom.','不要在教室裡大叫。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('show','v.','展示','elementary',1,'Show me the picture in your book.','給我看你書裡的圖片。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('six','n.','六','elementary',1,'Six ducks swim in the pond.','六隻鴨子在池塘裡游泳。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('sixteen','n.','十六','elementary',1,'Sixteen birds fly over the sea.','十六隻鳥飛過大海。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('skirt','n.','裙子','elementary',1,'Her blue skirt moves in the wind.','她的藍裙子在風中擺動。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('smile','v./n.','微笑','elementary',1,'The girl smiles when she sees her friend.','女孩看到朋友時微笑。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('snack','n.','點心','elementary',1,'A banana is my afternoon snack.','香蕉是我的下午點心。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('soccer','n.','足球','elementary',1,'Soccer is my favorite sport after school.','足球是我放學後最喜歡的運動。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('socks','n.','襪子','elementary',1,'My socks are wet after the rain.','下雨後我的襪子濕了。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('some','adj.','一些','elementary',1,'There are some pencils in the box.','盒子裡有一些鉛筆。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('someone','pron.','某人','elementary',1,'Someone left a notebook on the desk.','有人把筆記本留在書桌上。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('song','n.','歌曲','elementary',1,'This song helps us remember new words.','這首歌幫助我們記住新單字。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('start','v.','開始','elementary',1,'Class starts at eight in the morning.','早上八點開始上課。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('station','n.','車站','elementary',1,'Meet me at the train station.','在車站和我見面。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('stone','n.','石頭','elementary',1,'The moon stone feels warm in Lily''s hand.','月亮石在莉莉手中感覺溫暖。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('stop','v.','停止','elementary',1,'Stop at the red light before crossing.','過馬路前在紅燈停下。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('store','n.','商店','elementary',1,'The store sells notebooks and pencils.','那家商店賣筆記本和鉛筆。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('story','n.','故事','elementary',1,'The story is about a brave girl.','這個故事是關於一個勇敢的女孩。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('study','v.','讀書；學習','elementary',1,'I study English for ten minutes every day.','我每天讀十分鐘英文。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('sugar','n.','糖','elementary',1,'Do not put too much sugar in tea.','不要在茶裡放太多糖。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('sunday','n.','星期日','elementary',1,'Sunday is a quiet family day.','星期日是安靜的家庭日。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('supermarket','n.','超級市場','elementary',1,'We buy milk at the supermarket.','我們在超市買牛奶。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('ten','n.','十','elementary',1,'Write ten words in your notebook.','在筆記本裡寫十個單字。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('test','n.','考試；測驗','elementary',1,'The reading test has five questions.','閱讀測驗有五個問題。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('that','pron.','那個','elementary',1,'That picture shows a yellow bus.','那張圖片顯示黃色公車。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('their','pron.','他們的','elementary',1,'Their house is near the park.','他們的房子在公園附近。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('them','pron.','他們','elementary',1,'I help them carry the books.','我幫他們拿書。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('these','pron.','這些','elementary',1,'These words are in today''s lesson.','這些單字在今天的課裡。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('they','pron.','他們','elementary',1,'They play soccer after school.','他們放學後踢足球。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('third','adj.','第三','elementary',1,'The third picture shows a river.','第三張圖片顯示一條河。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('thirteen','n.','十三','elementary',1,'Thirteen apples are in the basket.','籃子裡有十三顆蘋果。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('thirty','n.','三十','elementary',1,'The bus comes in thirty minutes.','公車三十分鐘後來。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('this','pron.','這個','elementary',1,'This sentence is easy to read.','這個句子很容易讀。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('those','pron.','那些','elementary',1,'Those flowers are beside the river.','那些花在河邊。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('three','n.','三','elementary',1,'I have three pencils in my bag.','我的書包裡有三支鉛筆。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('thursday','n.','星期四','elementary',1,'I play basketball on Thursday afternoon.','我星期四下午打籃球。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('time','n.','時間','elementary',1,'It is time to listen and repeat.','該聽並跟讀了。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('to','prep.','到；給','elementary',1,'I walk to school with my brother.','我和哥哥走路去學校。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('tomato','n.','番茄','elementary',1,'A red tomato is in the salad.','沙拉裡有一顆紅番茄。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('touch','v.','觸摸','elementary',1,'Do not touch the hot soup bowl.','不要碰熱湯碗。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('toy','n.','玩具','elementary',1,'The toy car is under the bed.','玩具車在床下。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('try','v.','嘗試','elementary',1,'Try again if the answer is wrong.','答案錯了就再試一次。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('tshirt','n.','T恤','elementary',1,'My T-shirt has a green turtle on it.','我的 T 恤上有一隻綠色烏龜。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('tuesday','n.','星期二','elementary',1,'On Tuesday, I practice spelling words.','星期二我練習拼單字。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('turn','v./n.','轉動；輪到','elementary',1,'Turn left at the school gate.','在校門口向左轉。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('twelve','n.','十二','elementary',1,'There are twelve months in a year.','一年有十二個月。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('twenty','n.','二十','elementary',1,'We count to twenty in English.','我們用英文數到二十。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('two','n.','二','elementary',1,'Two birds sit in the tree.','兩隻鳥坐在樹上。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('up','adv.','向上','elementary',1,'Look up at the bright moon.','抬頭看明亮的月亮。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('us','pron.','我們','elementary',1,'The teacher gives us a reading card.','老師給我們一張閱讀卡。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('vegetable','n.','蔬菜','elementary',1,'I eat one vegetable with every meal.','我每餐都吃一種蔬菜。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('visit','v.','拜訪；參觀','elementary',1,'We visit the museum on Saturday.','我們星期六參觀博物館。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('wait','v.','等待','elementary',1,'Wait for your turn to speak.','等輪到你再說話。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('we','pron.','我們','elementary',1,'We practice English every morning.','我們每天早上練習英文。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('wednesday','n.','星期三','elementary',1,'Wednesday is our reading day.','星期三是我們的閱讀日。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('with','prep.','和...一起','elementary',1,'I read with my dad at night.','我晚上和爸爸一起閱讀。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('without','prep.','沒有','elementary',1,'I cannot write without a pencil.','沒有鉛筆我不能寫字。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('word','n.','單字','elementary',1,'I write one new word on each card.','我在每張卡片上寫一個新單字。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('work','v./n.','工作','elementary',1,'We work together to finish the poster.','我們一起完成海報。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('wrong','adj.','錯的','elementary',1,'I fix the wrong answer after checking it.','檢查後我修正錯誤答案。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('you','pron.','你；你們','elementary',1,'You can read this sentence slowly.','你可以慢慢讀這個句子。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('your','pron.','你的；你們的','elementary',1,'Put your pencil on the desk.','把你的鉛筆放在書桌上。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('zero','n.','零','elementary',1,'There are zero cookies left on the plate.','盤子上沒有餅乾了。','Supplemental','','[]'::jsonb,'[]'::jsonb),
('zoo','n.','動物園','elementary',1,'At the zoo, we see lions and elephants.','在動物園，我們看見獅子和大象。','Supplemental','','[]'::jsonb,'[]'::jsonb)
ON CONFLICT (word, level) DO NOTHING;
