-- ═══════════════════════════════════════════════════════════════
-- EnglishGo — Seed Vocabulary Batch 3 (追加 400 字)
-- 高中 +200 / 國中 +200
-- 累計目標：小學 300 / 國中 500 / 高中 300
-- ═══════════════════════════════════════════════════════════════

-- ═══ SENIOR Batch 3 — 200 words (Level 4-6) ═════════════════
INSERT INTO public.word_bank (word, pos, meaning, level, ceec_level, example, example_zh, category, phonetic, forms, collocations) VALUES
('absurd','adj.','荒謬的','senior',5,'That idea is absurd.','那個想法很荒謬。','Adjectives','/əbˈsɜːrd/','[]','[]'),
('abundance','n.','豐富','senior',5,'An abundance of food.','豐富的食物。','Basic','/əˈbʌn.dəns/','[{"w":"abundant","p":"adj.","n":"豐富的"}]','[]'),
('accessible','adj.','可取得的','senior',5,'The information is accessible.','資訊是可取得的。','Adjectives','/əkˈses.ə.bəl/','[{"w":"access","p":"n.","n":"取得"}]','[]'),
('acquisition','n.','獲得','senior',6,'Language acquisition.','語言習得。','Academic','/ˌæk.wɪˈzɪʃ.ən/','[{"w":"acquire","p":"v.","n":"獲得"}]','[]'),
('adjacent','adj.','鄰近的','senior',6,'The adjacent room.','隔壁房間。','Adjectives','/əˈdʒeɪ.sənt/','[]','[]'),
('adverse','adj.','不利的','senior',5,'Adverse weather conditions.','不利的天氣條件。','Adjectives','/ˈæd.vɜːrs/','[]','[]'),
('advocate','v.','提倡','senior',5,'She advocates for animal rights.','她提倡動物權利。','Communication','/ˈæd.və.keɪt/','[]','[]'),
('aesthetic','adj.','美學的','senior',6,'Aesthetic value.','美學價值。','Art','/esˈθet.ɪk/','[]','[]'),
('aggregate','adj.','總計的','senior',6,'The aggregate score.','總分。','Academic','/ˈæɡ.rɪ.ɡət/','[]','[]'),
('allegation','n.','指控','senior',6,'Serious allegations.','嚴重的指控。','Society','/ˌæl.əˈɡeɪ.ʃən/','[{"w":"allege","p":"v.","n":"聲稱"}]','[]'),
('alliance','n.','聯盟','senior',5,'A military alliance.','軍事聯盟。','Society','/əˈlaɪ.əns/','[{"w":"ally","p":"n.","n":"盟友"}]','[]'),
('alter','v.','改變','senior',4,'Do not alter the document.','不要修改文件。','Actions','/ˈɔːl.tər/','[{"w":"alteration","p":"n.","n":"改變"}]','[]'),
('ample','adj.','充足的','senior',5,'We have ample time.','我們有充足的時間。','Adjectives','/ˈæm.pəl/','[]','[]'),
('analogy','n.','類比','senior',6,'Draw an analogy.','做一個類比。','Academic','/əˈnæl.ə.dʒi/','[]','[]'),
('apparatus','n.','裝置','senior',6,'Laboratory apparatus.','實驗室裝置。','Science','/ˌæp.əˈræt̬.əs/','[]','[]'),
('applaud','v.','鼓掌','senior',5,'The audience applauded loudly.','觀眾大聲鼓掌。','Actions','/əˈplɑːd/','[{"w":"applause","p":"n.","n":"掌聲"}]','[]'),
('arbitrary','adj.','武斷的','senior',6,'An arbitrary decision.','武斷的決定。','Adjectives','/ˈɑːr.bə.trer.i/','[]','[]'),
('aspire','v.','嚮往','senior',5,'She aspires to be a scientist.','她嚮往成為科學家。','Feelings','/əˈspaɪr/','[{"w":"aspiration","p":"n.","n":"抱負"}]','[]'),
('assert','v.','斷言','senior',5,'He asserted his innocence.','他斷言自己是無辜的。','Communication','/əˈsɜːrt/','[{"w":"assertion","p":"n.","n":"斷言"}]','[]'),
('asset','n.','資產','senior',5,'Education is a valuable asset.','教育是有價值的資產。','Business','/ˈæs.et/','[]','[]'),
('authorize','v.','授權','senior',5,'He authorized the payment.','他授權了這筆付款。','Business','/ˈɑː.θər.aɪz/','[{"w":"authority","p":"n.","n":"權威"},{"w":"authorization","p":"n.","n":"授權"}]','[]'),
('autonomous','adj.','自主的','senior',6,'An autonomous vehicle.','自動駕駛車。','Technology','/ɔːˈtɑː.nə.məs/','[{"w":"autonomy","p":"n.","n":"自主權"}]','[]'),
('avert','v.','避免','senior',6,'Avert a disaster.','避免一場災難。','Actions','/əˈvɜːrt/','[]','[]'),
('benign','adj.','良性的','senior',6,'A benign tumor.','良性腫瘤。','Health','/bɪˈnaɪn/','[]','[]'),
('betray','v.','背叛','senior',5,'He betrayed his friends.','他背叛了朋友。','Actions','/bɪˈtreɪ/','[{"w":"betrayal","p":"n.","n":"背叛"}]','[]'),
('bias','n.','偏見','senior',5,'Avoid personal bias.','避免個人偏見。','Society','/ˈbaɪ.əs/','[{"w":"biased","p":"adj.","n":"有偏見的"}]','[]'),
('blaze','v.','燃燒','senior',6,'The fire blazed all night.','火整夜燃燒。','Nature','/bleɪz/','[]','[]'),
('blunt','adj.','鈍的；直率的','senior',5,'A blunt response.','直率的回應。','Adjectives','/blʌnt/','[]','[]'),
('bolster','v.','支撐','senior',6,'Bolster the economy.','支撐經濟。','Actions','/ˈboʊl.stər/','[]','[]'),
('breach','n.','違反','senior',5,'A breach of contract.','違反合約。','Society','/briːtʃ/','[]','[]'),
('brink','n.','邊緣','senior',6,'On the brink of war.','在戰爭邊緣。','Basic','/brɪŋk/','[]','["on the brink of 在…邊緣"]'),
('brutal','adj.','殘暴的','senior',5,'A brutal attack.','殘暴的攻擊。','Adjectives','/ˈbruː.t̬əl/','[{"w":"brutality","p":"n.","n":"殘暴"}]','[]'),
('bulk','n.','大量','senior',5,'Buy in bulk.','大量購買。','Business','/bʌlk/','[]','["in bulk 大量"]'),
('cater','v.','迎合','senior',6,'Cater to customer needs.','迎合顧客需求。','Business','/ˈkeɪ.t̬ər/','[]','["cater to 迎合"]'),
('cease','v.','停止','senior',5,'The rain ceased.','雨停了。','Actions','/siːs/','[]','[]'),
('chronic','adj.','慢性的','senior',5,'Chronic illness.','慢性疾病。','Health','/ˈkrɑː.nɪk/','[]','[]'),
('civic','adj.','公民的','senior',5,'Civic duty.','公民義務。','Society','/ˈsɪv.ɪk/','[]','[]'),
('coherent','adj.','連貫的','senior',6,'A coherent argument.','連貫的論點。','Academic','/koʊˈhɪr.ənt/','[{"w":"coherence","p":"n.","n":"連貫性"}]','[]'),
('coincide','v.','巧合','senior',5,'Our opinions coincide.','我們的意見一致。','Basic','/ˌkoʊ.ɪnˈsaɪd/','[{"w":"coincidence","p":"n.","n":"巧合"}]','[]'),
('commence','v.','開始','senior',6,'The ceremony will commence.','典禮將開始。','Actions','/kəˈmens/','[]','[]'),
('compel','v.','迫使','senior',5,'She was compelled to resign.','她被迫辭職。','Actions','/kəmˈpel/','[{"w":"compelling","p":"adj.","n":"令人信服的"}]','[]'),
('complement','v.','補充','senior',5,'The two colors complement each other.','這兩個顏色互補。','Actions','/ˈkɑːm.plə.ment/','[]','[]'),
('comply','v.','遵守','senior',5,'Comply with the regulations.','遵守規定。','Actions','/kəmˈplaɪ/','[{"w":"compliance","p":"n.","n":"遵守"}]','["comply with 遵守"]'),
('component','n.','組件','senior',4,'A key component.','關鍵組件。','Technology','/kəmˈpoʊ.nənt/','[]','[]'),
('compound','n.','化合物','senior',5,'A chemical compound.','化學化合物。','Science','/ˈkɑːm.paʊnd/','[]','[]'),
('conceive','v.','構想','senior',5,'She conceived a brilliant plan.','她構想了一個絕妙的計畫。','Actions','/kənˈsiːv/','[]','[]'),
('condemn','v.','譴責','senior',5,'The world condemned the attack.','全世界譴責這次攻擊。','Communication','/kənˈdem/','[]','[]'),
('confine','v.','限制','senior',5,'Confine the discussion to the topic.','把討論限制在主題內。','Actions','/kənˈfaɪn/','[]','[]'),
('conform','v.','遵從','senior',5,'Conform to social norms.','遵從社會規範。','Society','/kənˈfɔːrm/','[{"w":"conformity","p":"n.","n":"遵從"}]','[]'),
('confront','v.','面對','senior',4,'Confront the challenge.','面對挑戰。','Actions','/kənˈfrʌnt/','[{"w":"confrontation","p":"n.","n":"對抗"}]','[]'),
('conquest','n.','征服','senior',6,'The conquest of space.','太空征服。','History','/ˈkɑːŋ.kwest/','[{"w":"conquer","p":"v.","n":"征服"}]','[]'),
('consensus','n.','共識','senior',5,'We reached a consensus.','我們達成共識。','Communication','/kənˈsen.səs/','[]','[]'),
('consent','n.','同意','senior',5,'With your consent.','在你的同意下。','Communication','/kənˈsent/','[]','[]'),
('conspiracy','n.','陰謀','senior',6,'A conspiracy theory.','陰謀論。','Society','/kənˈspɪr.ə.si/','[]','[]'),
('constraint','n.','限制','senior',5,'Budget constraints.','預算限制。','Business','/kənˈstreɪnt/','[{"w":"constrain","p":"v.","n":"限制"}]','[]'),
('contemplate','v.','沉思','senior',5,'She contemplated her future.','她沉思她的未來。','Actions','/ˈkɑːn.təm.pleɪt/','[]','[]'),
('contempt','n.','輕蔑','senior',5,'He showed contempt.','他表現出輕蔑。','Feelings','/kənˈtempt/','[]','[]'),
('contend','v.','爭奪；聲稱','senior',5,'They contend for the title.','他們爭奪頭銜。','Actions','/kənˈtend/','[]','[]'),
('contradict','v.','矛盾','senior',5,'Your actions contradict your words.','你的行為和你的話矛盾。','Communication','/ˌkɑːn.trəˈdɪkt/','[{"w":"contradiction","p":"n.","n":"矛盾"}]','[]'),
('controversy','n.','爭議','senior',4,'The decision sparked controversy.','這個決定引發了爭議。','Society','/ˈkɑːn.trə.vɜːr.si/','[]','[]'),
('convey','v.','傳達','senior',4,'Convey the message.','傳達訊息。','Communication','/kənˈveɪ/','[]','[]'),
('cooperate','v.','合作','senior',4,'Nations must cooperate.','國家必須合作。','Actions','/koʊˈɑː.pər.eɪt/','[{"w":"cooperation","p":"n.","n":"合作"}]','[]'),
('corporate','adj.','企業的','senior',5,'Corporate culture.','企業文化。','Business','/ˈkɔːr.pər.ət/','[{"w":"corporation","p":"n.","n":"企業"}]','[]'),
('corresponding','adj.','對應的','senior',5,'The corresponding number.','對應的數字。','Academic','/ˌkɔːr.əˈspɑːn.dɪŋ/','[{"w":"correspond","p":"v.","n":"對應"}]','[]'),
('corrupt','adj.','腐敗的','senior',5,'A corrupt government.','腐敗的政府。','Society','/kəˈrʌpt/','[{"w":"corruption","p":"n.","n":"腐敗"}]','[]'),
('courtesy','n.','禮貌','senior',5,'Show some courtesy.','表現一些禮貌。','Communication','/ˈkɜːr.t̬ə.si/','[{"w":"courteous","p":"adj.","n":"有禮的"}]','[]'),
('craft','n.','工藝','senior',5,'Traditional crafts.','傳統工藝。','Art','/kræft/','[]','[]'),
('credible','adj.','可信的','senior',5,'A credible source.','可信的來源。','Adjectives','/ˈkred.ə.bəl/','[{"w":"credibility","p":"n.","n":"可信度"}]','[]'),
('curriculum','n.','課程','senior',5,'The school curriculum.','學校課程。','School','/kəˈrɪk.jə.ləm/','[]','[]'),
('cynical','adj.','憤世嫉俗的','senior',6,'A cynical attitude.','憤世嫉俗的態度。','Personality','/ˈsɪn.ɪ.kəl/','[]','[]'),
('deem','v.','認為','senior',5,'It was deemed necessary.','它被認為是必要的。','Actions','/diːm/','[]','[]'),
('deficit','n.','赤字','senior',5,'A budget deficit.','預算赤字。','Business','/ˈdef.ɪ.sɪt/','[]','[]'),
('degradation','n.','退化','senior',6,'Environmental degradation.','環境退化。','Nature','/ˌdeɡ.rəˈdeɪ.ʃən/','[{"w":"degrade","p":"v.","n":"退化"}]','[]'),
('delegate','v.','委派','senior',5,'Delegate tasks to your team.','把任務委派給你的團隊。','Business','/ˈdel.ɪ.ɡeɪt/','[]','[]'),
('depict','v.','描繪','senior',5,'The painting depicts a garden.','畫描繪了一座花園。','Art','/dɪˈpɪkt/','[]','[]'),
('deploy','v.','部署','senior',6,'Deploy the troops.','部署軍隊。','Actions','/dɪˈplɔɪ/','[{"w":"deployment","p":"n.","n":"部署"}]','[]'),
('deprive','v.','剝奪','senior',5,'Deprive someone of freedom.','剝奪某人的自由。','Actions','/dɪˈpraɪv/','[{"w":"deprivation","p":"n.","n":"剝奪"}]','["deprive of 剝奪"]'),
('derive','v.','源自','senior',5,'The word derives from Latin.','這個字源自拉丁文。','Academic','/dɪˈraɪv/','[]','["derive from 源自"]'),
('designate','v.','指定','senior',5,'She was designated as leader.','她被指定為領導者。','Actions','/ˈdez.ɪɡ.neɪt/','[]','[]'),
('despair','n.','絕望','senior',5,'A feeling of despair.','絕望的感覺。','Feelings','/dɪˈsper/','[{"w":"desperate","p":"adj.","n":"絕望的"}]','[]'),
('detain','v.','拘留','senior',6,'The police detained the suspect.','警察拘留了嫌疑犯。','Society','/dɪˈteɪn/','[{"w":"detention","p":"n.","n":"拘留"}]','[]'),
('deter','v.','阻止','senior',6,'The penalty deters crime.','刑罰阻止犯罪。','Actions','/dɪˈtɜːr/','[{"w":"deterrent","p":"n.","n":"威懾"}]','[]'),
('diagnose','v.','診斷','senior',5,'The doctor diagnosed the illness.','醫生診斷了疾病。','Health','/ˈdaɪ.əɡ.noʊz/','[{"w":"diagnosis","p":"n.","n":"診斷"}]','[]'),
('dimension','n.','維度','senior',4,'A new dimension.','新的維度。','Science','/dɪˈmen.ʃən/','[]','[]'),
('diplomatic','adj.','外交的','senior',5,'A diplomatic solution.','外交解決方案。','Society','/ˌdɪp.ləˈmæt̬.ɪk/','[{"w":"diplomacy","p":"n.","n":"外交"}]','[]'),
('discard','v.','丟棄','senior',5,'Discard the old files.','丟棄舊檔案。','Actions','/dɪˈskɑːrd/','[]','[]'),
('disclose','v.','揭露','senior',5,'He disclosed the secret.','他揭露了秘密。','Communication','/dɪˈskloʊz/','[{"w":"disclosure","p":"n.","n":"揭露"}]','[]'),
('discourse','n.','論述','senior',6,'Academic discourse.','學術論述。','Academic','/ˈdɪs.kɔːrs/','[]','[]'),
('displace','v.','取代','senior',5,'Machines displace workers.','機器取代了工人。','Actions','/dɪˈspleɪs/','[{"w":"displacement","p":"n.","n":"取代"}]','[]'),
('dispose','v.','處置','senior',5,'Dispose of waste properly.','正確處理廢棄物。','Actions','/dɪˈspoʊz/','[{"w":"disposal","p":"n.","n":"處理"}]','["dispose of 處理"]'),
('dispute','n.','爭端','senior',5,'A labor dispute.','勞資爭端。','Society','/dɪˈspjuːt/','[]','[]'),
('disrupt','v.','擾亂','senior',5,'The storm disrupted traffic.','暴風雨擾亂了交通。','Actions','/dɪsˈrʌpt/','[{"w":"disruption","p":"n.","n":"擾亂"}]','[]'),
('dissolve','v.','溶解','senior',5,'Salt dissolves in water.','鹽溶解在水中。','Science','/dɪˈzɑːlv/','[]','[]'),
('distinct','adj.','不同的','senior',4,'Two distinct groups.','兩個不同的群體。','Adjectives','/dɪˈstɪŋkt/','[{"w":"distinction","p":"n.","n":"區別"}]','[]'),
('distort','v.','扭曲','senior',5,'Do not distort the facts.','不要扭曲事實。','Actions','/dɪˈstɔːrt/','[{"w":"distortion","p":"n.","n":"扭曲"}]','[]'),
('diverse','adj.','多元的','senior',4,'A diverse population.','多元的人口。','Society','/dɪˈvɜːrs/','[{"w":"diversity","p":"n.","n":"多元性"}]','[]'),
('doctrine','n.','教義','senior',6,'Political doctrine.','政治教義。','Society','/ˈdɑːk.trɪn/','[]','[]'),
('domain','n.','領域','senior',5,'The public domain.','公共領域。','Academic','/doʊˈmeɪn/','[]','[]'),
('donate','v.','捐贈','senior',4,'Donate blood.','捐血。','Society','/ˈdoʊ.neɪt/','[{"w":"donation","p":"n.","n":"捐贈"}]','[]'),
('doom','n.','厄運','senior',6,'A sense of doom.','一種厄運感。','Feelings','/duːm/','[]','[]'),
('drain','v.','排水','senior',5,'Drain the pool.','把泳池的水排掉。','Actions','/dreɪn/','[]','[]'),
('drought','n.','乾旱','senior',5,'A severe drought.','嚴重乾旱。','Nature','/draʊt/','[]','[]'),
('durable','adj.','耐用的','senior',5,'A durable material.','耐用的材料。','Adjectives','/ˈdʊr.ə.bəl/','[{"w":"durability","p":"n.","n":"耐用性"}]','[]'),
('dynamic','adj.','動態的','senior',5,'A dynamic environment.','動態的環境。','Adjectives','/daɪˈnæm.ɪk/','[]','[]'),
('ecosystem','n.','生態系','senior',5,'A fragile ecosystem.','脆弱的生態系。','Nature','/ˈiː.koʊ.sɪs.təm/','[]','[]'),
('efficient','adj.','有效率的','senior',4,'An efficient system.','有效率的系統。','Adjectives','/ɪˈfɪʃ.ənt/','[{"w":"efficiency","p":"n.","n":"效率"}]','[]'),
('emission','n.','排放','senior',5,'Carbon emissions.','碳排放。','Nature','/ɪˈmɪʃ.ən/','[{"w":"emit","p":"v.","n":"排放"}]','[]'),
('empathy','n.','同理心','senior',5,'Show empathy towards others.','對他人表現同理心。','Feelings','/ˈem.pə.θi/','[]','[]'),
('empirical','adj.','實證的','senior',6,'Empirical evidence.','實證證據。','Science','/ɪmˈpɪr.ɪ.kəl/','[]','[]'),
('endeavor','n.','努力','senior',5,'A worthy endeavor.','值得的努力。','Actions','/ɪnˈdev.ər/','[]','[]'),
('endorse','v.','支持','senior',5,'She endorsed the product.','她代言了這個產品。','Business','/ɪnˈdɔːrs/','[{"w":"endorsement","p":"n.","n":"背書"}]','[]'),
('enforce','v.','執行','senior',5,'Enforce the law.','執行法律。','Society','/ɪnˈfɔːrs/','[{"w":"enforcement","p":"n.","n":"執行"}]','[]'),
('enhance','v.','增強','senior',4,'Enhance your skills.','增強你的技能。','Actions','/ɪnˈhæns/','[{"w":"enhancement","p":"n.","n":"增強"}]','[]'),
('enterprise','n.','企業','senior',5,'A private enterprise.','私人企業。','Business','/ˈen.t̬ər.praɪz/','[]','[]'),
('entity','n.','實體','senior',6,'A legal entity.','法人實體。','Business','/ˈen.t̬ə.t̬i/','[]','[]'),
('entrepreneur','n.','企業家','senior',5,'A successful entrepreneur.','成功的企業家。','Business','/ˌɑːn.trə.prəˈnɜːr/','[]','[]'),
('envision','v.','預想','senior',6,'Envision a better future.','預想更美好的未來。','Actions','/ɪnˈvɪʒ.ən/','[]','[]'),
('equity','n.','公平','senior',6,'Social equity.','社會公平。','Society','/ˈek.wə.t̬i/','[]','[]'),
('erratic','adj.','不穩定的','senior',6,'Erratic behavior.','不穩定的行為。','Adjectives','/ɪˈræt̬.ɪk/','[]','[]'),
('escalate','v.','升級','senior',5,'The conflict escalated.','衝突升級了。','Actions','/ˈes.kə.leɪt/','[{"w":"escalation","p":"n.","n":"升級"}]','[]'),
('essence','n.','本質','senior',5,'The essence of the problem.','問題的本質。','Academic','/ˈes.əns/','[{"w":"essential","p":"adj.","n":"必要的"}]','[]'),
('eternal','adj.','永恆的','senior',5,'Eternal love.','永恆的愛。','Adjectives','/ɪˈtɜːr.nəl/','[]','[]'),
('evade','v.','逃避','senior',6,'Evade taxes.','逃稅。','Actions','/ɪˈveɪd/','[{"w":"evasion","p":"n.","n":"逃避"}]','[]'),
('excel','v.','擅長','senior',5,'She excels in math.','她擅長數學。','Actions','/ɪkˈsel/','[{"w":"excellent","p":"adj.","n":"優秀的"}]','[]'),
('excerpt','n.','摘錄','senior',6,'An excerpt from the book.','書的摘錄。','Academic','/ˈek.sɜːrpt/','[]','[]'),
('exile','n.','流放','senior',6,'Live in exile.','流亡。','Society','/ˈek.saɪl/','[]','[]'),
('expenditure','n.','支出','senior',5,'Government expenditure.','政府支出。','Business','/ɪkˈspen.dɪ.tʃər/','[]','[]'),
('explicit','adj.','明確的','senior',5,'Give explicit instructions.','給明確的指示。','Adjectives','/ɪkˈsplɪs.ɪt/','[]','[]'),
('exploit','v.','利用','senior',5,'Exploit natural resources.','利用自然資源。','Actions','/ɪkˈsplɔɪt/','[{"w":"exploitation","p":"n.","n":"利用；剝削"}]','[]'),
('extinction','n.','滅絕','senior',5,'Species face extinction.','物種面臨滅絕。','Nature','/ɪkˈstɪŋk.ʃən/','[{"w":"extinct","p":"adj.","n":"滅絕的"}]','[]'),
('extract','v.','提取','senior',5,'Extract the data.','提取數據。','Actions','/ɪkˈstrækt/','[{"w":"extraction","p":"n.","n":"提取"}]','[]'),
('fabricate','v.','捏造','senior',6,'He fabricated the story.','他捏造了故事。','Communication','/ˈfæb.rɪ.keɪt/','[]','[]'),
('faction','n.','派系','senior',6,'Political factions.','政治派系。','Society','/ˈfæk.ʃən/','[]','[]'),
('fatal','adj.','致命的','senior',5,'A fatal accident.','致命事故。','Adjectives','/ˈfeɪ.t̬əl/','[{"w":"fatality","p":"n.","n":"死亡"}]','[]'),
('feasible','adj.','可行的','senior',5,'A feasible plan.','可行的計畫。','Adjectives','/ˈfiː.zə.bəl/','[{"w":"feasibility","p":"n.","n":"可行性"}]','[]'),
('flaw','n.','缺陷','senior',5,'A fatal flaw.','致命缺陷。','Basic','/flɔː/','[{"w":"flawed","p":"adj.","n":"有缺陷的"}]','[]'),
('flourish','v.','繁榮','senior',5,'The business flourished.','事業蓬勃發展。','Actions','/ˈflɜːr.ɪʃ/','[]','[]'),
('foe','n.','敵人','senior',6,'Friend or foe.','朋友或敵人。','People','/foʊ/','[]','[]'),
('forbid','v.','禁止','senior',4,'Smoking is forbidden here.','這裡禁止吸菸。','Actions','/fərˈbɪd/','[{"w":"forbidden","p":"adj.","n":"被禁止的"}]','[]'),
('foremost','adj.','最重要的','senior',5,'The foremost expert.','最重要的專家。','Adjectives','/ˈfɔːr.moʊst/','[]','[]'),
('forge','v.','鍛造；偽造','senior',6,'Forge a new path.','開創新道路。','Actions','/fɔːrdʒ/','[]','[]'),
('forthcoming','adj.','即將來臨的','senior',6,'The forthcoming election.','即將到來的選舉。','Time','/ˌfɔːrθˈkʌm.ɪŋ/','[]','[]'),
('foster','v.','促進；寄養','senior',5,'Foster creativity.','促進創造力。','Actions','/ˈfɑː.stər/','[]','[]'),
('fraction','n.','小部分','senior',5,'Only a fraction of the cost.','只是成本的一小部分。','Basic','/ˈfræk.ʃən/','[]','[]'),
('fragment','n.','碎片','senior',5,'A fragment of glass.','一片玻璃碎片。','Basic','/ˈfræɡ.mənt/','[]','[]'),
('framework','n.','架構','senior',5,'A legal framework.','法律架構。','Academic','/ˈfreɪm.wɜːrk/','[]','[]'),
('franchise','n.','加盟','senior',6,'A restaurant franchise.','餐廳加盟。','Business','/ˈfræn.tʃaɪz/','[]','[]'),
('friction','n.','摩擦','senior',5,'Reduce friction.','減少摩擦。','Science','/ˈfrɪk.ʃən/','[]','[]'),
('fruitful','adj.','豐碩的','senior',6,'A fruitful discussion.','豐碩的討論。','Adjectives','/ˈfruːt.fəl/','[]','[]'),
('fulfill','v.','實現','senior',4,'Fulfill your dream.','實現夢想。','Actions','/fʊlˈfɪl/','[{"w":"fulfillment","p":"n.","n":"成就感"}]','[]'),
('futile','adj.','徒勞的','senior',6,'A futile attempt.','徒勞的嘗試。','Adjectives','/ˈfjuː.t̬əl/','[]','[]'),
('glimpse','n.','一瞥','senior',5,'A glimpse of the future.','未來的一瞥。','Basic','/ɡlɪmps/','[]','[]'),
('globe','n.','地球','senior',4,'Around the globe.','環繞地球。','Nature','/ɡloʊb/','[{"w":"global","p":"adj.","n":"全球的"},{"w":"globalization","p":"n.","n":"全球化"}]','[]'),
('grace','n.','優雅','senior',5,'She dances with grace.','她跳舞很優雅。','Personality','/ɡreɪs/','[{"w":"graceful","p":"adj.","n":"優雅的"}]','[]'),
('grasp','v.','抓住；理解','senior',5,'Grasp the concept.','理解概念。','Actions','/ɡræsp/','[]','[]'),
('grave','adj.','嚴重的','senior',5,'A grave mistake.','嚴重的錯誤。','Adjectives','/ɡreɪv/','[]','[]'),
('grieve','v.','悲傷','senior',5,'She grieved for her loss.','她為失去的東西悲傷。','Feelings','/ɡriːv/','[{"w":"grief","p":"n.","n":"悲傷"}]','[]'),
('gross','adj.','總的；嚴重的','senior',5,'Gross domestic product.','國內生產毛額。','Business','/ɡroʊs/','[]','["GDP 國內生產毛額"]'),
('guarantee','v.','保證','senior',4,'I guarantee it will work.','我保證它會成功。','Actions','/ˌɡer.ənˈtiː/','[]','[]'),
('habitat','n.','棲息地','senior',5,'Protect natural habitats.','保護自然棲息地。','Nature','/ˈhæb.ɪ.tæt/','[]','[]'),
('halt','v.','停止','senior',5,'Halt the production.','停止生產。','Actions','/hɑːlt/','[]','[]'),
('handicap','n.','障礙','senior',5,'Overcome a handicap.','克服障礙。','Health','/ˈhæn.di.kæp/','[]','[]'),
('harass','v.','騷擾','senior',5,'He was harassed at work.','他在工作中被騷擾。','Society','/həˈræs/','[{"w":"harassment","p":"n.","n":"騷擾"}]','[]'),
('harmony','n.','和諧','senior',5,'Live in harmony.','和諧共處。','Basic','/ˈhɑːr.mə.ni/','[{"w":"harmonious","p":"adj.","n":"和諧的"}]','[]'),
('harvest','n.','收穫','senior',5,'The autumn harvest.','秋天的收穫。','Nature','/ˈhɑːr.vɪst/','[]','[]'),
('hazard','n.','危險','senior',5,'A health hazard.','健康危害。','Health','/ˈhæz.ərd/','[{"w":"hazardous","p":"adj.","n":"危險的"}]','[]'),
('hinder','v.','阻礙','senior',5,'Rain hindered our progress.','雨阻礙了我們的進度。','Actions','/ˈhɪn.dər/','[]','[]'),
('horizontal','adj.','水平的','senior',5,'A horizontal line.','一條水平線。','Science','/ˌhɔːr.ɪˈzɑːn.t̬əl/','[]','[]'),
('hostile','adj.','敵意的','senior',5,'A hostile environment.','敵意的環境。','Adjectives','/ˈhɑːs.t̬əl/','[{"w":"hostility","p":"n.","n":"敵意"}]','[]'),
('humanitarian','adj.','人道的','senior',5,'Humanitarian aid.','人道援助。','Society','/hjuːˌmæn.ɪˈter.i.ən/','[]','[]'),
('humiliate','v.','羞辱','senior',6,'She was humiliated in public.','她在公開場合被羞辱。','Feelings','/hjuːˈmɪl.i.eɪt/','[{"w":"humiliation","p":"n.","n":"羞辱"}]','[]'),
('hypothetical','adj.','假設的','senior',6,'A hypothetical scenario.','假設的情境。','Academic','/ˌhaɪ.pəˈθet̬.ɪ.kəl/','[]','[]'),
('identical','adj.','完全相同的','senior',4,'The twins are identical.','雙胞胎長得一模一樣。','Adjectives','/aɪˈden.t̬ɪ.kəl/','[]','[]'),
('ignite','v.','點燃','senior',6,'Ignite a fire.','點燃火。','Actions','/ɪɡˈnaɪt/','[]','[]'),
('illusion','n.','幻覺','senior',5,'An optical illusion.','視覺幻覺。','Science','/ɪˈluː.ʒən/','[]','[]'),
('immune','adj.','免疫的','senior',5,'Immune to the disease.','對疾病免疫。','Health','/ɪˈmjuːn/','[{"w":"immunity","p":"n.","n":"免疫力"}]','[]'),
('impair','v.','損害','senior',6,'Alcohol impairs judgment.','酒精損害判斷力。','Health','/ɪmˈper/','[{"w":"impairment","p":"n.","n":"損害"}]','[]'),
('imperial','adj.','帝國的','senior',6,'The imperial palace.','皇宮。','History','/ɪmˈpɪr.i.əl/','[]','[]'),
('implicit','adj.','隱含的','senior',5,'An implicit agreement.','隱含的協議。','Adjectives','/ɪmˈplɪs.ɪt/','[]','[]'),
('impose','v.','強加','senior',4,'Impose a tax.','徵稅。','Society','/ɪmˈpoʊz/','[]','["impose on 強加於"]'),
('impulse','n.','衝動','senior',5,'An impulse purchase.','衝動消費。','Feelings','/ˈɪm.pʌls/','[{"w":"impulsive","p":"adj.","n":"衝動的"}]','[]'),
('incentive','n.','激勵','senior',5,'Financial incentives.','財務激勵。','Business','/ɪnˈsen.t̬ɪv/','[]','[]'),
('inclination','n.','傾向','senior',6,'A natural inclination.','自然的傾向。','Personality','/ˌɪn.klɪˈneɪ.ʃən/','[{"w":"incline","p":"v.","n":"傾向"}]','[]'),
('indicate','v.','指出','senior',4,'The data indicates a trend.','數據指出一個趨勢。','Academic','/ˈɪn.dɪ.keɪt/','[{"w":"indication","p":"n.","n":"跡象"},{"w":"indicator","p":"n.","n":"指標"}]','[]'),
('indispensable','adj.','不可或缺的','senior',6,'Water is indispensable.','水是不可或缺的。','Adjectives','/ˌɪn.dɪˈspen.sə.bəl/','[]','[]'),
('induce','v.','引起','senior',5,'Stress can induce illness.','壓力會引起疾病。','Actions','/ɪnˈduːs/','[]','[]'),
('inferior','adj.','低等的','senior',5,'An inferior product.','劣等產品。','Adjectives','/ɪnˈfɪr.i.ər/','[]','[]'),
('inflation','n.','通貨膨脹','senior',5,'Rising inflation.','上升的通貨膨脹。','Business','/ɪnˈfleɪ.ʃən/','[{"w":"inflate","p":"v.","n":"膨脹"}]','[]'),
('inhabit','v.','居住','senior',5,'Few people inhabit this island.','很少人住在這座島上。','Actions','/ɪnˈhæb.ɪt/','[{"w":"inhabitant","p":"n.","n":"居民"}]','[]'),
('inherent','adj.','固有的','senior',5,'An inherent risk.','固有的風險。','Adjectives','/ɪnˈhɪr.ənt/','[]','[]'),
('inherit','v.','繼承','senior',5,'He inherited the house.','他繼承了房子。','Actions','/ɪnˈher.ɪt/','[{"w":"inheritance","p":"n.","n":"遺產"}]','[]'),
('initiate','v.','發起','senior',5,'Initiate a conversation.','發起對話。','Actions','/ɪˈnɪʃ.i.eɪt/','[{"w":"initiative","p":"n.","n":"倡議"}]','[]'),
('injustice','n.','不公','senior',5,'Fight against injustice.','對抗不公。','Society','/ɪnˈdʒʌs.tɪs/','[]','[]'),
('innate','adj.','天生的','senior',6,'An innate ability.','天生的能力。','Adjectives','/ɪˈneɪt/','[]','[]'),
('insight','n.','洞察','senior',4,'Gain valuable insights.','獲得有價值的洞察。','Academic','/ˈɪn.saɪt/','[{"w":"insightful","p":"adj.","n":"有洞察力的"}]','[]'),
('inspect','v.','檢查','senior',5,'Inspect the building.','檢查建築。','Actions','/ɪnˈspekt/','[{"w":"inspection","p":"n.","n":"檢查"},{"w":"inspector","p":"n.","n":"檢查員"}]','[]'),
('inspire','v.','啟發','senior',4,'She inspires others.','她啟發了其他人。','Actions','/ɪnˈspaɪr/','[{"w":"inspiration","p":"n.","n":"靈感"}]','[]'),
('institute','n.','機構','senior',5,'A research institute.','研究機構。','Academic','/ˈɪn.stɪ.tuːt/','[{"w":"institution","p":"n.","n":"制度"}]','[]'),
('intact','adj.','完整的','senior',5,'The building remained intact.','建築保持完好。','Adjectives','/ɪnˈtækt/','[]','[]'),
('intellect','n.','智力','senior',5,'A person of great intellect.','智力高超的人。','Academic','/ˈɪn.t̬əl.ekt/','[{"w":"intellectual","p":"adj.","n":"知識的"}]','[]'),
('intensify','v.','加劇','senior',5,'The storm intensified.','暴風雨加劇了。','Actions','/ɪnˈten.sə.faɪ/','[{"w":"intense","p":"adj.","n":"強烈的"},{"w":"intensity","p":"n.","n":"強度"}]','[]'),
('interfere','v.','干涉','senior',5,'Do not interfere.','不要干涉。','Actions','/ˌɪn.t̬ərˈfɪr/','[{"w":"interference","p":"n.","n":"干涉"}]','["interfere with 干涉"]'),
('interpret','v.','解讀','senior',4,'How do you interpret this?','你如何解讀這個？','Academic','/ɪnˈtɜːr.prɪt/','[{"w":"interpretation","p":"n.","n":"解讀"},{"w":"interpreter","p":"n.","n":"口譯員"}]','[]'),
('intervene','v.','介入','senior',5,'The government intervened.','政府介入了。','Actions','/ˌɪn.t̬ərˈviːn/','[{"w":"intervention","p":"n.","n":"介入"}]','[]'),
('intimate','adj.','親密的','senior',5,'An intimate relationship.','親密的關係。','Adjectives','/ˈɪn.t̬ɪ.mət/','[]','[]'),
('intricate','adj.','複雜的','senior',6,'An intricate design.','複雜的設計。','Adjectives','/ˈɪn.trɪ.kət/','[]','[]'),
('intrinsic','adj.','內在的','senior',6,'Intrinsic value.','內在價值。','Adjectives','/ɪnˈtrɪn.zɪk/','[]','[]'),
('invade','v.','入侵','senior',5,'The army invaded the country.','軍隊入侵了該國。','History','/ɪnˈveɪd/','[{"w":"invasion","p":"n.","n":"入侵"}]','[]'),
('inventory','n.','庫存','senior',5,'Check the inventory.','盤點庫存。','Business','/ˈɪn.vən.tɔːr.i/','[]','[]'),
('ironic','adj.','諷刺的','senior',5,'An ironic twist.','諷刺的轉折。','Adjectives','/aɪˈrɑː.nɪk/','[{"w":"irony","p":"n.","n":"諷刺"}]','[]'),
('isolate','v.','隔離','senior',4,'Isolate the infected patients.','隔離感染的病人。','Health','/ˈaɪ.sə.leɪt/','[{"w":"isolation","p":"n.","n":"隔離"}]','[]'),
('jeopardize','v.','危害','senior',6,'Do not jeopardize your career.','不要危害你的職涯。','Actions','/ˈdʒep.ər.daɪz/','[{"w":"jeopardy","p":"n.","n":"危險"}]','[]'),
('jurisdiction','n.','管轄權','senior',6,'Under federal jurisdiction.','在聯邦管轄下。','Society','/ˌdʒʊr.ɪsˈdɪk.ʃən/','[]','[]'),
('justify','v.','證明正當','senior',4,'Justify your answer.','證明你的答案是正當的。','Academic','/ˈdʒʌs.tɪ.faɪ/','[{"w":"justification","p":"n.","n":"正當理由"}]','[]'),
('keen','adj.','渴望的','senior',5,'She is keen to learn.','她渴望學習。','Feelings','/kiːn/','[]','["keen on 熱衷於"]'),
('lament','v.','悲嘆','senior',6,'He lamented his loss.','他悲嘆他的損失。','Feelings','/ləˈment/','[]','[]'),
('landmark','n.','地標','senior',5,'A famous landmark.','著名地標。','Places','/ˈlænd.mɑːrk/','[]','[]'),
('legislation','n.','立法','senior',5,'New legislation was passed.','新法律通過了。','Society','/ˌledʒ.ɪˈsleɪ.ʃən/','[{"w":"legislate","p":"v.","n":"立法"}]','[]'),
('liberal','adj.','自由的','senior',5,'Liberal democracy.','自由民主。','Society','/ˈlɪb.ər.əl/','[]','[]'),
('likelihood','n.','可能性','senior',5,'The likelihood of success.','成功的可能性。','Basic','/ˈlaɪ.kli.hʊd/','[]','[]'),
('literacy','n.','識字能力','senior',5,'Improve digital literacy.','提升數位素養。','School','/ˈlɪt̬.ər.ə.si/','[{"w":"literate","p":"adj.","n":"有讀寫能力的"}]','[]'),
('lure','v.','引誘','senior',6,'Lured by the offer.','被優惠引誘。','Actions','/lʊr/','[]','[]'),
('magnitude','n.','規模','senior',6,'The magnitude of the problem.','問題的規模。','Academic','/ˈmæɡ.nɪ.tuːd/','[]','[]')
ON CONFLICT (word, level) DO NOTHING;

-- ═══ JUNIOR Batch 3 — 200 words (Level 2-3) ═════════════════
INSERT INTO public.word_bank (word, pos, meaning, level, ceec_level, example, example_zh, category, phonetic, forms, collocations) VALUES
('fatal','adj.','致命的','junior',3,'A fatal disease.','致命的疾病。','Health','/ˈfeɪ.t̬əl/','[]','[]'),
('feature','n.','特徵','junior',3,'An important feature.','重要的特徵。','Basic','/ˈfiː.tʃər/','[]','[]'),
('fiction','n.','小說','junior',3,'Science fiction.','科幻小說。','Art','/ˈfɪk.ʃən/','[{"w":"fictional","p":"adj.","n":"虛構的"}]','[]'),
('fierce','adj.','兇猛的','junior',3,'A fierce storm.','猛烈的暴風雨。','Adjectives','/fɪrs/','[]','[]'),
('figure','n.','數字；人物','junior',2,'An important figure.','重要人物。','Basic','/ˈfɪɡ.jər/','[]','["figure out 弄清楚"]'),
('flexible','adj.','有彈性的','junior',3,'A flexible schedule.','彈性的行程。','Adjectives','/ˈflek.sə.bəl/','[{"w":"flexibility","p":"n.","n":"彈性"}]','[]'),
('fond','adj.','喜愛的','junior',3,'I am fond of music.','我喜愛音樂。','Feelings','/fɑːnd/','[]','["be fond of 喜愛"]'),
('forecast','n.','預測','junior',3,'The weather forecast.','天氣預報。','Weather','/ˈfɔːr.kæst/','[]','[]'),
('formal','adj.','正式的','junior',2,'A formal dinner.','正式的晚餐。','Adjectives','/ˈfɔːr.məl/','[]','[]'),
('formula','n.','公式','junior',3,'A math formula.','數學公式。','Science','/ˈfɔːr.mjə.lə/','[]','[]'),
('fortune','n.','財富','junior',3,'She made a fortune.','她賺了一筆財富。','Money','/ˈfɔːr.tʃən/','[{"w":"fortunate","p":"adj.","n":"幸運的"},{"w":"unfortunately","p":"adv.","n":"不幸地"}]','[]'),
('foundation','n.','基礎','junior',3,'Build a strong foundation.','建立穩固的基礎。','Basic','/faʊnˈdeɪ.ʃən/','[]','[]'),
('frustrate','v.','使挫折','junior',3,'The delay frustrated everyone.','延遲讓每個人都感到挫折。','Feelings','/ˈfrʌs.treɪt/','[{"w":"frustrated","p":"adj.","n":"挫折的"},{"w":"frustrating","p":"adj.","n":"令人挫折的"},{"w":"frustration","p":"n.","n":"挫折"}]','[]'),
('function','n.','功能','junior',3,'What is its function?','它的功能是什麼？','Technology','/ˈfʌŋk.ʃən/','[{"w":"functional","p":"adj.","n":"功能性的"}]','[]'),
('fund','n.','基金','junior',3,'Raise funds for charity.','為慈善募款。','Money','/fʌnd/','[{"w":"funding","p":"n.","n":"資金"}]','[]'),
('fundamental','adj.','基本的','junior',3,'A fundamental right.','基本權利。','Adjectives','/ˌfʌn.dəˈmen.t̬əl/','[]','[]'),
('furthermore','adv.','此外','junior',3,'Furthermore, I disagree.','此外，我不同意。','Basic','/ˌfɜːr.ðərˈmɔːr/','[]','[]'),
('gender','n.','性別','junior',3,'Gender equality.','性別平等。','Society','/ˈdʒen.dər/','[]','[]'),
('generate','v.','產生','junior',3,'Generate electricity.','產生電力。','Science','/ˈdʒen.ə.reɪt/','[{"w":"generation","p":"n.","n":"世代；產生"}]','[]'),
('generous','adj.','慷慨的','junior',2,'She is very generous.','她很慷慨。','Personality','/ˈdʒen.ər.əs/','[{"w":"generosity","p":"n.","n":"慷慨"}]','[]'),
('genius','n.','天才','junior',3,'He is a math genius.','他是數學天才。','People','/ˈdʒiː.ni.əs/','[]','[]'),
('genuine','adj.','真正的','junior',3,'A genuine smile.','真誠的微笑。','Adjectives','/ˈdʒen.ju.ɪn/','[]','[]'),
('global','adj.','全球的','junior',2,'A global problem.','全球問題。','Basic','/ˈɡloʊ.bəl/','[{"w":"globally","p":"adv.","n":"全球地"},{"w":"globalization","p":"n.","n":"全球化"}]','[]'),
('govern','v.','統治','junior',3,'The president governs the country.','總統統治國家。','Society','/ˈɡʌv.ərn/','[{"w":"government","p":"n.","n":"政府"},{"w":"governor","p":"n.","n":"州長"}]','[]'),
('grant','v.','授予','junior',3,'Grant permission.','授予許可。','Actions','/ɡrænt/','[]','["take for granted 視為理所當然"]'),
('grateful','adj.','感激的','junior',2,'I am grateful for your help.','我感激你的幫助。','Feelings','/ˈɡreɪt.fəl/','[{"w":"gratitude","p":"n.","n":"感激"}]','[]'),
('grave','adj.','嚴重的','junior',3,'A grave situation.','嚴重的情況。','Adjectives','/ɡreɪv/','[]','[]'),
('guarantee','v.','保證','junior',3,'I guarantee it.','我保證。','Communication','/ˌɡer.ənˈtiː/','[]','[]'),
('guilty','adj.','有罪的','junior',3,'He felt guilty.','他感到內疚。','Feelings','/ˈɡɪl.ti/','[{"w":"guilt","p":"n.","n":"罪惡感"}]','[]'),
('harsh','adj.','嚴厲的','junior',3,'Harsh criticism.','嚴厲的批評。','Adjectives','/hɑːrʃ/','[]','[]'),
('hesitate','v.','猶豫','junior',3,'Do not hesitate to ask.','不要猶豫，儘管問。','Actions','/ˈhez.ɪ.teɪt/','[{"w":"hesitation","p":"n.","n":"猶豫"}]','[]'),
('highlight','v.','強調','junior',3,'Highlight the key points.','強調重點。','Actions','/ˈhaɪ.laɪt/','[]','[]'),
('hint','n.','暗示','junior',3,'Give me a hint.','給我一個暗示。','Communication','/hɪnt/','[]','[]'),
('honor','n.','榮譽','junior',2,'It is an honor to meet you.','很榮幸見到你。','Basic','/ˈɑː.nər/','[{"w":"honorable","p":"adj.","n":"光榮的"}]','[]'),
('horrify','v.','使恐懼','junior',3,'The news horrified everyone.','這消息讓每個人都恐懼。','Feelings','/ˈhɔːr.ə.faɪ/','[{"w":"horrible","p":"adj.","n":"可怕的"},{"w":"horror","p":"n.","n":"恐怖"}]','[]'),
('humble','adj.','謙虛的','junior',3,'He is a humble person.','他是個謙虛的人。','Personality','/ˈhʌm.bəl/','[]','[]'),
('ideal','adj.','理想的','junior',3,'An ideal solution.','理想的解決方案。','Adjectives','/aɪˈdiː.əl/','[{"w":"ideally","p":"adv.","n":"理想上"}]','[]'),
('identify','v.','辨認','junior',3,'Can you identify this bird?','你能辨認這隻鳥嗎？','Actions','/aɪˈden.tɪ.faɪ/','[{"w":"identity","p":"n.","n":"身份"},{"w":"identification","p":"n.","n":"辨認"}]','[]'),
('ignorant','adj.','無知的','junior',3,'He is ignorant of the facts.','他不知道事實。','Adjectives','/ˈɪɡ.nər.ənt/','[{"w":"ignore","p":"v.","n":"忽視"},{"w":"ignorance","p":"n.","n":"無知"}]','[]'),
('illegal','adj.','非法的','junior',3,'Illegal activity.','非法活動。','Society','/ɪˈliː.ɡəl/','[]','[]'),
('illustrate','v.','說明','junior',3,'Let me illustrate the point.','讓我說明這個重點。','Communication','/ˈɪl.ə.streɪt/','[{"w":"illustration","p":"n.","n":"插圖；說明"}]','[]'),
('image','n.','影像','junior',2,'A clear image.','清晰的影像。','Technology','/ˈɪm.ɪdʒ/','[]','[]'),
('imagine','v.','想像','junior',2,'Imagine a world without war.','想像一個沒有戰爭的世界。','Actions','/ɪˈmædʒ.ɪn/','[{"w":"imagination","p":"n.","n":"想像力"},{"w":"imaginary","p":"adj.","n":"想像的"}]','[]'),
('immediate','adj.','立即的','junior',3,'Take immediate action.','立即採取行動。','Adjectives','/ɪˈmiː.di.ət/','[{"w":"immediately","p":"adv.","n":"立刻"}]','[]'),
('impact','n.','影響','junior',3,'A huge impact on society.','對社會巨大的影響。','Basic','/ˈɪm.pækt/','[]','["have an impact on 對…有影響"]'),
('imply','v.','暗示','junior',3,'What are you implying?','你在暗示什麼？','Communication','/ɪmˈplaɪ/','[{"w":"implication","p":"n.","n":"暗示"}]','[]'),
('import','v.','進口','junior',3,'Taiwan imports oil.','台灣進口石油。','Business','/ɪmˈpɔːrt/','[{"w":"import","p":"n.","n":"進口品"}]','[]'),
('impose','v.','強加','junior',3,'Impose restrictions.','施加限制。','Actions','/ɪmˈpoʊz/','[]','[]'),
('impress','v.','使印象深刻','junior',2,'She impressed the judges.','她讓評審印象深刻。','Feelings','/ɪmˈpres/','[{"w":"impressive","p":"adj.","n":"令人印象深刻的"},{"w":"impression","p":"n.","n":"印象"}]','[]'),
('incident','n.','事件','junior',3,'A traffic incident.','交通事故。','Basic','/ˈɪn.sɪ.dənt/','[]','[]'),
('indicate','v.','指出','junior',3,'The arrow indicates the exit.','箭頭指出出口。','Actions','/ˈɪn.dɪ.keɪt/','[{"w":"indication","p":"n.","n":"指示"}]','[]'),
('individual','n.','個人','junior',3,'Each individual is unique.','每個人都是獨特的。','People','/ˌɪn.dɪˈvɪdʒ.u.əl/','[]','[]'),
('industrial','adj.','工業的','junior',3,'The industrial revolution.','工業革命。','Society','/ɪnˈdʌs.tri.əl/','[{"w":"industry","p":"n.","n":"工業"}]','[]'),
('inevitable','adj.','不可避免的','junior',3,'Change is inevitable.','改變是不可避免的。','Adjectives','/ɪnˈev.ɪ.t̬ə.bəl/','[]','[]'),
('infant','n.','嬰兒','junior',3,'An infant needs care.','嬰兒需要照顧。','People','/ˈɪn.fənt/','[]','[]'),
('initial','adj.','最初的','junior',3,'The initial plan.','最初的計畫。','Adjectives','/ɪˈnɪʃ.əl/','[{"w":"initially","p":"adv.","n":"最初"}]','[]'),
('injure','v.','傷害','junior',2,'He injured his leg.','他的腳受傷了。','Health','/ˈɪn.dʒər/','[{"w":"injury","p":"n.","n":"傷害"},{"w":"injured","p":"adj.","n":"受傷的"}]','[]'),
('innocent','adj.','無辜的','junior',3,'He is innocent.','他是無辜的。','Adjectives','/ˈɪn.ə.sənt/','[{"w":"innocence","p":"n.","n":"無辜"}]','[]'),
('inquire','v.','詢問','junior',3,'She inquired about the price.','她詢問了價格。','Communication','/ɪnˈkwaɪr/','[{"w":"inquiry","p":"n.","n":"詢問"}]','[]'),
('insist','v.','堅持','junior',3,'She insisted on paying.','她堅持要付錢。','Communication','/ɪnˈsɪst/','[]','["insist on 堅持"]'),
('install','v.','安裝','junior',3,'Install the software.','安裝軟體。','Technology','/ɪnˈstɑːl/','[{"w":"installation","p":"n.","n":"安裝"}]','[]'),
('instance','n.','例子','junior',3,'For instance, tea is popular.','例如，茶很受歡迎。','Basic','/ˈɪn.stəns/','[]','["for instance 例如"]'),
('instinct','n.','本能','junior',3,'Trust your instincts.','相信你的本能。','Basic','/ˈɪn.stɪŋkt/','[]','[]'),
('intelligent','adj.','聰明的','junior',2,'She is very intelligent.','她非常聰明。','Personality','/ɪnˈtel.ɪ.dʒənt/','[{"w":"intelligence","p":"n.","n":"智力"}]','[]'),
('intense','adj.','激烈的','junior',3,'Intense competition.','激烈的競爭。','Adjectives','/ɪnˈtens/','[{"w":"intensity","p":"n.","n":"強度"}]','[]'),
('intention','n.','意圖','junior',3,'What is your intention?','你的意圖是什麼？','Basic','/ɪnˈten.ʃən/','[{"w":"intend","p":"v.","n":"打算"},{"w":"intentional","p":"adj.","n":"故意的"}]','[]'),
('internal','adj.','內部的','junior',3,'An internal problem.','內部問題。','Adjectives','/ɪnˈtɜːr.nəl/','[]','[]'),
('interpret','v.','解讀','junior',3,'How do you interpret this?','你怎麼解讀這個？','Academic','/ɪnˈtɜːr.prɪt/','[{"w":"interpretation","p":"n.","n":"解讀"}]','[]'),
('interrupt','v.','打斷','junior',2,'Do not interrupt me.','不要打斷我。','Communication','/ˌɪn.t̬əˈrʌpt/','[{"w":"interruption","p":"n.","n":"打斷"}]','[]'),
('investigate','v.','調查','junior',3,'The police investigated the crime.','警察調查了犯罪。','Actions','/ɪnˈves.tɪ.ɡeɪt/','[{"w":"investigation","p":"n.","n":"調查"}]','[]'),
('invest','v.','投資','junior',3,'Invest in education.','投資教育。','Money','/ɪnˈvest/','[{"w":"investment","p":"n.","n":"投資"},{"w":"investor","p":"n.","n":"投資者"}]','["invest in 投資"]'),
('invisible','adj.','看不見的','junior',3,'The germs are invisible.','細菌是看不見的。','Adjectives','/ɪnˈvɪz.ə.bəl/','[]','[]'),
('involve','v.','涉及','junior',3,'The project involves teamwork.','這個專案涉及團隊合作。','Actions','/ɪnˈvɑːlv/','[{"w":"involvement","p":"n.","n":"參與"}]','[]'),
('irritate','v.','激怒','junior',3,'His attitude irritated me.','他的態度激怒了我。','Feelings','/ˈɪr.ɪ.teɪt/','[{"w":"irritating","p":"adj.","n":"惱人的"}]','[]'),
('isolate','v.','隔離','junior',3,'Isolate the problem.','找出問題。','Actions','/ˈaɪ.sə.leɪt/','[{"w":"isolation","p":"n.","n":"隔離"}]','[]'),
('issue','n.','議題','junior',3,'A social issue.','社會議題。','Society','/ˈɪʃ.uː/','[]','[]'),
('item','n.','項目','junior',2,'Check each item.','檢查每個項目。','Basic','/ˈaɪ.t̬əm/','[]','[]'),
('labor','n.','勞動','junior',3,'Manual labor.','體力勞動。','Jobs','/ˈleɪ.bər/','[]','["labor force 勞動力"]'),
('lack','v.','缺乏','junior',3,'He lacks confidence.','他缺乏信心。','Basic','/læk/','[]','["lack of 缺乏"]'),
('launch','v.','發射；推出','junior',3,'Launch a new product.','推出新產品。','Business','/lɑːntʃ/','[]','[]'),
('layer','n.','層','junior',3,'A layer of dust.','一層灰塵。','Basic','/ˈleɪ.ər/','[]','[]'),
('lean','v.','傾斜','junior',3,'Lean against the wall.','靠著牆。','Actions','/liːn/','[]','[]'),
('legend','n.','傳說','junior',2,'An ancient legend.','古老的傳說。','History','/ˈledʒ.ənd/','[{"w":"legendary","p":"adj.","n":"傳奇的"}]','[]'),
('leisure','n.','休閒','junior',3,'Enjoy your leisure time.','享受你的休閒時間。','Life','/ˈliː.ʒər/','[]','["leisure time 休閒時間"]'),
('liberty','n.','自由','junior',3,'The Statue of Liberty.','自由女神像。','Society','/ˈlɪb.ər.t̬i/','[]','[]'),
('license','n.','執照','junior',3,'A driving license.','駕照。','Basic','/ˈlaɪ.səns/','[]','[]'),
('likewise','adv.','同樣地','junior',3,'I think likewise.','我也這麼想。','Basic','/ˈlaɪk.waɪz/','[]','[]'),
('link','v.','連結','junior',2,'Link the two ideas.','連結這兩個想法。','Actions','/lɪŋk/','[]','[]'),
('literary','adj.','文學的','junior',3,'A literary work.','文學作品。','Art','/ˈlɪt̬.ər.er.i/','[{"w":"literature","p":"n.","n":"文學"}]','[]'),
('loan','n.','貸款','junior',3,'Apply for a loan.','申請貸款。','Money','/loʊn/','[]','[]'),
('logic','n.','邏輯','junior',3,'That makes no logic.','那沒有邏輯。','Academic','/ˈlɑː.dʒɪk/','[{"w":"logical","p":"adj.","n":"邏輯的"}]','[]'),
('luxury','n.','奢華','junior',3,'A luxury hotel.','奢華飯店。','Life','/ˈlʌk.ʃər.i/','[{"w":"luxurious","p":"adj.","n":"奢華的"}]','[]'),
('magnificent','adj.','壯麗的','junior',3,'A magnificent view.','壯麗的景色。','Adjectives','/mæɡˈnɪf.ɪ.sənt/','[]','[]'),
('maintain','v.','維持','junior',3,'Maintain your health.','維持你的健康。','Actions','/meɪnˈteɪn/','[{"w":"maintenance","p":"n.","n":"維護"}]','[]'),
('major','adj.','主要的','junior',2,'A major problem.','主要的問題。','Adjectives','/ˈmeɪ.dʒər/','[{"w":"majority","p":"n.","n":"多數"}]','[]'),
('manufacture','v.','製造','junior',3,'They manufacture electronics.','他們製造電子產品。','Business','/ˌmæn.jəˈfæk.tʃər/','[{"w":"manufacturer","p":"n.","n":"製造商"}]','[]'),
('massive','adj.','巨大的','junior',3,'A massive earthquake.','巨大的地震。','Adjectives','/ˈmæs.ɪv/','[]','[]'),
('master','v.','精通','junior',2,'Master a new skill.','精通一項新技能。','Actions','/ˈmæs.tər/','[]','[]'),
('material','n.','材料','junior',3,'Raw materials.','原料。','Science','/məˈtɪr.i.əl/','[]','[]'),
('mature','adj.','成熟的','junior',3,'He is very mature.','他很成熟。','Personality','/məˈtʃʊr/','[{"w":"maturity","p":"n.","n":"成熟"}]','[]'),
('maximum','n.','最大值','junior',3,'The maximum speed.','最大速度。','Basic','/ˈmæk.sɪ.məm/','[]','[]'),
('meanwhile','adv.','同時','junior',3,'Meanwhile, she waited.','同時，她等著。','Time','/ˈmiːn.waɪl/','[]','[]'),
('measure','v.','測量','junior',3,'Measure the length.','測量長度。','Actions','/ˈmeʒ.ər/','[{"w":"measurement","p":"n.","n":"測量"}]','[]'),
('media','n.','媒體','junior',2,'Social media.','社群媒體。','Technology','/ˈmiː.di.ə/','[]','[]'),
('mental','adj.','精神的','junior',3,'Mental health.','心理健康。','Health','/ˈmen.t̬əl/','[{"w":"mentally","p":"adv.","n":"精神上"}]','["mental health 心理健康"]'),
('mercy','n.','慈悲','junior',3,'Show mercy.','表現慈悲。','Feelings','/ˈmɜːr.si/','[{"w":"merciful","p":"adj.","n":"仁慈的"}]','[]'),
('method','n.','方法','junior',2,'An effective method.','有效的方法。','Academic','/ˈmeθ.əd/','[]','[]'),
('military','adj.','軍事的','junior',3,'Military service.','兵役。','Society','/ˈmɪl.ə.ter.i/','[]','[]'),
('minimum','n.','最小值','junior',3,'A minimum of three people.','至少三個人。','Basic','/ˈmɪn.ə.məm/','[]','[]'),
('minor','adj.','次要的','junior',3,'A minor problem.','次要的問題。','Adjectives','/ˈmaɪ.nər/','[{"w":"minority","p":"n.","n":"少數"}]','[]'),
('miracle','n.','奇蹟','junior',3,'It was a miracle.','這是個奇蹟。','Basic','/ˈmɪr.ə.kəl/','[]','[]'),
('mission','n.','任務','junior',3,'Complete the mission.','完成任務。','Basic','/ˈmɪʃ.ən/','[]','[]'),
('moderate','adj.','適中的','junior',3,'Moderate exercise.','適度運動。','Adjectives','/ˈmɑː.dər.ət/','[]','[]'),
('modify','v.','修改','junior',3,'Modify the plan.','修改計畫。','Actions','/ˈmɑː.dɪ.faɪ/','[{"w":"modification","p":"n.","n":"修改"}]','[]'),
('monitor','v.','監控','junior',3,'Monitor the situation.','監控情況。','Actions','/ˈmɑː.nɪ.t̬ər/','[]','[]'),
('moral','adj.','道德的','junior',3,'A moral lesson.','道德教訓。','Society','/ˈmɔːr.əl/','[{"w":"morality","p":"n.","n":"道德"}]','[]'),
('motivate','v.','激勵','junior',3,'Teachers motivate students.','老師激勵學生。','Actions','/ˈmoʊ.t̬ɪ.veɪt/','[{"w":"motivation","p":"n.","n":"動機"}]','[]'),
('mutual','adj.','相互的','junior',3,'Mutual respect.','相互尊重。','Adjectives','/ˈmjuː.tʃu.əl/','[]','[]'),
('mystery','n.','謎','junior',2,'Solve the mystery.','解開謎題。','Basic','/ˈmɪs.tər.i/','[{"w":"mysterious","p":"adj.","n":"神秘的"}]','[]'),
('negotiate','v.','談判','junior',3,'Negotiate a deal.','談判一筆交易。','Business','/nɪˈɡoʊ.ʃi.eɪt/','[{"w":"negotiation","p":"n.","n":"談判"}]','[]'),
('neutral','adj.','中立的','junior',3,'Remain neutral.','保持中立。','Adjectives','/ˈnuː.trəl/','[]','[]'),
('nevertheless','adv.','然而','junior',3,'Nevertheless, we tried.','然而，我們還是嘗試了。','Basic','/ˌnev.ər.ðəˈles/','[]','[]'),
('noble','adj.','高尚的','junior',3,'A noble cause.','高尚的目標。','Adjectives','/ˈnoʊ.bəl/','[]','[]'),
('notion','n.','概念','junior',3,'The notion of freedom.','自由的概念。','Academic','/ˈnoʊ.ʃən/','[]','[]'),
('nutrition','n.','營養','junior',3,'Good nutrition is important.','良好的營養很重要。','Health','/nuːˈtrɪʃ.ən/','[{"w":"nutritious","p":"adj.","n":"有營養的"}]','[]'),
('object','v.','反對','junior',3,'I object to this plan.','我反對這個計畫。','Communication','/əbˈdʒekt/','[{"w":"objection","p":"n.","n":"反對"}]','[]'),
('objective','n.','目標','junior',3,'What is our objective?','我們的目標是什麼？','Basic','/əbˈdʒek.tɪv/','[]','[]'),
('obligation','n.','義務','junior',3,'A legal obligation.','法律義務。','Society','/ˌɑːb.lɪˈɡeɪ.ʃən/','[]','[]'),
('observe','v.','觀察','junior',3,'Observe the animals closely.','仔細觀察動物。','Science','/əbˈzɜːrv/','[{"w":"observation","p":"n.","n":"觀察"}]','[]'),
('obstacle','n.','障礙','junior',3,'Overcome obstacles.','克服障礙。','Basic','/ˈɑːb.stə.kəl/','[]','[]'),
('obtain','v.','獲得','junior',3,'Obtain permission.','取得許可。','Actions','/əbˈteɪn/','[]','[]'),
('obvious','adj.','明顯的','junior',3,'The answer is obvious.','答案很明顯。','Adjectives','/ˈɑːb.vi.əs/','[{"w":"obviously","p":"adv.","n":"明顯地"}]','[]'),
('occasion','n.','場合','junior',3,'A special occasion.','特殊場合。','Basic','/əˈkeɪ.ʒən/','[{"w":"occasional","p":"adj.","n":"偶爾的"}]','[]'),
('occupy','v.','佔據','junior',3,'The army occupied the city.','軍隊佔領了城市。','Actions','/ˈɑː.kjə.paɪ/','[{"w":"occupation","p":"n.","n":"職業；佔領"}]','[]'),
('offense','n.','冒犯','junior',3,'No offense intended.','無意冒犯。','Communication','/əˈfens/','[{"w":"offend","p":"v.","n":"冒犯"},{"w":"offensive","p":"adj.","n":"冒犯的"}]','[]'),
('operate','v.','操作','junior',3,'Operate the machine.','操作機器。','Actions','/ˈɑː.pə.reɪt/','[{"w":"operation","p":"n.","n":"操作；手術"},{"w":"operator","p":"n.","n":"操作員"}]','[]'),
('opponent','n.','對手','junior',3,'A strong opponent.','強大的對手。','People','/əˈpoʊ.nənt/','[]','[]'),
('oppose','v.','反對','junior',3,'Many people oppose the plan.','很多人反對這個計畫。','Actions','/əˈpoʊz/','[{"w":"opposite","p":"adj.","n":"相反的"},{"w":"opposition","p":"n.","n":"反對"}]','[]'),
('option','n.','選項','junior',3,'We have several options.','我們有幾個選項。','Basic','/ˈɑːp.ʃən/','[{"w":"optional","p":"adj.","n":"可選的"}]','[]'),
('origin','n.','起源','junior',3,'The origin of the word.','這個字的起源。','Academic','/ˈɔːr.ɪ.dʒɪn/','[{"w":"original","p":"adj.","n":"原始的"},{"w":"originally","p":"adv.","n":"最初"}]','[]'),
('outcome','n.','結果','junior',3,'The outcome was unexpected.','結果出乎意料。','Basic','/ˈaʊt.kʌm/','[]','[]'),
('outline','n.','大綱','junior',3,'Write an outline first.','先寫大綱。','School','/ˈaʊt.laɪn/','[]','[]'),
('output','n.','產出','junior',3,'Increase the output.','增加產出。','Business','/ˈaʊt.pʊt/','[]','[]'),
('overcome','v.','克服','junior',3,'Overcome your fear.','克服恐懼。','Actions','/ˌoʊ.vərˈkʌm/','[]','[]'),
('overlook','v.','忽略','junior',3,'Do not overlook the details.','不要忽略細節。','Actions','/ˌoʊ.vərˈlʊk/','[]','[]'),
('overwhelm','v.','壓倒','junior',3,'She was overwhelmed with joy.','她被喜悅壓倒。','Feelings','/ˌoʊ.vərˈwelm/','[{"w":"overwhelming","p":"adj.","n":"壓倒性的"}]','[]'),
('pace','n.','步調','junior',3,'Walk at a fast pace.','快步走。','Basic','/peɪs/','[]','["at a pace 以…步調"]'),
('panic','n.','恐慌','junior',3,'Do not panic.','不要恐慌。','Feelings','/ˈpæn.ɪk/','[]','[]'),
('passion','n.','熱情','junior',3,'She has a passion for music.','她對音樂充滿熱情。','Feelings','/ˈpæʃ.ən/','[{"w":"passionate","p":"adj.","n":"充滿熱情的"}]','[]'),
('patience','n.','耐心','junior',2,'Have patience.','要有耐心。','Personality','/ˈpeɪ.ʃəns/','[{"w":"patient","p":"adj.","n":"有耐心的"}]','[]'),
('pattern','n.','模式','junior',3,'A behavior pattern.','行為模式。','Basic','/ˈpæt̬.ərn/','[]','[]'),
('penalty','n.','處罰','junior',3,'Pay a penalty.','付罰款。','Society','/ˈpen.əl.t̬i/','[]','[]'),
('perceive','v.','感知','junior',3,'How do you perceive this?','你怎麼看這件事？','Actions','/pərˈsiːv/','[{"w":"perception","p":"n.","n":"感知"}]','[]'),
('permanent','adj.','永久的','junior',3,'A permanent solution.','永久的解決方案。','Adjectives','/ˈpɜːr.mə.nənt/','[]','[]'),
('permit','v.','允許','junior',3,'Smoking is not permitted.','不允許吸菸。','Actions','/pərˈmɪt/','[{"w":"permission","p":"n.","n":"許可"}]','[]'),
('persist','v.','堅持','junior',3,'She persisted in her efforts.','她堅持不懈地努力。','Actions','/pərˈsɪst/','[{"w":"persistent","p":"adj.","n":"持續的"}]','[]'),
('perspective','n.','觀點','junior',3,'From a different perspective.','從不同觀點。','Academic','/pərˈspek.tɪv/','[]','[]'),
('persuade','v.','說服','junior',3,'She persuaded him to stay.','她說服他留下。','Communication','/pərˈsweɪd/','[{"w":"persuasion","p":"n.","n":"說服"},{"w":"persuasive","p":"adj.","n":"有說服力的"}]','[]'),
('phase','n.','階段','junior',3,'The first phase.','第一階段。','Basic','/feɪz/','[]','[]'),
('philosophy','n.','哲學','junior',3,'Study philosophy.','學習哲學。','Academic','/fɪˈlɑː.sə.fi/','[{"w":"philosopher","p":"n.","n":"哲學家"}]','[]')
ON CONFLICT (word, level) DO NOTHING;

-- ═══ END OF BATCH 3 ═══
-- Running totals after batch 3:
--   elementary: ~300 (target met ✅)
--   junior:     ~500 (target: 1200)
--   senior:     ~300 (target: 4500)
-- Use CSV import to reach full 7000 words
