-- Elementary watercolor illustrations, batch 5. Upload assets before metadata.
BEGIN;
INSERT INTO public.word_illustrations (id, level, word, sort_order, sense, alt_zh, example, example_zh, image_url, local_path, style, version) VALUES
('elementary-orange-01-v1', 'elementary', 'orange', 1, '柳橙', '一顆帶有綠葉的柳橙，旁邊放著切開的半顆柳橙。', 'This orange has a green leaf.', '這顆柳橙有一片綠葉。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/orange-01-v1.webp', '/images/vocabulary/elementary/orange-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-carrot-01-v1', 'elementary', 'carrot', 1, '紅蘿蔔', '一根橘色紅蘿蔔，頂端連著綠色葉子。', 'The carrot has green leaves.', '這根紅蘿蔔有綠色的葉子。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/carrot-01-v1.webp', '/images/vocabulary/elementary/carrot-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-tomato-01-v1', 'elementary', 'tomato', 1, '番茄', '一顆成熟的紅番茄，頂端有綠色的蒂。', 'This tomato is red.', '這顆番茄是紅色的。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/tomato-01-v1.webp', '/images/vocabulary/elementary/tomato-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-corn-01-v1', 'elementary', 'corn', 1, '玉米', '一根剝開綠色外葉的玉米，露出一排排金黃色玉米粒。', 'The corn has yellow kernels.', '這根玉米有黃色的玉米粒。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/corn-01-v1.webp', '/images/vocabulary/elementary/corn-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-rice-01-v1', 'elementary', 'rice', 1, '飯；米', '一個淺藍色碗裡盛著白飯。', 'There is rice in the bowl.', '碗裡有白飯。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/rice-01-v1.webp', '/images/vocabulary/elementary/rice-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-juice-01-v1', 'elementary', 'juice', 1, '果汁', '透明玻璃杯裡裝著柳橙汁，旁邊放著半顆柳橙。', 'There is orange juice in the glass.', '玻璃杯裡有柳橙汁。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/juice-01-v1.webp', '/images/vocabulary/elementary/juice-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-potato-01-v1', 'elementary', 'potato', 1, '馬鈴薯', '一大一小兩顆褐色馬鈴薯並排放著。', 'The big potato is next to the small one.', '大馬鈴薯在小馬鈴薯旁邊。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/potato-01-v1.webp', '/images/vocabulary/elementary/potato-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-cookie-01-v1', 'elementary', 'cookie', 1, '餅乾', '一片圓圓的金黃色餅乾，上面有深褐色巧克力塊。', 'This cookie has chocolate chips.', '這片餅乾裡有巧克力豆。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/cookie-01-v1.webp', '/images/vocabulary/elementary/cookie-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-soup-01-v1', 'elementary', 'soup', 1, '湯', '淺藍色碗裡盛著有紅蘿蔔片和豌豆的蔬菜湯，上方冒著熱氣。', 'There are carrots in the soup.', '湯裡有紅蘿蔔。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/soup-01-v1.webp', '/images/vocabulary/elementary/soup-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-sandwich-01-v1', 'elementary', 'sandwich', 1, '三明治', '白色盤子上放著切成兩半的三明治，裡面夾著生菜、番茄和起司。', 'The sandwich has lettuce and cheese.', '這份三明治裡有生菜和起司。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/sandwich-01-v1.webp', '/images/vocabulary/elementary/sandwich-01-v1.webp', 'watercolor-pencil-v1', 1)
ON CONFLICT (id) DO NOTHING;
COMMIT;
