-- Batch 12: upload assets before metadata.
BEGIN;
INSERT INTO public.word_illustrations (id, level, word, sort_order, sense, alt_zh, example, example_zh, image_url, local_path, style, version) VALUES
('elementary-train-01-v1', 'elementary', 'train', 1, '火車', '一列紅色火車有車頭和兩節車廂，行駛在鐵軌上。', 'The red train travels along the tracks.', '這列紅色火車沿著鐵軌行駛。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/train-01-v1.webp', '/images/vocabulary/elementary/train-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-motorcycle-01-v1', 'elementary', 'motorcycle', 1, '機車', '一輛藍色機車停著，有兩個輪子、座墊和把手。', 'The blue motorcycle has two wheels.', '這輛藍色機車有兩個輪子。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/motorcycle-01-v1.webp', '/images/vocabulary/elementary/motorcycle-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-taxi-01-v1', 'elementary', 'taxi', 1, '計程車', '一輛黃色計程車有車頂燈和黑色輪胎。', 'The yellow taxi waits by the road.', '這輛黃色計程車在路邊等候。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/taxi-01-v1.webp', '/images/vocabulary/elementary/taxi-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-bridge-01-v1', 'elementary', 'bridge', 1, '橋', '一座石拱橋橫跨小河，連接兩岸。', 'The stone bridge crosses the river.', '這座石橋跨過河流。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/bridge-01-v1.webp', '/images/vocabulary/elementary/bridge-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-mountain-01-v1', 'elementary', 'mountain', 1, '山', '一座高山有尖尖的山頂，山腳有綠色坡地。', 'The mountain rises high above the hills.', '這座山高高聳立在丘陵之上。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/mountain-01-v1.webp', '/images/vocabulary/elementary/mountain-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-river-01-v1', 'elementary', 'river', 1, '河流', '一條藍色河流彎曲地流過兩側綠色河岸。', 'The river flows between the green banks.', '這條河流經兩側綠色河岸之間。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/river-01-v1.webp', '/images/vocabulary/elementary/river-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-beach-01-v1', 'elementary', 'beach', 1, '海灘', '金黃色沙灘旁有藍色海水和輕柔的白色浪花。', 'Small waves wash onto the sandy beach.', '小浪花沖上沙灘。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/beach-01-v1.webp', '/images/vocabulary/elementary/beach-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-island-01-v1', 'elementary', 'island', 1, '島', '一座小島四周被藍色海水包圍，島上有綠地和樹木。', 'Water surrounds the small island.', '水環繞著這座小島。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/island-01-v1.webp', '/images/vocabulary/elementary/island-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-lake-01-v1', 'elementary', 'lake', 1, '湖', '一片平靜的湖水四周被草地和低矮山丘環繞。', 'The calm lake reflects the nearby trees.', '平靜的湖水映照著附近的樹木。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/lake-01-v1.webp', '/images/vocabulary/elementary/lake-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-sea-01-v1', 'elementary', 'sea', 1, '海', '寬廣的藍色海面有層層波浪，遠處連著天空。', 'Blue waves roll across the sea.', '藍色波浪在海面上翻滾。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/sea-01-v1.webp', '/images/vocabulary/elementary/sea-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-forest-01-v1', 'elementary', 'forest', 1, '森林', '許多高矮不同的樹木緊密生長，形成一片森林。', 'Many tall trees grow in the forest.', '許多高大的樹木生長在森林裡。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/forest-01-v1.webp', '/images/vocabulary/elementary/forest-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-star-01-v1', 'elementary', 'star', 1, '星星', '夜空中有一顆明亮的星星，周圍有幾顆微小星點。', 'A bright star shines in the night sky.', '一顆明亮的星星在夜空中閃耀。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/star-01-v1.webp', '/images/vocabulary/elementary/star-01-v1.webp', 'watercolor-pencil-v1', 1)
ON CONFLICT (id) DO UPDATE SET level = EXCLUDED.level, word = EXCLUDED.word, sort_order = EXCLUDED.sort_order, sense = EXCLUDED.sense, alt_zh = EXCLUDED.alt_zh, example = EXCLUDED.example, example_zh = EXCLUDED.example_zh, image_url = EXCLUDED.image_url, local_path = EXCLUDED.local_path, style = EXCLUDED.style, version = EXCLUDED.version;
COMMIT;
