-- ═══════════════════════════════════════════════════════════════
-- EnglishGo — Seed Vocabulary Batch 2 (追加 600 字)
-- 第二批種子資料：小學 +200 / 國中 +200 / 高中 +200
-- 執行前請先確認 batch 1 (seed_vocabulary.sql) 已執行
-- ═══════════════════════════════════════════════════════════════

-- ═══ ELEMENTARY Batch 2 — 200 words (Level 1) ════════════════
INSERT INTO public.word_bank (word, pos, meaning, level, ceec_level, example, example_zh, category, phonetic, forms, collocations) VALUES
('age','n.','年齡','elementary',1,'What is your age?','你幾歲？','People','/eɪdʒ/','[]','[]'),
('ago','adv.','以前','elementary',1,'I came here two years ago.','我兩年前來這裡。','Time','/əˈɡoʊ/','[]','[]'),
('air','n.','空氣','elementary',1,'The air is fresh today.','今天空氣很新鮮。','Nature','/er/','[]','["fresh air 新鮮空氣"]'),
('airplane','n.','飛機','elementary',1,'I want to fly an airplane.','我想開飛機。','Transport','/ˈer.pleɪn/','[]','[]'),
('also','adv.','也','elementary',1,'I also like ice cream.','我也喜歡冰淇淋。','Basic','','[]','[]'),
('always','adv.','總是','elementary',1,'She always smiles.','她總是微笑。','Basic','/ˈɔːl.weɪz/','[]','[]'),
('angry','adj.','生氣的','elementary',1,'Mom is angry at me.','媽媽對我生氣。','Feelings','/ˈæŋ.ɡri/','[{"w":"anger","p":"n.","n":"憤怒"}]','[]'),
('answer','n.','答案','elementary',1,'I know the answer.','我知道答案。','School','/ˈæn.sər/','[]','[]'),
('any','adj.','任何','elementary',1,'Do you have any questions?','你有任何問題嗎？','Basic','','[]','[]'),
('arm','n.','手臂','elementary',1,'She hurt her arm.','她的手臂受傷了。','Body','/ɑːrm/','[]','[]'),
('around','prep.','周圍','elementary',1,'Look around you.','看看你周圍。','Basic','/əˈraʊnd/','[]','[]'),
('ask','v.','問','elementary',1,'Can I ask you a question?','我可以問你一個問題嗎？','Actions','/æsk/','[]','["ask for 要求"]'),
('aunt','n.','阿姨','elementary',1,'My aunt lives in Taipei.','我阿姨住在台北。','Family','/ænt/','[]','[]'),
('autumn','n.','秋天','elementary',1,'I like autumn best.','我最喜歡秋天。','Weather','/ˈɔː.təm/','[]','[]'),
('baby','n.','嬰兒','elementary',1,'The baby is sleeping.','嬰兒在睡覺。','People','/ˈbeɪ.bi/','[]','[]'),
('back','n.','背部；回來','elementary',1,'Come back soon.','快回來。','Basic','/bæk/','[]','["come back 回來"]'),
('bag','n.','袋子','elementary',1,'Put it in the bag.','把它放進袋子裡。','Objects','/bæɡ/','[]','[]'),
('banana','n.','香蕉','elementary',1,'I eat a banana every morning.','我每天早上吃香蕉。','Food','/bəˈnæn.ə/','[]','[]'),
('bank','n.','銀行','elementary',1,'The bank is near my house.','銀行在我家附近。','Places','/bæŋk/','[]','[]'),
('baseball','n.','棒球','elementary',1,'I play baseball on weekends.','我週末打棒球。','Sports','/ˈbeɪs.bɑːl/','[]','[]'),
('basket','n.','籃子','elementary',1,'Put the fruit in the basket.','把水果放在籃子裡。','Objects','/ˈbæs.kɪt/','[]','[]'),
('bathroom','n.','浴室','elementary',1,'The bathroom is upstairs.','浴室在樓上。','Home','/ˈbæθ.ruːm/','[]','[]'),
('beach','n.','海灘','elementary',1,'We went to the beach.','我們去了海灘。','Places','/biːtʃ/','[]','[]'),
('bear','n.','熊','elementary',1,'Bears live in the forest.','熊住在森林裡。','Animals','/ber/','[]','[]'),
('become','v.','成為','elementary',1,'I want to become a doctor.','我想成為醫生。','Actions','/bɪˈkʌm/','[{"w":"became","p":"v.","n":"過去式"}]','[]'),
('begin','v.','開始','elementary',1,'Class begins at eight.','八點開始上課。','Actions','/bɪˈɡɪn/','[{"w":"began","p":"v.","n":"過去式"},{"w":"begun","p":"v.","n":"過去分詞"}]','[]'),
('behind','prep.','在…後面','elementary',1,'The cat is behind the door.','貓在門後面。','Basic','/bɪˈhaɪnd/','[]','[]'),
('below','prep.','在…下面','elementary',1,'The temperature is below zero.','溫度在零度以下。','Basic','/bɪˈloʊ/','[]','[]'),
('beside','prep.','在…旁邊','elementary',1,'Sit beside me.','坐在我旁邊。','Basic','/bɪˈsaɪd/','[]','[]'),
('between','prep.','在…之間','elementary',1,'I sit between Tom and Mary.','我坐在Tom和Mary之間。','Basic','/bɪˈtwiːn/','[]','[]'),
('bicycle','n.','腳踏車','elementary',1,'I ride a bicycle to school.','我騎腳踏車上學。','Transport','/ˈbaɪ.sɪ.kəl/','[]','["ride a bicycle 騎腳踏車"]'),
('boat','n.','船','elementary',1,'We took a boat to the island.','我們搭船去小島。','Transport','/boʊt/','[]','[]'),
('born','adj.','出生的','elementary',1,'I was born in Taipei.','我在台北出生。','People','/bɔːrn/','[]','["be born 出生"]'),
('both','adj.','兩者都','elementary',1,'Both of us like music.','我們兩個都喜歡音樂。','Basic','/boʊθ/','[]','[]'),
('bottom','n.','底部','elementary',1,'Look at the bottom of the page.','看頁面底部。','Basic','/ˈbɑː.t̬əm/','[]','[]'),
('bowl','n.','碗','elementary',1,'A bowl of rice, please.','請給我一碗飯。','Home','/boʊl/','[]','[]'),
('box','n.','箱子','elementary',1,'Open the box.','打開箱子。','Objects','/bɑːks/','[{"w":"boxes","p":"n.","n":"複數"}]','[]'),
('bread','n.','麵包','elementary',1,'I eat bread for breakfast.','我早餐吃麵包。','Food','/bred/','[]','[]'),
('break','v.','打破','elementary',1,'Be careful not to break it.','小心不要打破它。','Actions','/breɪk/','[{"w":"broke","p":"v.","n":"過去式"},{"w":"broken","p":"v.","n":"過去分詞"}]','[]'),
('breakfast','n.','早餐','elementary',1,'I eat breakfast at seven.','我七點吃早餐。','Food','/ˈbrek.fəst/','[]','["have breakfast 吃早餐"]'),
('bridge','n.','橋','elementary',1,'We walked across the bridge.','我們走過橋。','Places','/brɪdʒ/','[]','[]'),
('bright','adj.','明亮的','elementary',1,'The sun is very bright.','太陽很明亮。','Adjectives','/braɪt/','[]','[]'),
('bring','v.','帶來','elementary',1,'Please bring your book.','請帶你的書。','Actions','/brɪŋ/','[{"w":"brought","p":"v.","n":"過去式"}]','[]'),
('brown','adj.','棕色的','elementary',1,'She has brown eyes.','她有棕色的眼睛。','Colors','/braʊn/','[]','[]'),
('brush','v.','刷','elementary',1,'Brush your teeth.','刷牙。','Actions','/brʌʃ/','[]','["brush teeth 刷牙"]'),
('build','v.','建造','elementary',1,'They build a new house.','他們建了新房子。','Actions','/bɪld/','[{"w":"built","p":"v.","n":"過去式"}]','[]'),
('bus','n.','公車','elementary',1,'I take the bus to school.','我搭公車上學。','Transport','/bʌs/','[]','["by bus 搭公車"]'),
('busy','adj.','忙碌的','elementary',1,'Mom is very busy today.','媽媽今天很忙。','Adjectives','/ˈbɪz.i/','[]','[]'),
('butter','n.','奶油','elementary',1,'Put butter on the bread.','在麵包上塗奶油。','Food','/ˈbʌt̬.ər/','[]','[]'),
('candy','n.','糖果','elementary',1,'Children love candy.','小孩喜歡糖果。','Food','/ˈkæn.di/','[]','[]'),
('car','n.','車','elementary',1,'Dad drives a car.','爸爸開車。','Transport','/kɑːr/','[]','["by car 開車"]'),
('card','n.','卡片','elementary',1,'She sent me a birthday card.','她寄給我一張生日卡片。','Objects','/kɑːrd/','[]','[]'),
('careful','adj.','小心的','elementary',1,'Be careful when you cross the street.','過馬路時要小心。','Adjectives','/ˈker.fəl/','[{"w":"carefully","p":"adv.","n":"小心地"}]','[]'),
('carry','v.','攜帶','elementary',1,'Please carry this bag for me.','請幫我提這個袋子。','Actions','/ˈker.i/','[]','[]'),
('catch','v.','接住；抓','elementary',1,'Catch the ball!','接住球！','Actions','/kætʃ/','[{"w":"caught","p":"v.","n":"過去式"}]','["catch a cold 感冒"]'),
('celebrate','v.','慶祝','elementary',1,'We celebrate birthdays.','我們慶祝生日。','Actions','/ˈsel.ə.breɪt/','[]','[]'),
('center','n.','中心','elementary',1,'The park is in the center of the city.','公園在城市中心。','Places','/ˈsen.t̬ər/','[]','[]'),
('chance','n.','機會','elementary',1,'Give me a chance.','給我一個機會。','Basic','/tʃæns/','[]','[]'),
('change','v.','改變','elementary',1,'Things will change.','事情會改變。','Actions','/tʃeɪndʒ/','[]','[]'),
('cheap','adj.','便宜的','elementary',1,'This shirt is cheap.','這件衣服很便宜。','Adjectives','/tʃiːp/','[]','[]'),
('cheese','n.','起司','elementary',1,'I like cheese on my pizza.','我喜歡披薩上的起司。','Food','/tʃiːz/','[]','[]'),
('choose','v.','選擇','elementary',1,'Choose your favorite color.','選你最喜歡的顏色。','Actions','/tʃuːz/','[{"w":"chose","p":"v.","n":"過去式"}]','[]'),
('Christmas','n.','聖誕節','elementary',1,'Merry Christmas!','聖誕快樂！','Time','/ˈkrɪs.məs/','[]','[]'),
('church','n.','教堂','elementary',1,'The church is very old.','那座教堂很古老。','Places','/tʃɜːrtʃ/','[]','[]'),
('circle','n.','圓圈','elementary',1,'Draw a circle.','畫一個圓圈。','School','/ˈsɜːr.kəl/','[]','[]'),
('climb','v.','爬','elementary',1,'We climbed the mountain.','我們爬了那座山。','Actions','/klaɪm/','[]','["climb a mountain 爬山"]'),
('clock','n.','時鐘','elementary',1,'Look at the clock.','看時鐘。','Objects','/klɑːk/','[]','[]'),
('clothes','n.','衣服','elementary',1,'I need new clothes.','我需要新衣服。','Objects','/kloʊðz/','[]','[]'),
('cloud','n.','雲','elementary',1,'There are many clouds today.','今天很多雲。','Nature','/klaʊd/','[{"w":"cloudy","p":"adj.","n":"多雲的"}]','[]'),
('coat','n.','外套','elementary',1,'Wear your coat, it is cold.','穿上外套，很冷。','Objects','/koʊt/','[]','[]'),
('coffee','n.','咖啡','elementary',1,'Mom drinks coffee every morning.','媽媽每天早上喝咖啡。','Food','/ˈkɑː.fi/','[]','[]'),
('collect','v.','收集','elementary',1,'I collect stamps.','我收集郵票。','Actions','/kəˈlekt/','[{"w":"collection","p":"n.","n":"收藏"}]','[]'),
('comfortable','adj.','舒適的','elementary',1,'This chair is comfortable.','這張椅子很舒適。','Adjectives','/ˈkʌm.fər.tə.bəl/','[]','[]'),
('common','adj.','常見的','elementary',1,'Cats are common pets.','貓是常見的寵物。','Adjectives','/ˈkɑː.mən/','[]','[]'),
('computer','n.','電腦','elementary',1,'I use the computer every day.','我每天用電腦。','Objects','/kəmˈpjuː.t̬ər/','[]','[]'),
('copy','v.','複製','elementary',1,'Copy this sentence.','抄寫這個句子。','Actions','/ˈkɑː.pi/','[]','[]'),
('corner','n.','角落','elementary',1,'The shop is on the corner.','商店在轉角。','Places','/ˈkɔːr.nər/','[]','[]'),
('correct','adj.','正確的','elementary',1,'Your answer is correct.','你的答案是正確的。','Adjectives','/kəˈrekt/','[]','[]'),
('cost','v.','花費','elementary',1,'How much does it cost?','這要多少錢？','Money','/kɑːst/','[]','[]'),
('count','v.','數','elementary',1,'Count from one to ten.','從一數到十。','Actions','/kaʊnt/','[]','[]'),
('course','n.','課程','elementary',1,'I take an English course.','我上英文課。','School','/kɔːrs/','[]','["of course 當然"]'),
('cousin','n.','表/堂兄弟姊妹','elementary',1,'My cousin is twelve.','我表哥十二歲。','Family','/ˈkʌz.ən/','[]','[]'),
('cover','v.','覆蓋','elementary',1,'Cover the pot with a lid.','用蓋子蓋住鍋子。','Actions','/ˈkʌv.ər/','[]','[]'),
('cow','n.','牛','elementary',1,'The cow gives us milk.','牛給我們牛奶。','Animals','/kaʊ/','[]','[]'),
('cross','v.','穿越','elementary',1,'Cross the street carefully.','小心過馬路。','Actions','/krɑːs/','[]','["cross the street 過馬路"]'),
('cry','v.','哭','elementary',1,'The baby is crying.','嬰兒在哭。','Feelings','/kraɪ/','[]','[]'),
('cut','v.','切','elementary',1,'Cut the paper in half.','把紙切成兩半。','Actions','/kʌt/','[]','[]'),
('dangerous','adj.','危險的','elementary',1,'Swimming alone is dangerous.','一個人游泳很危險。','Adjectives','/ˈdeɪn.dʒər.əs/','[{"w":"danger","p":"n.","n":"危險"}]','[]'),
('dark','adj.','暗的','elementary',1,'It is dark at night.','晚上很暗。','Adjectives','/dɑːrk/','[]','[]'),
('date','n.','日期','elementary',1,'What is the date today?','今天幾號？','Time','/deɪt/','[]','[]'),
('daughter','n.','女兒','elementary',1,'She is my daughter.','她是我的女兒。','Family','/ˈdɑː.t̬ər/','[]','[]'),
('dead','adj.','死的','elementary',1,'The flower is dead.','花枯死了。','Adjectives','/ded/','[{"w":"death","p":"n.","n":"死亡"}]','[]'),
('decide','v.','決定','elementary',1,'I decided to go.','我決定去。','Actions','/dɪˈsaɪd/','[]','[]'),
('deep','adj.','深的','elementary',1,'The ocean is very deep.','海洋非常深。','Adjectives','/diːp/','[]','[]'),
('delicious','adj.','好吃的','elementary',1,'This cake is delicious.','這蛋糕很好吃。','Adjectives','/dɪˈlɪʃ.əs/','[]','[]'),
('desk','n.','書桌','elementary',1,'My books are on the desk.','我的書在書桌上。','School','/desk/','[]','[]'),
('die','v.','死','elementary',1,'The plant died.','植物死了。','Actions','/daɪ/','[]','[]'),
('different','adj.','不同的','elementary',1,'We are different.','我們是不同的。','Adjectives','/ˈdɪf.ər.ənt/','[]','[]'),
('difficult','adj.','困難的','elementary',1,'This test is difficult.','這考試很難。','Adjectives','/ˈdɪf.ɪ.kəlt/','[]','[]'),
('dinner','n.','晚餐','elementary',1,'We eat dinner at six.','我們六點吃晚餐。','Food','/ˈdɪn.ər/','[]','["have dinner 吃晚餐"]'),
('dirty','adj.','髒的','elementary',1,'Your hands are dirty.','你的手好髒。','Adjectives','/ˈdɜːr.t̬i/','[]','[]'),
('dish','n.','盤子；菜','elementary',1,'Wash the dishes.','洗盤子。','Home','/dɪʃ/','[]','[]'),
('dollar','n.','美元','elementary',1,'It costs ten dollars.','這要十塊美元。','Money','/ˈdɑː.lər/','[]','[]'),
('down','adv.','往下','elementary',1,'Sit down, please.','請坐下。','Basic','/daʊn/','[]','["sit down 坐下"]'),
('dream','n.','夢','elementary',1,'I had a nice dream.','我做了一個好夢。','Feelings','/driːm/','[]','[]'),
('dress','n.','洋裝','elementary',1,'She wears a red dress.','她穿紅色洋裝。','Objects','/dres/','[]','[]'),
('drive','v.','開車','elementary',1,'Dad drives to work.','爸爸開車上班。','Actions','/draɪv/','[{"w":"drove","p":"v.","n":"過去式"}]','[]'),
('drop','v.','掉落','elementary',1,'I dropped my phone.','我的手機掉了。','Actions','/drɑːp/','[]','[]'),
('dry','adj.','乾的','elementary',1,'The clothes are dry.','衣服乾了。','Adjectives','/draɪ/','[]','[]'),
('during','prep.','在…期間','elementary',1,'I sleep during class.','我上課時睡覺。','Time','/ˈdʊr.ɪŋ/','[]','[]'),
('each','adj.','每個','elementary',1,'Each student has a book.','每個學生都有書。','Basic','/iːtʃ/','[]','["each other 彼此"]'),
('ear','n.','耳朵','elementary',1,'He has big ears.','他有大耳朵。','Body','/ɪr/','[]','[]'),
('early','adj.','早的','elementary',1,'I get up early.','我早起。','Time','/ˈɜːr.li/','[]','[]'),
('earth','n.','地球','elementary',1,'The earth is round.','地球是圓的。','Nature','/ɜːrθ/','[]','[]'),
('easy','adj.','容易的','elementary',1,'This question is easy.','這題很簡單。','Adjectives','/ˈiː.zi/','[{"w":"easily","p":"adv.","n":"容易地"}]','[]'),
('else','adv.','其他','elementary',1,'What else do you need?','你還需要什麼？','Basic','/els/','[]','[]'),
('end','n.','結束','elementary',1,'This is the end of the story.','這是故事的結尾。','Basic','/end/','[]','["in the end 最後"]'),
('enough','adj.','足夠的','elementary',1,'Do you have enough money?','你有足夠的錢嗎？','Basic','/ɪˈnʌf/','[]','[]'),
('enter','v.','進入','elementary',1,'Please enter the room.','請進入房間。','Actions','/ˈen.t̬ər/','[]','[]'),
('even','adv.','甚至','elementary',1,'I even forgot my name.','我甚至忘了名字。','Basic','/ˈiː.vən/','[]','[]'),
('evening','n.','傍晚','elementary',1,'Good evening!','晚安！','Time','/ˈiːv.nɪŋ/','[]','["good evening 晚安"]'),
('every','adj.','每個','elementary',1,'I study every day.','我每天讀書。','Basic','/ˈev.ri/','[]','["every day 每天"]'),
('everyone','pron.','每個人','elementary',1,'Everyone is here.','每個人都在。','People','/ˈev.ri.wʌn/','[]','[]'),
('everything','pron.','每件事','elementary',1,'Everything is OK.','一切都好。','Basic','/ˈev.ri.θɪŋ/','[]','[]'),
('example','n.','例子','elementary',1,'Give me an example.','給我一個例子。','Basic','/ɪɡˈzæm.pəl/','[]','["for example 例如"]'),
('excited','adj.','興奮的','elementary',1,'I am so excited!','我好興奮！','Feelings','/ɪkˈsaɪ.t̬ɪd/','[{"w":"exciting","p":"adj.","n":"令人興奮的"},{"w":"excitement","p":"n.","n":"興奮"}]','[]'),
('excuse','v.','原諒','elementary',1,'Excuse me, where is the bank?','不好意思，銀行在哪？','Basic','/ɪkˈskjuːz/','[]','["excuse me 不好意思"]'),
('exercise','n.','運動','elementary',1,'Exercise is good for health.','運動對健康有好處。','Sports','/ˈek.sər.saɪz/','[]','[]'),
('expensive','adj.','昂貴的','elementary',1,'This watch is expensive.','這隻手錶很貴。','Adjectives','/ɪkˈspen.sɪv/','[]','[]'),
('explain','v.','解釋','elementary',1,'Please explain it to me.','請跟我解釋。','Actions','/ɪkˈspleɪn/','[]','[]'),
('fact','n.','事實','elementary',1,'That is a fact.','那是事實。','Basic','/fækt/','[]','["in fact 事實上"]'),
('fail','v.','失敗','elementary',1,'I failed the test.','我考試不及格。','School','/feɪl/','[]','[]'),
('fair','adj.','公平的','elementary',1,'That is not fair.','那不公平。','Adjectives','/fer/','[]','[]'),
('fall','v.','落下','elementary',1,'Leaves fall in autumn.','葉子在秋天落下。','Actions','/fɔːl/','[{"w":"fell","p":"v.","n":"過去式"}]','["fall down 跌倒"]'),
('famous','adj.','有名的','elementary',1,'He is a famous singer.','他是有名的歌手。','Adjectives','/ˈfeɪ.məs/','[]','[]'),
('fan','n.','風扇；粉絲','elementary',1,'Turn on the fan.','打開風扇。','Objects','/fæn/','[]','[]'),
('far','adj.','遠的','elementary',1,'How far is the school?','學校多遠？','Adjectives','/fɑːr/','[{"w":"farther","p":"adj.","n":"更遠"}]','[]'),
('farm','n.','農場','elementary',1,'My uncle has a farm.','我叔叔有一個農場。','Places','/fɑːrm/','[{"w":"farmer","p":"n.","n":"農夫"}]','[]'),
('fat','adj.','胖的','elementary',1,'The cat is very fat.','那隻貓很胖。','Adjectives','/fæt/','[]','[]'),
('favorite','adj.','最喜歡的','elementary',1,'What is your favorite food?','你最喜歡的食物是什麼？','Basic','/ˈfeɪ.vər.ɪt/','[]','[]'),
('feel','v.','感覺','elementary',1,'I feel happy today.','我今天感覺很開心。','Feelings','/fiːl/','[{"w":"felt","p":"v.","n":"過去式"},{"w":"feeling","p":"n.","n":"感覺"}]','[]'),
('few','adj.','很少','elementary',1,'I have a few friends.','我有幾個朋友。','Basic','/fjuː/','[]','["a few 一些"]'),
('fight','v.','打架','elementary',1,'Do not fight with others.','不要和別人打架。','Actions','/faɪt/','[{"w":"fought","p":"v.","n":"過去式"}]','[]'),
('fill','v.','填滿','elementary',1,'Fill the cup with water.','把杯子裝滿水。','Actions','/fɪl/','[]','["fill in 填寫"]'),
('final','adj.','最後的','elementary',1,'This is the final chance.','這是最後一次機會。','Adjectives','/ˈfaɪ.nəl/','[{"w":"finally","p":"adv.","n":"最後"}]','[]'),
('fine','adj.','好的','elementary',1,'I am fine, thank you.','我很好，謝謝。','Feelings','/faɪn/','[]','[]'),
('finger','n.','手指','elementary',1,'I have ten fingers.','我有十根手指。','Body','/ˈfɪŋ.ɡər/','[]','[]'),
('finish','v.','完成','elementary',1,'I finished my homework.','我完成了功課。','Actions','/ˈfɪn.ɪʃ/','[]','[]'),
('fire','n.','火','elementary',1,'Be careful with fire.','小心火。','Nature','/faɪr/','[]','[]'),
('first','adj.','第一的','elementary',1,'She was the first to arrive.','她第一個到。','Basic','/fɜːrst/','[]','["first of all 首先"]'),
('fix','v.','修理','elementary',1,'Dad can fix the car.','爸爸會修車。','Actions','/fɪks/','[]','[]'),
('floor','n.','地板；樓層','elementary',1,'We live on the third floor.','我們住在三樓。','Home','/flɔːr/','[]','[]'),
('fly','v.','飛','elementary',1,'Birds can fly.','鳥會飛。','Actions','/flaɪ/','[{"w":"flew","p":"v.","n":"過去式"}]','[]'),
('follow','v.','跟隨','elementary',1,'Follow me, please.','請跟我來。','Actions','/ˈfɑː.loʊ/','[]','[]'),
('foot','n.','腳','elementary',1,'My foot hurts.','我的腳痛。','Body','/fʊt/','[{"w":"feet","p":"n.","n":"複數"}]','["on foot 步行"]'),
('foreign','adj.','外國的','elementary',1,'I want to learn a foreign language.','我想學外語。','Basic','/ˈfɔːr.ən/','[]','[]'),
('forget','v.','忘記','elementary',1,'Do not forget your homework.','不要忘記功課。','Actions','/fərˈɡet/','[{"w":"forgot","p":"v.","n":"過去式"}]','[]'),
('free','adj.','免費的；自由的','elementary',1,'This book is free.','這本書免費。','Adjectives','/friː/','[{"w":"freedom","p":"n.","n":"自由"}]','[]'),
('fresh','adj.','新鮮的','elementary',1,'The vegetables are fresh.','蔬菜很新鮮。','Adjectives','/freʃ/','[]','[]'),
('frog','n.','青蛙','elementary',1,'A frog lives near the pond.','一隻青蛙住在池塘邊。','Animals','/frɑːɡ/','[]','[]'),
('front','n.','前面','elementary',1,'Sit in front of the TV.','坐在電視前面。','Basic','/frʌnt/','[]','["in front of 在前面"]'),
('full','adj.','滿的','elementary',1,'The bus is full.','公車客滿了。','Adjectives','/fʊl/','[]','[]'),
('future','n.','未來','elementary',1,'I hope for a bright future.','我希望有光明的未來。','Time','/ˈfjuː.tʃər/','[]','["in the future 未來"]'),
('garden','n.','花園','elementary',1,'We have a beautiful garden.','我們有一個美麗的花園。','Places','/ˈɡɑːr.dən/','[]','[]'),
('gas','n.','瓦斯；汽油','elementary',1,'Turn off the gas.','關掉瓦斯。','Home','/ɡæs/','[]','[]'),
('gate','n.','大門','elementary',1,'Wait at the gate.','在大門等。','Home','/ɡeɪt/','[]','[]'),
('get','v.','得到','elementary',1,'I got a present.','我收到禮物。','Actions','/ɡet/','[{"w":"got","p":"v.","n":"過去式"}]','["get up 起床"]'),
('gift','n.','禮物','elementary',1,'Thank you for the gift.','謝謝你的禮物。','Objects','/ɡɪft/','[]','[]'),
('glad','adj.','高興的','elementary',1,'I am glad to see you.','我很高興見到你。','Feelings','/ɡlæd/','[]','[]'),
('glass','n.','玻璃杯','elementary',1,'A glass of water, please.','請給我一杯水。','Home','/ɡlæs/','[]','["a glass of 一杯"]'),
('glove','n.','手套','elementary',1,'Wear your gloves.','戴上手套。','Objects','/ɡlʌv/','[]','[]'),
('gold','n.','黃金','elementary',1,'Gold is expensive.','黃金很貴。','Objects','/ɡoʊld/','[{"w":"golden","p":"adj.","n":"金色的"}]','[]'),
('grade','n.','年級；成績','elementary',1,'I am in the third grade.','我讀三年級。','School','/ɡreɪd/','[]','[]'),
('grandfather','n.','爺爺','elementary',1,'My grandfather is 80.','我爺爺80歲。','Family','/ˈɡrænd.fɑː.ðər/','[]','[]'),
('grandmother','n.','奶奶','elementary',1,'My grandmother cooks well.','我奶奶很會煮飯。','Family','/ˈɡrænd.mʌð.ər/','[]','[]'),
('grass','n.','草','elementary',1,'The grass is green.','草是綠色的。','Nature','/ɡræs/','[]','[]'),
('gray','adj.','灰色的','elementary',1,'The sky is gray today.','今天天空是灰色的。','Colors','/ɡreɪ/','[]','[]'),
('great','adj.','很棒的','elementary',1,'That is a great idea!','那是個好主意！','Adjectives','/ɡreɪt/','[]','[]'),
('grow','v.','成長','elementary',1,'Plants grow in spring.','植物在春天生長。','Nature','/ɡroʊ/','[{"w":"grew","p":"v.","n":"過去式"},{"w":"grown","p":"v.","n":"過去分詞"}]','["grow up 長大"]'),
('guess','v.','猜','elementary',1,'Can you guess the answer?','你能猜出答案嗎？','Actions','/ɡes/','[]','[]'),
('half','n.','一半','elementary',1,'Cut it in half.','切成一半。','Basic','/hæf/','[]','[]'),
('happen','v.','發生','elementary',1,'What happened?','發生什麼事了？','Actions','/ˈhæp.ən/','[]','[]'),
('hard','adj.','困難的；硬的','elementary',1,'This question is hard.','這題很難。','Adjectives','/hɑːrd/','[]','["work hard 努力工作"]'),
('hat','n.','帽子','elementary',1,'She wears a red hat.','她戴紅色帽子。','Objects','/hæt/','[]','[]'),
('hate','v.','恨','elementary',1,'I hate waking up early.','我討厭早起。','Feelings','/heɪt/','[]','[]'),
('hear','v.','聽見','elementary',1,'I can hear music.','我聽到音樂。','Actions','/hɪr/','[{"w":"heard","p":"v.","n":"過去式"}]','[]'),
('heart','n.','心','elementary',1,'I love you with all my heart.','我全心愛你。','Body','/hɑːrt/','[]','[]'),
('heavy','adj.','重的','elementary',1,'This box is very heavy.','這箱子很重。','Adjectives','/ˈhev.i/','[]','[]'),
('high','adj.','高的','elementary',1,'The mountain is very high.','那座山很高。','Adjectives','/haɪ/','[]','[]'),
('hill','n.','小山','elementary',1,'We walked up the hill.','我們走上小山。','Nature','/hɪl/','[]','[]'),
('history','n.','歷史','elementary',1,'I like history class.','我喜歡歷史課。','School','/ˈhɪs.tər.i/','[]','[]'),
('hit','v.','打','elementary',1,'He hit the ball.','他打了球。','Actions','/hɪt/','[]','[]'),
('hobby','n.','嗜好','elementary',1,'My hobby is reading.','我的嗜好是閱讀。','Life','/ˈhɑː.bi/','[]','[]'),
('hold','v.','握住','elementary',1,'Hold my hand.','牽我的手。','Actions','/hoʊld/','[{"w":"held","p":"v.","n":"過去式"}]','[]'),
('hole','n.','洞','elementary',1,'There is a hole in my sock.','我襪子有一個洞。','Objects','/hoʊl/','[]','[]'),
('holiday','n.','假日','elementary',1,'We go on holiday next week.','我們下週放假。','Time','/ˈhɑː.lɪ.deɪ/','[]','[]'),
('homework','n.','功課','elementary',1,'I have a lot of homework.','我有很多功課。','School','/ˈhoʊm.wɜːrk/','[]','["do homework 做功課"]'),
('hope','v.','希望','elementary',1,'I hope you feel better.','我希望你好起來。','Feelings','/hoʊp/','[]','[]'),
('horse','n.','馬','elementary',1,'She can ride a horse.','她會騎馬。','Animals','/hɔːrs/','[]','[]'),
('hospital','n.','醫院','elementary',1,'He is in the hospital.','他在醫院。','Places','/ˈhɑː.spɪ.t̬əl/','[]','[]'),
('hour','n.','小時','elementary',1,'I study for two hours.','我讀了兩小時。','Time','/aʊr/','[]','[]'),
('hundred','n.','百','elementary',1,'There are one hundred students.','有一百個學生。','Numbers','','[]','[]'),
('hurt','v.','傷害','elementary',1,'My leg hurts.','我的腳痛。','Body','/hɜːrt/','[]','[]'),
('husband','n.','丈夫','elementary',1,'Her husband is a teacher.','她丈夫是老師。','Family','/ˈhʌz.bənd/','[]','[]'),
('ice','n.','冰','elementary',1,'I want some ice.','我要一些冰。','Food','/aɪs/','[]','["ice cream 冰淇淋"]'),
('idea','n.','主意','elementary',1,'That is a good idea.','那是個好主意。','Basic','/aɪˈdiː.ə/','[]','[]'),
('important','adj.','重要的','elementary',1,'English is important.','英文很重要。','Adjectives','/ɪmˈpɔːr.t̬ənt/','[{"w":"importance","p":"n.","n":"重要性"}]','[]'),
('inside','prep.','在裡面','elementary',1,'Come inside the house.','進到房子裡面。','Basic','/ɪnˈsaɪd/','[]','[]'),
('instead','adv.','反而','elementary',1,'Let us walk instead.','我們改走路吧。','Basic','/ɪnˈsted/','[]','["instead of 而不是"]'),
('interest','n.','興趣','elementary',1,'I have no interest in sports.','我對運動沒興趣。','Feelings','/ˈɪn.trəst/','[{"w":"interesting","p":"adj.","n":"有趣的"},{"w":"interested","p":"adj.","n":"感興趣的"}]','[]'),
('invite','v.','邀請','elementary',1,'I invite you to my party.','我邀請你來我的派對。','Actions','/ɪnˈvaɪt/','[{"w":"invitation","p":"n.","n":"邀請"}]','[]'),
('island','n.','島','elementary',1,'Taiwan is an island.','台灣是一個島嶼。','Nature','/ˈaɪ.lənd/','[]','[]'),
('job','n.','工作','elementary',1,'What is your job?','你的工作是什麼？','Jobs','/dʒɑːb/','[]','[]'),
('join','v.','加入','elementary',1,'Can I join you?','我可以加入你們嗎？','Actions','/dʒɔɪn/','[]','[]'),
('joy','n.','喜悅','elementary',1,'The children were full of joy.','孩子們充滿喜悅。','Feelings','/dʒɔɪ/','[{"w":"joyful","p":"adj.","n":"喜悅的"}]','[]'),
('jump','v.','跳','elementary',1,'The frog can jump high.','青蛙可以跳很高。','Actions','/dʒʌmp/','[]','[]'),
('just','adv.','剛剛；只是','elementary',1,'I just got home.','我剛到家。','Basic','/dʒʌst/','[]','[]'),
('keep','v.','保持','elementary',1,'Keep your room clean.','保持房間乾淨。','Actions','/kiːp/','[{"w":"kept","p":"v.","n":"過去式"}]','["keep quiet 保持安靜"]'),
('key','n.','鑰匙','elementary',1,'I lost my key.','我的鑰匙不見了。','Objects','/kiː/','[]','[]'),
('kick','v.','踢','elementary',1,'He kicked the ball.','他踢了球。','Actions','/kɪk/','[]','[]'),
('kid','n.','小孩','elementary',1,'The kids are playing.','小孩們在玩。','People','/kɪd/','[]','[]'),
('kill','v.','殺','elementary',1,'Do not kill animals.','不要殺動物。','Actions','/kɪl/','[]','[]'),
('kind','adj.','善良的；種類','elementary',1,'She is very kind.','她很善良。','Personality','/kaɪnd/','[{"w":"kindness","p":"n.","n":"善良"}]','["kind of 有點"]'),
('king','n.','國王','elementary',1,'The king lives in a castle.','國王住在城堡裡。','People','/kɪŋ/','[]','[]'),
('kitchen','n.','廚房','elementary',1,'Mom is in the kitchen.','媽媽在廚房。','Home','/ˈkɪtʃ.ən/','[]','[]'),
('knee','n.','膝蓋','elementary',1,'I hurt my knee.','我的膝蓋受傷了。','Body','/niː/','[]','[]'),
('knife','n.','刀','elementary',1,'Be careful with the knife.','小心刀子。','Home','/naɪf/','[{"w":"knives","p":"n.","n":"複數"}]','[]'),
('knock','v.','敲','elementary',1,'Someone is knocking on the door.','有人在敲門。','Actions','/nɑːk/','[]','["knock on 敲"]')
ON CONFLICT (word, level) DO NOTHING;

-- ═══ JUNIOR Batch 2 — 200 words (Level 2-3) ═════════════════
INSERT INTO public.word_bank (word, pos, meaning, level, ceec_level, example, example_zh, category, phonetic, forms, collocations) VALUES
('abandon','v.','放棄','junior',3,'He abandoned his plan.','他放棄了計畫。','Actions','/əˈbæn.dən/','[]','[]'),
('absorb','v.','吸收','junior',3,'Sponges absorb water.','海綿吸收水。','Science','/əbˈzɔːrb/','[]','[]'),
('accomplish','v.','完成','junior',3,'She accomplished her mission.','她完成了任務。','Actions','/əˈkɑːm.plɪʃ/','[{"w":"accomplishment","p":"n.","n":"成就"}]','[]'),
('accurate','adj.','準確的','junior',3,'The data is accurate.','數據是準確的。','Adjectives','/ˈæk.jər.ət/','[{"w":"accuracy","p":"n.","n":"準確性"}]','[]'),
('accuse','v.','指控','junior',3,'He was accused of lying.','他被指控說謊。','Communication','/əˈkjuːz/','[]','["accuse of 指控"]'),
('adapt','v.','適應','junior',3,'We must adapt to changes.','我們必須適應改變。','Actions','/əˈdæpt/','[{"w":"adaptation","p":"n.","n":"適應"}]','["adapt to 適應"]'),
('admire','v.','欽佩','junior',3,'I admire her courage.','我欽佩她的勇氣。','Feelings','/ədˈmaɪr/','[{"w":"admiration","p":"n.","n":"欽佩"}]','[]'),
('adopt','v.','採用；領養','junior',3,'They adopted a child.','他們領養了一個小孩。','Actions','/əˈdɑːpt/','[{"w":"adoption","p":"n.","n":"領養"}]','[]'),
('advance','v.','進步','junior',3,'Technology advances quickly.','科技進步得很快。','Actions','/ədˈvæns/','[{"w":"advanced","p":"adj.","n":"先進的"}]','[]'),
('adventure','n.','冒險','junior',2,'Life is an adventure.','人生是一場冒險。','Life','/ədˈven.tʃər/','[{"w":"adventurous","p":"adj.","n":"冒險的"}]','[]'),
('advertise','v.','廣告','junior',3,'They advertise on TV.','他們在電視上打廣告。','Business','/ˈæd.vər.taɪz/','[{"w":"advertisement","p":"n.","n":"廣告"}]','[]'),
('alongside','prep.','在旁邊','junior',3,'He works alongside his father.','他和他父親一起工作。','Basic','/əˌlɔːŋˈsaɪd/','[]','[]'),
('alternative','n.','替代方案','junior',3,'There is no alternative.','沒有替代方案。','Basic','/ɑːlˈtɜːr.nə.tɪv/','[]','[]'),
('amaze','v.','驚嘆','junior',2,'The magic show amazed us.','魔術表演令我們驚嘆。','Feelings','/əˈmeɪz/','[{"w":"amazing","p":"adj.","n":"令人驚嘆的"},{"w":"amazed","p":"adj.","n":"感到驚嘆的"}]','[]'),
('ambition','n.','雄心','junior',3,'She has great ambition.','她很有雄心。','Personality','/æmˈbɪʃ.ən/','[{"w":"ambitious","p":"adj.","n":"有雄心的"}]','[]'),
('ancient','adj.','古代的','junior',2,'Ancient Egypt is fascinating.','古埃及很迷人。','History','/ˈeɪn.ʃənt/','[]','[]'),
('anxious','adj.','焦慮的','junior',3,'She feels anxious about the exam.','她對考試感到焦慮。','Feelings','/ˈæŋk.ʃəs/','[{"w":"anxiety","p":"n.","n":"焦慮"}]','[]'),
('apologize','v.','道歉','junior',2,'I apologize for being late.','我為遲到道歉。','Communication','/əˈpɑː.lə.dʒaɪz/','[{"w":"apology","p":"n.","n":"道歉"}]','["apologize for 為…道歉"]'),
('appetite','n.','食慾','junior',3,'Exercise gives me an appetite.','運動讓我有食慾。','Health','/ˈæp.ə.taɪt/','[]','[]'),
('appreciate','v.','感激','junior',2,'I appreciate your help.','我感激你的幫助。','Communication','/əˈpriː.ʃi.eɪt/','[{"w":"appreciation","p":"n.","n":"感激"}]','[]'),
('approach','v.','接近','junior',3,'Winter is approaching.','冬天快到了。','Actions','/əˈproʊtʃ/','[]','[]'),
('arrange','v.','安排','junior',3,'I will arrange a meeting.','我會安排一場會議。','Actions','/əˈreɪndʒ/','[{"w":"arrangement","p":"n.","n":"安排"}]','[]'),
('arrest','v.','逮捕','junior',3,'The police arrested him.','警察逮捕了他。','Society','/əˈrest/','[]','[]'),
('artificial','adj.','人工的','junior',3,'Artificial flowers last longer.','人工花比較持久。','Adjectives','/ˌɑːr.t̬ɪˈfɪʃ.əl/','[]','["artificial intelligence 人工智慧"]'),
('assign','v.','指派','junior',3,'The teacher assigned homework.','老師指派功課。','School','/əˈsaɪn/','[{"w":"assignment","p":"n.","n":"作業"}]','[]'),
('assist','v.','協助','junior',3,'Can I assist you?','我可以協助你嗎？','Actions','/əˈsɪst/','[{"w":"assistant","p":"n.","n":"助理"},{"w":"assistance","p":"n.","n":"協助"}]','[]'),
('assume','v.','假設','junior',3,'I assume you agree.','我假設你同意。','Communication','/əˈsuːm/','[{"w":"assumption","p":"n.","n":"假設"}]','[]'),
('athlete','n.','運動員','junior',2,'She is a professional athlete.','她是專業運動員。','Sports','/ˈæθ.liːt/','[{"w":"athletic","p":"adj.","n":"運動的"}]','[]'),
('atmosphere','n.','氣氛；大氣','junior',3,'The atmosphere was friendly.','氣氛很友善。','Basic','/ˈæt.mə.sfɪr/','[]','[]'),
('attempt','v.','嘗試','junior',3,'He attempted to climb the wall.','他嘗試爬牆。','Actions','/əˈtempt/','[]','[]'),
('attract','v.','吸引','junior',3,'The show attracts many visitors.','表演吸引很多遊客。','Actions','/əˈtrækt/','[{"w":"attraction","p":"n.","n":"景點；吸引力"},{"w":"attractive","p":"adj.","n":"有吸引力的"}]','[]'),
('authority','n.','權威','junior',3,'He has authority over the team.','他對團隊有權威。','Society','/əˈθɔːr.ə.t̬i/','[]','[]'),
('available','adj.','可用的','junior',3,'Is this seat available?','這個位子有人嗎？','Adjectives','/əˈveɪ.lə.bəl/','[]','[]'),
('average','adj.','平均的','junior',3,'The average score is 75.','平均分數是75。','Basic','/ˈæv.ər.ɪdʒ/','[]','["on average 平均"]'),
('aware','adj.','察覺的','junior',3,'I am aware of the problem.','我知道這個問題。','Feelings','/əˈwer/','[{"w":"awareness","p":"n.","n":"意識"}]','["be aware of 察覺"]'),
('balance','n.','平衡','junior',3,'Find a balance between work and life.','找到工作和生活的平衡。','Basic','/ˈbæl.əns/','[]','[]'),
('ban','v.','禁止','junior',3,'Smoking is banned here.','這裡禁止吸菸。','Society','/bæn/','[]','[]'),
('bargain','n.','便宜貨','junior',3,'That was a real bargain.','那真是划算。','Shopping','/ˈbɑːr.ɡən/','[]','[]'),
('barrier','n.','障礙','junior',3,'Language is a barrier.','語言是一個障礙。','Basic','/ˈber.i.ər/','[]','[]'),
('basis','n.','基礎','junior',3,'This is the basis of our plan.','這是我們計畫的基礎。','Basic','/ˈbeɪ.sɪs/','[]','["on the basis of 基於"]'),
('battle','n.','戰鬥','junior',3,'The battle lasted three days.','戰鬥持續了三天。','History','/ˈbæt̬.əl/','[]','[]'),
('blame','v.','責怪','junior',3,'Do not blame yourself.','不要責怪自己。','Communication','/bleɪm/','[]','["blame for 因…責怪"]'),
('blank','adj.','空白的','junior',3,'Fill in the blank.','填空。','Adjectives','/blæŋk/','[]','[]'),
('bless','v.','祝福','junior',3,'God bless you.','上帝保佑你。','Basic','/bles/','[{"w":"blessing","p":"n.","n":"祝福"}]','[]'),
('blind','adj.','盲的','junior',3,'He has been blind since birth.','他天生失明。','Health','/blaɪnd/','[]','[]'),
('block','v.','阻擋','junior',3,'The road was blocked.','路被堵住了。','Actions','/blɑːk/','[]','[]'),
('blow','v.','吹','junior',2,'The wind blows strongly.','風吹得很強。','Nature','/bloʊ/','[{"w":"blew","p":"v.","n":"過去式"}]','[]'),
('bond','n.','連結','junior',3,'The bond between them is strong.','他們之間的連結很強。','People','/bɑːnd/','[]','[]'),
('bore','v.','使無聊','junior',2,'The lecture bored me.','講座讓我覺得無聊。','Feelings','/bɔːr/','[{"w":"boring","p":"adj.","n":"無聊的"},{"w":"bored","p":"adj.","n":"感到無聊的"}]','[]'),
('borrow','v.','借入','junior',2,'Can I borrow your pen?','我可以借你的筆嗎？','Actions','/ˈbɑːr.oʊ/','[]','["borrow from 從…借"]'),
('boundary','n.','界線','junior',3,'Stay within the boundary.','待在界線內。','Basic','/ˈbaʊn.dər.i/','[]','[]'),
('branch','n.','分支；樹枝','junior',3,'The bird sat on a branch.','鳥坐在樹枝上。','Nature','/bræntʃ/','[]','[]'),
('brand','n.','品牌','junior',3,'What brand do you prefer?','你偏好什麼品牌？','Business','/brænd/','[]','[]'),
('brave','adj.','勇敢的','junior',2,'The firefighter is brave.','消防員很勇敢。','Personality','/breɪv/','[{"w":"bravery","p":"n.","n":"勇氣"}]','[]'),
('broadcast','v.','廣播','junior',3,'The game was broadcast live.','比賽現場轉播。','Communication','/ˈbrɔːd.kæst/','[]','[]'),
('budget','n.','預算','junior',3,'We have a limited budget.','我們預算有限。','Money','/ˈbʌdʒ.ɪt/','[]','[]'),
('burden','n.','負擔','junior',3,'That is a heavy burden.','那是沉重的負擔。','Basic','/ˈbɜːr.dən/','[]','[]'),
('campaign','n.','活動','junior',3,'An election campaign.','選舉活動。','Society','/kæmˈpeɪn/','[]','[]'),
('cancel','v.','取消','junior',3,'The flight was canceled.','航班被取消了。','Actions','/ˈkæn.səl/','[]','[]'),
('capture','v.','捕獲','junior',3,'The photo captures the moment.','照片捕捉了那一刻。','Actions','/ˈkæp.tʃər/','[]','[]'),
('career','n.','職業','junior',3,'She has a successful career.','她有成功的職涯。','Jobs','/kəˈrɪr/','[]','[]'),
('careless','adj.','粗心的','junior',2,'He made a careless mistake.','他犯了粗心的錯誤。','Personality','/ˈker.ləs/','[]','[]'),
('cast','v.','投射','junior',3,'The sun cast a shadow.','太陽投射了影子。','Actions','/kæst/','[]','[]'),
('casual','adj.','隨意的','junior',3,'Wear casual clothes.','穿輕便的衣服。','Adjectives','/ˈkæʒ.u.əl/','[{"w":"casually","p":"adv.","n":"隨意地"}]','[]'),
('category','n.','類別','junior',3,'Divide them into categories.','把它們分類。','Basic','/ˈkæt̬.ə.ɡɔːr.i/','[]','[]'),
('cause','v.','造成','junior',2,'Rain caused the flood.','雨造成了洪水。','Actions','/kɑːz/','[]','[]'),
('cautious','adj.','謹慎的','junior',3,'Be cautious when driving.','開車要謹慎。','Personality','/ˈkɑː.ʃəs/','[{"w":"caution","p":"n.","n":"謹慎"}]','[]'),
('ceremony','n.','典禮','junior',3,'A graduation ceremony.','畢業典禮。','Society','/ˈser.ə.moʊ.ni/','[]','[]'),
('chain','n.','鏈子','junior',3,'A food chain.','食物鏈。','Basic','/tʃeɪn/','[]','["food chain 食物鏈"]'),
('characteristic','n.','特徵','junior',3,'What are her characteristics?','她的特徵是什麼？','Basic','/ˌker.ək.təˈrɪs.tɪk/','[]','[]'),
('charge','v.','收費；充電','junior',3,'How much do you charge?','你收費多少？','Money','/tʃɑːrdʒ/','[]','["in charge of 負責"]'),
('charity','n.','慈善','junior',3,'She donates to charity.','她捐錢給慈善機構。','Society','/ˈtʃer.ə.t̬i/','[]','[]'),
('chemical','adj.','化學的','junior',3,'Chemical reactions.','化學反應。','Science','/ˈkem.ɪ.kəl/','[]','[]'),
('circumstance','n.','情況','junior',3,'Under these circumstances.','在這些情況下。','Basic','/ˈsɜːr.kəm.stæns/','[]','[]'),
('citizen','n.','公民','junior',3,'Every citizen has rights.','每個公民都有權利。','Society','/ˈsɪt̬.ɪ.zən/','[{"w":"citizenship","p":"n.","n":"公民身份"}]','[]'),
('claim','v.','聲稱','junior',3,'He claims to be innocent.','他聲稱自己是無辜的。','Communication','/kleɪm/','[]','[]'),
('classify','v.','分類','junior',3,'Classify the animals.','把動物分類。','Science','/ˈklæs.ɪ.faɪ/','[{"w":"classification","p":"n.","n":"分類"}]','[]'),
('climate','n.','氣候','junior',3,'The climate is changing.','氣候正在改變。','Nature','/ˈklaɪ.mət/','[]','["climate change 氣候變遷"]'),
('colleague','n.','同事','junior',3,'My colleague is very kind.','我同事很善良。','Jobs','/ˈkɑː.liːɡ/','[]','[]'),
('command','v.','命令','junior',3,'The general commanded his troops.','將軍命令他的軍隊。','Actions','/kəˈmænd/','[]','[]'),
('comment','n.','評論','junior',3,'Do you have any comments?','你有什麼評論嗎？','Communication','/ˈkɑː.ment/','[]','[]'),
('commit','v.','承諾；犯罪','junior',3,'He committed a crime.','他犯了罪。','Actions','/kəˈmɪt/','[{"w":"commitment","p":"n.","n":"承諾"}]','[]'),
('community','n.','社區','junior',2,'Our community is friendly.','我們的社區很友善。','Society','/kəˈmjuː.nə.t̬i/','[]','[]'),
('companion','n.','同伴','junior',3,'A good travel companion.','好的旅伴。','People','/kəmˈpæn.jən/','[]','[]'),
('complex','adj.','複雜的','junior',3,'This is a complex problem.','這是一個複雜的問題。','Adjectives','/kɑːmˈpleks/','[{"w":"complexity","p":"n.","n":"複雜性"}]','[]'),
('concentrate','v.','集中','junior',3,'I cannot concentrate.','我無法集中注意力。','Actions','/ˈkɑːn.sən.treɪt/','[{"w":"concentration","p":"n.","n":"專注"}]','["concentrate on 專注於"]'),
('concept','n.','概念','junior',3,'Explain the concept.','解釋這個概念。','Academic','/ˈkɑːn.sept/','[]','[]'),
('conclude','v.','結論','junior',3,'We concluded the meeting.','我們結束了會議。','Actions','/kənˈkluːd/','[{"w":"conclusion","p":"n.","n":"結論"}]','[]'),
('condition','n.','條件；狀況','junior',3,'The car is in good condition.','車況很好。','Basic','/kənˈdɪʃ.ən/','[]','["on condition that 在…條件下"]'),
('conduct','v.','進行','junior',3,'Conduct an experiment.','進行實驗。','Science','/kənˈdʌkt/','[]','[]'),
('confidence','n.','信心','junior',3,'She has great confidence.','她很有信心。','Personality','/ˈkɑːn.fɪ.dəns/','[{"w":"confident","p":"adj.","n":"有信心的"}]','[]'),
('confirm','v.','確認','junior',3,'Please confirm your order.','請確認你的訂單。','Communication','/kənˈfɜːrm/','[{"w":"confirmation","p":"n.","n":"確認"}]','[]'),
('conflict','n.','衝突','junior',3,'Avoid unnecessary conflict.','避免不必要的衝突。','Society','/ˈkɑːn.flɪkt/','[]','[]'),
('confuse','v.','困惑','junior',3,'The instructions confused me.','這些指示讓我困惑。','Feelings','/kənˈfjuːz/','[{"w":"confused","p":"adj.","n":"困惑的"},{"w":"confusing","p":"adj.","n":"令人困惑的"},{"w":"confusion","p":"n.","n":"困惑"}]','[]'),
('connect','v.','連接','junior',2,'Connect the cable.','連接電線。','Actions','/kəˈnekt/','[{"w":"connection","p":"n.","n":"連接"}]','["connect to 連接到"]'),
('conscious','adj.','有意識的','junior',3,'She is conscious of the risk.','她意識到風險。','Adjectives','/ˈkɑːn.ʃəs/','[{"w":"consciousness","p":"n.","n":"意識"}]','[]'),
('consequence','n.','後果','junior',3,'Think about the consequences.','想想後果。','Basic','/ˈkɑːn.sə.kwens/','[]','[]'),
('conservation','n.','保育','junior',3,'Wildlife conservation.','野生動物保育。','Nature','/ˌkɑːn.sərˈveɪ.ʃən/','[{"w":"conserve","p":"v.","n":"保護"}]','[]'),
('consist','v.','組成','junior',3,'The team consists of five people.','團隊由五人組成。','Basic','/kənˈsɪst/','[]','["consist of 由…組成"]'),
('constant','adj.','持續的','junior',3,'Constant practice is important.','持續練習很重要。','Adjectives','/ˈkɑːn.stənt/','[{"w":"constantly","p":"adv.","n":"不斷地"}]','[]'),
('construct','v.','建造','junior',3,'They constructed a bridge.','他們建了一座橋。','Actions','/kənˈstrʌkt/','[{"w":"construction","p":"n.","n":"建設"}]','[]'),
('consult','v.','諮詢','junior',3,'Consult a doctor.','諮詢醫生。','Communication','/kənˈsʌlt/','[]','[]'),
('consume','v.','消費','junior',3,'We consume too much energy.','我們消耗太多能源。','Actions','/kənˈsuːm/','[{"w":"consumer","p":"n.","n":"消費者"},{"w":"consumption","p":"n.","n":"消費"}]','[]'),
('contact','v.','聯繫','junior',2,'Please contact me.','請聯繫我。','Communication','/ˈkɑːn.tækt/','[]','[]'),
('content','adj.','滿足的','junior',3,'I am content with my life.','我對生活很滿足。','Feelings','/kənˈtent/','[]','[]'),
('context','n.','脈絡','junior',3,'Understand the context.','理解脈絡。','Academic','/ˈkɑːn.tekst/','[]','[]'),
('contract','n.','合約','junior',3,'Sign the contract.','簽合約。','Business','/ˈkɑːn.trækt/','[]','[]'),
('contrast','n.','對比','junior',3,'The contrast is striking.','對比很明顯。','Basic','/ˈkɑːn.træst/','[]','["in contrast 相比之下"]'),
('controversial','adj.','有爭議的','junior',3,'A controversial topic.','一個有爭議的話題。','Society','/ˌkɑːn.trəˈvɜːr.ʃəl/','[{"w":"controversy","p":"n.","n":"爭議"}]','[]'),
('convention','n.','慣例','junior',3,'Follow social conventions.','遵循社會慣例。','Society','/kənˈven.ʃən/','[{"w":"conventional","p":"adj.","n":"傳統的"}]','[]'),
('cooperate','v.','合作','junior',3,'They cooperated with each other.','他們互相合作。','Actions','/koʊˈɑː.pər.eɪt/','[{"w":"cooperation","p":"n.","n":"合作"}]','[]'),
('cope','v.','應對','junior',3,'How do you cope with stress?','你怎麼應對壓力？','Actions','/koʊp/','[]','["cope with 應對"]'),
('crisis','n.','危機','junior',3,'A financial crisis.','金融危機。','Society','/ˈkraɪ.sɪs/','[]','[]'),
('critical','adj.','關鍵的；批評的','junior',3,'This is a critical moment.','這是關鍵時刻。','Adjectives','/ˈkrɪt̬.ɪ.kəl/','[{"w":"criticism","p":"n.","n":"批評"},{"w":"criticize","p":"v.","n":"批評"}]','[]'),
('crowd','n.','人群','junior',2,'A large crowd gathered.','一大群人聚集了。','People','/kraʊd/','[{"w":"crowded","p":"adj.","n":"擁擠的"}]','[]'),
('crucial','adj.','關鍵的','junior',3,'This is a crucial decision.','這是關鍵的決定。','Adjectives','/ˈkruː.ʃəl/','[]','[]'),
('cure','v.','治療','junior',3,'There is no cure for this disease.','這疾病無藥可治。','Health','/kjʊr/','[]','[]'),
('current','adj.','目前的','junior',3,'The current situation.','目前的情況。','Adjectives','/ˈkɜːr.ənt/','[{"w":"currently","p":"adv.","n":"目前"}]','[]'),
('custom','n.','習俗','junior',3,'Local customs are interesting.','當地習俗很有趣。','Society','/ˈkʌs.təm/','[{"w":"customary","p":"adj.","n":"習慣的"}]','[]'),
('cycle','n.','循環','junior',3,'The cycle of seasons.','季節的循環。','Science','/ˈsaɪ.kəl/','[]','["life cycle 生命週期"]'),
('data','n.','數據','junior',3,'Collect the data.','收集數據。','Science','/ˈdeɪ.t̬ə/','[]','[]'),
('debate','n.','辯論','junior',3,'A heated debate.','激烈的辯論。','Communication','/dɪˈbeɪt/','[]','[]'),
('decade','n.','十年','junior',3,'In the past decade.','在過去十年。','Time','/ˈdek.eɪd/','[]','[]'),
('decline','v.','下降','junior',3,'Sales have declined.','銷售量下降了。','Business','/dɪˈklaɪn/','[]','[]'),
('decorate','v.','裝飾','junior',2,'We decorated the room.','我們裝飾了房間。','Actions','/ˈdek.ə.reɪt/','[{"w":"decoration","p":"n.","n":"裝飾"}]','[]'),
('decrease','v.','減少','junior',3,'The temperature decreased.','溫度下降了。','Actions','/dɪˈkriːs/','[]','[]'),
('dedicate','v.','致力於','junior',3,'She dedicated her life to teaching.','她把一生獻給教學。','Actions','/ˈded.ɪ.keɪt/','[{"w":"dedication","p":"n.","n":"奉獻"}]','[]'),
('defeat','v.','擊敗','junior',3,'We defeated the other team.','我們擊敗了對方。','Actions','/dɪˈfiːt/','[]','[]'),
('defend','v.','防禦','junior',3,'Defend your country.','保衛你的國家。','Actions','/dɪˈfend/','[{"w":"defense","p":"n.","n":"防禦"}]','[]'),
('define','v.','定義','junior',3,'Define this word.','定義這個字。','Academic','/dɪˈfaɪn/','[{"w":"definition","p":"n.","n":"定義"}]','[]'),
('delay','v.','延遲','junior',3,'The flight was delayed.','航班延誤了。','Actions','/dɪˈleɪ/','[]','[]'),
('democratic','adj.','民主的','junior',3,'A democratic society.','民主社會。','Society','/ˌdem.əˈkræt̬.ɪk/','[{"w":"democracy","p":"n.","n":"民主"}]','[]'),
('deny','v.','否認','junior',3,'He denied the accusation.','他否認了指控。','Communication','/dɪˈnaɪ/','[{"w":"denial","p":"n.","n":"否認"}]','[]'),
('depress','v.','使沮喪','junior',3,'The news depressed him.','這消息讓他沮喪。','Feelings','/dɪˈpres/','[{"w":"depressed","p":"adj.","n":"沮喪的"},{"w":"depression","p":"n.","n":"憂鬱"}]','[]'),
('desire','n.','渴望','junior',3,'A strong desire to succeed.','強烈的成功渴望。','Feelings','/dɪˈzaɪr/','[]','[]'),
('despite','prep.','儘管','junior',3,'Despite the rain, we went out.','儘管下雨，我們還是出去了。','Basic','/dɪˈspaɪt/','[]','[]'),
('destroy','v.','摧毀','junior',2,'The fire destroyed the house.','火災摧毀了房子。','Actions','/dɪˈstrɔɪ/','[{"w":"destruction","p":"n.","n":"摧毀"}]','[]'),
('detect','v.','偵測','junior',3,'The sensor detects motion.','感應器偵測動作。','Science','/dɪˈtekt/','[{"w":"detection","p":"n.","n":"偵測"}]','[]'),
('determine','v.','決定','junior',3,'We must determine the cause.','我們必須確定原因。','Actions','/dɪˈtɜːr.mɪn/','[{"w":"determination","p":"n.","n":"決心"}]','[]'),
('device','n.','裝置','junior',3,'A mobile device.','行動裝置。','Technology','/dɪˈvaɪs/','[]','[]'),
('devote','v.','奉獻','junior',3,'She devoted her time to study.','她把時間奉獻給讀書。','Actions','/dɪˈvoʊt/','[{"w":"devotion","p":"n.","n":"奉獻"}]','["devote to 奉獻給"]'),
('digital','adj.','數位的','junior',3,'The digital age.','數位時代。','Technology','/ˈdɪdʒ.ɪ.t̬əl/','[]','[]'),
('dimension','n.','維度','junior',3,'A three-dimensional object.','三維物體。','Science','/dɪˈmen.ʃən/','[]','[]'),
('direction','n.','方向','junior',2,'Which direction is north?','哪個方向是北？','Basic','/dɪˈrek.ʃən/','[]','[]'),
('disaster','n.','災難','junior',3,'A natural disaster.','自然災害。','Nature','/dɪˈzæs.tər/','[{"w":"disastrous","p":"adj.","n":"災難性的"}]','[]'),
('discipline','n.','紀律','junior',3,'Students need discipline.','學生需要紀律。','School','/ˈdɪs.ə.plɪn/','[]','[]'),
('distinguish','v.','區分','junior',3,'Can you distinguish the two?','你能區分這兩個嗎？','Actions','/dɪˈstɪŋ.ɡwɪʃ/','[]','["distinguish between 區分"]'),
('distribute','v.','分發','junior',3,'Distribute the handouts.','分發講義。','Actions','/dɪˈstrɪb.juːt/','[{"w":"distribution","p":"n.","n":"分配"}]','[]'),
('disturb','v.','打擾','junior',3,'Do not disturb me.','不要打擾我。','Communication','/dɪˈstɜːrb/','[]','[]'),
('diverse','adj.','多元的','junior',3,'A diverse community.','多元的社區。','Society','/dɪˈvɜːrs/','[{"w":"diversity","p":"n.","n":"多元性"}]','[]'),
('document','n.','文件','junior',3,'Sign the document.','簽署文件。','Business','/ˈdɑː.kjə.mənt/','[]','[]'),
('domestic','adj.','國內的','junior',3,'Domestic flights.','國內航班。','Travel','/dəˈmes.tɪk/','[]','[]'),
('dominate','v.','主宰','junior',3,'They dominate the market.','他們主宰了市場。','Business','/ˈdɑː.mɪ.neɪt/','[{"w":"dominant","p":"adj.","n":"主導的"}]','[]'),
('donate','v.','捐贈','junior',3,'She donated money.','她捐了錢。','Society','/ˈdoʊ.neɪt/','[{"w":"donation","p":"n.","n":"捐贈"}]','[]'),
('doubt','v.','懷疑','junior',2,'I doubt he will come.','我懷疑他會來。','Feelings','/daʊt/','[]','["no doubt 無疑"]'),
('draft','n.','草稿','junior',3,'Write a first draft.','寫初稿。','School','/dræft/','[]','[]'),
('dramatic','adj.','戲劇性的','junior',3,'A dramatic change.','戲劇性的改變。','Adjectives','/drəˈmæt̬.ɪk/','[{"w":"dramatically","p":"adv.","n":"戲劇性地"}]','[]'),
('due','adj.','到期的','junior',3,'The report is due tomorrow.','報告明天到期。','Basic','/duː/','[]','["due to 由於"]'),
('duty','n.','義務','junior',3,'It is my duty to help.','幫忙是我的義務。','Basic','/ˈduː.t̬i/','[]','[]'),
('eager','adj.','渴望的','junior',3,'She is eager to learn.','她渴望學習。','Feelings','/ˈiː.ɡər/','[]','["eager to 渴望"]'),
('earn','v.','賺取','junior',2,'He earns a good salary.','他賺了不錯的薪水。','Money','/ɜːrn/','[{"w":"earnings","p":"n.","n":"收入"}]','[]'),
('economy','n.','經濟','junior',3,'The economy is growing.','經濟正在成長。','Society','/ɪˈkɑː.nə.mi/','[{"w":"economic","p":"adj.","n":"經濟的"}]','[]'),
('edit','v.','編輯','junior',3,'Edit the document.','編輯文件。','Actions','/ˈed.ɪt/','[{"w":"editor","p":"n.","n":"編輯"}]','[]'),
('effective','adj.','有效的','junior',3,'An effective method.','有效的方法。','Adjectives','/ɪˈfek.tɪv/','[{"w":"effectively","p":"adv.","n":"有效地"}]','[]'),
('efficient','adj.','有效率的','junior',3,'She is very efficient.','她很有效率。','Adjectives','/ɪˈfɪʃ.ənt/','[{"w":"efficiency","p":"n.","n":"效率"}]','[]'),
('element','n.','元素','junior',3,'The basic elements.','基本元素。','Science','/ˈel.ə.mənt/','[]','[]'),
('embarrass','v.','使尷尬','junior',3,'His behavior embarrassed me.','他的行為讓我尷尬。','Feelings','/ɪmˈber.əs/','[{"w":"embarrassed","p":"adj.","n":"尷尬的"},{"w":"embarrassing","p":"adj.","n":"令人尷尬的"}]','[]'),
('emerge','v.','浮現','junior',3,'New problems emerged.','新問題浮現了。','Actions','/ɪˈmɜːrdʒ/','[]','[]'),
('emotion','n.','情緒','junior',3,'Express your emotions.','表達你的情緒。','Feelings','/ɪˈmoʊ.ʃən/','[{"w":"emotional","p":"adj.","n":"情緒的"}]','[]'),
('emphasize','v.','強調','junior',3,'The teacher emphasized the point.','老師強調了這個重點。','Communication','/ˈem.fə.saɪz/','[{"w":"emphasis","p":"n.","n":"強調"}]','[]'),
('employ','v.','雇用','junior',3,'The company employs 200 people.','公司雇用200人。','Business','/ɪmˈplɔɪ/','[{"w":"employee","p":"n.","n":"員工"},{"w":"employer","p":"n.","n":"雇主"},{"w":"employment","p":"n.","n":"就業"}]','[]'),
('enable','v.','使能夠','junior',3,'Technology enables communication.','科技使溝通成為可能。','Actions','/ɪˈneɪ.bəl/','[]','[]'),
('encounter','v.','遭遇','junior',3,'I encountered a problem.','我遇到了問題。','Actions','/ɪnˈkaʊn.t̬ər/','[]','[]'),
('endure','v.','忍受','junior',3,'She endured the pain.','她忍受了痛苦。','Actions','/ɪnˈdʊr/','[{"w":"endurance","p":"n.","n":"耐力"}]','[]'),
('engage','v.','參與','junior',3,'Engage students in learning.','讓學生參與學習。','Actions','/ɪnˈɡeɪdʒ/','[{"w":"engagement","p":"n.","n":"參與；訂婚"}]','["engage in 參與"]'),
('enormous','adj.','巨大的','junior',3,'An enormous building.','一棟巨大的建築。','Adjectives','/ɪˈnɔːr.məs/','[]','[]'),
('ensure','v.','確保','junior',3,'Ensure everyone understands.','確保每個人都理解。','Actions','/ɪnˈʃʊr/','[]','[]'),
('entertainment','n.','娛樂','junior',3,'What is your favorite entertainment?','你最喜歡的娛樂是什麼？','Life','/ˌen.t̬ərˈteɪn.mənt/','[{"w":"entertain","p":"v.","n":"娛樂"}]','[]'),
('entire','adj.','全部的','junior',3,'The entire class passed.','全班都通過了。','Basic','/ɪnˈtaɪr/','[{"w":"entirely","p":"adv.","n":"完全地"}]','[]'),
('entry','n.','入口','junior',3,'The entry is on the left.','入口在左邊。','Places','/ˈen.tri/','[]','[]'),
('equal','adj.','平等的','junior',3,'All people are equal.','所有人都平等。','Society','/ˈiː.kwəl/','[{"w":"equality","p":"n.","n":"平等"}]','[]'),
('equipment','n.','設備','junior',3,'Sports equipment.','運動器材。','Objects','/ɪˈkwɪp.mənt/','[]','[]'),
('era','n.','時代','junior',3,'The digital era.','數位時代。','History','/ˈɪr.ə/','[]','[]'),
('escape','v.','逃跑','junior',2,'The bird escaped from the cage.','鳥從籠子裡逃走了。','Actions','/ɪˈskeɪp/','[]','[]'),
('essential','adj.','必要的','junior',3,'Water is essential for life.','水對生命是必要的。','Adjectives','/ɪˈsen.ʃəl/','[]','[]'),
('establish','v.','建立','junior',3,'She established a company.','她成立了一家公司。','Actions','/ɪˈstæb.lɪʃ/','[{"w":"establishment","p":"n.","n":"建立"}]','[]'),
('estimate','v.','估計','junior',3,'I estimate it will take an hour.','我估計要花一小時。','Actions','/ˈes.tə.meɪt/','[{"w":"estimation","p":"n.","n":"估計"}]','[]'),
('evaluate','v.','評估','junior',3,'Evaluate the results.','評估結果。','Academic','/ɪˈvæl.ju.eɪt/','[{"w":"evaluation","p":"n.","n":"評估"}]','[]'),
('evidence','n.','證據','junior',3,'There is no evidence.','沒有證據。','Academic','/ˈev.ɪ.dəns/','[]','[]'),
('evident','adj.','明顯的','junior',3,'It is evident that he lied.','很明顯他說謊了。','Adjectives','/ˈev.ɪ.dənt/','[{"w":"evidently","p":"adv.","n":"顯然"}]','[]'),
('evolve','v.','進化','junior',3,'Species evolve over time.','物種隨時間進化。','Science','/ɪˈvɑːlv/','[{"w":"evolution","p":"n.","n":"進化"}]','[]'),
('exact','adj.','確切的','junior',3,'The exact time is 3:15.','確切時間是3:15。','Adjectives','/ɪɡˈzækt/','[{"w":"exactly","p":"adv.","n":"正好"}]','[]'),
('exceed','v.','超過','junior',3,'Do not exceed the speed limit.','不要超過速限。','Actions','/ɪkˈsiːd/','[]','[]'),
('exception','n.','例外','junior',3,'There are no exceptions.','沒有例外。','Basic','/ɪkˈsep.ʃən/','[{"w":"exceptional","p":"adj.","n":"特殊的"}]','[]'),
('excessive','adj.','過度的','junior',3,'Excessive noise.','過度的噪音。','Adjectives','/ɪkˈses.ɪv/','[]','[]'),
('exclude','v.','排除','junior',3,'They excluded him from the group.','他們把他排除在團體外。','Actions','/ɪkˈskluːd/','[{"w":"exclusion","p":"n.","n":"排除"}]','[]'),
('executive','n.','主管','junior',3,'A business executive.','商業主管。','Jobs','/ɪɡˈzek.jə.t̬ɪv/','[]','[]'),
('exhibit','v.','展覽','junior',3,'The museum exhibits paintings.','博物館展覽畫作。','Art','/ɪɡˈzɪb.ɪt/','[{"w":"exhibition","p":"n.","n":"展覽"}]','[]'),
('expand','v.','擴展','junior',3,'The company is expanding.','公司正在擴展。','Business','/ɪkˈspænd/','[{"w":"expansion","p":"n.","n":"擴展"}]','[]'),
('experiment','n.','實驗','junior',3,'We did an experiment.','我們做了實驗。','Science','/ɪkˈsper.ɪ.mənt/','[{"w":"experimental","p":"adj.","n":"實驗性的"}]','[]'),
('expose','v.','暴露','junior',3,'Do not expose skin to the sun.','不要把皮膚暴露在陽光下。','Actions','/ɪkˈspoʊz/','[{"w":"exposure","p":"n.","n":"暴露"}]','[]'),
('extend','v.','延伸','junior',3,'Extend the deadline.','延長截止日。','Actions','/ɪkˈstend/','[{"w":"extension","p":"n.","n":"延伸"}]','[]'),
('extent','n.','程度','junior',3,'To what extent do you agree?','你同意到什麼程度？','Basic','/ɪkˈstent/','[]','["to some extent 在某種程度上"]'),
('extinct','adj.','滅絕的','junior',3,'Dinosaurs are extinct.','恐龍滅絕了。','Nature','/ɪkˈstɪŋkt/','[{"w":"extinction","p":"n.","n":"滅絕"}]','[]'),
('extreme','adj.','極端的','junior',3,'Extreme weather conditions.','極端天氣。','Adjectives','/ɪkˈstriːm/','[{"w":"extremely","p":"adv.","n":"極度"}]','[]'),
('factor','n.','因素','junior',3,'An important factor.','重要的因素。','Academic','/ˈfæk.tər/','[]','[]'),
('fade','v.','褪色','junior',3,'The color faded.','顏色褪了。','Actions','/feɪd/','[]','[]'),
('failure','n.','失敗','junior',3,'Failure is part of learning.','失敗是學習的一部分。','Life','/ˈfeɪ.ljər/','[]','[]')
ON CONFLICT (word, level) DO NOTHING;

-- ═══ END OF BATCH 2 ═══
-- Total after batch 2: ~900 words (300 original + 600 new)
-- Next batch can expand to 1500+ words
-- For the full 7000 words, use CSV import via Supabase Dashboard
