-- Batch 13: upload assets before metadata.
BEGIN;
INSERT INTO public.word_illustrations (id, level, word, sort_order, sense, alt_zh, example, example_zh, image_url, local_path, style, version) VALUES
('elementary-cloud-01-v1', 'elementary', 'cloud', 1, '雲', '一朵蓬鬆的白雲飄在淡藍色天空中。', 'A white cloud floats in the blue sky.', '一朵白雲飄在藍天中。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/cloud-01-v1.webp', '/images/vocabulary/elementary/cloud-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-rainbow-01-v1', 'elementary', 'rainbow', 1, '彩虹', '一道彩虹跨過天空，兩端靠近綠色小山丘。', 'A colorful rainbow arches over the hills.', '一道繽紛的彩虹橫跨山丘上方。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/rainbow-01-v1.webp', '/images/vocabulary/elementary/rainbow-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-rain-01-v1', 'elementary', 'rain', 1, '雨', '灰色雲朵下落著雨滴，地面有小水窪和漣漪。', 'Rain falls into small puddles.', '雨落進小水窪裡。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/rain-01-v1.webp', '/images/vocabulary/elementary/rain-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-snow-01-v1', 'elementary', 'snow', 1, '雪', '白色雪花輕輕飄落，積雪覆蓋小樹和地面。', 'Snow falls gently onto the ground.', '雪輕輕飄落到地面上。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/snow-01-v1.webp', '/images/vocabulary/elementary/snow-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-wind-01-v1', 'elementary', 'wind', 1, '風', '風吹彎小樹，幾片葉子朝同一方向飛去。', 'The wind blows leaves through the air.', '風吹著葉子在空中飛舞。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/wind-01-v1.webp', '/images/vocabulary/elementary/wind-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-leaf-01-v1', 'elementary', 'leaf', 1, '葉子', '一片綠色葉子有清楚的葉脈和短葉柄。', 'The green leaf has tiny veins.', '這片綠葉有細小的葉脈。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/leaf-01-v1.webp', '/images/vocabulary/elementary/leaf-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-branch-01-v1', 'elementary', 'branch', 1, '樹枝', '一根棕色樹枝分出幾根細枝，上面長著綠葉。', 'Green leaves grow on the branch.', '綠葉長在樹枝上。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/branch-01-v1.webp', '/images/vocabulary/elementary/branch-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-grass-01-v1', 'elementary', 'grass', 1, '草', '一小片草地長著高矮不同的細長綠色草葉。', 'Green grass grows in the yard.', '綠草生長在院子裡。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/grass-01-v1.webp', '/images/vocabulary/elementary/grass-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-rock-01-v1', 'elementary', 'rock', 1, '岩石', '一塊灰色岩石有不規則的邊緣和粗糙的表面。', 'The gray rock has a rough surface.', '這塊灰色岩石有粗糙的表面。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/rock-01-v1.webp', '/images/vocabulary/elementary/rock-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-sand-01-v1', 'elementary', 'sand', 1, '沙', '一小堆金黃色細沙散在地上，可看見細小沙粒。', 'Fine sand forms a small pile.', '細沙堆成一座小沙堆。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/sand-01-v1.webp', '/images/vocabulary/elementary/sand-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-pond-01-v1', 'elementary', 'pond', 1, '池塘', '一座小池塘四周長著草，水面有睡蓮葉。', 'Lily pads float on the small pond.', '睡蓮葉漂浮在小池塘的水面上。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/pond-01-v1.webp', '/images/vocabulary/elementary/pond-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-cave-01-v1', 'elementary', 'cave', 1, '洞穴', '岩石山壁上有一個洞口，洞內光線較暗。', 'The cave has a dark entrance.', '這個洞穴有一個昏暗的入口。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/cave-01-v1.webp', '/images/vocabulary/elementary/cave-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-towel-01-v1', 'elementary', 'towel', 1, '毛巾', '一條藍色毛巾掛在橫桿上，底部有細條紋。', 'A blue towel hangs on the rail.', '一條藍色毛巾掛在橫桿上。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/towel-01-v1.webp', '/images/vocabulary/elementary/towel-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-lamp-01-v1', 'elementary', 'lamp', 1, '檯燈', '一盞黃色檯燈有圓形底座和朝下照的燈罩。', 'The yellow lamp shines on the desk.', '這盞黃色檯燈照亮書桌。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/lamp-01-v1.webp', '/images/vocabulary/elementary/lamp-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-sofa-01-v1', 'elementary', 'sofa', 1, '沙發', '一張綠色雙人沙發有柔軟的坐墊和兩側扶手。', 'The green sofa has soft cushions.', '這張綠色沙發有柔軟的坐墊。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/sofa-01-v1.webp', '/images/vocabulary/elementary/sofa-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-refrigerator-01-v1', 'elementary', 'refrigerator', 1, '冰箱', '一台白色雙門冰箱打開下層門，露出架上的牛奶和蔬果。', 'Milk and vegetables stay cool in the refrigerator.', '牛奶和蔬菜在冰箱裡保持冰涼。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/refrigerator-01-v1.webp', '/images/vocabulary/elementary/refrigerator-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-fan-01-v1', 'elementary', 'fan', 1, '電風扇', '一台藍色電風扇有圓形護網、三片扇葉和穩固底座。', 'The blue fan blows cool air.', '這台藍色電風扇吹出涼風。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/fan-01-v1.webp', '/images/vocabulary/elementary/fan-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-television-01-v1', 'elementary', 'television', 1, '電視', '一台平面電視立在兩隻腳架上，螢幕顯示山丘和天空。', 'The television shows green hills.', '電視上顯示綠色山丘。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/television-01-v1.webp', '/images/vocabulary/elementary/television-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-gate-01-v1', 'elementary', 'gate', 1, '大門', '一道木製大門連接兩側矮圍籬，門上有金屬門閂。', 'The wooden gate opens into the garden.', '這道木門通往花園。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/gate-01-v1.webp', '/images/vocabulary/elementary/gate-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-wall-01-v1', 'elementary', 'wall', 1, '牆壁', '一面紅磚牆由一排排交錯排列的磚塊砌成。', 'Red bricks form a strong wall.', '紅磚砌成一道堅固的牆。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/wall-01-v1.webp', '/images/vocabulary/elementary/wall-01-v1.webp', 'watercolor-pencil-v1', 1)
ON CONFLICT (id) DO UPDATE SET level = EXCLUDED.level, word = EXCLUDED.word, sort_order = EXCLUDED.sort_order, sense = EXCLUDED.sense, alt_zh = EXCLUDED.alt_zh, example = EXCLUDED.example, example_zh = EXCLUDED.example_zh, image_url = EXCLUDED.image_url, local_path = EXCLUDED.local_path, style = EXCLUDED.style, version = EXCLUDED.version;
COMMIT;
