-- ═══════════════════════════════════════════════════════════════
-- EnglishGo — 種子單字資料（300 精選字）
-- 基於大考中心高中英文參考詞彙表 Level 1-6
-- 小學 = Level 1 / 國中 = Level 2-3 / 高中 = Level 4-6
--
-- 執行方式：在 Supabase SQL Editor 貼上執行
-- 之後可用 CSV 匯入更多單字
-- ═══════════════════════════════════════════════════════════════

-- ═══ ELEMENTARY 小學 (Level 1) — 100 words ═══════════════════
INSERT INTO public.word_bank (word, pos, meaning, level, ceec_level, example, example_zh, category, phonetic, forms, collocations) VALUES
('a','art.','一個','elementary',1,'I have a dog.','我有一隻狗。','Basic','','[]','[]'),
('about','prep.','關於','elementary',1,'Tell me about your family.','告訴我關於你的家庭。','Basic','/əˈbaʊt/','[]','["about time 差不多"]'),
('after','prep.','在…之後','elementary',1,'I play after school.','我放學後去玩。','Time','/ˈæf.tər/','[]','["after school 放學後"]'),
('all','adj.','全部的','elementary',1,'All students are here.','所有學生都在這裡。','Basic','/ɔːl/','[]','["all day 整天"]'),
('am','v.','是（I am）','elementary',1,'I am a student.','我是學生。','Basic','','[]','[]'),
('and','conj.','和','elementary',1,'I like dogs and cats.','我喜歡狗和貓。','Basic','','[]','[]'),
('animal','n.','動物','elementary',1,'My favorite animal is a cat.','我最喜歡的動物是貓。','Animals','/ˈæn.ɪ.məl/','[{"w":"animals","p":"n.","n":"複數"}]','["animal farm 動物農場"]'),
('apple','n.','蘋果','elementary',1,'I eat an apple every day.','我每天吃一顆蘋果。','Food','/ˈæp.əl/','[{"w":"apples","p":"n.","n":"複數"}]','["apple juice 蘋果汁"]'),
('are','v.','是（you/we/they are）','elementary',1,'We are friends.','我們是朋友。','Basic','','[]','[]'),
('at','prep.','在','elementary',1,'I am at school.','我在學校。','Basic','','[]','["at home 在家"]'),
('bad','adj.','壞的','elementary',1,'This is a bad idea.','這是個壞主意。','Feelings','/bæd/','[{"w":"worse","p":"adj.","n":"更壞"},{"w":"worst","p":"adj.","n":"最壞"}]','[]'),
('ball','n.','球','elementary',1,'He kicks the ball.','他踢球。','Sports','/bɔːl/','[]','["play ball 打球"]'),
('be','v.','是','elementary',1,'I want to be a teacher.','我想當老師。','Basic','/biː/','[{"w":"am/is/are","p":"v.","n":"現在式"},{"w":"was/were","p":"v.","n":"過去式"}]','[]'),
('beautiful','adj.','美麗的','elementary',1,'The flower is beautiful.','這朵花很美。','Adjectives','/ˈbjuː.tɪ.fəl/','[{"w":"beauty","p":"n.","n":"美麗"}]','[]'),
('because','conj.','因為','elementary',1,'I am happy because it is sunny.','我很開心因為天氣晴朗。','Basic','/bɪˈkɒz/','[]','[]'),
('bed','n.','床','elementary',1,'I go to bed at nine.','我九點上床睡覺。','Home','/bed/','[]','["go to bed 上床睡覺"]'),
('before','prep.','在…之前','elementary',1,'Wash your hands before eating.','吃飯前要洗手。','Time','/bɪˈfɔːr/','[]','[]'),
('big','adj.','大的','elementary',1,'The elephant is very big.','大象非常大。','Adjectives','/bɪɡ/','[{"w":"bigger","p":"adj.","n":"更大"},{"w":"biggest","p":"adj.","n":"最大"}]','["big city 大城市"]'),
('bird','n.','鳥','elementary',1,'The bird can fly.','鳥會飛。','Animals','/bɜːrd/','[]','[]'),
('birthday','n.','生日','elementary',1,'Happy birthday to you!','祝你生日快樂！','Time','/ˈbɜːrθ.deɪ/','[]','["birthday party 生日派對"]'),
('black','adj.','黑色的','elementary',1,'I have a black cat.','我有一隻黑貓。','Colors','/blæk/','[]','[]'),
('blue','adj.','藍色的','elementary',1,'The sky is blue.','天空是藍色的。','Colors','/bluː/','[]','[]'),
('body','n.','身體','elementary',1,'Exercise is good for your body.','運動對身體有好處。','Body','/ˈbɑː.di/','[]','[]'),
('book','n.','書','elementary',1,'I read a book before bed.','我睡前讀書。','School','/bʊk/','[{"w":"bookstore","p":"n.","n":"書店"}]','["read a book 讀書"]'),
('boy','n.','男孩','elementary',1,'The boy is playing.','男孩在玩。','People','/bɔɪ/','[]','[]'),
('brother','n.','兄弟','elementary',1,'He is my brother.','他是我的兄弟。','Family','/ˈbrʌð.ər/','[]','[]'),
('but','conj.','但是','elementary',1,'I like cats but not dogs.','我喜歡貓但不喜歡狗。','Basic','','[]','[]'),
('buy','v.','買','elementary',1,'I want to buy a new book.','我想買一本新書。','Actions','/baɪ/','[{"w":"bought","p":"v.","n":"過去式"}]','[]'),
('by','prep.','藉由；在…旁邊','elementary',1,'I go to school by bus.','我搭公車上學。','Basic','/baɪ/','[]','["by bus 搭公車"]'),
('cake','n.','蛋糕','elementary',1,'I love chocolate cake.','我愛巧克力蛋糕。','Food','/keɪk/','[]','["birthday cake 生日蛋糕"]'),
('call','v.','打電話；叫','elementary',1,'Please call me tonight.','請今晚打電話給我。','Actions','/kɔːl/','[]','["call back 回電"]'),
('can','v.','能；可以','elementary',1,'I can swim.','我會游泳。','Basic','/kæn/','[{"w":"could","p":"v.","n":"過去式"}]','[]'),
('cat','n.','貓','elementary',1,'The cat is sleeping.','貓在睡覺。','Animals','/kæt/','[]','[]'),
('chair','n.','椅子','elementary',1,'Please sit on the chair.','請坐在椅子上。','Home','/tʃer/','[]','[]'),
('chicken','n.','雞；雞肉','elementary',1,'I like fried chicken.','我喜歡炸雞。','Food','/ˈtʃɪk.ɪn/','[]','[]'),
('child','n.','小孩','elementary',1,'Every child is special.','每個小孩都是特別的。','People','/tʃaɪld/','[{"w":"children","p":"n.","n":"複數"}]','[]'),
('city','n.','城市','elementary',1,'Taipei is a big city.','台北是一個大城市。','Places','/ˈsɪt.i/','[{"w":"cities","p":"n.","n":"複數"}]','[]'),
('class','n.','班級；課','elementary',1,'We have English class today.','我們今天有英文課。','School','/klæs/','[]','["class teacher 班導師"]'),
('clean','adj.','乾淨的','elementary',1,'Keep your room clean.','保持房間乾淨。','Adjectives','/kliːn/','[]','[]'),
('close','v.','關閉','elementary',1,'Please close the door.','請關門。','Actions','/kloʊz/','[]','[]'),
('cold','adj.','冷的','elementary',1,'It is very cold today.','今天很冷。','Weather','/koʊld/','[]','["cold water 冷水"]'),
('color','n.','顏色','elementary',1,'What color do you like?','你喜歡什麼顏色？','Basic','/ˈkʌl.ər/','[{"w":"colorful","p":"adj.","n":"彩色的"}]','[]'),
('come','v.','來','elementary',1,'Come here, please.','請過來。','Actions','/kʌm/','[{"w":"came","p":"v.","n":"過去式"}]','["come back 回來"]'),
('cook','v.','煮','elementary',1,'My mom can cook well.','我媽媽很會煮飯。','Actions','/kʊk/','[]','[]'),
('cool','adj.','涼爽的；酷','elementary',1,'It is cool in autumn.','秋天很涼爽。','Weather','/kuːl/','[]','[]'),
('country','n.','國家','elementary',1,'Taiwan is a beautiful country.','台灣是個美麗的國家。','Places','/ˈkʌn.tri/','[]','[]'),
('cup','n.','杯子','elementary',1,'A cup of tea, please.','請給我一杯茶。','Home','/kʌp/','[]','["a cup of 一杯"]'),
('dad','n.','爸爸','elementary',1,'My dad is a doctor.','我爸爸是醫生。','Family','/dæd/','[]','[]'),
('dance','v.','跳舞','elementary',1,'She likes to dance.','她喜歡跳舞。','Actions','/dæns/','[{"w":"dancer","p":"n.","n":"舞者"}]','[]'),
('day','n.','天；日子','elementary',1,'Today is a beautiful day.','今天是美好的一天。','Time','/deɪ/','[]','["every day 每天"]'),
('dear','adj.','親愛的','elementary',1,'Dear Mom, thank you.','親愛的媽媽，謝謝你。','Basic','/dɪr/','[]','[]'),
('do','v.','做','elementary',1,'What do you do?','你做什麼工作？','Actions','/duː/','[{"w":"did","p":"v.","n":"過去式"},{"w":"done","p":"v.","n":"過去分詞"}]','["do homework 做功課"]'),
('doctor','n.','醫生','elementary',1,'I want to be a doctor.','我想當醫生。','Jobs','/ˈdɑːk.tər/','[]','["see a doctor 看醫生"]'),
('dog','n.','狗','elementary',1,'The dog is friendly.','那隻狗很友善。','Animals','/dɔːɡ/','[]','[]'),
('door','n.','門','elementary',1,'Please open the door.','請開門。','Home','/dɔːr/','[]','[]'),
('draw','v.','畫','elementary',1,'I like to draw pictures.','我喜歡畫畫。','Actions','/drɔː/','[{"w":"drew","p":"v.","n":"過去式"}]','[]'),
('drink','v.','喝','elementary',1,'Drink more water.','多喝水。','Actions','/drɪŋk/','[{"w":"drank","p":"v.","n":"過去式"}]','[]'),
('eat','v.','吃','elementary',1,'We eat lunch at noon.','我們中午吃午餐。','Actions','/iːt/','[{"w":"ate","p":"v.","n":"過去式"},{"w":"eaten","p":"v.","n":"過去分詞"}]','["eat out 外食"]'),
('egg','n.','蛋','elementary',1,'I eat eggs for breakfast.','我早餐吃蛋。','Food','/eɡ/','[]','[]'),
('eight','n.','八','elementary',1,'I have eight books.','我有八本書。','Numbers','','[]','[]'),
('English','n.','英文','elementary',1,'I study English every day.','我每天學英文。','School','/ˈɪŋ.ɡlɪʃ/','[]','[]'),
('enjoy','v.','享受','elementary',1,'I enjoy reading books.','我享受閱讀。','Feelings','/ɪnˈdʒɔɪ/','[{"w":"enjoyable","p":"adj.","n":"令人愉快的"}]','[]'),
('eye','n.','眼睛','elementary',1,'She has beautiful eyes.','她有美麗的眼睛。','Body','/aɪ/','[]','[]'),
('face','n.','臉','elementary',1,'Wash your face.','洗臉。','Body','/feɪs/','[]','[]'),
('family','n.','家庭','elementary',1,'I love my family.','我愛我的家人。','Family','/ˈfæm.əl.i/','[]','[]'),
('fast','adj.','快的','elementary',1,'He can run very fast.','他跑得很快。','Adjectives','/fæst/','[]','[]'),
('father','n.','父親','elementary',1,'My father is kind.','我父親很善良。','Family','/ˈfɑː.ðər/','[]','[]'),
('find','v.','找到','elementary',1,'I cannot find my pen.','我找不到我的筆。','Actions','/faɪnd/','[{"w":"found","p":"v.","n":"過去式"}]','[]'),
('fish','n.','魚','elementary',1,'I like to eat fish.','我喜歡吃魚。','Food','/fɪʃ/','[]','[]'),
('five','n.','五','elementary',1,'I have five fingers.','我有五根手指。','Numbers','','[]','[]'),
('flower','n.','花','elementary',1,'The flower is red.','花是紅色的。','Nature','/ˈflaʊ.ər/','[]','[]'),
('food','n.','食物','elementary',1,'This food is delicious.','這食物很好吃。','Food','/fuːd/','[]','["fast food 速食"]'),
('for','prep.','為了','elementary',1,'This gift is for you.','這禮物是給你的。','Basic','','[]','[]'),
('friend','n.','朋友','elementary',1,'She is my best friend.','她是我最好的朋友。','People','/frend/','[{"w":"friendly","p":"adj.","n":"友善的"},{"w":"friendship","p":"n.","n":"友誼"}]','["best friend 最好的朋友"]'),
('fruit','n.','水果','elementary',1,'Eat more fruit.','多吃水果。','Food','/fruːt/','[]','[]'),
('fun','n.','樂趣','elementary',1,'We have a lot of fun.','我們玩得很開心。','Feelings','/fʌn/','[{"w":"funny","p":"adj.","n":"有趣的"}]','["have fun 玩得開心"]'),
('game','n.','遊戲','elementary',1,'Let us play a game.','讓我們玩個遊戲。','School','/ɡeɪm/','[]','["video game 電動遊戲"]'),
('girl','n.','女孩','elementary',1,'The girl is singing.','女孩在唱歌。','People','/ɡɜːrl/','[]','[]'),
('give','v.','給','elementary',1,'Please give me the book.','請給我那本書。','Actions','/ɡɪv/','[{"w":"gave","p":"v.","n":"過去式"},{"w":"given","p":"v.","n":"過去分詞"}]','[]'),
('go','v.','去','elementary',1,'I go to school by bus.','我搭公車上學。','Actions','/ɡoʊ/','[{"w":"went","p":"v.","n":"過去式"},{"w":"gone","p":"v.","n":"過去分詞"}]','["go home 回家"]'),
('good','adj.','好的','elementary',1,'She is a good student.','她是好學生。','Adjectives','/ɡʊd/','[{"w":"better","p":"adj.","n":"更好"},{"w":"best","p":"adj.","n":"最好"}]','["good morning 早安"]'),
('green','adj.','綠色的','elementary',1,'The grass is green.','草是綠色的。','Colors','/ɡriːn/','[]','[]'),
('hair','n.','頭髮','elementary',1,'She has long hair.','她有長頭髮。','Body','/her/','[]','[]'),
('hand','n.','手','elementary',1,'Raise your hand.','舉手。','Body','/hænd/','[]','[]'),
('happy','adj.','開心的','elementary',1,'I am very happy today.','我今天很開心。','Feelings','/ˈhæp.i/','[{"w":"happiness","p":"n.","n":"快樂"},{"w":"happily","p":"adv.","n":"開心地"}]','["happy birthday 生日快樂"]'),
('have','v.','有','elementary',1,'I have two sisters.','我有兩個姊妹。','Basic','/hæv/','[{"w":"had","p":"v.","n":"過去式"}]','["have lunch 吃午餐"]'),
('he','pron.','他','elementary',1,'He is my friend.','他是我的朋友。','Basic','','[]','[]'),
('head','n.','頭','elementary',1,'Use your head to think.','用腦袋想。','Body','/hed/','[]','[]'),
('help','v.','幫助','elementary',1,'Can you help me?','你可以幫我嗎？','Actions','/help/','[{"w":"helpful","p":"adj.","n":"有幫助的"}]','[]'),
('here','adv.','這裡','elementary',1,'Come here, please.','請過來這裡。','Basic','/hɪr/','[]','[]'),
('home','n.','家','elementary',1,'I go home at five.','我五點回家。','Places','/hoʊm/','[]','["go home 回家"]'),
('hot','adj.','熱的','elementary',1,'It is very hot today.','今天很熱。','Weather','/hɑːt/','[]','["hot dog 熱狗"]'),
('house','n.','房子','elementary',1,'We live in a big house.','我們住在大房子裡。','Places','/haʊs/','[]','[]'),
('how','adv.','如何','elementary',1,'How are you?','你好嗎？','Basic','/haʊ/','[]','["how much 多少"]'),
('hungry','adj.','餓的','elementary',1,'I am hungry.','我餓了。','Feelings','/ˈhʌŋ.ɡri/','[]','[]'),
('it','pron.','它','elementary',1,'It is a cat.','它是一隻貓。','Basic','','[]','[]'),
('juice','n.','果汁','elementary',1,'I like orange juice.','我喜歡柳橙汁。','Food','/dʒuːs/','[]','[]'),
('know','v.','知道','elementary',1,'I know the answer.','我知道答案。','Basic','/noʊ/','[{"w":"knew","p":"v.","n":"過去式"},{"w":"known","p":"v.","n":"過去分詞"}]','[]'),
('like','v.','喜歡','elementary',1,'I like to read books.','我喜歡讀書。','Feelings','/laɪk/','[]','[]'),
('look','v.','看','elementary',1,'Look at the bird!','看那隻鳥！','Actions','/lʊk/','[]','["look at 看"]'),
('love','v.','愛','elementary',1,'I love my family.','我愛我的家人。','Feelings','/lʌv/','[{"w":"lovely","p":"adj.","n":"可愛的"}]','[]'),
('make','v.','做；製作','elementary',1,'Mom makes breakfast for me.','媽媽幫我做早餐。','Actions','/meɪk/','[{"w":"made","p":"v.","n":"過去式"}]','[]'),
('many','adj.','許多','elementary',1,'There are many people here.','這裡有很多人。','Basic','/ˈmen.i/','[]','["how many 多少"]'),
('milk','n.','牛奶','elementary',1,'I drink milk every morning.','我每天早上喝牛奶。','Food','/mɪlk/','[]','[]'),
('mom','n.','媽媽','elementary',1,'My mom is a teacher.','我媽媽是老師。','Family','','[]','[]'),
('mouth','n.','嘴巴','elementary',1,'Open your mouth.','張開嘴巴。','Body','/maʊθ/','[]','[]');

-- ═══ JUNIOR 國中 (Level 2-3) — 100 words ═════════════════════
INSERT INTO public.word_bank (word, pos, meaning, level, ceec_level, example, example_zh, category, phonetic, forms, collocations) VALUES
('ability','n.','能力','junior',2,'She has the ability to lead.','她有領導能力。','Personality','/əˈbɪl.ə.ti/','[]','[]'),
('abroad','adv.','國外','junior',2,'He wants to study abroad.','他想出國讀書。','Travel','/əˈbrɔːd/','[]','["go abroad 出國"]'),
('accept','v.','接受','junior',2,'I accept your invitation.','我接受你的邀請。','Actions','/əkˈsept/','[{"w":"acceptable","p":"adj.","n":"可接受的"}]','[]'),
('achieve','v.','達成','junior',2,'She achieved her dream.','她達成了夢想。','Actions','/əˈtʃiːv/','[{"w":"achievement","p":"n.","n":"成就"}]','["achieve a goal 達成目標"]'),
('actually','adv.','事實上','junior',2,'Actually, I disagree.','事實上，我不同意。','Basic','/ˈæk.tʃu.ə.li/','[]','[]'),
('advantage','n.','優勢','junior',3,'This is a big advantage.','這是很大的優勢。','Basic','/ədˈvæn.tɪdʒ/','[]','["take advantage of 利用"]'),
('advice','n.','建議','junior',2,'Thank you for your advice.','謝謝你的建議。','Communication','/ədˈvaɪs/','[{"w":"advise","p":"v.","n":"建議"}]','["give advice 給建議"]'),
('affect','v.','影響','junior',3,'The weather affects my mood.','天氣影響我的心情。','Actions','/əˈfekt/','[{"w":"effect","p":"n.","n":"效果"}]','[]'),
('afford','v.','負擔得起','junior',3,'I cannot afford a new car.','我買不起新車。','Money','/əˈfɔːrd/','[]','[]'),
('agree','v.','同意','junior',2,'I agree with you.','我同意你的看法。','Communication','/əˈɡriː/','[{"w":"agreement","p":"n.","n":"協議"}]','["agree with 同意"]'),
('allow','v.','允許','junior',2,'Mom allows me to go out.','媽媽允許我出去。','Actions','/əˈlaʊ/','[]','[]'),
('although','conj.','雖然','junior',2,'Although it rained, we went out.','雖然下雨，我們還是出去了。','Basic','/ɔːlˈðoʊ/','[]','[]'),
('amount','n.','數量','junior',3,'A large amount of money.','一大筆錢。','Basic','/əˈmaʊnt/','[]','["a large amount of 大量"]'),
('announce','v.','宣布','junior',3,'The teacher announced the results.','老師宣布了結果。','Communication','/əˈnaʊns/','[{"w":"announcement","p":"n.","n":"宣布"}]','[]'),
('appear','v.','出現','junior',2,'The sun appeared.','太陽出現了。','Actions','/əˈpɪr/','[{"w":"appearance","p":"n.","n":"外表"}]','[]'),
('apply','v.','申請；應用','junior',3,'I applied for the job.','我申請了那份工作。','Actions','/əˈplaɪ/','[{"w":"application","p":"n.","n":"申請"}]','["apply for 申請"]'),
('argue','v.','爭論','junior',3,'They argued about politics.','他們爭論政治。','Communication','/ˈɑːr.ɡjuː/','[{"w":"argument","p":"n.","n":"爭論"}]','[]'),
('attend','v.','參加','junior',2,'I attend school every day.','我每天上學。','Actions','/əˈtend/','[{"w":"attention","p":"n.","n":"注意"}]','["pay attention 注意"]'),
('avoid','v.','避免','junior',3,'Try to avoid mistakes.','盡量避免錯誤。','Actions','/əˈvɔɪd/','[]','[]'),
('basic','adj.','基本的','junior',2,'Learn the basic rules first.','先學基本規則。','Adjectives','/ˈbeɪ.sɪk/','[{"w":"basically","p":"adv.","n":"基本上"}]','[]'),
('behave','v.','表現','junior',3,'Please behave yourself.','請注意你的行為。','Actions','/bɪˈheɪv/','[{"w":"behavior","p":"n.","n":"行為"}]','[]'),
('believe','v.','相信','junior',2,'I believe in you.','我相信你。','Feelings','/bɪˈliːv/','[{"w":"belief","p":"n.","n":"信念"}]','["believe in 相信"]'),
('belong','v.','屬於','junior',3,'This book belongs to me.','這本書屬於我。','Basic','/bɪˈlɔːŋ/','[]','["belong to 屬於"]'),
('benefit','n.','益處','junior',3,'Exercise has many benefits.','運動有很多好處。','Basic','/ˈben.ɪ.fɪt/','[{"w":"beneficial","p":"adj.","n":"有益的"}]','[]'),
('bother','v.','打擾','junior',3,'Sorry to bother you.','抱歉打擾你。','Communication','/ˈbɑː.ðər/','[]','[]'),
('capable','adj.','有能力的','junior',3,'She is very capable.','她很有能力。','Personality','/ˈkeɪ.pə.bəl/','[{"w":"capability","p":"n.","n":"能力"}]','[]'),
('celebrate','v.','慶祝','junior',2,'We celebrate Chinese New Year.','我們慶祝農曆新年。','Actions','/ˈsel.ə.breɪt/','[{"w":"celebration","p":"n.","n":"慶祝"}]','[]'),
('certain','adj.','確定的','junior',3,'I am certain about this.','我對此很確定。','Adjectives','/ˈsɜːr.tən/','[{"w":"certainly","p":"adv.","n":"當然"}]','[]'),
('challenge','n.','挑戰','junior',3,'This is a big challenge.','這是很大的挑戰。','Basic','/ˈtʃæl.ɪndʒ/','[{"w":"challenging","p":"adj.","n":"有挑戰性的"}]','[]'),
('chance','n.','機會','junior',2,'Give me one more chance.','再給我一次機會。','Basic','/tʃæns/','[]','[]'),
('character','n.','角色；性格','junior',3,'He is a main character.','他是主角。','People','/ˈker.ək.tər/','[]','[]'),
('choose','v.','選擇','junior',2,'Choose one you like.','選一個你喜歡的。','Actions','/tʃuːz/','[{"w":"chose","p":"v.","n":"過去式"},{"w":"choice","p":"n.","n":"選擇"}]','[]'),
('communicate','v.','溝通','junior',3,'It is important to communicate clearly.','清楚溝通很重要。','Communication','/kəˈmjuː.nɪ.keɪt/','[{"w":"communication","p":"n.","n":"溝通"}]','[]'),
('compare','v.','比較','junior',3,'Compare these two pictures.','比較這兩張圖。','Actions','/kəmˈper/','[{"w":"comparison","p":"n.","n":"比較"}]','["compare with 與…比較"]'),
('complain','v.','抱怨','junior',3,'He always complains.','他總是抱怨。','Communication','/kəmˈpleɪn/','[{"w":"complaint","p":"n.","n":"抱怨"}]','[]'),
('complete','v.','完成','junior',2,'Please complete the form.','請填完表格。','Actions','/kəmˈpliːt/','[{"w":"completely","p":"adv.","n":"完全地"}]','[]'),
('concern','n.','擔心','junior',3,'Health is my main concern.','健康是我最擔心的。','Feelings','/kənˈsɜːrn/','[{"w":"concerned","p":"adj.","n":"擔心的"}]','[]'),
('consider','v.','考慮','junior',3,'I will consider your suggestion.','我會考慮你的建議。','Actions','/kənˈsɪd.ər/','[{"w":"consideration","p":"n.","n":"考慮"}]','[]'),
('contain','v.','包含','junior',3,'This box contains books.','這個箱子裝著書。','Basic','/kənˈteɪn/','[{"w":"container","p":"n.","n":"容器"}]','[]'),
('continue','v.','繼續','junior',2,'Please continue reading.','請繼續閱讀。','Actions','/kənˈtɪn.juː/','[]','[]'),
('contribute','v.','貢獻','junior',3,'Everyone can contribute.','每個人都能貢獻。','Actions','/kənˈtrɪb.juːt/','[{"w":"contribution","p":"n.","n":"貢獻"}]','[]'),
('control','v.','控制','junior',3,'He cannot control his anger.','他無法控制憤怒。','Actions','/kənˈtroʊl/','[]','[]'),
('convenient','adj.','方便的','junior',3,'The location is very convenient.','這個位置很方便。','Adjectives','/kənˈviː.ni.ənt/','[{"w":"convenience","p":"n.","n":"便利"}]','[]'),
('convince','v.','說服','junior',3,'She convinced me to go.','她說服我去。','Communication','/kənˈvɪns/','[]','[]'),
('create','v.','創造','junior',2,'Artists create beautiful things.','藝術家創造美麗的東西。','Actions','/kriˈeɪt/','[{"w":"creative","p":"adj.","n":"有創意的"},{"w":"creation","p":"n.","n":"創作"}]','[]'),
('culture','n.','文化','junior',2,'I love Taiwanese culture.','我愛台灣文化。','Society','/ˈkʌl.tʃər/','[{"w":"cultural","p":"adj.","n":"文化的"}]','[]'),
('curious','adj.','好奇的','junior',3,'Children are very curious.','小孩子很好奇。','Personality','/ˈkjʊr.i.əs/','[{"w":"curiosity","p":"n.","n":"好奇心"}]','[]'),
('customer','n.','顧客','junior',3,'The customer is always right.','顧客永遠是對的。','Business','/ˈkʌs.tə.mər/','[]','[]'),
('damage','n.','損害','junior',3,'The typhoon caused damage.','颱風造成損害。','Basic','/ˈdæm.ɪdʒ/','[]','[]'),
('deal','v.','處理','junior',3,'How do you deal with stress?','你怎麼處理壓力？','Actions','/diːl/','[]','["deal with 處理"]'),
('decide','v.','決定','junior',2,'I decided to study harder.','我決定更用功。','Actions','/dɪˈsaɪd/','[{"w":"decision","p":"n.","n":"決定"}]','[]'),
('deliver','v.','遞送','junior',3,'The mailman delivers letters.','郵差送信。','Actions','/dɪˈlɪv.ər/','[{"w":"delivery","p":"n.","n":"遞送"}]','[]'),
('demand','v.','要求','junior',3,'The job demands hard work.','這份工作要求努力。','Actions','/dɪˈmænd/','[]','[]'),
('depend','v.','依賴','junior',3,'It depends on the weather.','這取決於天氣。','Basic','/dɪˈpend/','[{"w":"dependent","p":"adj.","n":"依賴的"}]','["depend on 取決於"]'),
('describe','v.','描述','junior',2,'Describe your best friend.','描述你最好的朋友。','Communication','/dɪˈskraɪb/','[{"w":"description","p":"n.","n":"描述"}]','[]'),
('design','v.','設計','junior',3,'She designs beautiful clothes.','她設計美麗的衣服。','Actions','/dɪˈzaɪn/','[{"w":"designer","p":"n.","n":"設計師"}]','[]'),
('develop','v.','發展','junior',3,'The city is developing fast.','這座城市發展得很快。','Actions','/dɪˈvel.əp/','[{"w":"development","p":"n.","n":"發展"}]','[]'),
('difference','n.','差異','junior',2,'What is the difference?','有什麼差異？','Basic','/ˈdɪf.ər.əns/','[{"w":"different","p":"adj.","n":"不同的"}]','[]'),
('difficult','adj.','困難的','junior',2,'Math is difficult for me.','數學對我來說很難。','Adjectives','/ˈdɪf.ɪ.kəlt/','[{"w":"difficulty","p":"n.","n":"困難"}]','[]'),
('disappoint','v.','使失望','junior',3,'I am sorry to disappoint you.','抱歉讓你失望。','Feelings','/ˌdɪs.əˈpɔɪnt/','[{"w":"disappointed","p":"adj.","n":"失望的"},{"w":"disappointing","p":"adj.","n":"令人失望的"}]','[]'),
('discover','v.','發現','junior',2,'Columbus discovered America.','哥倫布發現了美洲。','Actions','/dɪˈskʌv.ər/','[{"w":"discovery","p":"n.","n":"發現"}]','[]'),
('discuss','v.','討論','junior',2,'Let us discuss this problem.','讓我們討論這個問題。','Communication','/dɪˈskʌs/','[{"w":"discussion","p":"n.","n":"討論"}]','[]'),
('education','n.','教育','junior',2,'Education is very important.','教育非常重要。','School','/ˌedʒ.uˈkeɪ.ʃən/','[{"w":"educate","p":"v.","n":"教育"}]','[]'),
('encourage','v.','鼓勵','junior',3,'My teacher encourages me.','我的老師鼓勵我。','Communication','/ɪnˈkɜːr.ɪdʒ/','[{"w":"encouragement","p":"n.","n":"鼓勵"}]','[]'),
('energy','n.','能量','junior',3,'I have a lot of energy today.','我今天精力充沛。','Science','/ˈen.ər.dʒi/','[]','["solar energy 太陽能"]'),
('environment','n.','環境','junior',2,'Protect the environment.','保護環境。','Nature','/ɪnˈvaɪ.rən.mənt/','[{"w":"environmental","p":"adj.","n":"環境的"}]','[]'),
('especially','adv.','尤其','junior',3,'I love fruit, especially apples.','我愛水果，尤其是蘋果。','Basic','/ɪˈspeʃ.əl.i/','[]','[]'),
('event','n.','事件','junior',3,'It was an important event.','那是重要的事件。','Basic','/ɪˈvent/','[]','[]'),
('examine','v.','檢查','junior',3,'The doctor examined the patient.','醫生檢查了病人。','Actions','/ɪɡˈzæm.ɪn/','[{"w":"examination","p":"n.","n":"考試；檢查"}]','[]'),
('example','n.','例子','junior',2,'Give me an example.','給我一個例子。','Basic','/ɪɡˈzæm.pəl/','[]','["for example 例如"]'),
('exchange','v.','交換','junior',3,'Let us exchange ideas.','讓我們交換意見。','Actions','/ɪksˈtʃeɪndʒ/','[]','["exchange student 交換學生"]'),
('exist','v.','存在','junior',3,'Dinosaurs no longer exist.','恐龍已不存在。','Basic','/ɪɡˈzɪst/','[{"w":"existence","p":"n.","n":"存在"}]','[]'),
('expect','v.','期待','junior',2,'I expect to pass the exam.','我期待通過考試。','Feelings','/ɪkˈspekt/','[{"w":"expectation","p":"n.","n":"期待"}]','[]'),
('experience','n.','經驗','junior',2,'It was a great experience.','那是很棒的經歷。','Life','/ɪkˈspɪr.i.əns/','[{"w":"experienced","p":"adj.","n":"有經驗的"}]','[]'),
('explain','v.','解釋','junior',2,'Please explain it to me.','請向我解釋。','Communication','/ɪkˈspleɪn/','[{"w":"explanation","p":"n.","n":"解釋"}]','[]'),
('express','v.','表達','junior',3,'I cannot express my feelings.','我無法表達我的感受。','Communication','/ɪkˈspres/','[{"w":"expression","p":"n.","n":"表達"}]','[]'),
('familiar','adj.','熟悉的','junior',3,'This place looks familiar.','這地方看起來很熟悉。','Adjectives','/fəˈmɪl.jər/','[]','["be familiar with 熟悉"]'),
('focus','v.','專注','junior',3,'Focus on your study.','專注在你的學業。','Actions','/ˈfoʊ.kəs/','[]','["focus on 專注於"]'),
('foreign','adj.','外國的','junior',2,'I want to learn a foreign language.','我想學外國語言。','Basic','/ˈfɔːr.ən/','[{"w":"foreigner","p":"n.","n":"外國人"}]','[]'),
('gather','v.','聚集','junior',3,'People gathered in the park.','人們聚集在公園。','Actions','/ˈɡæð.ər/','[]','[]'),
('generation','n.','世代','junior',3,'The younger generation.','年輕世代。','Society','/ˌdʒen.əˈreɪ.ʃən/','[]','[]'),
('gradually','adv.','逐漸地','junior',3,'The weather gradually improved.','天氣逐漸改善。','Basic','/ˈɡrædʒ.u.ə.li/','[{"w":"gradual","p":"adj.","n":"逐漸的"}]','[]'),
('habit','n.','習慣','junior',2,'Reading is a good habit.','閱讀是好習慣。','Life','/ˈhæb.ɪt/','[]','[]'),
('improve','v.','改善','junior',2,'Practice can improve your English.','練習可以提升英文。','Actions','/ɪmˈpruːv/','[{"w":"improvement","p":"n.","n":"改善"}]','[]'),
('include','v.','包含','junior',3,'The price includes tax.','價格包含稅金。','Basic','/ɪnˈkluːd/','[{"w":"including","p":"prep.","n":"包括"}]','[]'),
('increase','v.','增加','junior',3,'The population is increasing.','人口正在增加。','Actions','/ɪnˈkriːs/','[]','[]'),
('influence','n.','影響','junior',3,'Music has a great influence.','音樂有很大的影響。','Basic','/ˈɪn.flu.əns/','[{"w":"influential","p":"adj.","n":"有影響力的"}]','[]'),
('intend','v.','打算','junior',3,'I intend to study abroad.','我打算出國讀書。','Actions','/ɪnˈtend/','[{"w":"intention","p":"n.","n":"意圖"}]','[]'),
('involve','v.','涉及','junior',3,'This project involves teamwork.','這專案涉及團隊合作。','Actions','/ɪnˈvɑːlv/','[]','[]'),
('judge','v.','判斷','junior',3,'Do not judge people by appearance.','不要以貌取人。','Actions','/dʒʌdʒ/','[{"w":"judgment","p":"n.","n":"判斷"}]','[]'),
('manage','v.','管理','junior',3,'She manages a restaurant.','她管理一家餐廳。','Business','/ˈmæn.ɪdʒ/','[{"w":"manager","p":"n.","n":"經理"},{"w":"management","p":"n.","n":"管理"}]','[]'),
('mention','v.','提到','junior',3,'He mentioned your name.','他提到了你的名字。','Communication','/ˈmen.ʃən/','[]','[]'),
('normal','adj.','正常的','junior',2,'This is perfectly normal.','這完全正常。','Adjectives','/ˈnɔːr.məl/','[{"w":"normally","p":"adv.","n":"通常"}]','[]'),
('notice','v.','注意到','junior',2,'I noticed something strange.','我注意到一些奇怪的事。','Actions','/ˈnoʊ.tɪs/','[]','[]'),
('opportunity','n.','機會','junior',3,'This is a golden opportunity.','這是黃金機會。','Life','/ˌɑː.pərˈtuː.nə.ti/','[]','[]'),
('organize','v.','組織','junior',3,'She organized a party.','她組織了一個派對。','Actions','/ˈɔːr.ɡə.naɪz/','[{"w":"organization","p":"n.","n":"組織"}]','[]'),
('participate','v.','參與','junior',3,'Students participate in activities.','學生參與活動。','Actions','/pɑːrˈtɪs.ɪ.peɪt/','[{"w":"participation","p":"n.","n":"參與"}]','["participate in 參加"]'),
('population','n.','人口','junior',3,'The population is growing.','人口正在增長。','Society','/ˌpɑː.pjəˈleɪ.ʃən/','[]','[]'),
('process','n.','過程','junior',3,'Learning is a slow process.','學習是一個緩慢的過程。','Basic','/ˈprɑː.ses/','[]','[]'),
('purpose','n.','目的','junior',3,'What is the purpose of this?','這個的目的是什麼？','Basic','/ˈpɜːr.pəs/','[]','["on purpose 故意"]'),
('realize','v.','意識到','junior',3,'I realized my mistake.','我意識到我的錯誤。','Actions','/ˈriː.ə.laɪz/','[]','[]'),
('reduce','v.','減少','junior',3,'We should reduce waste.','我們應該減少浪費。','Actions','/rɪˈduːs/','[{"w":"reduction","p":"n.","n":"減少"}]','[]'),
('require','v.','需要','junior',3,'This job requires patience.','這工作需要耐心。','Actions','/rɪˈkwaɪr/','[{"w":"requirement","p":"n.","n":"要求"}]','[]'),
('respect','n.','尊重','junior',2,'Show respect to others.','對他人表示尊重。','Communication','/rɪˈspekt/','[{"w":"respectful","p":"adj.","n":"尊重的"}]','[]'),
('responsible','adj.','負責任的','junior',3,'He is a responsible person.','他是負責任的人。','Personality','/rɪˈspɑːn.sə.bəl/','[{"w":"responsibility","p":"n.","n":"責任"}]','[]'),
('result','n.','結果','junior',2,'What is the test result?','考試結果如何？','Basic','/rɪˈzʌlt/','[]','["as a result 結果"]'),
('separate','v.','分開','junior',3,'Separate the colors.','把顏色分開。','Actions','/ˈsep.ər.eɪt/','[]','[]'),
('similar','adj.','相似的','junior',3,'These two pictures are similar.','這兩張圖很相似。','Adjectives','/ˈsɪm.ə.lər/','[{"w":"similarity","p":"n.","n":"相似"}]','["similar to 與…相似"]'),
('situation','n.','情況','junior',3,'This is a difficult situation.','這是困難的情況。','Basic','/ˌsɪtʃ.uˈeɪ.ʃən/','[]','[]'),
('society','n.','社會','junior',3,'We live in a modern society.','我們生活在現代社會。','Society','/səˈsaɪ.ə.ti/','[{"w":"social","p":"adj.","n":"社會的"}]','[]'),
('suggest','v.','建議','junior',2,'I suggest you rest more.','我建議你多休息。','Communication','/səˈdʒest/','[{"w":"suggestion","p":"n.","n":"建議"}]','[]'),
('support','v.','支持','junior',2,'My family supports me.','我的家人支持我。','Actions','/səˈpɔːrt/','[{"w":"supportive","p":"adj.","n":"支持的"}]','[]');

-- ═══ SENIOR 高中 (Level 4-6) — 100 words ═════════════════════
INSERT INTO public.word_bank (word, pos, meaning, level, ceec_level, example, example_zh, category, phonetic, forms, collocations) VALUES
('abolish','v.','廢除','senior',4,'The law was abolished.','這條法律被廢除了。','Society','/əˈbɑː.lɪʃ/','[]','[]'),
('abstract','adj.','抽象的','senior',4,'Art can be abstract.','藝術可以是抽象的。','Art','/ˈæb.strækt/','[]','[]'),
('accommodate','v.','容納','senior',5,'The hotel can accommodate 200 guests.','這家旅館能容納200位客人。','Actions','/əˈkɑː.mə.deɪt/','[{"w":"accommodation","p":"n.","n":"住宿"}]','[]'),
('accumulate','v.','累積','senior',5,'He accumulated a fortune.','他累積了財富。','Actions','/əˈkjuː.mjə.leɪt/','[]','[]'),
('acknowledge','v.','承認','senior',5,'He acknowledged his mistake.','他承認了他的錯誤。','Communication','/əkˈnɑː.lɪdʒ/','[]','[]'),
('adequate','adj.','足夠的','senior',4,'We need adequate preparation.','我們需要充分的準備。','Adjectives','/ˈæd.ə.kwət/','[]','[]'),
('alleviate','v.','減輕','senior',5,'This medicine alleviates pain.','這藥可以減輕疼痛。','Health','/əˈliː.vi.eɪt/','[{"w":"alleviation","p":"n.","n":"減輕"}]','[]'),
('allocate','v.','分配','senior',6,'Resources were allocated fairly.','資源被公平分配。','Business','/ˈæl.ə.keɪt/','[{"w":"allocation","p":"n.","n":"分配"}]','[]'),
('ambiguous','adj.','模稜兩可的','senior',5,'The message was ambiguous.','這訊息模稜兩可。','Communication','/æmˈbɪɡ.ju.əs/','[{"w":"ambiguity","p":"n.","n":"模糊"}]','[]'),
('analyze','v.','分析','senior',4,'We need to analyze the data.','我們需要分析數據。','Science','/ˈæn.əl.aɪz/','[{"w":"analysis","p":"n.","n":"分析"},{"w":"analyst","p":"n.","n":"分析師"}]','[]'),
('anonymous','adj.','匿名的','senior',6,'The donor remained anonymous.','捐贈者保持匿名。','Society','/əˈnɑː.nɪ.məs/','[]','[]'),
('anticipate','v.','預期','senior',5,'We anticipate strong demand.','我們預期強勁需求。','Actions','/ænˈtɪs.ə.peɪt/','[{"w":"anticipation","p":"n.","n":"預期"}]','[]'),
('apparently','adv.','顯然','senior',4,'Apparently, he was right.','顯然，他是對的。','Basic','/əˈpær.ənt.li/','[{"w":"apparent","p":"adj.","n":"明顯的"}]','[]'),
('appropriate','adj.','適當的','senior',4,'Use appropriate language.','使用適當的語言。','Adjectives','/əˈproʊ.pri.ət/','[]','[]'),
('approximately','adv.','大約','senior',4,'Approximately 100 people came.','大約100人來了。','Basic','/əˈprɑːk.sɪ.mət.li/','[{"w":"approximate","p":"adj.","n":"大約的"}]','[]'),
('associate','v.','聯想','senior',4,'I associate summer with vacation.','我把夏天和假期聯想在一起。','Actions','/əˈsoʊ.ʃi.eɪt/','[{"w":"association","p":"n.","n":"聯想；協會"}]','[]'),
('assumption','n.','假設','senior',5,'That is a wrong assumption.','那是錯誤的假設。','Academic','/əˈsʌmp.ʃən/','[{"w":"assume","p":"v.","n":"假設"}]','[]'),
('authentic','adj.','真正的','senior',5,'This is an authentic painting.','這是一幅真跡。','Art','/ɔːˈθen.tɪk/','[]','[]'),
('bureaucracy','n.','官僚體制','senior',6,'The bureaucracy slows things down.','官僚體制使事情變慢。','Society','/bjʊˈrɑː.krə.si/','[]','[]'),
('catastrophe','n.','大災難','senior',6,'The earthquake was a catastrophe.','地震是一場大災難。','Nature','/kəˈtæs.trə.fi/','[{"w":"catastrophic","p":"adj.","n":"災難性的"}]','[]'),
('chronic','adj.','慢性的','senior',5,'She has chronic pain.','她有慢性疼痛。','Health','/ˈkrɑː.nɪk/','[]','[]'),
('circumstance','n.','情況','senior',4,'Under the circumstances, we had no choice.','在這種情況下，我們別無選擇。','Basic','/ˈsɜːr.kəm.stæns/','[]','["under the circumstances 在此情況下"]'),
('collaborate','v.','合作','senior',5,'Scientists collaborated on the project.','科學家合作進行這個計畫。','Actions','/kəˈlæb.ə.reɪt/','[{"w":"collaboration","p":"n.","n":"合作"}]','[]'),
('compensate','v.','補償','senior',5,'The company compensated the workers.','公司補償了工人。','Business','/ˈkɑːm.pen.seɪt/','[{"w":"compensation","p":"n.","n":"補償"}]','[]'),
('comprehensive','adj.','全面的','senior',4,'A comprehensive report.','一份全面的報告。','Academic','/ˌkɑːm.prɪˈhen.sɪv/','[{"w":"comprehension","p":"n.","n":"理解力"}]','[]'),
('compromise','n.','妥協','senior',5,'We reached a compromise.','我們達成了妥協。','Communication','/ˈkɑːm.prə.maɪz/','[]','[]'),
('consecutive','adj.','連續的','senior',6,'He won three consecutive games.','他連勝三場。','Basic','/kənˈsek.jə.tɪv/','[]','[]'),
('consequence','n.','後果','senior',4,'Every action has consequences.','每個行動都有後果。','Basic','/ˈkɑːn.sə.kwens/','[{"w":"consequently","p":"adv.","n":"因此"}]','[]'),
('conservative','adj.','保守的','senior',5,'A conservative approach.','保守的做法。','Society','/kənˈsɜːr.və.tɪv/','[]','[]'),
('constitute','v.','構成','senior',6,'Women constitute 50% of the population.','女性構成了50%的人口。','Academic','/ˈkɑːn.stə.tuːt/','[{"w":"constitution","p":"n.","n":"憲法"}]','[]'),
('contemporary','adj.','當代的','senior',5,'Contemporary art museum.','當代藝術博物館。','Art','/kənˈtem.pə.rer.i/','[]','[]'),
('controversy','n.','爭議','senior',4,'The policy caused controversy.','這項政策引起爭議。','Society','/ˈkɑːn.trə.vɜːr.si/','[{"w":"controversial","p":"adj.","n":"有爭議的"}]','[]'),
('correlation','n.','相關性','senior',6,'There is a strong correlation.','有強烈的相關性。','Science','/ˌkɔːr.əˈleɪ.ʃən/','[]','[]'),
('criterion','n.','標準','senior',5,'What is the main criterion?','主要標準是什麼？','Academic','/kraɪˈtɪr.i.ən/','[{"w":"criteria","p":"n.","n":"複數"}]','[]'),
('crucial','adj.','關鍵的','senior',4,'This is a crucial moment.','這是關鍵時刻。','Adjectives','/ˈkruː.ʃəl/','[]','[]'),
('deliberate','adj.','故意的','senior',5,'It was a deliberate choice.','這是故意的選擇。','Adjectives','/dɪˈlɪb.ər.ət/','[{"w":"deliberately","p":"adv.","n":"故意地"}]','[]'),
('demonstrate','v.','示範','senior',4,'She demonstrated the technique.','她示範了這個技巧。','Actions','/ˈdem.ən.streɪt/','[{"w":"demonstration","p":"n.","n":"示範"}]','[]'),
('deteriorate','v.','惡化','senior',5,'His health deteriorated.','他的健康惡化了。','Health','/dɪˈtɪr.i.ə.reɪt/','[{"w":"deterioration","p":"n.","n":"惡化"}]','[]'),
('dilemma','n.','兩難','senior',5,'I face a difficult dilemma.','我面臨困難的兩難。','Basic','/dɪˈlem.ə/','[]','[]'),
('diminish','v.','減少','senior',5,'The pain gradually diminished.','疼痛逐漸減少。','Actions','/dɪˈmɪn.ɪʃ/','[]','[]'),
('discrimination','n.','歧視','senior',5,'Discrimination is wrong.','歧視是錯誤的。','Society','/dɪˌskrɪm.ɪˈneɪ.ʃən/','[{"w":"discriminate","p":"v.","n":"歧視"}]','[]'),
('disproportionate','adj.','不成比例的','senior',6,'A disproportionate response.','不成比例的反應。','Academic','/ˌdɪs.prəˈpɔːr.ʃən.ət/','[]','[]'),
('elaborate','adj.','精心的','senior',5,'An elaborate plan.','精心的計畫。','Adjectives','/ɪˈlæb.ər.ət/','[]','[]'),
('eliminate','v.','消除','senior',4,'We must eliminate waste.','我們必須消除浪費。','Actions','/ɪˈlɪm.ɪ.neɪt/','[{"w":"elimination","p":"n.","n":"消除"}]','[]'),
('embrace','v.','擁抱；接受','senior',5,'Embrace change.','擁抱改變。','Actions','/ɪmˈbreɪs/','[]','[]'),
('emerge','v.','浮現','senior',4,'New evidence emerged.','新證據浮現了。','Actions','/ɪˈmɜːrdʒ/','[{"w":"emergence","p":"n.","n":"浮現"}]','[]'),
('enormous','adj.','巨大的','senior',4,'An enormous building.','一棟巨大的建築。','Adjectives','/ɪˈnɔːr.məs/','[]','[]'),
('epidemic','n.','流行病','senior',5,'A flu epidemic.','流感流行病。','Health','/ˌep.ɪˈdem.ɪk/','[]','[]'),
('equivalent','adj.','等同的','senior',5,'One dollar is equivalent to 30 NT.','一美元等同於30台幣。','Basic','/ɪˈkwɪv.əl.ənt/','[]','[]'),
('erode','v.','侵蝕','senior',6,'The coast is being eroded.','海岸正被侵蝕。','Nature','/ɪˈroʊd/','[{"w":"erosion","p":"n.","n":"侵蝕"}]','[]'),
('ethical','adj.','倫理的','senior',5,'An ethical question.','一個倫理問題。','Society','/ˈeθ.ɪ.kəl/','[{"w":"ethics","p":"n.","n":"倫理學"}]','[]'),
('exaggerate','v.','誇大','senior',5,'Do not exaggerate.','不要誇大。','Communication','/ɪɡˈzædʒ.ə.reɪt/','[]','[]'),
('exploit','v.','利用；剝削','senior',5,'Companies exploit workers.','公司剝削工人。','Society','/ɪkˈsplɔɪt/','[{"w":"exploitation","p":"n.","n":"剝削"}]','[]'),
('facilitate','v.','促進','senior',4,'Technology facilitates learning.','科技促進學習。','Actions','/fəˈsɪl.ɪ.teɪt/','[{"w":"facilitator","p":"n.","n":"引導者"}]','[]'),
('fluctuate','v.','波動','senior',6,'Prices fluctuate daily.','價格每天波動。','Business','/ˈflʌk.tʃu.eɪt/','[{"w":"fluctuation","p":"n.","n":"波動"}]','[]'),
('formulate','v.','制定','senior',5,'Formulate a plan.','制定計畫。','Actions','/ˈfɔːr.mjə.leɪt/','[]','[]'),
('fundamental','adj.','基本的','senior',4,'A fundamental problem.','一個根本問題。','Academic','/ˌfʌn.dəˈmen.təl/','[{"w":"fundamentally","p":"adv.","n":"根本地"}]','[]'),
('genuine','adj.','真正的','senior',4,'A genuine smile.','真誠的微笑。','Adjectives','/ˈdʒen.ju.ɪn/','[]','[]'),
('hierarchy','n.','階層','senior',6,'The company hierarchy.','公司階層。','Business','/ˈhaɪ.ə.rɑːr.ki/','[]','[]'),
('hypothesis','n.','假說','senior',5,'Test the hypothesis.','測試假說。','Science','/haɪˈpɑː.θə.sɪs/','[{"w":"hypothetical","p":"adj.","n":"假設的"}]','[]'),
('ideology','n.','意識形態','senior',6,'Political ideology.','政治意識形態。','Society','/ˌaɪ.diˈɑː.lə.dʒi/','[]','[]'),
('immense','adj.','巨大的','senior',5,'Immense pressure.','巨大的壓力。','Adjectives','/ɪˈmens/','[]','[]'),
('implement','v.','實施','senior',4,'Implement the new policy.','實施新政策。','Actions','/ˈɪm.plə.ment/','[{"w":"implementation","p":"n.","n":"實施"}]','[]'),
('implication','n.','暗示；影響','senior',5,'The implications are serious.','影響很嚴重。','Academic','/ˌɪm.plɪˈkeɪ.ʃən/','[{"w":"imply","p":"v.","n":"暗示"}]','[]'),
('incorporate','v.','納入','senior',5,'Incorporate new ideas.','納入新想法。','Actions','/ɪnˈkɔːr.pə.reɪt/','[]','[]'),
('indigenous','adj.','原住民的','senior',6,'Indigenous cultures.','原住民文化。','Society','/ɪnˈdɪdʒ.ən.əs/','[]','[]'),
('inevitable','adj.','不可避免的','senior',5,'Change is inevitable.','改變是不可避免的。','Adjectives','/ɪnˈev.ɪ.tə.bəl/','[{"w":"inevitably","p":"adv.","n":"不可避免地"}]','[]'),
('infrastructure','n.','基礎設施','senior',6,'Modern infrastructure.','現代基礎設施。','Society','/ˈɪn.frə.strʌk.tʃər/','[]','[]'),
('innovation','n.','創新','senior',5,'Technological innovation.','科技創新。','Technology','/ˌɪn.əˈveɪ.ʃən/','[{"w":"innovative","p":"adj.","n":"創新的"},{"w":"innovate","p":"v.","n":"創新"}]','[]'),
('integrate','v.','整合','senior',5,'Integrate different systems.','整合不同的系統。','Actions','/ˈɪn.tə.ɡreɪt/','[{"w":"integration","p":"n.","n":"整合"}]','[]'),
('integrity','n.','正直','senior',6,'A person of integrity.','正直的人。','Personality','/ɪnˈteɡ.rə.ti/','[]','[]'),
('legitimate','adj.','合法的','senior',5,'A legitimate concern.','合理的擔憂。','Society','/lɪˈdʒɪt.ɪ.mət/','[]','[]'),
('mechanism','n.','機制','senior',5,'A defense mechanism.','防衛機制。','Science','/ˈmek.ə.nɪ.zəm/','[]','[]'),
('phenomenon','n.','現象','senior',4,'A natural phenomenon.','自然現象。','Science','/fɪˈnɑː.mə.nɑːn/','[{"w":"phenomena","p":"n.","n":"複數"}]','[]'),
('pragmatic','adj.','務實的','senior',6,'A pragmatic approach.','務實的做法。','Personality','/præɡˈmæt.ɪk/','[]','[]'),
('predominant','adj.','主要的','senior',6,'The predominant opinion.','主流意見。','Academic','/prɪˈdɑː.mɪ.nənt/','[{"w":"predominantly","p":"adv.","n":"主要地"}]','[]'),
('profound','adj.','深刻的','senior',5,'A profound impact.','深刻的影響。','Adjectives','/prəˈfaʊnd/','[]','[]'),
('resilient','adj.','有韌性的','senior',6,'Children are resilient.','孩子是有韌性的。','Personality','/rɪˈzɪl.i.ənt/','[{"w":"resilience","p":"n.","n":"韌性"}]','[]'),
('rhetoric','n.','修辭','senior',6,'Political rhetoric.','政治修辭。','Communication','/ˈret.ər.ɪk/','[]','[]'),
('simultaneously','adv.','同時地','senior',5,'Events happened simultaneously.','事件同時發生。','Basic','/ˌsaɪ.məlˈteɪ.ni.əs.li/','[{"w":"simultaneous","p":"adj.","n":"同時的"}]','[]'),
('skeptical','adj.','懷疑的','senior',5,'I am skeptical about this.','我對此持懷疑態度。','Personality','/ˈskep.tɪ.kəl/','[]','[]'),
('sophisticated','adj.','精密的','senior',4,'Sophisticated technology.','精密的科技。','Technology','/səˈfɪs.tɪ.keɪ.tɪd/','[{"w":"sophistication","p":"n.","n":"精密"}]','[]'),
('sovereignty','n.','主權','senior',6,'National sovereignty.','國家主權。','Society','/ˈsɑːv.rən.ti/','[]','[]'),
('stimulate','v.','刺激','senior',5,'Exercise stimulates the brain.','運動刺激大腦。','Science','/ˈstɪm.jə.leɪt/','[{"w":"stimulus","p":"n.","n":"刺激"}]','[]'),
('substantial','adj.','大量的','senior',4,'A substantial amount.','大量的。','Adjectives','/səbˈstæn.ʃəl/','[{"w":"substantially","p":"adv.","n":"大幅地"}]','[]'),
('sustainable','adj.','可持續的','senior',4,'Sustainable development.','永續發展。','Environment','/səˈsteɪ.nə.bəl/','[{"w":"sustainability","p":"n.","n":"可持續性"}]','[]'),
('sympathy','n.','同情','senior',4,'I have sympathy for them.','我同情他們。','Feelings','/ˈsɪm.pə.θi/','[{"w":"sympathetic","p":"adj.","n":"同情的"}]','[]'),
('tentative','adj.','暫定的','senior',6,'A tentative plan.','暫定的計畫。','Adjectives','/ˈten.tə.tɪv/','[]','[]'),
('transparent','adj.','透明的','senior',5,'A transparent process.','透明的流程。','Adjectives','/trænˈspær.ənt/','[{"w":"transparency","p":"n.","n":"透明度"}]','[]'),
('unanimous','adj.','一致的','senior',6,'A unanimous decision.','一致的決定。','Basic','/juˈnæn.ə.məs/','[]','[]'),
('undermine','v.','破壞','senior',5,'This undermines trust.','這破壞了信任。','Actions','/ˌʌn.dərˈmaɪn/','[]','[]'),
('unprecedented','adj.','史無前例的','senior',4,'Unprecedented challenges.','史無前例的挑戰。','Adjectives','/ʌnˈpres.ə.den.tɪd/','[{"w":"precedent","p":"n.","n":"先例"}]','[]'),
('vulnerable','adj.','脆弱的','senior',5,'Children are vulnerable.','孩子是脆弱的。','Adjectives','/ˈvʌl.nər.ə.bəl/','[{"w":"vulnerability","p":"n.","n":"脆弱性"}]','[]')
ON CONFLICT (word, level) DO NOTHING;
