-- Elementary watercolor illustrations, batch 4. Upload assets before metadata.
BEGIN;
INSERT INTO public.word_illustrations (id, level, word, sort_order, sense, alt_zh, example, example_zh, image_url, local_path, style, version) VALUES
('elementary-rabbit-01-v1', 'elementary', 'rabbit', 1, '兔子', '一隻有長耳朵與短尾巴的白兔坐在地上。', 'The rabbit has long ears.', '這隻兔子有長長的耳朵。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/rabbit-01-v1.webp', '/images/vocabulary/elementary/rabbit-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-turtle-01-v1', 'elementary', 'turtle', 1, '烏龜', '一隻背著綠褐色龜殼的烏龜站在地上。', 'The turtle has a hard shell.', '這隻烏龜有堅硬的殼。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/turtle-01-v1.webp', '/images/vocabulary/elementary/turtle-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-bear-01-v1', 'elementary', 'bear', 1, '熊', '一隻棕熊用四隻腳站在地上。', 'The bear has brown fur.', '這隻熊有棕色的毛。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/bear-01-v1.webp', '/images/vocabulary/elementary/bear-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-elephant-01-v1', 'elementary', 'elephant', 1, '大象', '一隻灰色大象有大耳朵和微微捲起的長鼻子。', 'The elephant has a long trunk.', '這隻大象有長長的鼻子。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/elephant-01-v1.webp', '/images/vocabulary/elementary/elephant-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-bus-01-v1', 'elementary', 'bus', 1, '公車', '一輛有大車窗與前門的黃色公車。', 'The yellow bus has many seats.', '這輛黃色公車有很多座位。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/bus-01-v1.webp', '/images/vocabulary/elementary/bus-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-bike-01-v1', 'elementary', 'bike', 1, '腳踏車', '一輛有兩個輪子、棕色坐墊與踏板的藍綠色腳踏車。', 'My bike has two wheels.', '我的腳踏車有兩個輪子。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/bike-01-v1.webp', '/images/vocabulary/elementary/bike-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-car-01-v1', 'elementary', 'car', 1, '汽車', '一輛有車窗、車燈和黑色輪胎的紅色小汽車。', 'This little car is red.', '這輛小汽車是紅色的。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/car-01-v1.webp', '/images/vocabulary/elementary/car-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-cake-01-v1', 'elementary', 'cake', 1, '蛋糕', '一個有白色鮮奶油和草莓的蛋糕，旁邊放著切下的一片。', 'There are strawberries on the cake.', '蛋糕上有草莓。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/cake-01-v1.webp', '/images/vocabulary/elementary/cake-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-sun-01-v1', 'elementary', 'sun', 1, '太陽', '金黃色的太陽散發光芒，下方有少許淡藍色雲朵。', 'The sun shines in the sky.', '太陽在天空中發光。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/sun-01-v1.webp', '/images/vocabulary/elementary/sun-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-moon-01-v1', 'elementary', 'moon', 1, '月亮', '圓圓的月亮掛在深藍色夜空中，周圍有三顆小星星。', 'The moon is round tonight.', '今晚的月亮是圓的。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/moon-01-v1.webp', '/images/vocabulary/elementary/moon-01-v1.webp', 'watercolor-pencil-v1', 1)
ON CONFLICT (id) DO NOTHING;
COMMIT;
