-- Batch 14: upload assets before metadata.
BEGIN;
INSERT INTO public.word_illustrations (id, level, word, sort_order, sense, alt_zh, example, example_zh, image_url, local_path, style, version) VALUES
('elementary-body-01-v1', 'elementary', 'body', 1, '身體', '一名穿著青綠色上衣和赭色短褲的孩子自然站立，從頭到腳都清楚可見。', 'Exercise keeps my body strong for sports day.', '運動讓我的身體在運動會時保持強壯。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/body-01-v1.webp', '/images/vocabulary/elementary/body-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-tooth-01-v1', 'elementary', 'tooth', 1, '牙齒', '一顆小小的白色乳牙放在孩子張開的手掌上，後方有微笑的臉部。', 'My loose tooth falls out after dinner.', '我的鬆動牙齒在晚餐後掉了。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/tooth-01-v1.webp', '/images/vocabulary/elementary/tooth-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-neck-01-v1', 'elementary', 'neck', 1, '脖子', '孩子微笑著用手指輕輕指向下巴與衣領之間的脖子。', 'Wear a scarf around your neck on a cold morning.', '寒冷的早晨把圍巾圍在脖子上。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/neck-01-v1.webp', '/images/vocabulary/elementary/neck-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-shoulder-01-v1', 'elementary', 'shoulder', 1, '肩膀', '孩子從背後伸手觸碰肩膀，清楚呈現肩膀與上臂的連接處。', 'The school bag feels heavy on my shoulder.', '書包背在肩膀上感覺很重。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/shoulder-01-v1.webp', '/images/vocabulary/elementary/shoulder-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-finger-01-v1', 'elementary', 'finger', 1, '手指', '一隻手豎起食指，其他手指自然彎曲。', 'Point to each word with your finger as you read.', '閱讀時用手指指著每一個單字。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/finger-01-v1.webp', '/images/vocabulary/elementary/finger-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-heart-01-v1', 'elementary', 'heart', 1, '心臟；心', '一顆粉紅紅色的人體心臟，帶有幾條紅色與藍色血管。', 'My heart beats fast before I speak on stage.', '上台說話前，我的心跳得很快。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/heart-01-v1.webp', '/images/vocabulary/elementary/heart-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-stomach-01-v1', 'elementary', 'stomach', 1, '胃；肚子', '一個簡化的粉紅色胃部器官連接食道與小腸。', 'My stomach hurts when I eat too quickly.', '我吃太快時肚子會痛。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/stomach-01-v1.webp', '/images/vocabulary/elementary/stomach-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-knee-01-v1', 'elementary', 'knee', 1, '膝蓋', '孩子彎曲腿部，另一隻手指向膝蓋關節。', 'I put a bandage on my knee after I fall.', '我跌倒後在膝蓋貼上OK繃。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/knee-01-v1.webp', '/images/vocabulary/elementary/knee-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-doctor-01-v1', 'elementary', 'doctor', 1, '醫生', '醫生用聽診器為坐著的孩子檢查心跳。', 'The doctor checks my throat when I am sick.', '我生病時醫生檢查我的喉嚨。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/doctor-01-v1.webp', '/images/vocabulary/elementary/doctor-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-nurse-01-v1', 'elementary', 'nurse', 1, '護士', '護理師在孩子的手肘上貼一小片繃帶。', 'The nurse puts a bandage on my knee.', '護士在我的膝蓋貼上繃帶。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/nurse-01-v1.webp', '/images/vocabulary/elementary/nurse-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-medicine-01-v1', 'elementary', 'medicine', 1, '藥物', '大人陪著孩子用湯匙服用藥水，旁邊有無標籤的藥瓶。', 'Take the medicine after dinner, the doctor says.', '醫生說晚餐後吃藥。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/medicine-01-v1.webp', '/images/vocabulary/elementary/medicine-01-v1.webp', 'watercolor-pencil-v1', 1),
('elementary-headache-01-v1', 'elementary', 'headache', 1, '頭痛', '孩子閉著眼睛、雙手放在太陽穴旁，表現出頭痛不適。', 'I have a headache, so I rest in the nurse''s office.', '我頭痛，所以在保健室休息。', 'https://jbspxqebcrkilfcddluo.supabase.co/storage/v1/object/public/word-illustrations/elementary/headache-01-v1.webp', '/images/vocabulary/elementary/headache-01-v1.webp', 'watercolor-pencil-v1', 1)
ON CONFLICT (id) DO UPDATE SET level = EXCLUDED.level, word = EXCLUDED.word, sort_order = EXCLUDED.sort_order, sense = EXCLUDED.sense, alt_zh = EXCLUDED.alt_zh, example = EXCLUDED.example, example_zh = EXCLUDED.example_zh, image_url = EXCLUDED.image_url, local_path = EXCLUDED.local_path, style = EXCLUDED.style, version = EXCLUDED.version;
COMMIT;
