-- EnglishGo - Update elementary supplemental word examples
-- Generated from src/data/extraWords.js
-- Safe to re-run: updates only public.word_bank supplemental elementary rows.

UPDATE public.word_bank AS wb
SET example = v.example,
    example_zh = v.example_zh
FROM (VALUES
('about','This story is about a brave girl.','這個故事是關於一個勇敢的女孩。'),
('after','We play games after English class.','英文課後我們玩遊戲。'),
('afternoon','In the afternoon, we play word games.','下午我們玩單字遊戲。'),
('again','Please read the sentence again.','請再讀一次這個句子。'),
('alive','The forest feels alive after the magic returns.','魔法回來後，森林充滿生命力。'),
('all','All the students listen to the story.','所有學生都聽這個故事。'),
('alone','Lily is not alone because Coco helps her.','莉莉並不孤單，因為可可幫助她。'),
('amazing','The amazing crystal shines like a star.','驚人的水晶像星星一樣發光。'),
('ancient','Ancient stones stand near the hidden cave.','古老的石頭立在隱藏洞穴旁。'),
('and','I read and write after school.','我放學後閱讀和書寫。'),
('answer','She answers the question in English.','她用英文回答問題。'),
('any','Do you have any questions after class?','下課後你有任何問題嗎？'),
('april','April rain helps the grass grow.','四月的雨幫助草生長。'),
('arm','She carries the doll in her arm.','她用手臂抱著娃娃。'),
('art','In art class, we draw colorful flowers.','美術課時，我們畫彩色花朵。'),
('ask','I ask my teacher for help.','我向老師請求幫助。'),
('august','August days are hot and bright.','八月的日子又熱又明亮。'),
('baby','The baby smiles when we sing softly.','我們輕聲唱歌時，寶寶微笑了。'),
('bad','Bad weather keeps us inside today.','今天的壞天氣讓我們待在室內。'),
('bag','My school bag is heavy today.','我的書包今天很重。'),
('balance','The small shadow finds balance with the light.','小影子在光中找到平衡。'),
('banana','A monkey eats a banana in the zoo.','猴子在動物園吃香蕉。'),
('baseball','My brother watches baseball with Dad.','我哥哥和爸爸看棒球。'),
('basketball','We play basketball on the playground.','我們在操場打籃球。'),
('bathroom','I wash my face in the bathroom.','我在浴室洗臉。'),
('beach','We build a sand house on the beach.','我們在海灘上蓋沙屋。'),
('bear','The bear sits beside a tall tree.','熊坐在高樹旁。'),
('beautiful','A beautiful rainbow appears after the rain.','雨後出現一道美麗的彩虹。'),
('because','I smile because I know the answer.','我微笑，因為我知道答案。'),
('bed','I put my doll on the bed.','我把娃娃放在床上。'),
('bedroom','I read a book in my bedroom.','我在臥室讀書。'),
('bee','A bee flies around the yellow flower.','蜜蜂繞著黃色花朵飛。'),
('beef','The beef noodles smell very good.','牛肉麵聞起來很香。'),
('before','Wash your hands before lunch.','午餐前洗手。'),
('begin','The story begins in a quiet forest.','故事從一座安靜的森林開始。'),
('behind','The cat hides behind the sofa.','貓躲在沙發後面。'),
('beneath','A shining key waits beneath the water.','一把發亮的鑰匙在水下等待。'),
('beside','The ball is beside the door.','球在門旁邊。'),
('between','The desk is between two chairs.','書桌在兩張椅子中間。'),
('bike','I ride my bike to the library.','我騎腳踏車去圖書館。'),
('bird','A bird sings in the tree every morning.','一隻鳥每天早上在樹上唱歌。'),
('black','My black pen is on the desk.','我的黑筆在書桌上。'),
('blue','The blue bag is under the chair.','藍色的書包在椅子下面。'),
('both','Both sisters like to read at night.','兩個姊妹都喜歡晚上閱讀。'),
('bottom','The bell is at the bottom of the river.','鈴鐺在河底。'),
('boy','The boy asks a question in English.','那個男孩用英文問問題。'),
('branch','A long branch helps Lily reach the bell.','長樹枝幫助莉莉拿到鈴鐺。'),
('brave','The brave child speaks in front of the class.','勇敢的孩子在全班面前說話。'),
('bread','She puts an egg on the bread.','她把蛋放在麵包上。'),
('breakfast','Breakfast gives me energy for school.','早餐給我上學的精神。'),
('brother','My brother rides his bike to the park.','我兄弟騎腳踏車去公園。'),
('brown','The brown dog runs beside me.','那隻棕色的狗在我旁邊跑。'),
('brush','I brush my teeth before I sleep.','我睡覺前刷牙。'),
('bus','The bus comes at seven thirty.','公車七點半來。'),
('but','The test is hard, but I try.','測驗很難，但我會嘗試。'),
('buy','We buy fruit at the market.','我們在市場買水果。'),
('by','Lily sits by the quiet river.','莉莉坐在安靜河流旁。'),
('cake','We share a cake at the birthday party.','我們在生日派對分享蛋糕。'),
('call','Call your dad when you get home.','到家時打電話給爸爸。'),
('candy','I keep one candy in my bag.','我在書包裡放一顆糖果。'),
('cap','He wears a cap at the baseball game.','他在棒球比賽時戴帽子。'),
('car','The red car stops near the school.','紅色車子停在學校附近。'),
('carrot','The rabbit eats a carrot near the tree.','兔子在樹旁吃紅蘿蔔。'),
('carry','He carries a heavy bag to school.','他背著很重的書包去上學。'),
('cat','The cat likes to sleep on the sofa.','貓喜歡睡在沙發上。'),
('cave','The hidden cave is behind the rock wall.','隱藏洞穴在岩壁後面。'),
('chair','A blue bag is under the chair.','藍色書包在椅子下面。'),
('chicken','A chicken walks near the farm gate.','一隻雞走在農場大門旁。'),
('child','The child draws a flower on the page.','那個小孩在頁面上畫一朵花。'),
('children','The children play games after class.','孩子們下課後玩遊戲。'),
('chocolate','I eat chocolate only after dinner.','我只有晚餐後才吃巧克力。'),
('choose','Choose the moon stone to open the path.','選擇月亮石來打開道路。'),
('class','Our class reads together every Friday.','我們班每週五一起閱讀。'),
('classroom','Our classroom has a big window.','我們的教室有一扇大窗戶。'),
('claw','A dark claw reaches toward the crystal.','一隻黑色爪子伸向水晶。'),
('clean','Please keep your desk clean after lunch.','午餐後請保持你的書桌乾淨。'),
('close','Close the window when the wind is strong.','風很大時把窗戶關上。'),
('cloud','A white cloud moves across the sky.','一朵白雲飄過天空。'),
('coat','I need a coat on a cold night.','寒冷的夜晚我需要外套。'),
('cold','I wear a jacket on a cold morning.','寒冷的早晨我會穿夾克。'),
('come','Please come to the classroom before class.','請在上課前來教室。'),
('complete','I complete my homework before dinner.','我在晚餐前完成作業。'),
('computer','We use a computer to listen to the story.','我們用電腦聽故事。'),
('cook','My dad cooks soup in the kitchen.','我爸爸在廚房煮湯。'),
('cookie','The cookie is sweet and small.','這片餅乾又甜又小。'),
('cool','A cool wind blows after the rain.','雨後吹來一陣涼爽的風。'),
('corn','We put corn in the soup.','我們把玉米放進湯裡。'),
('courage','Lily''s courage helps her face the shadow.','莉莉的勇氣幫助她面對影子。'),
('cow','The cow eats grass on the farm.','牛在農場吃草。'),
('cry','The baby cries when he is hungry.','寶寶餓的時候會哭。'),
('crystal','The crystal shines in the hidden cave.','水晶在隱藏洞穴中發光。'),
('curious','The curious girl opens the old book carefully.','好奇的女孩小心地打開那本舊書。'),
('cute','The cute puppy follows the girl home.','那隻可愛的小狗跟著女孩回家。'),
('dad','Dad plays basketball with me on Sunday.','爸爸星期日和我打籃球。'),
('dance','The children dance when the music starts.','音樂開始時孩子們跳舞。'),
('day','A sunny day is good for a picnic.','晴天很適合野餐。'),
('december','December nights are cold and quiet.','十二月的夜晚寒冷又安靜。'),
('desk','My pencil is beside the desk.','我的鉛筆在書桌旁。'),
('destroy','The shadow wants to destroy the forest magic.','影子想破壞森林魔法。'),
('different','These two pictures show different animals.','這兩張圖片展示不同的動物。'),
('dinner','We talk about our day at dinner.','我們在晚餐時聊今天的事。'),
('dirty','My shoes are dirty after playing soccer.','我踢完足球後鞋子很髒。'),
('disappear','The shadow disappears when the light shines.','光照耀時影子消失了。'),
('dive','The frog can dive into the cool water.','青蛙可以潛入涼涼的水中。'),
('dog','My dog runs with me in the park.','我的狗和我在公園裡跑。'),
('doll','My little sister plays with a doll.','我的妹妹玩娃娃。'),
('door','Please close the door quietly.','請輕輕關門。'),
('down','Put the box down beside the table.','把盒子放在桌子旁邊。'),
('draw','Draw a small bird in your notebook.','在筆記本裡畫一隻小鳥。'),
('dress','She wears a yellow dress to the party.','她穿黃色洋裝去派對。'),
('drink','I drink water after I play soccer.','我踢足球後喝水。'),
('drive','My father drives carefully on rainy days.','下雨天我爸爸小心開車。'),
('duck','The duck swims across the pond.','鴨子游過池塘。'),
('each','Each page has one new sentence.','每一頁都有一個新句子。'),
('ear','I listen with my left ear.','我用左耳聽。'),
('early','I get to school early on Monday.','星期一我很早到學校。'),
('easy','This easy sentence helps me read faster.','這個簡單的句子幫助我讀得更快。'),
('echo','Lily hears an echo inside the cave.','莉莉在洞穴裡聽見回音。'),
('edge','Lily stands at the edge of the forest.','莉莉站在森林邊緣。'),
('egg','There is one egg in my lunch box.','我的便當盒裡有一顆蛋。'),
('eight','I wake up at eight on Sunday.','我星期日八點起床。'),
('eighteen','Eighteen players stand on the field.','十八位球員站在場上。'),
('elephant','The elephant uses its long nose.','大象使用牠長長的鼻子。'),
('eleven','Eleven children sing in the classroom.','十一個孩子在教室裡唱歌。'),
('entrance','The cave entrance is cold and dark.','洞穴入口又冷又暗。'),
('eraser','I use an eraser to fix my mistake.','我用橡皮擦修正錯誤。'),
('evening','In the evening, Dad reads with me.','晚上爸爸和我一起閱讀。'),
('every','Every child gets a book today.','今天每個孩子都拿到一本書。'),
('everyone','Everyone claps after the song ends.','歌曲結束後每個人都拍手。'),
('evil','The evil shadow tries to steal the light.','邪惡的影子想偷走光。'),
('explore','Lily explores the forest after school.','莉莉放學後探索森林。'),
('eye','Close one eye and look at the picture.','閉上一隻眼睛看這張圖片。'),
('face','I wash my face every morning.','我每天早上洗臉。'),
('fairy','A little fairy hides under a mushroom.','一位小精靈躲在蘑菇下面。'),
('family','My family eats dinner together at home.','我的家人在家一起吃晚餐。'),
('farm','The farm has cows, pigs, and ducks.','農場裡有牛、豬和鴨子。'),
('fast','The bus is fast in the morning.','早上的公車開得很快。'),
('father','My father drives us to the zoo.','我爸爸開車帶我們去動物園。'),
('favorite','My favorite animal is the elephant.','我最喜歡的動物是大象。'),
('february','February has many cool days.','二月有許多涼爽的日子。'),
('feet','My feet are tired after the long walk.','走了很久後我的腳很累。'),
('few','A few birds fly over the playground.','幾隻鳥飛過操場。'),
('fifteen','I practice English for fifteen minutes.','我練習英文十五分鐘。'),
('fifty','Grandma is fifty years old.','奶奶五十歲。'),
('find','I find my pencil under the desk.','我在書桌下面找到鉛筆。'),
('finish','I finish my homework before I play.','我玩之前先完成作業。'),
('first','Read the first sentence on the page.','讀頁面上的第一個句子。'),
('fish','The fish swims in the blue river.','魚在藍色河裡游泳。'),
('five','We learn five words today.','我們今天學五個單字。'),
('flower','The flower opens in the warm sun.','花在溫暖的陽光下綻放。'),
('fly','Birds fly high in the blue sky.','鳥兒在藍天中高飛。'),
('foot','Put your right foot on the line.','把你的右腳放在線上。'),
('for','This card is for my mother.','這張卡片是給媽媽的。'),
('force','Do not use force to open the old gate.','不要用力量打開舊大門。'),
('forest','The forest is full of tall trees.','森林裡滿是高大的樹。'),
('forty','The story has forty words.','這篇故事有四十個字。'),
('four','Four students answer the question.','四位學生回答問題。'),
('fourteen','Fourteen students read the story aloud.','十四位學生大聲讀故事。'),
('friday','Friday is a good day for songs.','星期五很適合唱歌。'),
('from','This letter is from my teacher.','這封信來自我的老師。'),
('fruit','Fruit is a healthy snack after class.','水果是下課後健康的點心。'),
('full','I am full after eating noodles for lunch.','午餐吃完麵後我很飽。'),
('funny','The funny story makes everyone laugh.','那個好笑的故事讓大家都笑了。'),
('game','The word game helps us learn quickly.','單字遊戲幫助我們快速學習。'),
('gate','The old gate opens with the moon key.','舊大門用月之鑰匙打開。'),
('gentle','A gentle voice comes from the tree.','一個溫柔的聲音從樹裡傳來。'),
('get','I get a new book from the library.','我從圖書館拿到一本新書。'),
('girl','The girl carries a pink school bag.','那個女孩背著粉紅色書包。'),
('give','Please give the pencil to your sister.','請把鉛筆給你的姊妹。'),
('glow','The magic leaf glows in Lily''s hand.','魔法葉子在莉莉手中發光。'),
('go','I go to school by bus every day.','我每天搭公車去上學。'),
('good','You did a good job on the reading test.','你在閱讀測驗中表現得很好。'),
('grass','The rabbit hops across the grass.','兔子跳過草地。'),
('gray','Gray clouds cover the mountain.','灰色的雲遮住了山。'),
('green','Green leaves grow on the tree.','綠色的葉子長在樹上。'),
('guide','The Light Leaf guides Lily through the forest.','光之葉引導莉莉穿過森林。'),
('hair','My hair is wet after I wash it.','我洗完頭後頭髮是濕的。'),
('hamburger','Tom buys a hamburger for lunch.','湯姆午餐買了一個漢堡。'),
('hand','Raise your hand if you know the answer.','如果你知道答案就舉手。'),
('hard','The puzzle is hard, but I keep trying.','這個謎題很難，但我繼續嘗試。'),
('has','She has a yellow kite.','她有一個黃色風箏。'),
('hat','A hat keeps the sun off my face.','帽子幫我的臉遮太陽。'),
('have','I have a picture book in my bag.','我的書包裡有一本圖畫書。'),
('he','He answers the question clearly.','他清楚地回答問題。'),
('head','I put a hat on my head.','我把帽子戴在頭上。'),
('help','I help my friend carry her books.','我幫朋友拿她的書。'),
('helper','Coco becomes Lily''s forest helper.','可可成為莉莉的森林幫手。'),
('her','Her sister sings with the class.','她的姊妹和全班一起唱歌。'),
('here','Come here and look at this picture.','來這裡看這張圖片。'),
('him','I give him a new eraser.','我給他一塊新橡皮擦。'),
('his','His bike is near the gate.','他的腳踏車在大門附近。'),
('home','I go home after school and read.','我放學後回家閱讀。'),
('homework','Homework helps me practice after school.','家庭作業幫助我放學後練習。'),
('horse','A horse runs on the farm.','一匹馬在農場奔跑。'),
('hot','The soup is hot, so I wait a minute.','湯很燙，所以我等了一分鐘。'),
('hour','We read for one hour on Sunday.','星期日我們閱讀一小時。'),
('house','There is a tree beside my house.','我家旁邊有一棵樹。'),
('how','How do you say this word?','這個單字怎麼說？'),
('hundred','There are one hundred cards in the box.','盒子裡有一百張卡片。'),
('hungry','I feel hungry after basketball practice.','籃球練習後我覺得很餓。'),
('in','The pencil is in the blue bag.','鉛筆在藍色書包裡。'),
('inside','The key is inside the small box.','鑰匙在小盒子裡面。'),
('into','The frog jumps into the pond.','青蛙跳進池塘裡。'),
('it','It is a small brown dog.','牠是一隻小棕狗。'),
('its','The bird opens its wing.','那隻鳥張開牠的翅膀。'),
('jacket','My jacket is on the chair.','我的夾克在椅子上。'),
('january','In January, the morning air is cold.','一月的早晨空氣很冷。'),
('journey','Their journey begins near the talking tree.','她們的旅程從會說話的樹旁開始。'),
('juice','I drink orange juice after soccer practice.','足球練習後我喝柳橙汁。'),
('july','In July, we swim in the pool.','七月我們在游泳池游泳。'),
('jump','The cat can jump onto the chair.','貓可以跳到椅子上。'),
('june','June is the start of summer vacation.','六月是暑假的開始。'),
('keep','Keep your room clean after you play.','玩完後保持房間乾淨。'),
('keyhole','There is no keyhole on the stone door.','石門上沒有鑰匙孔。'),
('kind','A kind classmate shares his pencil with me.','一位親切的同學把鉛筆借給我。'),
('kindness','Kindness changes the lonely shadow.','善良改變了孤單的影子。'),
('kitchen','Mom cooks breakfast in the kitchen.','媽媽在廚房做早餐。'),
('kite','We fly a kite on a windy day.','有風的日子我們放風箏。'),
('know','I know the answer to this question.','我知道這個問題的答案。'),
('lake','The quiet lake reflects the moon.','安靜的湖映出月亮。'),
('large','A large tree gives us shade in the park.','公園裡有一棵大樹幫我們遮陰。'),
('last','The last page has a happy ending.','最後一頁有快樂的結局。'),
('late','Tom is late because he missed the bus.','湯姆遲到了，因為他錯過公車。'),
('laugh','We laugh at the funny picture.','我們看到好笑的圖片就笑了。'),
('leaf','A green leaf falls into the river.','一片綠葉落進河裡。'),
('learn','I learn three new words today.','我今天學三個新單字。'),
('left','Turn left after the school gate.','經過校門後向左轉。'),
('leg','My leg hurts after running fast.','我跑很快後腿會痛。'),
('lesson','Today''s lesson is about animals.','今天的課是關於動物。'),
('letter','The letter A is at the start of apple.','字母 A 在 apple 的開頭。'),
('library','The library has many picture books.','圖書館有許多圖畫書。'),
('like','I like stories about animals.','我喜歡關於動物的故事。'),
('lion','The lion opens its mouth and roars.','獅子張開嘴巴吼叫。'),
('listen','Listen to the sentence before you repeat it.','重複之前先聽句子。'),
('little','I have a little notebook for English class.','我有一本上英文課用的小筆記本。'),
('live','I live near a small park.','我住在一座小公園附近。'),
('lonely','The lonely shadow waits beside the tree.','孤單的影子在樹旁等待。'),
('long','My sister reads a long story before bed.','我妹妹睡前讀了一篇長故事。'),
('look','Look at the picture and say the word.','看著圖片並說出單字。'),
('loud','The music is too loud for the baby.','這音樂對寶寶來說太大聲了。'),
('love','I love reading with my family.','我喜歡和家人一起閱讀。'),
('lunch','I eat lunch with my classmates.','我和同學一起吃午餐。'),
('magic','The magic light helps the flowers grow.','魔法光幫助花朵生長。'),
('make','I make a paper flower for Mom.','我做一朵紙花給媽媽。'),
('man','The man waits beside the station.','那位男人在車站旁等待。'),
('many','Many students sing the song together.','許多學生一起唱這首歌。'),
('march','In March, flowers begin to grow.','三月花朵開始生長。'),
('market','We buy fruit at the morning market.','我們在早市買水果。'),
('may','In May, we sing for our mothers.','五月我們為媽媽唱歌。'),
('me','This book is for me.','這本書是給我的。'),
('meat','My dad cooks meat for dinner.','我爸爸晚餐煮肉。'),
('meet','I meet my friend at the station.','我在車站和朋友見面。'),
('memory','The stone shows a memory from long ago.','石頭顯示很久以前的記憶。'),
('milk','I drink milk with breakfast.','我早餐喝牛奶。'),
('mine','This green notebook is mine.','這本綠色筆記本是我的。'),
('minute','Wait one minute before you answer.','回答前等一分鐘。'),
('mirror','The lake looks like a silver mirror.','湖面看起來像銀色鏡子。'),
('miss','I miss my friends during winter vacation.','寒假時我想念朋友。'),
('mistake','A mistake helps me learn the right answer.','錯誤幫助我學會正確答案。'),
('mom','Mom makes breakfast before I go to school.','媽媽在我上學前做早餐。'),
('monday','We have English class on Monday.','我們星期一有英文課。'),
('monkey','The monkey climbs the tree quickly.','猴子快速爬上樹。'),
('month','This month, our class reads one book.','這個月我們班讀一本書。'),
('moon','The moon shines above the lake.','月亮照在湖上方。'),
('more','I want to learn more English words.','我想學更多英文單字。'),
('morning','In the morning, I wash my face.','早上我洗臉。'),
('mother','My mother helps me read a story.','我媽媽幫我讀故事。'),
('mountain','A cloud sits over the mountain.','一朵雲停在山上方。'),
('mouse','A small mouse runs behind the box.','一隻小老鼠跑到盒子後面。'),
('mouth','Open your mouth and say the word clearly.','張開嘴巴，清楚說出這個字。'),
('move','Move your chair closer to the table.','把椅子移近桌子。'),
('movie','The movie has a funny animal story.','這部電影有一個有趣的動物故事。'),
('much','I do not put much sugar in my tea.','我不在茶裡放太多糖。'),
('museum','The museum shows old pictures and stones.','博物館展示舊照片和石頭。'),
('music','Soft music plays before the song starts.','歌曲開始前播放輕柔的音樂。'),
('my','My bag is beside the chair.','我的書包在椅子旁邊。'),
('narrow','The narrow path leads to a small lake.','狹窄的小路通往一座小湖。'),
('near','My school is near the library.','我的學校在圖書館附近。'),
('need','We need quiet voices in the library.','我們在圖書館需要輕聲說話。'),
('new','I write new words in my notebook.','我把新的單字寫在筆記本裡。'),
('next','Turn to the next page after you finish.','完成後翻到下一頁。'),
('nice','Our teacher says nice words when we try.','我們努力時，老師會說友善的話。'),
('night','At night, I read with my family.','晚上我和家人一起閱讀。'),
('nine','Nine flowers grow beside the path.','九朵花長在小路旁。'),
('nineteen','Nineteen clouds move across the sky.','十九朵雲飄過天空。'),
('no','No, the answer is not seven.','不，答案不是七。'),
('noodles','We eat noodles on a rainy day.','下雨天我們吃麵。'),
('noon','At noon, we eat lunch together.','中午我們一起吃午餐。'),
('nose','My nose feels cold in winter.','冬天我的鼻子覺得冷。'),
('notebook','Write the new sentence in your notebook.','把新句子寫進你的筆記本。'),
('november','November evenings get dark early.','十一月的傍晚很早變暗。'),
('october','In October, the wind feels cool.','十月的風感覺涼爽。'),
('office','My mother works in an office.','我媽媽在辦公室工作。'),
('ok','It is ok to make a small mistake.','犯一個小錯是沒關係的。'),
('old','My grandpa keeps an old photo on his desk.','我爺爺把一張舊照片放在書桌上。'),
('on','The book is on the table.','書在桌上。'),
('one','I read one page before dinner.','我晚餐前讀一頁。'),
('open','Open the book to page ten.','把書打開到第十頁。'),
('orange','I eat an orange after lunch.','我午餐後吃一顆柳橙。'),
('our','Our class reads in the library.','我們班在圖書館閱讀。'),
('out','Take your book out of the bag.','把你的書從書包拿出來。'),
('outside','The children play outside after class.','孩子們下課後在外面玩。'),
('page','Read the first page slowly.','慢慢讀第一頁。'),
('pants','These pants are too long for me.','這件褲子對我來說太長。'),
('paper','Fold the paper into a small boat.','把紙摺成一艘小船。'),
('parent','A parent signs my homework notebook.','一位家長在我的作業簿上簽名。'),
('path','The silver path leads to the lake.','銀色小路通往湖邊。'),
('pattern','The moon pattern matches the key.','月亮圖案和鑰匙相符合。'),
('peaceful','The lake becomes peaceful under the moon.','月光下的湖變得很平靜。'),
('pen','Use a black pen to write your name.','用黑筆寫你的名字。'),
('pencil','My pencil is sharp and ready.','我的鉛筆削好了，可以使用。'),
('petal','A pink petal falls on Lily''s hand.','一片粉紅花瓣落在莉莉手上。'),
('phone','Mom calls me on the phone after class.','媽媽下課後打電話給我。'),
('picture','The picture shows a happy family.','這張圖片顯示一個快樂家庭。'),
('pig','A pink pig sleeps in the mud.','一隻粉紅豬睡在泥巴裡。'),
('pink','My sister wears a pink dress today.','我妹妹今天穿粉紅色洋裝。'),
('pizza','My friends share pizza after the game.','比賽後我的朋友們分享披薩。'),
('playground','Children run on the playground after class.','孩子們下課後在操場跑。'),
('point','Point to the word you can read.','指出你會讀的單字。'),
('pond','A duck swims across the small pond.','一隻鴨子游過小池塘。'),
('pork','Mom puts pork in the lunch box.','媽媽把豬肉放進便當盒。'),
('post','I post a letter to my teacher.','我寄一封信給老師。'),
('potato','The hot potato is too warm to hold.','熱馬鈴薯太燙，不能拿。'),
('practice','We practice speaking English after class.','我們下課後練習說英文。'),
('purple','The purple flower grows near the gate.','紫色的花長在大門旁。'),
('put','Put the ruler beside the notebook.','把尺放在筆記本旁邊。'),
('puzzle','The wall puzzle has three glowing circles.','牆上的謎題有三個發光圓圈。'),
('question','Please read the question before you answer.','回答前請先讀問題。'),
('quiet','The library is quiet in the afternoon.','下午的圖書館很安靜。'),
('rabbit','The rabbit hops across the grass.','兔子跳過草地。'),
('rain','Rain falls softly on the window.','雨輕輕落在窗戶上。'),
('rainbow','The rainbow has many beautiful colors.','彩虹有許多美麗的顏色。'),
('react','The key reacts when it touches the door.','鑰匙碰到門時產生反應。'),
('read','I read one English page every night.','我每天晚上讀一頁英文。'),
('ready','I am ready to read the next page.','我準備好閱讀下一頁了。'),
('red','I draw a red apple on the paper.','我在紙上畫一顆紅蘋果。'),
('reflect','The lake reflects the moon at night.','夜晚湖面映出月亮。'),
('reject','The crystal does not reject the small shadow now.','水晶現在沒有拒絕小影子。'),
('ribbon','Lily ties a red ribbon to a branch.','莉莉把紅緞帶綁在樹枝上。'),
('rice','I eat rice with vegetables for dinner.','我晚餐吃飯配蔬菜。'),
('ride','She rides a bike to the playground.','她騎腳踏車去操場。'),
('right','The library is on your right.','圖書館在你的右邊。'),
('river','The river sings when the bell rings.','鈴聲響起時，河流唱歌。'),
('rock','The frog sits on a warm rock.','青蛙坐在溫暖的岩石上。'),
('room','My room has a desk and a bed.','我的房間有書桌和床。'),
('ruler','The ruler helps me draw a line.','尺幫我畫直線。'),
('salad','The salad has carrots and corn.','沙拉裡有紅蘿蔔和玉米。'),
('salt','Dad adds a little salt to the soup.','爸爸在湯裡加一點鹽。'),
('same','We read the same story in class.','我們在課堂上讀同一個故事。'),
('sand','Sand gets into my shoes at the beach.','沙子在海灘上跑進我的鞋裡。'),
('sandwich','I make a sandwich with egg and tomato.','我用蛋和番茄做三明治。'),
('saturday','On Saturday, we visit the zoo.','星期六我們參觀動物園。'),
('say','Say the word slowly and clearly.','慢慢並清楚地說出這個單字。'),
('sea','The sea looks blue under the sun.','陽光下的大海看起來很藍。'),
('second','The second question is about the cat.','第二題是關於那隻貓。'),
('see','I see a rainbow after the rain.','雨後我看見一道彩虹。'),
('sentence','Read the sentence and circle the answer.','讀句子並圈出答案。'),
('september','School starts again in September.','九月學校再次開學。'),
('seven','Class starts at seven fifty.','七點五十開始上課。'),
('seventeen','Seventeen pages are in this chapter.','這一章有十七頁。'),
('shadow','A dark shadow moves behind the tree.','一道黑影在樹後移動。'),
('share','We share cookies with our classmates.','我們和同學分享餅乾。'),
('she','She reads a story after dinner.','她晚餐後讀故事。'),
('sheep','The sheep stands on the green hill.','羊站在綠色山丘上。'),
('shirt','He wears a white shirt to school.','他穿白襯衫去上學。'),
('shoes','Put your shoes beside the door.','把鞋子放在門旁邊。'),
('short','This short song is easy to sing.','這首短歌很容易唱。'),
('shorts','I wear shorts on a hot day.','熱天我穿短褲。'),
('shout','Do not shout in the classroom.','不要在教室裡大叫。'),
('show','Show me the picture in your book.','給我看你書裡的圖片。'),
('sick','My brother is sick and stays at home.','我哥哥生病了，待在家裡。'),
('silent','The forest is silent before the birds sing.','鳥兒唱歌前，森林很安靜。'),
('sing','We sing an English song together.','我們一起唱英文歌。'),
('sister','My sister sings a song with me.','我姊妹和我一起唱歌。'),
('sit','Please sit on the chair and listen.','請坐在椅子上聽。'),
('six','Six ducks swim in the pond.','六隻鴨子在池塘裡游泳。'),
('sixteen','Sixteen birds fly over the sea.','十六隻鳥飛過大海。'),
('skirt','Her blue skirt moves in the wind.','她的藍裙子在風中擺動。'),
('sky','The sky is blue after the rain.','雨後天空是藍色的。'),
('sleep','The baby sleeps after dinner.','寶寶晚餐後睡覺。'),
('slow','The turtle walks slowly across the grass.','烏龜慢慢走過草地。'),
('small','The small cat sleeps beside my school bag.','那隻小貓睡在我的書包旁邊。'),
('smile','The girl smiles when she sees her friend.','女孩看到朋友時微笑。'),
('smoke','Dark smoke fills the old cave.','黑煙充滿古老洞穴。'),
('smoky','The smoky cave is hard to see inside.','煙霧般的洞穴裡面很難看清楚。'),
('snack','A banana is my afternoon snack.','香蕉是我的下午點心。'),
('snake','The snake hides under a rock.','蛇躲在岩石下面。'),
('snow','Snow covers the street in the morning.','早上雪覆蓋了街道。'),
('soccer','Soccer is my favorite sport after school.','足球是我放學後最喜歡的運動。'),
('socks','My socks are wet after the rain.','下雨後我的襪子濕了。'),
('solid','The solid rock wall does not move.','堅固的岩壁沒有移動。'),
('some','There are some pencils in the box.','盒子裡有一些鉛筆。'),
('someone','Someone left a notebook on the desk.','有人把筆記本留在書桌上。'),
('song','This song helps us remember new words.','這首歌幫助我們記住新單字。'),
('soup','The hot soup smells good.','熱湯聞起來很香。'),
('sparkle','The silver bell sparkles under the water.','銀色鈴鐺在水下閃耀。'),
('speak','I speak English with my teacher.','我和老師說英文。'),
('spiral','The spiral symbol points to the secret door.','螺旋符號指向秘密門。'),
('spirit','The lake spirit speaks in a gentle voice.','湖的精靈用溫柔的聲音說話。'),
('spoon','A shiny spoon helps Lily see under the lake.','一支亮亮的湯匙幫莉莉看見湖底。'),
('stand','Stand beside your desk and read aloud.','站在你的書桌旁大聲朗讀。'),
('star','A bright star appears in the night sky.','一顆明亮的星星出現在夜空。'),
('start','Class starts at eight in the morning.','早上八點開始上課。'),
('station','Meet me at the train station.','在車站和我見面。'),
('steady','Lily walks with steady steps across the bridge.','莉莉用穩定的步伐走過橋。'),
('stone','The moon stone feels warm in Lily''s hand.','月亮石在莉莉手中感覺溫暖。'),
('stop','Stop at the red light before crossing.','過馬路前在紅燈停下。'),
('store','The store sells notebooks and pencils.','那家商店賣筆記本和鉛筆。'),
('story','The story is about a brave girl.','這個故事是關於一個勇敢的女孩。'),
('street','Look left and right before crossing the street.','過街前左右看。'),
('strong','Practice makes my English stronger every day.','每天練習讓我的英文更強。'),
('student','The student writes the answer carefully.','學生小心地寫下答案。'),
('study','I study English for ten minutes every day.','我每天讀十分鐘英文。'),
('sugar','Do not put too much sugar in tea.','不要在茶裡放太多糖。'),
('sun','The sun shines over the playground.','太陽照在操場上。'),
('sunday','Sunday is a quiet family day.','星期日是安靜的家庭日。'),
('supermarket','We buy milk at the supermarket.','我們在超市買牛奶。'),
('surface','The key floats near the water surface.','鑰匙漂在水面附近。'),
('surround','Warm light surrounds Lily in the cave.','溫暖的光包圍洞穴中的莉莉。'),
('swim','Fish swim under the bridge.','魚在橋下游泳。'),
('symbol','The moon symbol glows on the stone.','月亮符號在石頭上發光。'),
('table','The cake is on the table.','蛋糕在桌上。'),
('take','Take your notebook out of your bag.','把你的筆記本從書包拿出來。'),
('tall','The tall boy can reach the top shelf.','那個高個子男孩碰得到最上面的架子。'),
('tea','Grandma drinks warm tea after dinner.','奶奶晚餐後喝溫茶。'),
('teacher','The teacher tells us a funny story.','老師告訴我們一個好笑的故事。'),
('tell','Please tell me your favorite color.','請告訴我你最喜歡的顏色。'),
('ten','Write ten words in your notebook.','在筆記本裡寫十個單字。'),
('test','The reading test has five questions.','閱讀測驗有五個問題。'),
('that','That picture shows a yellow bus.','那張圖片顯示黃色公車。'),
('their','Their house is near the park.','他們的房子在公園附近。'),
('them','I help them carry the books.','我幫他們拿書。'),
('there','There is a rabbit under the tree.','樹下有一隻兔子。'),
('these','These words are in today''s lesson.','這些單字在今天的課裡。'),
('they','They play soccer after school.','他們放學後踢足球。'),
('think','I think this story is interesting.','我覺得這個故事很有趣。'),
('third','The third picture shows a river.','第三張圖片顯示一條河。'),
('thirsty','I am thirsty, so I drink some water.','我口渴了，所以喝一些水。'),
('thirteen','Thirteen apples are in the basket.','籃子裡有十三顆蘋果。'),
('thirty','The bus comes in thirty minutes.','公車三十分鐘後來。'),
('this','This sentence is easy to read.','這個句子很容易讀。'),
('those','Those flowers are beside the river.','那些花在河邊。'),
('three','I have three pencils in my bag.','我的書包裡有三支鉛筆。'),
('thursday','I play basketball on Thursday afternoon.','我星期四下午打籃球。'),
('tiger','The tiger walks quietly in the zoo.','老虎在動物園安靜地走著。'),
('time','It is time to listen and repeat.','該聽並跟讀了。'),
('tired','The children are tired after a long walk.','孩子們走了很久後很累。'),
('to','I walk to school with my brother.','我和哥哥走路去學校。'),
('today','Today we learn a song about animals.','今天我們學一首關於動物的歌。'),
('tomato','A red tomato is in the salad.','沙拉裡有一顆紅番茄。'),
('tomorrow','Tomorrow we will read the next chapter.','明天我們會讀下一章。'),
('too','I want to sing too.','我也想唱歌。'),
('touch','Do not touch the hot soup bowl.','不要碰熱湯碗。'),
('toy','The toy car is under the bed.','玩具車在床下。'),
('tree','A big tree stands beside the river.','一棵大樹立在河邊。'),
('tremble','Lily''s hands tremble, but she stays brave.','莉莉的手在發抖，但她保持勇敢。'),
('trunk','The tree trunk has glowing green lines.','樹幹上有發光的綠色線條。'),
('trust','Trust your heart when you feel afraid.','害怕時要相信自己的心。'),
('truth','Lily sees the truth inside the crystal.','莉莉在水晶裡看見真相。'),
('try','Try again if the answer is wrong.','答案錯了就再試一次。'),
('tshirt','My T-shirt has a green turtle on it.','我的 T 恤上有一隻綠色烏龜。'),
('tuesday','On Tuesday, I practice spelling words.','星期二我練習拼單字。'),
('turn','Turn left at the school gate.','在校門口向左轉。'),
('turtle','The turtle moves slowly on the road.','烏龜在路上慢慢移動。'),
('twelve','There are twelve months in a year.','一年有十二個月。'),
('twenty','We count to twenty in English.','我們用英文數到二十。'),
('twig','Lily moves the twig away from the fairy.','莉莉把小樹枝從小精靈身上移開。'),
('twisted','A twisted branch lies beside the path.','一根扭曲的樹枝躺在小路旁。'),
('two','Two birds sit in the tree.','兩隻鳥坐在樹上。'),
('under','The dog sleeps under the chair.','狗睡在椅子下面。'),
('up','Look up at the bright moon.','抬頭看明亮的月亮。'),
('us','The teacher gives us a reading card.','老師給我們一張閱讀卡。'),
('use','Use a ruler to draw a straight line.','用尺畫一條直線。'),
('vegetable','I eat one vegetable with every meal.','我每餐都吃一種蔬菜。'),
('very','The story is very interesting.','這個故事非常有趣。'),
('visit','We visit the museum on Saturday.','我們星期六參觀博物館。'),
('wait','Wait for your turn to speak.','等輪到你再說話。'),
('wake','I wake up early for school.','我為了上學早起。'),
('walk','We walk home together after school.','我們放學後一起走路回家。'),
('want','I want a new pencil for class.','我想要一支上課用的新鉛筆。'),
('warm','The warm sun shines through the window.','溫暖的陽光從窗戶照進來。'),
('wash','Wash your hands before lunch.','午餐前洗手。'),
('watch','We watch a short movie in English class.','我們在英文課看一部短電影。'),
('wave','A small wave brings the key to Lily.','一個小浪把鑰匙帶到莉莉面前。'),
('we','We practice English every morning.','我們每天早上練習英文。'),
('wednesday','Wednesday is our reading day.','星期三是我們的閱讀日。'),
('week','I learn five new words every week.','我每週學五個新單字。'),
('what','What do you eat for breakfast?','你早餐吃什麼？'),
('when','When does the song start?','這首歌什麼時候開始？'),
('where','Where is your English notebook?','你的英文筆記本在哪裡？'),
('whisper','The trees whisper softly in the wind.','樹在風中輕輕低語。'),
('white','A white bird flies across the sky.','一隻白色的鳥飛過天空。'),
('who','Who is reading the story aloud?','誰正在大聲讀故事？'),
('why','Why is the river so quiet?','為什麼河流這麼安靜？'),
('wind','The wind moves the leaves on the tree.','風吹動樹上的葉子。'),
('window','Open the window to let in fresh air.','打開窗戶讓新鮮空氣進來。'),
('wing','The fairy''s blue wing sparkles in the light.','小精靈的藍色翅膀在光中閃耀。'),
('with','I read with my dad at night.','我晚上和爸爸一起閱讀。'),
('without','I cannot write without a pencil.','沒有鉛筆我不能寫字。'),
('woman','The woman buys vegetables at the market.','那位女人在市場買蔬菜。'),
('word','I write one new word on each card.','我在每張卡片上寫一個新單字。'),
('work','We work together to finish the poster.','我們一起完成海報。'),
('write','Write your name at the top of the page.','把你的名字寫在頁面上方。'),
('wrong','I fix the wrong answer after checking it.','檢查後我修正錯誤答案。'),
('year','I grow taller every year.','我每年都長高。'),
('yellow','The yellow bus stops near my house.','黃色公車停在我家附近。'),
('yes','Yes, I can read this sentence.','是的，我會讀這個句子。'),
('yesterday','Yesterday I practiced English with Mom.','昨天我和媽媽練習英文。'),
('you','You can read this sentence slowly.','你可以慢慢讀這個句子。'),
('young','The young student raises her hand to answer.','那位年紀小的學生舉手回答。'),
('your','Put your pencil on the desk.','把你的鉛筆放在書桌上。'),
('zero','There are zero cookies left on the plate.','盤子上沒有餅乾了。'),
('zoo','At the zoo, we see lions and elephants.','在動物園，我們看見獅子和大象。')
) AS v(word, example, example_zh)
WHERE wb.level = 'elementary'
  AND wb.category = 'Supplemental'
  AND lower(wb.word) = lower(v.word);
