-- Upsert Clock Tower junior novel vocabulary into public.word_bank.
-- Generated from src/data/juniorNovelWords.js.
INSERT INTO public.word_bank
  (word, pos, meaning, level, ceec_level, example, example_zh, category, phonetic, forms, collocations)
VALUES
  ('accepted', 'v.', '被接受；被錄取', 'junior', 2, 'Ethan was accepted into Clock Tower Magic School after the black envelope arrived.', '黑色信封送達後，伊森被錄取進入時鐘塔魔法學院。', '國中小說：時鐘塔', '', '[{"w":"accept","p":"v.","n":"原形"}]'::jsonb, '["be accepted into 被錄取進入"]'::jsonb),
  ('apartment', 'n.', '公寓', 'junior', 1, 'The storm cut the power in Ethan''s apartment building.', '暴風雨讓伊森的公寓大樓停電。', '國中小說：時鐘塔', '', '[]'::jsonb, '["apartment building 公寓大樓"]'::jsonb),
  ('attack', 'n./v.', '攻擊；襲擊', 'junior', 2, 'After the attack in the Great Hall, students whispered about Ethan.', '大廳遭到襲擊後，學生們低聲談論伊森。', '國中小說：時鐘塔', '', '[{"w":"attacked","p":"v.","n":"過去式"}]'::jsonb, '["under attack 遭到攻擊"]'::jsonb),
  ('awaken', 'v.', '喚醒；醒來', 'junior', 2, 'The old watch began to awaken when the tower bell rang.', '高塔鐘聲響起時，古老懷錶開始甦醒。', '國中小說：時鐘塔', '', '[{"w":"awakened","p":"v.","n":"過去式"}]'::jsonb, '["awaken a memory 喚醒記憶"]'::jsonb),
  ('awakened', 'v.', '甦醒；被喚醒', 'junior', 2, 'Something deep inside the Forbidden Tower had awakened.', '禁忌高塔深處有某種東西已經甦醒。', '國中小說：時鐘塔', '', '[{"w":"awaken","p":"v.","n":"原形"}]'::jsonb, '["be awakened 被喚醒"]'::jsonb),
  ('balance', 'n.', '平衡', 'junior', 2, 'The silver seal kept the balance between light and darkness.', '銀色封印維持著光明與黑暗之間的平衡。', '國中小說：時鐘塔', '', '[{"w":"balanced","p":"adj.","n":"平衡的"}]'::jsonb, '["find balance 找到平衡"]'::jsonb),
  ('barrier', 'n.', '屏障；障礙', 'junior', 3, 'A silver barrier rose between Ethan and the shadow creature.', '一道銀色屏障在伊森和暗影怪物之間升起。', '國中小說：時鐘塔', '', '[]'::jsonb, '["magical barrier 魔法屏障"]'::jsonb),
  ('battle', 'n.', '戰鬥；戰役', 'junior', 2, 'The final battle began when the tower clock rang in the storm.', '暴風雨中鐘塔響起時，最後一戰開始了。', '國中小說：時鐘塔', '', '[]'::jsonb, '["final battle 最後一戰"]'::jsonb),
  ('below', 'adv./prep.', '在下方；到下面', 'junior', 1, 'A whisper came from the dark staircase below.', '一陣低語從下方的黑暗樓梯傳來。', '國中小說：時鐘塔', '', '[]'::jsonb, '["deep below 在深處下方"]'::jsonb),
  ('beneath', 'prep.', '在…下方', 'junior', 3, 'The hidden library waited beneath the clock tower.', '隱藏圖書館就在時鐘塔下方等待著。', '國中小說：時鐘塔', '', '[]'::jsonb, '["beneath the tower 在高塔下方"]'::jsonb),
  ('betrayal', 'n.', '背叛', 'junior', 3, 'The old book revealed a betrayal among the first keepers.', '古書揭露初代守護者之間的一場背叛。', '國中小說：時鐘塔', '', '[{"w":"betray","p":"v.","n":"背叛"}]'::jsonb, '["a painful betrayal 痛苦的背叛"]'::jsonb),
  ('bloodline', 'n.', '血統；家族血脈', 'junior', 3, 'The watch glowed when it recognized Ethan''s bloodline.', '懷錶認出伊森的血統時發出光芒。', '國中小說：時鐘塔', '', '[]'::jsonb, '["family bloodline 家族血脈"]'::jsonb),
  ('brick', 'n.', '磚塊', 'junior', 1, 'The ticket led Ethan through a brick wall at the station.', '車票引導伊森穿過車站的一面磚牆。', '國中小說：時鐘塔', '', '[]'::jsonb, '["brick wall 磚牆"]'::jsonb),
  ('bridge', 'n.', '橋；橋樑', 'junior', 2, 'A narrow bridge connected the floating classrooms above the valley.', '一座狹窄的橋連接著山谷上方漂浮的教室。', '國中小說：時鐘塔', '', '[]'::jsonb, '["cross a bridge 過橋"]'::jsonb),
  ('cabin', 'n.', '車廂；小木屋', 'junior', 2, 'Ethan met Adrian inside Cabin Seven on the train.', '伊森在列車七號車廂裡遇見亞德里安。', '國中小說：時鐘塔', '', '[]'::jsonb, '["train cabin 火車車廂"]'::jsonb),
  ('candle', 'n.', '蠟燭', 'junior', 1, 'His grandmother lit a candle when the lights went out.', '停電時，奶奶點起一根蠟燭。', '國中小說：時鐘塔', '', '[]'::jsonb, '["light a candle 點蠟燭"]'::jsonb),
  ('ceiling', 'n.', '天花板', 'junior', 2, 'A dark mark spread across the ceiling of the Great Hall.', '黑色印記在大廳天花板上擴散。', '國中小說：時鐘塔', '', '[]'::jsonb, '["on the ceiling 在天花板上"]'::jsonb),
  ('ceremony', 'n.', '典禮；儀式', 'junior', 2, 'The arrival ceremony stopped when the purple eyes appeared.', '紫色眼睛出現時，入學儀式停了下來。', '國中小說：時鐘塔', '', '[]'::jsonb, '["arrival ceremony 入學儀式"]'::jsonb),
  ('chains', 'n.', '鎖鏈', 'junior', 2, 'Silver chains shook above the underground prison.', '銀色鎖鏈在地下囚牢上方晃動。', '國中小說：時鐘塔', '', '[{"w":"chain","p":"n.","n":"單數"}]'::jsonb, '["iron chains 鐵鍊"]'::jsonb),
  ('chamber', 'n.', '房間；密室', 'junior', 3, 'The key opened a hidden chamber under the school.', '鑰匙打開了學院底下的隱藏密室。', '國中小說：時鐘塔', '', '[]'::jsonb, '["hidden chamber 隱藏密室"]'::jsonb),
  ('choice', 'n.', '選擇', 'junior', 2, 'Ethan had to make a choice between power and his friends.', '伊森必須在力量與朋友之間做出選擇。', '國中小說：時鐘塔', '', '[]'::jsonb, '["make a choice 做出選擇"]'::jsonb),
  ('claws', 'n.', '爪子', 'junior', 3, 'Dark claws reached toward the Star Crown.', '黑色爪子伸向星之王冠。', '國中小說：時鐘塔', '', '[{"w":"claw","p":"n.","n":"單數"}]'::jsonb, '["dark claws 黑色爪子"]'::jsonb),
  ('clock', 'n.', '時鐘', 'junior', 1, 'The giant clock on the wall moved backward three times.', '牆上的巨大時鐘倒轉了三次。', '國中小說：時鐘塔', '', '[]'::jsonb, '["giant clock 巨大時鐘"]'::jsonb),
  ('collapse', 'v./n.', '倒塌；崩塌', 'junior', 3, 'The tower began to collapse after the seal cracked.', '封印裂開後，高塔開始崩塌。', '國中小說：時鐘塔', '', '[{"w":"collapsed","p":"v.","n":"過去式"}]'::jsonb, '["begin to collapse 開始崩塌"]'::jsonb),
  ('connected', 'adj./v.', '連接的；有關聯的', 'junior', 2, 'The tower clocks were connected by ancient magic.', '高塔裡的時鐘被古老魔法連接在一起。', '國中小說：時鐘塔', '', '[{"w":"connect","p":"v.","n":"原形"}]'::jsonb, '["be connected to 與…相連"]'::jsonb),
  ('courage', 'n.', '勇氣', 'junior', 2, 'Ethan showed courage when he stood before the Hollow King.', '伊森站在虛空之王面前時展現了勇氣。', '國中小說：時鐘塔', '', '[{"w":"courageous","p":"adj.","n":"勇敢的"}]'::jsonb, '["show courage 展現勇氣"]'::jsonb),
  ('crack', 'n./v.', '裂縫；裂開', 'junior', 2, 'A giant crack opened across the library floor.', '圖書館地板裂開一道巨大裂縫。', '國中小說：時鐘塔', '', '[{"w":"cracked","p":"adj.","n":"裂開的"}]'::jsonb, '["a crack across the wall 牆上的裂縫"]'::jsonb),
  ('creature', 'n.', '生物；怪物', 'junior', 2, 'A smoky creature crawled across the train window.', '一隻煙霧般的怪物爬過列車窗戶。', '國中小說：時鐘塔', '', '[]'::jsonb, '["strange creature 奇怪的生物"]'::jsonb),
  ('crown', 'n.', '王冠', 'junior', 2, 'The silver crown floated above the ancient chamber.', '銀色王冠漂浮在古老密室上方。', '國中小說：時鐘塔', '', '[]'::jsonb, '["silver crown 銀色王冠"]'::jsonb),
  ('danger', 'n.', '危險', 'junior', 2, 'Lucy sensed danger when every candle turned blue.', '當每根蠟燭都變成藍色時，露西感覺到危險。', '國中小說：時鐘塔', '', '[{"w":"dangerous","p":"adj.","n":"危險的"}]'::jsonb, '["sense danger 感覺到危險"]'::jsonb),
  ('dangerous', 'adj.', '危險的', 'junior', 2, 'Adrian warned Ethan that the hidden tower was dangerous.', '亞德里安警告伊森那座隱藏高塔很危險。', '國中小說：時鐘塔', '', '[{"w":"danger","p":"n.","n":"危險"}]'::jsonb, '["dangerous place 危險的地方"]'::jsonb),
  ('darkness', 'n.', '黑暗', 'junior', 2, 'Darkness poured out from the crack beneath the tower.', '黑暗從高塔下方的裂縫湧出。', '國中小說：時鐘塔', '', '[{"w":"dark","p":"adj.","n":"黑暗的"}]'::jsonb, '["move through darkness 穿過黑暗"]'::jsonb),
  ('destroy', 'v.', '破壞；摧毀', 'junior', 2, 'The Hollow King wanted to destroy the silver seal.', '虛空之王想摧毀銀色封印。', '國中小說：時鐘塔', '', '[{"w":"destroyed","p":"v.","n":"過去式"}]'::jsonb, '["destroy the seal 破壞封印"]'::jsonb),
  ('dormitory', 'n.', '宿舍', 'junior', 3, 'A secret door appeared inside the west tower dormitory.', '一扇秘密門出現在西塔宿舍裡。', '國中小說：時鐘塔', '', '[]'::jsonb, '["tower dormitory 高塔宿舍"]'::jsonb),
  ('enchanted', 'adj.', '被施魔法的；著魔的', 'junior', 3, 'The enchanted stairs changed direction without warning.', '被施魔法的樓梯毫無預警地改變方向。', '國中小說：時鐘塔', '', '[{"w":"enchant","p":"v.","n":"施魔法"}]'::jsonb, '["enchanted stairs 被施法的樓梯"]'::jsonb),
  ('enormous', 'adj.', '巨大的', 'junior', 2, 'Ethan stared at the enormous hall filled with floating candles.', '伊森望著充滿漂浮蠟燭的巨大大廳。', '國中小說：時鐘塔', '', '[]'::jsonb, '["enormous hall 巨大的大廳"]'::jsonb),
  ('envelope', 'n.', '信封', 'junior', 2, 'The black envelope carried Ethan''s invitation to the magic school.', '黑色信封帶來伊森前往魔法學院的邀請。', '國中小說：時鐘塔', '', '[]'::jsonb, '["black envelope 黑色信封"]'::jsonb),
  ('escape', 'v./n.', '逃脫；逃跑', 'junior', 2, 'The students ran through the tunnel to escape the smoke.', '學生們穿過隧道逃離黑煙。', '國中小說：時鐘塔', '', '[{"w":"escaped","p":"v.","n":"過去式"}]'::jsonb, '["escape from danger 逃離危險"]'::jsonb),
  ('fall', 'v./n.', '落下；倒塌', 'junior', 2, 'Stones began to fall from the tower as the seal cracked.', '當封印裂開時，石塊開始從高塔落下。', '國中小說：時鐘塔', '', '[{"w":"fell","p":"v.","n":"過去式"}]'::jsonb, '["fall apart 崩塌"]'::jsonb),
  ('father', 'n.', '父親', 'junior', 1, 'Ethan learned that his father had once studied at the school.', '伊森得知父親曾在這所學校讀書。', '國中小說：時鐘塔', '', '[]'::jsonb, '["Ethan’s father 伊森的父親"]'::jsonb),
  ('fear', 'n./v.', '恐懼；害怕', 'junior', 2, 'Fear filled the hall when the Mark of Noctis returned.', '諾克提斯印記回歸時，恐懼籠罩整座大廳。', '國中小說：時鐘塔', '', '[{"w":"fearful","p":"adj.","n":"害怕的"}]'::jsonb, '["feel fear 感到恐懼"]'::jsonb),
  ('final', 'adj.', '最後的；最終的', 'junior', 2, 'The final gate opened beneath the clock tower.', '最後一道門在時鐘塔下方打開。', '國中小說：時鐘塔', '', '[{"w":"finally","p":"adv.","n":"最後"}]'::jsonb, '["final choice 最後的選擇"]'::jsonb),
  ('flames', 'n.', '火焰', 'junior', 2, 'Blue flames burned beside the stone pathway.', '藍色火焰在石頭小路旁燃燒。', '國中小說：時鐘塔', '', '[{"w":"flame","p":"n.","n":"單數"}]'::jsonb, '["blue flames 藍色火焰"]'::jsonb),
  ('floating', 'adj./v.', '漂浮的；漂浮著', 'junior', 2, 'Floating candles brightened when the Headmaster spoke.', '校長開口時，漂浮蠟燭變得更亮。', '國中小說：時鐘塔', '', '[{"w":"float","p":"v.","n":"漂浮"}]'::jsonb, '["floating candles 漂浮蠟燭"]'::jsonb),
  ('forbidden', 'adj.', '被禁止的；禁忌的', 'junior', 3, 'No student was allowed to enter the Forbidden Tower.', '沒有學生被允許進入禁忌高塔。', '國中小說：時鐘塔', '', '[{"w":"forbid","p":"v.","n":"禁止"}]'::jsonb, '["forbidden tower 禁忌高塔"]'::jsonb),
  ('force', 'n./v.', '力量；強迫', 'junior', 2, 'The shadow tried to take the crown by force.', '黑影試圖用力量奪走王冠。', '國中小說：時鐘塔', '', '[{"w":"forceful","p":"adj.","n":"強而有力的"}]'::jsonb, '["by force 用力量"]'::jsonb),
  ('friend', 'n.', '朋友', 'junior', 1, 'Lucy stayed beside Ethan like a true friend in the darkest moment.', '在最黑暗的時刻，露西像真正的朋友一樣留在伊森身邊。', '國中小說：時鐘塔', '', '[{"w":"friendly","p":"adj.","n":"友善的"}]'::jsonb, '["stand with a friend 和朋友站在一起"]'::jsonb),
  ('frozen', 'adj.', '凍結的；僵住的', 'junior', 2, 'The students stood frozen when the giant clock stopped.', '巨大時鐘停止時，學生們僵在原地。', '國中小說：時鐘塔', '', '[{"w":"freeze","p":"v.","n":"結冰；僵住"}]'::jsonb, '["stand frozen 僵住不動"]'::jsonb),
  ('future', 'n.', '未來', 'junior', 1, 'Ethan knew the school''s future depended on his choice.', '伊森知道學院的未來取決於他的選擇。', '國中小說：時鐘塔', '', '[]'::jsonb, '["in the future 在未來"]'::jsonb),
  ('goodbye', 'n./interj.', '再見；道別', 'junior', 1, 'At sunrise, Ethan said goodbye to the old tower keeper.', '日出時，伊森向老高塔守護者道別。', '國中小說：時鐘塔', '', '[]'::jsonb, '["say goodbye 道別"]'::jsonb),
  ('guardian', 'n.', '守護者；監護人', 'junior', 2, 'The guardian warned Ethan not to open the prison door.', '守護者警告伊森不要打開囚牢大門。', '國中小說：時鐘塔', '', '[]'::jsonb, '["tower guardian 高塔守護者"]'::jsonb),
  ('headmaster', 'n.', '校長', 'junior', 2, 'The Headmaster watched Ethan after the silver watch glowed.', '銀色懷錶發光後，校長注視著伊森。', '國中小說：時鐘塔', '', '[]'::jsonb, '["school headmaster 學校校長"]'::jsonb),
  ('heir', 'n.', '繼承人', 'junior', 3, 'The message on the watch called Ethan the heir.', '懷錶上的訊息稱伊森為繼承者。', '國中小說：時鐘塔', '', '[]'::jsonb, '["the heir to the tower 高塔繼承人"]'::jsonb),
  ('hidden', 'adj.', '隱藏的', 'junior', 2, 'A hidden staircase appeared behind the giant clock.', '巨大時鐘後方出現一座隱藏樓梯。', '國中小說：時鐘塔', '', '[{"w":"hide","p":"v.","n":"隱藏"}]'::jsonb, '["hidden door 隱藏門"]'::jsonb),
  ('hollow', 'adj.', '空洞的；中空的', 'junior', 3, 'A hollow voice echoed from the prison below.', '一道空洞的聲音從下方囚牢回響。', '國中小說：時鐘塔', '', '[]'::jsonb, '["hollow voice 空洞的聲音"]'::jsonb),
  ('house', 'n.', '學院；房子', 'junior', 1, 'Each tower house trained a different kind of magic.', '每個高塔學院都訓練不同種類的魔法。', '國中小說：時鐘塔', '', '[]'::jsonb, '["tower house 高塔學院"]'::jsonb),
  ('injured', 'adj.', '受傷的', 'junior', 2, 'An injured student was carried out of the shaking hall.', '一名受傷的學生被帶離搖晃的大廳。', '國中小說：時鐘塔', '', '[{"w":"injure","p":"v.","n":"使受傷"}]'::jsonb, '["be injured 受傷"]'::jsonb),
  ('journey', 'n.', '旅程', 'junior', 1, 'Ethan''s journey began with a letter in the rain.', '伊森的旅程從雨中的一封信開始。', '國中小說：時鐘塔', '', '[]'::jsonb, '["begin a journey 開始旅程"]'::jsonb),
  ('keeper', 'n.', '守護者', 'junior', 3, 'The old keeper guarded the door to the Forbidden Tower.', '老守護者看守通往禁忌高塔的門。', '國中小說：時鐘塔', '', '[]'::jsonb, '["clock tower keeper 時鐘塔守護者"]'::jsonb),
  ('keepers', 'n.', '守護者們', 'junior', 3, 'The first keepers built the seal beneath the school.', '初代守護者在學院下方建造了封印。', '國中小說：時鐘塔', '', '[{"w":"keeper","p":"n.","n":"單數"}]'::jsonb, '["first keepers 初代守護者"]'::jsonb),
  ('king', 'n.', '國王；王', 'junior', 2, 'The Hollow King waited behind the broken seal.', '虛空之王在破裂的封印後等待著。', '國中小說：時鐘塔', '', '[]'::jsonb, '["Hollow King 虛空之王"]'::jsonb),
  ('lantern', 'n.', '燈籠；提燈', 'junior', 2, 'Each stone statue held a glowing lantern.', '每座石像都拿著一盞發光提燈。', '國中小說：時鐘塔', '', '[]'::jsonb, '["glowing lantern 發光燈籠"]'::jsonb),
  ('library', 'n.', '圖書館', 'junior', 1, 'The hidden library held the memories of the first keepers.', '隱藏圖書館保存著初代守護者的記憶。', '國中小說：時鐘塔', '', '[]'::jsonb, '["hidden library 隱藏圖書館"]'::jsonb),
  ('light', 'n./v.', '光；點亮', 'junior', 1, 'Silver light burst from Ethan''s watch.', '銀色光芒從伊森的懷錶中爆發。', '國中小說：時鐘塔', '', '[]'::jsonb, '["silver light 銀色光芒"]'::jsonb),
  ('magic', 'n.', '魔法', 'junior', 1, 'Magic felt real when the candle floated above the table.', '當蠟燭漂浮在桌上時，魔法變得真實。', '國中小說：時鐘塔', '', '[{"w":"magical","p":"adj.","n":"魔法的"}]'::jsonb, '["magic school 魔法學院"]'::jsonb),
  ('map', 'n.', '地圖', 'junior', 1, 'The hidden map showed a tunnel beneath the library.', '隱藏地圖顯示圖書館下方有一條隧道。', '國中小說：時鐘塔', '', '[]'::jsonb, '["old map 舊地圖"]'::jsonb),
  ('mark', 'n./v.', '印記；標記', 'junior', 2, 'The forbidden mark appeared on the ceiling.', '禁忌印記出現在天花板上。', '國中小說：時鐘塔', '', '[]'::jsonb, '["forbidden mark 禁忌印記"]'::jsonb),
  ('memory', 'n.', '記憶', 'junior', 2, 'The crystal showed Ethan a memory of his parents.', '水晶讓伊森看見父母的記憶。', '國中小說：時鐘塔', '', '[{"w":"memories","p":"n.","n":"複數"}]'::jsonb, '["old memory 舊記憶"]'::jsonb),
  ('midnight', 'n.', '午夜', 'junior', 2, 'The Midnight Train waited behind the hidden platform.', '午夜列車在隱藏月台後方等待。', '國中小說：時鐘塔', '', '[]'::jsonb, '["midnight train 午夜列車"]'::jsonb),
  ('mother', 'n.', '母親', 'junior', 1, 'The memory showed Ethan''s mother standing beside the silver seal.', '記憶中，伊森的母親站在銀色封印旁。', '國中小說：時鐘塔', '', '[]'::jsonb, '["Ethan’s mother 伊森的母親"]'::jsonb),
  ('parents', 'n.', '父母親', 'junior', 1, 'Ethan discovered that his parents had been keepers.', '伊森發現父母曾是守護者。', '國中小說：時鐘塔', '', '[{"w":"parent","p":"n.","n":"單數"}]'::jsonb, '["Ethan’s parents 伊森的父母"]'::jsonb),
  ('platform', 'n.', '月台；平台', 'junior', 2, 'Platform Nine was hidden behind a brick wall.', '九號月台藏在一面磚牆後方。', '國中小說：時鐘塔', '', '[]'::jsonb, '["train platform 火車月台"]'::jsonb),
  ('polite', 'adj.', '有禮貌的', 'junior', 2, 'Adrian sounded polite, but his eyes stayed serious.', '亞德里安聽起來很有禮貌，但眼神依然嚴肅。', '國中小說：時鐘塔', '', '[{"w":"politely","p":"adv.","n":"有禮貌地"}]'::jsonb, '["be polite 有禮貌"]'::jsonb),
  ('portrait', 'n.', '肖像；畫像', 'junior', 3, 'The portrait on the wall whispered Ethan''s family name.', '牆上的肖像低聲說出伊森的家族姓氏。', '國中小說：時鐘塔', '', '[]'::jsonb, '["old portrait 舊肖像"]'::jsonb),
  ('power', 'n.', '力量；能力', 'junior', 2, 'The crown offered Ethan great power.', '王冠給予伊森強大的力量誘惑。', '國中小說：時鐘塔', '', '[{"w":"powerful","p":"adj.","n":"強大的"}]'::jsonb, '["magical power 魔法力量"]'::jsonb),
  ('prison', 'n.', '監獄；囚牢', 'junior', 2, 'The old prison lay deep beneath the tower.', '古老囚牢位於高塔深處下方。', '國中小說：時鐘塔', '', '[]'::jsonb, '["underground prison 地下囚牢"]'::jsonb),
  ('prisoner', 'n.', '囚犯', 'junior', 3, 'The prisoner behind the gate called Ethan by name.', '門後的囚犯叫出了伊森的名字。', '國中小說：時鐘塔', '', '[]'::jsonb, '["hidden prisoner 隱藏的囚犯"]'::jsonb),
  ('promise', 'n./v.', '承諾；答應', 'junior', 2, 'Ethan made a promise to protect the school and his friends.', '伊森承諾要保護學院和朋友。', '國中小說：時鐘塔', '', '[]'::jsonb, '["keep a promise 遵守承諾"]'::jsonb),
  ('prophecy', 'n.', '預言', 'junior', 3, 'The prophecy warned that the heir would face the Hollow King.', '預言警告繼承者將面對虛空之王。', '國中小說：時鐘塔', '', '[]'::jsonb, '["old prophecy 古老預言"]'::jsonb),
  ('protect', 'v.', '保護', 'junior', 2, 'The teachers raised their wands to protect the students.', '老師們舉起魔杖保護學生。', '國中小說：時鐘塔', '', '[{"w":"protection","p":"n.","n":"保護"}]'::jsonb, '["protect the school 保護學校"]'::jsonb),
  ('rain', 'n./v.', '雨；下雨', 'junior', 1, 'Rain tapped softly against Ethan''s window.', '雨輕輕敲打伊森的窗戶。', '國中小說：時鐘塔', '', '[{"w":"rainy","p":"adj.","n":"下雨的"}]'::jsonb, '["heavy rain 大雨"]'::jsonb),
  ('rebuild', 'v.', '重建', 'junior', 2, 'After the battle, students worked together to rebuild the damaged hall.', '戰鬥後，學生們一起重建受損的大廳。', '國中小說：時鐘塔', '', '[{"w":"rebuilt","p":"v.","n":"過去式"}]'::jsonb, '["rebuild the school 重建學校"]'::jsonb),
  ('return', 'v./n.', '回來；歸還', 'junior', 2, 'The mark''s return made every teacher afraid.', '印記的回歸讓每位老師都感到害怕。', '國中小說：時鐘塔', '', '[{"w":"returned","p":"v.","n":"過去式"}]'::jsonb, '["return to school 回到學校"]'::jsonb),
  ('ruler', 'n.', '統治者；尺', 'junior', 2, 'The Hollow King wanted to become the ruler of the tower.', '虛空之王想成為高塔的統治者。', '國中小說：時鐘塔', '', '[]'::jsonb, '["true ruler 真正的統治者"]'::jsonb),
  ('sacrifice', 'n./v.', '犧牲', 'junior', 3, 'The first keepers made a sacrifice to lock away the king.', '初代守護者做出犧牲來封印國王。', '國中小說：時鐘塔', '', '[]'::jsonb, '["make a sacrifice 做出犧牲"]'::jsonb),
  ('save', 'v.', '拯救；節省', 'junior', 1, 'Ethan raised the watch to save his friends.', '伊森舉起懷錶拯救朋友。', '國中小說：時鐘塔', '', '[{"w":"saved","p":"v.","n":"過去式"}]'::jsonb, '["save the school 拯救學校"]'::jsonb),
  ('seal', 'n./v.', '封印；封住', 'junior', 3, 'The silver seal cracked under the tower.', '銀色封印在高塔底下裂開。', '國中小說：時鐘塔', '', '[]'::jsonb, '["break the seal 打破封印"]'::jsonb),
  ('secret', 'n./adj.', '秘密；秘密的', 'junior', 2, 'Adrian knew a secret about the Forbidden Tower.', '亞德里安知道一個關於禁忌高塔的秘密。', '國中小說：時鐘塔', '', '[]'::jsonb, '["keep a secret 保守秘密"]'::jsonb),
  ('serious', 'adj.', '嚴肅的；嚴重的', 'junior', 2, 'Adrian''s face became serious when the watch started ticking.', '懷錶開始滴答作響時，亞德里安的表情變得嚴肅。', '國中小說：時鐘塔', '', '[{"w":"seriously","p":"adv.","n":"嚴肅地"}]'::jsonb, '["look serious 看起來嚴肅"]'::jsonb),
  ('shadow', 'n.', '影子；陰影', 'junior', 2, 'A dark shadow moved between the library shelves.', '一道黑影在圖書館書架間移動。', '國中小說：時鐘塔', '', '[]'::jsonb, '["dark shadow 黑影"]'::jsonb),
  ('shatter', 'v.', '粉碎；碎裂', 'junior', 3, 'A burst of silver light made the dark mirror shatter.', '一道銀光讓黑暗鏡子碎裂。', '國中小說：時鐘塔', '', '[{"w":"shattered","p":"v.","n":"過去式"}]'::jsonb, '["shatter like glass 像玻璃般碎裂"]'::jsonb),
  ('shelves', 'n.', '書架；架子', 'junior', 2, 'Old books covered the library shelves.', '古老書本堆滿圖書館書架。', '國中小說：時鐘塔', '', '[{"w":"shelf","p":"n.","n":"單數"}]'::jsonb, '["library shelves 圖書館書架"]'::jsonb),
  ('smoke', 'n./v.', '煙；冒煙', 'junior', 2, 'Black smoke spread across the Great Hall.', '黑煙在大廳中擴散。', '國中小說：時鐘塔', '', '[{"w":"smoky","p":"adj.","n":"煙霧瀰漫的"}]'::jsonb, '["black smoke 黑煙"]'::jsonb),
  ('spell', 'n./v.', '咒語；拼寫', 'junior', 2, 'Lucy shouted a spell as the creature moved closer.', '怪物靠近時，露西喊出一道咒語。', '國中小說：時鐘塔', '', '[]'::jsonb, '["cast a spell 施咒"]'::jsonb),
  ('staircase', 'n.', '樓梯', 'junior', 2, 'The hidden staircase seemed to go down forever.', '隱藏樓梯彷彿一路通往無盡深處。', '國中小說：時鐘塔', '', '[]'::jsonb, '["hidden staircase 隱藏樓梯"]'::jsonb),
  ('station', 'n.', '車站', 'junior', 2, 'Ethan reached the station just before midnight.', '伊森在午夜前抵達車站。', '國中小說：時鐘塔', '', '[]'::jsonb, '["train station 火車站"]'::jsonb),
  ('street', 'n.', '街道', 'junior', 1, 'Rain made the street outside Ethan''s home shine.', '雨讓伊森家外的街道閃閃發亮。', '國中小說：時鐘塔', '', '[]'::jsonb, '["quiet street 安靜街道"]'::jsonb),
  ('suitcase', 'n.', '手提箱；行李箱', 'junior', 2, 'Ethan packed his suitcase before leaving for school.', '前往學校前，伊森整理好行李箱。', '國中小說：時鐘塔', '', '[]'::jsonb, '["pack a suitcase 打包行李箱"]'::jsonb),
  ('symbol', 'n.', '符號；象徵', 'junior', 2, 'A silver tower symbol glowed on the envelope.', '銀色高塔符號在信封上發光。', '國中小說：時鐘塔', '', '[]'::jsonb, '["silver symbol 銀色符號"]'::jsonb),
  ('ticket', 'n.', '票；車票', 'junior', 1, 'A strange train ticket was hidden inside the letter.', '一張奇怪的火車票藏在信裡。', '國中小說：時鐘塔', '', '[]'::jsonb, '["train ticket 火車票"]'::jsonb),
  ('tower', 'n.', '高塔；塔', 'junior', 1, 'The clock tower watched over the whole school.', '時鐘塔俯視整座學院。', '國中小說：時鐘塔', '', '[]'::jsonb, '["clock tower 時鐘塔"]'::jsonb),
  ('train', 'n./v.', '火車；訓練', 'junior', 1, 'The Midnight Train carried students to the magic school.', '午夜列車載著學生前往魔法學院。', '國中小說：時鐘塔', '', '[]'::jsonb, '["midnight train 午夜列車"]'::jsonb),
  ('tremble', 'v.', '顫抖；震動', 'junior', 3, 'The floor began to tremble as the prison door opened.', '囚牢大門打開時，地板開始顫抖。', '國中小說：時鐘塔', '', '[{"w":"trembled","p":"v.","n":"過去式"}]'::jsonb, '["tremble with fear 害怕得發抖"]'::jsonb),
  ('trust', 'n./v.', '信任', 'junior', 2, 'Ethan had to trust Lucy when the stairs began to move.', '樓梯開始移動時，伊森必須信任露西。', '國中小說：時鐘塔', '', '[]'::jsonb, '["trust a friend 信任朋友"]'::jsonb),
  ('truth', 'n.', '真相', 'junior', 2, 'The hidden library revealed the truth about Ethan''s parents.', '隱藏圖書館揭露了伊森父母的真相。', '國中小說：時鐘塔', '', '[]'::jsonb, '["find the truth 找到真相"]'::jsonb),
  ('tunnel', 'n.', '隧道', 'junior', 2, 'The tunnel under the library led to an ancient chamber.', '圖書館下方的隧道通往一間古老密室。', '國中小說：時鐘塔', '', '[]'::jsonb, '["dark tunnel 黑暗隧道"]'::jsonb),
  ('uniform', 'n.', '制服', 'junior', 2, 'The students wore dark uniforms with silver buttons.', '學生們穿著有銀色鈕扣的黑色制服。', '國中小說：時鐘塔', '', '[]'::jsonb, '["school uniform 學校制服"]'::jsonb),
  ('voice', 'n.', '聲音；嗓音', 'junior', 2, 'A low voice echoed from the darkness below.', '一道低沉聲音從下方黑暗中回響。', '國中小說：時鐘塔', '', '[]'::jsonb, '["low voice 低沉的聲音"]'::jsonb),
  ('warning', 'n.', '警告', 'junior', 2, 'The old keeper gave Ethan a warning before he entered.', '老守護者在伊森進入前給了他警告。', '國中小說：時鐘塔', '', '[{"w":"warn","p":"v.","n":"警告"}]'::jsonb, '["give a warning 給予警告"]'::jsonb),
  ('watch', 'n./v.', '懷錶；手錶；觀看', 'junior', 1, 'Ethan''s silver watch ticked loudly in the silent room.', '伊森的銀色懷錶在安靜房間裡大聲滴答作響。', '國中小說：時鐘塔', '', '[]'::jsonb, '["silver watch 銀色懷錶"]'::jsonb),
  ('whisper', 'n./v.', '低語；耳語', 'junior', 2, 'A whisper echoed from below the hidden staircase.', '一陣低語從隱藏樓梯下方回響。', '國中小說：時鐘塔', '', '[{"w":"whispered","p":"v.","n":"過去式"}]'::jsonb, '["whisper quietly 小聲低語"]'::jsonb),
  ('window', 'n.', '窗戶', 'junior', 1, 'Ethan saw the tower through the train window.', '伊森透過列車窗戶看見高塔。', '國中小說：時鐘塔', '', '[]'::jsonb, '["look out the window 看向窗外"]'::jsonb),
  ('winter', 'n.', '冬天', 'junior', 1, 'Winter winds howled softly outside the castle windows.', '冬季寒風在城堡窗外輕輕呼嘯。', '國中小說：時鐘塔', '', '[]'::jsonb, '["winter morning 冬天早晨"]'::jsonb)
ON CONFLICT (word, level) DO UPDATE SET
  pos = EXCLUDED.pos,
  meaning = EXCLUDED.meaning,
  ceec_level = COALESCE(public.word_bank.ceec_level, EXCLUDED.ceec_level),
  example = EXCLUDED.example,
  example_zh = EXCLUDED.example_zh,
  category = EXCLUDED.category,
  phonetic = COALESCE(NULLIF(public.word_bank.phonetic, ''), NULLIF(EXCLUDED.phonetic, ''), ''),
  forms = EXCLUDED.forms,
  collocations = EXCLUDED.collocations;
