import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { NOVELS } from "../src/data/novels.js";
import {
  NOVEL_CHINESE_AUDIO_VERSION,
  NOVEL_CHINESE_RATE,
  NOVEL_CHINESE_VOICE_ID,
  NOVEL_ENGLISH_RATE,
  makeNovelAudioAssetId,
  novelBlockPairs,
} from "../src/data/novelAudio.js";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outputPath = resolve(projectRoot, "netlify/functions/novel-audio-catalog.js");
const catalog = {};

function addEntry(input) {
  const id = makeNovelAudioAssetId(input);
  if (catalog[id]) throw new Error(`Duplicate novel audio asset id: ${id}`);
  catalog[id] = {
    text: input.text,
    lang: /^zh/i.test(input.lang) ? "zh-TW" : "en-US",
  };
}

for (const novels of Object.values(NOVELS)) {
  for (const novel of novels) {
    for (const chapter of novel.chapters || []) {
      addEntry({ novelId: novel.id, chapterNo: chapter.no, lang: "en-US", kind: "title", text: chapter.title });
      addEntry({ novelId: novel.id, chapterNo: chapter.no, lang: "zh-TW", kind: "title", text: chapter.zhTitle });
      for (const block of novelBlockPairs(chapter.en, chapter.zh)) {
        if (block.en) addEntry({ novelId: novel.id, chapterNo: chapter.no, lang: "en-US", blockIndex: block.i, text: block.en });
        if (block.zh) addEntry({ novelId: novel.id, chapterNo: chapter.no, lang: "zh-TW", blockIndex: block.i, text: block.zh });
      }
    }
  }
}

const config = {
  chineseAudioVersion: NOVEL_CHINESE_AUDIO_VERSION,
  chineseVoiceId: NOVEL_CHINESE_VOICE_ID,
  chineseRate: NOVEL_CHINESE_RATE,
  englishRate: NOVEL_ENGLISH_RATE,
};
const source = `// Generated by scripts/generateNovelAudioCatalog.mjs. Do not edit by hand.\nexport const NOVEL_AUDIO_CONFIG = Object.freeze(${JSON.stringify(config, null, 2)});\nexport const NOVEL_AUDIO_CATALOG = Object.freeze(${JSON.stringify(catalog, null, 2)});\n`;
await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, source, "utf8");
console.log(`Generated ${Object.keys(catalog).length} fixed novel audio entries at ${outputPath}`);
