import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const REPO_URL = "https://github.com/VivanChen/EnglishGo";
const OUTPUT_PATH = resolve(dirname(fileURLToPath(import.meta.url)), "../src/data/recentFeatures.generated.js");

const FEATURE_RULES = [
  {
    match: /Add junior Dream in Color song/i,
    title: "國中歌曲新增",
    description: "Dream in Color K-Pop 英文教學歌",
    category: "歌曲",
    level: "國中",
    icon: "🎧",
    tone: "#6366F1",
  },
  {
    match: /Add senior Taipei Cipher song/i,
    title: "高中歌曲新增",
    description: "Taipei Cipher 台北接力饒舌",
    category: "歌曲",
    level: "高中",
    icon: "🎤",
    tone: "#D85A30",
  },
  {
    match: /Add exam range SRS review/i,
    title: "考試範圍複習",
    description: "自行輸入單字，產生一輪複習",
    category: "複習",
    level: "全階段",
    icon: "📝",
    tone: "#10B981",
  },
  {
    match: /Add AI kid-friendly dictionary panel/i,
    title: "AI 小朋友字典",
    description: "單字卡旁即時產生友善解釋",
    category: "AI",
    level: "全階段",
    icon: "🔎",
    tone: "#8B5CF6",
  },
  {
    match: /Add pet adventure battle mode/i,
    title: "寵物冒險戰鬥",
    description: "用英文答題推進冒險戰鬥",
    category: "遊戲",
    level: "全階段",
    icon: "🐾",
    tone: "#EC4899",
  },
];

const EXCLUDED_SUBJECTS = [
  /^(Fix|Polish|Improve|Optimize|Refine|Tune|Use|Clarify|Unify|Restore)\b/i,
  /\b(word bank|vocabulary|words?|speech controls|dictionary audio|timing|calibration|setup guide|key setup)\b/i,
];

const FALLBACK_UPDATES = [
  {
    title: "高中歌曲新增",
    description: "Taipei Cipher 台北接力饒舌",
    category: "歌曲",
    level: "高中",
    icon: "🎤",
    tone: "#D85A30",
    date: "2026-05-21",
    href: `${REPO_URL}/commits/main`,
  },
  {
    title: "國中歌曲新增",
    description: "Dream in Color K-Pop 英文教學歌",
    category: "歌曲",
    level: "國中",
    icon: "🎧",
    tone: "#6366F1",
    date: "2026-05-21",
    href: `${REPO_URL}/commits/main`,
  },
  {
    title: "考試範圍複習",
    description: "自行輸入單字，產生一輪複習",
    category: "複習",
    level: "全階段",
    icon: "📝",
    tone: "#10B981",
    date: "2026-05-21",
    href: `${REPO_URL}/commits/main`,
  },
];

export function parseGitLog(raw) {
  return raw
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean)
    .map((line) => {
      const [hash, date, ...subjectParts] = line.split("\t");
      return { hash, date, subject: subjectParts.join("\t") };
    })
    .filter((commit) => commit.hash && commit.date && commit.subject);
}

function commitHref(hash) {
  return `${REPO_URL}/commit/${hash}`;
}

function genericFeature(commit) {
  const subject = commit.subject.replace(/^Add\s+/i, "").trim();
  if (!subject) return null;
  return {
    title: "功能新增",
    description: subject,
    category: "功能",
    level: "NEW",
    icon: "✨",
    tone: "#06B6D4",
  };
}

export function classifyFeatureCommit(commit) {
  if (!commit?.subject) return null;
  if (!/^Add\b/i.test(commit.subject)) return null;
  if (EXCLUDED_SUBJECTS.some((pattern) => pattern.test(commit.subject))) return null;

  const rule = FEATURE_RULES.find((item) => item.match.test(commit.subject));
  if (!rule) return genericFeature(commit);

  const { match, ...feature } = rule;
  return feature;
}

export function collectRecentFeatureUpdates(commits, { limit = 4 } = {}) {
  const seen = new Set();
  const updates = [];

  for (const commit of commits) {
    const feature = classifyFeatureCommit(commit);
    if (!feature) continue;

    const key = `${feature.title}:${feature.description}`;
    if (seen.has(key)) continue;
    seen.add(key);

    updates.push({
      ...feature,
      date: commit.date,
      href: commit.hash ? commitHref(commit.hash) : `${REPO_URL}/commits/main`,
    });

    if (updates.length >= limit) break;
  }

  return updates.length ? updates : FALLBACK_UPDATES.slice(0, limit);
}

export function readGitCommits() {
  const raw = execFileSync("git", ["log", "--date=short", "--format=%H%x09%cd%x09%s", "-n", "80"], {
    encoding: "utf8",
  });
  return parseGitLog(raw);
}

export function writeRecentFeatures(updates, outputPath = OUTPUT_PATH) {
  mkdirSync(dirname(outputPath), { recursive: true });
  const body = `// Generated by scripts/recentFeatures.mjs from git commit history.\n` +
    `// Do not edit by hand; run npm run generate:recent-features.\n\n` +
    `export const RECENT_FEATURES = ${JSON.stringify(updates, null, 2)};\n`;
  writeFileSync(outputPath, body, "utf8");
}

export function generateRecentFeatures() {
  let updates = FALLBACK_UPDATES;
  try {
    updates = collectRecentFeatureUpdates(readGitCommits(), { limit: 4 });
  } catch {
    updates = FALLBACK_UPDATES;
  }
  writeRecentFeatures(updates);
  return updates;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  generateRecentFeatures();
}
